### ISSUE TITLE
await packager(options) fails

### ISSUE THREAD

**Issue by LordMidi** [electron-userland/electron-packager#1000]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 13.1.1
* **Electron Version:**
  * 4.2.2
* **Operating System:**
  * Windows 10

### Expected Behavior
I can start the packager via the API with async / await.

### Actual Behavior
An SyntaxError is thrown.

### To Reproduce
```
const packager = require('electron-packager');
const packagerOptions = {
  dir: '.',
  out: 'offline',
};
const appPaths = await packager(packagerOptions);
                 ^^^^^
SyntaxError: await is only valid in async function
```

### Additional Information
The example includes the async / await example which I can't get to work.
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#electron-packager-api

**Comment by malept** [comment]
This is a JavaScript question rather than an Electron Packager question.

If you're copy/pasting the code directly into a script, it will fail because as of this comment, Node does not have support for [top-level `await`](https://github.com/tc39/proposal-top-level-await).

What you should do instead is:

```javascript
async function main() {
  const appPaths = await packager(packagerOptions);
  console.log(`Bundles created:\n${appPaths.join("\n")}`);
}

main()
```

**Comment by LordMidi** [comment]
thanks
