### ISSUE TITLE
Spawned `rec` process produces delays when running from packaged electron app on macOS

### ISSUE THREAD

**Issue by BenBergman** [electron-userland/electron-packager#1001]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 13.1.1
* **Electron Version:**
  * 4.0.1
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron Packager version:**:
  * N/A

### Expected Behavior
I have an Electron project that uses `node-record-lpcm16` to pipe audio from a spawned instance of `rec` (from `sox`) into a Google Dialogflow system. When running just with `electron .` audio is picked up instantly.

### Actual Behavior
Once I package my app, there is about a 5 second delay from the point that the audio process is spawned to when it starts capturing audio.

### To Reproduce
I am working to create a stripped down project that demonstrates this issue. I have created a basic Electron app that just spawns a recording process and just prints when it gets new data instead of hooking into Dialogflow. This minimal app works fine with `electron .` and `electron-packager`. In my app, unhooking Dialogflow does not change behaviour. If I start commenting out huge swaths of code unrelated to the audio input process then the delay reduces but is still present, which to me implies there could be a few things affecting the process. I'm still working to try some things out in hopes of producing a minimal reproduction, but so far I'm not having much luck there.

### Additional Information
Spawning other processes does not result in delays in their data output.

**Comment by BenBergman** [comment]
I discovered that if I run `myapp.app/Contents/MacOS/myapp` from the command line the delay goes away again. I'm not sure if this helps pinpoint where the issue is coming from, but thought it was worth noting.

**Comment by malept** [comment]
This doesn't seem like an issue with Electron Packager itself, but rather with how macOS apps work.It seems your problem happens only when you launch MyApp.app, vs. executing the actual binary. I would go looking to see if there is indeed some sort of bug around that (from the details and my lack of macOS knowledge, I don't know if it's Electron specific or more general to macOS apps).

**Comment by will-stone** [comment]
I’ve had this issue. The only way I found to get around it, is to sign the app. This will cost you as you’ll need an Apple Developer.

**Comment by BenBergman** [comment]
That is super strange. We aren't distributing the app, just running it in a single instance, basically a kiosk, so we'll stick with running the binary from the command line.

Thanks for the extra info @will-stone !
