### ISSUE TITLE
Indicator of portable app loading

### ISSUE THREAD

**Issue by campbellhennessy** [electron-userland/electron-packager#1015]
I have packaged a portable exe that is running off a USB.  There are a lot of static media files in the project so my app.asar is several hundred MB in size.  The application itself loads quickly in development (like 2-3s) but when opened from the exe it takes about a minute to load on some computers from the time the user clicks.  I assume that this is the app.asar being copied to a temporary directory and decompressed.

My issue isn't with the delay, this is the price we pay for wanting it portable on a USB.  The issue we are having is that there is no indication to the user that the application is still loading.  The cursor spins for a few seconds but then goes back to a normal mouse and the only way you can tell the program is loading is that there is an entry in the task manger.  This leads to some users clicking the executable many times before many windows start to open.

Is there a way to launch a small modal or other indication to the user that the application is still alive before the app.asar is transferred?

**Comment by malept** [comment]
Electron Packager doesn't create portable EXEs, it only customizes and bundles an Electron app. You probably have this project mistaken for another one.

**Comment by campbellhennessy** [comment]
SO sorry!  You are exactly right, my apologies, I didn't pay enough attention to what I was doing there
