### ISSUE TITLE
Packaged app blank on Windows, but ok on OSX

### ISSUE THREAD

**Issue by dottodot** [electron-userland/electron-packager#1021]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 14.0.0
* **Electron Version:**
  * 4.2.5
* **Operating System:**
  * macOs 10.14.5
* **Last Known Working Electron Packager version:**:
  *N/A

### Expected Behavior
Both osx and window to build and run

### Actual Behavior
When packaged for osx my app runs as expected, but when packaged for windows it loads as a blank white screen. Also if I use `openDevTools` I get a warning of of Devtool was disconnected from page.

### To Reproduce
Here are my scripts i'm using to package the app

```
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "start:electron": "electron dist/electron",
    "serve:electron": "electron dist/electron --serve",
    "build": "ng build",
    "build:electron-main": "tsc -p src/electron",
    "postbuild:electron-main": "cpx package.json dist/electron",
    "build:electron-renderer": "ng build electron",
    "build:electron": "npm run build:electron-renderer && npm run build:electron-main",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "package:win": "npm run build:electron && DEBUG=electron-packager cross-var electron-packager dist/electron $npm_package_name --out=packages --platform=win32 --arch=x64  --overwrite",
    "package:linux": "npm run build:electron && cross-var electron-packager dist/electron $npm_package_name --out=packages --platform=linux --arch=all --overwrite",
    "package:osx": "npm run build:electron && cross-var electron-packager dist/electron $npm_package_name --out=packages --platform=darwin --arch=all --overwrite --icon=src/Icon/Icon.icns",
    "package:all": "npm run build:electron && cross-var electron-packager dist/electron $npm_package_name --out=packages --all --arch=all --overwrite "
  },
```

### Additional Information
It's a Angular app. I've also install wine using homebrew.

The output from debug is

```
electron-packager Electron Packager 14.0.0
  electron-packager Node v10.16.0
  electron-packager Host Operating system: darwin (x64) +0ms
  electron-packager Packager Options: {"_":["dist/electron","ars-desktop"],"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"out":"packages","platform":"win32","arch":"x64","overwrite":true,"dir":"dist/electron","name":"ars-desktop","protocols":[]} +2ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /ars-desktop/dist/electron/package.json +0ms
  electron-packager Inferring target Electron version from electron in /ars-desktop/dist/electron/package.json +3ms
  electron-packager Application name: ars-desktop +15ms
  electron-packager Target Electron version: 4.2.5 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"4.2.5","artifactName":"electron"} +0ms
  electron-packager Removing packages/ars-desktop-win32-x64 due to setting overwrite: true +7ms
Packaging app for platform win32 x64 using electron v4.2.5
  electron-packager Creating /var/folders/h_/nr3rbk_917v1v7f01_tpt4_80000gn/T/electron-packager/win32-x64-template +15ms
  electron-packager Extracting /Users/marcuswilliams/Library/Caches/electron/electron-v4.2.5-win32-x64.zip to /var/folders/h_/nr3rbk_917v1v7f01_tpt4_80000gn/T/electron-packager/win32-x64-template +1ms
  electron-packager Initializing app in /var/folders/h_/nr3rbk_917v1v7f01_tpt4_80000gn/T/electron-packager/win32-x64/ars-desktop-win32-x64 from /var/folders/h_/nr3rbk_917v1v7f01_tpt4_80000gn/T/electron-packager/win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/ars-desktop/packages' ] +1s
  electron-packager Renaming electron.exe to ars-desktop.exe in /var/folders/h_/nr3rbk_917v1v7f01_tpt4_80000gn/T/electron-packager/win32-x64/ars-desktop-win32-x64 +87ms
  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"ars-desktop","InternalName":"ars-desktop","OriginalFilename":"ars-desktop.exe","ProductName":"ars-desktop"},"file-version":"0.0.0","product-version":"0.0.0"} +0ms
  electron-packager Moving /var/folders/h_/nr3rbk_917v1v7f01_tpt4_80000gn/T/electron-packager/win32-x64/ars-desktop-win32-x64 to packages/ars-desktop-win32-x64 +6s
Wrote new app to packages/ars-desktop-win32-x64
```

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by dottodot** [comment]
@malept 
https://github.com/dottodot/electron-test
Seems like it something to do with making a post request in angular, but there isn't any other way to do it and the problem only occurs after being packaged for windows.

**Comment by malept** [comment]
I can't reproduce the error on Linux, either. I don't have access to a Windows machine, so I can only give you suggestions on how to go about debugging this.

Based on what you've said, I doubt it's a problem with Electron Packager itself. First, I would suggest replacing [this code](https://github.com/dottodot/electron-test/blob/e985e613148c65af52582b5161f36bc7b24cd938/src/electron/index.ts#L30-L36) with `await mainWindow.loadFile(path.join(__dirname, 'index.html'))` (see [Electron docs](https://electronjs.org/docs/api/browser-window#winloadfilefilepath-options)). Second, if that doesn't work, I would start using the DevTools pane to start debugging.

If you need more assistance, consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.

**Comment by dottodot** [comment]
Just for reference in case anyone else comes across this issue. The problem is loading Google Fonts in the index file i.e

```
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
If I remove those the app loads.
