### ISSUE TITLE
Hangs when unzipping prebuilt Electron binary on Windows 7, due to missing Powershell dependency

### ISSUE THREAD

**Issue by AGrinthal** [electron-userland/electron-packager#1022]
I am attempting to create a package using the Electron-Quick-Start application.  This application runs when I issue npm Start however when I try to package the application is just hangs.

I used debug and was able to see that the win32 Platform zip file is created however it never gets extracted to the temp folder from the Electron\Cache folder.  

I'm at a loss on what next to do.   Below is the debug statements when its run

```
C:\Consolidation\My Documents\Electron\Electron-Quick-Start>electron-packager .  electron-packager Electron Packager 14.0.0  electron-packager Node v10.13.0  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"_":["."],"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":".","protocols":[]} +3ms
  electron-packager Target Platforms: win32 +2ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring application name from name in C:\Consolidation\MyDocuments\Electron\Electron-Quick-Start\package.json +0ms
  electron-packager Inferring appVersion from version in C:\Consolidation\My Documents\Electron\Electron-Quick-Start\package.json +1ms
  electron-packager Inferring win32metadata.CompanyName from author in C:\Consolidation\My Documents\Electron\Electron-Quick-Start\package.json +0ms
  electron-packager Inferring target Electron version from electron in C:\Consolidation\My Documents\Electron\Electron-Quick-Start\package.json +4ms
  electron-packager Application name: electron-quick-start +17ms
  electron-packager Target Electron version: 5.0.5 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"5.0.5","artifactName":"electron"} +0ms
  Packaging app for platform win32 x64 using electron v5.0.5  electron-packager Creating C:\Users\AGRINT~1\AppData\Local\Temp\electron-packager\win32-x64-template +9ms
  electron-packager Extracting C:\Users\AGrinthal\AppData\Local\electron\Cache\electron-v5.0.5-win32-x64.zip to C:\Users\AGRINT~1\AppData\Local\Temp\electron-packager\win32-x64-template +3ms
```

Any help or direction would be appreciated. I can develop all day long with npm Start however I need to see a deliverable package and cannot get it to run.  I am using Windows 7

Thanks
Andy

**Comment by malept** [comment]
Make sure you have the [correct dependencies for unzipping](https://github.com/feross/cross-zip#windows-users) installed (which are also mentioned in the README).

**Comment by AGrinthal** [comment]
Mark,

  Thank you for the information.  I use .net so I would think they are in my machine but I will double check. 

Appreciate the quick response.  This has been driving me crazy!

 

Andy

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about a week, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

**Comment by AGrinthal** [comment]
Sorry about the delay as I wasn't give a chance to try your comment until today.  I installed the cross-zip dependencies however I still hand at the point Where the packager has made the zip file and it appears to be trying to unzip it.

Packaging app for platform win32 x64 using electron v5.0.5
  electron-packager Creating C:\Users\AGRINT~1\AppData\Local\Temp\electron-packa
ger\win32-x64-template +12ms

  electron-packager Extracting C:\Users\AGrinthal\AppData\Local\electron\Cache\e
lectron-v5.0.5-win32-x64.zip to C:\Users\AGRINT~1\AppData\Local\Temp\electron-pa
ckager\win32-x64-template +2ms

Maybe i didn't install the cross-zip correctly?  Any other comments?

**Comment by malept** [comment]
Can you manually extract `C:\Users\AGrinthal\AppData\Local\electron\Cache\electron-v5.0.5-win32-x64.zip` ?

**Comment by AGrinthal** [comment]
Yes. I can unzip it no problem MANUALLY

**Comment by malept** [comment]
Can you try running the powershell from `cross-zip`, but manually and with the proper paths in the right places?

https://github.com/feross/cross-zip/blob/854c4088102572273fa836035f22b710b078f226/index.js#L99

**Comment by AGrinthal** [comment]
I will try that after the holidays.  Just so I am getting some understanding here is it because powershell is not firing or because it can't find the path's for some reason?  I guess what I'm asking is that this is the issue for why I am "Hangining"  I would never have know this without the debug command.  I appreciate this help.  happy 4th  !

**Comment by malept** [comment]
I don't know why it's hanging, that's why I'm asking to run the command manually. The only reason I've encountered so far that it would hang is that the dependencies aren't installed.

**Comment by AGrinthal** [comment]
This is just  a simple example I ran that uses Shell to open a PDF file in Adobe and also open a Word Document in MS Word.  It works fine when I run npm start However when I run "electron-packager ."  it hangs after making the zip file as noted above. 
HOWEVER
the strange part is that after I manually unzip the zip file and run the EXE it's not the application that I defined. It's some sort of app that says "to run the Local app, execute the following on the command line" Then it has a box that shows:  $ electron.exe path-to-app"  

I'm just trying to get my feet wet here but teh Packager shouldn't hang and shouldn't the unzipped content be MY app?  
Not sure what's going on here.

**Comment by malept** [comment]
The zipped file is the prebuilt Electron binary, not your app.

I would still like to know if the powershell command from https://github.com/electron-userland/electron-packager/issues/1022#issuecomment-508287549 works for you.

**Comment by AGrinthal** [comment]
Ok thanks
I am checking on my power shell now. It appears I need 3.0 and I just checked and I have 2.0 So I am trying to upgrade to 3

**Comment by malept** [comment]
If that's the issue, then it's not an Electron Packager bug, so I'm closing this issue.

**Comment by gerroon** [comment]
I have this exact issue with building Winx64 version on Debian Linux. I can build the app for other platforms (like linux)  but it is stuck at this stage when building for winx64.

```
found 7 vulnerabilities (5 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
Copying required windows binaries
Packaging app for platform win32 x64 using electron v6.0.12
```

```
ls /home/USER/.cache/electron

electron-v3.0.10-linux-x64.zip
electron-v6.0.12-linux-x64.zip
httpsgithub.comelectronelectronreleasesdownloadv6.0.12electron-v6.0.12-linux-x64.zip
httpsgithub.comelectronelectronreleasesdownloadv6.0.12electron-v6.0.12-win32-x64.zip
httpsgithub.comelectronelectronreleasesdownloadv6.0.12SHASUMS256.txt
SHASUMS256.txt-3.0.10
SHASUMS256.txt-6.0.12


```

**Comment by malept** [comment]
> I have this exact issue with building Winx64 version on Debian Linux. I can build the app for other platforms (like linux) but it is stuck at this stage when building for winx64.

This is unrelated to this issue and also does not have enough information to be actionable. Please file a new issue and follow the issue template.
