### ISSUE TITLE
Packaging app for platform win32 x64 taking too long using electron v5.0.6

### ISSUE THREAD

**Issue by mariemabc** [electron-userland/electron-packager#1028]
I developped a web app with angular i need to package my web app using electron , it all seems fine until i run electron-packager , it takes forever , i dont know if it is supposed to be this slow or is there something wrong ? ps : im on windows 7

**Comment by malept** [comment]
Duplicate of #1018

**Comment by kabaluyot** [comment]
Why close it @malept? The duplicate issue is still unresolved.

**Comment by malept** [comment]
#1018 is resolved, and duplicate issues are not left open anyway.
