### ISSUE TITLE
Please add support for Linux ARM

### ISSUE THREAD

**Issue by JamesKyburz** [electron-userland/electron-packager#106]

**Comment by malept** [comment]
In the future, since you had a PR ready to go as well, just filing the PR (instead of an additional issue) is sufficient - discussion can go there.

**Comment by JamesKyburz** [comment]
@malept will do.

**Comment by robertely** [comment]
I was just hunting around seeing if i needed to do this my self. Thanks James!

**Comment by ebonet** [comment]
What's the status on this? Trying to build for raspberry pi 2, even though electron supports arm the packager doesn't.

**Comment by malept** [comment]
We're still blocked on #107 (and by extension, https://github.com/electron/electron/issues/2343).
