### ISSUE TITLE
package electron with edge.js native module

### ISSUE THREAD

**Issue by gtaranas** [electron-userland/electron-packager#110]
I have rebuild edge.js native module with electron headers and running fine but when i'm running electron-packager and trying to run application i get the following error: 

[Error: The edge module has not been pre-compiled for node.js version v2.3.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.]

**Comment by zeke** [comment]
This is an issue with edge. You may want to look into using a specific Electron version. See https://www.npmjs.com/package/edge-atom-shell
