### ISSUE TITLE
What output files are required from a linux build?

### ISSUE THREAD

**Issue by grofit** [electron-userland/electron-packager#116]
I am building for linux and the build size seems quite large, the app.asar is about 50mb, and then the MyApp file (which acts as the executable) is about 50mb, then there are the *.so libs which I know are needed, so thats another 30mb or so, so I end up with like 130mb file...

Now I can appreciate that this lib just takes what electron gives it and renames it and puts some apps in some locaitons, but is there anything that can be dropped here?

**Comment by kfranqueiro** [comment]
`app.asar` probably shouldn't actually be 50MB, though I suppose it depends on how much you have in the way of production dependencies for the application.

What does your directory structure and configuration look like?  Are you sure you aren't neglecting to `ignore` some things you should be?

**Comment by grofit** [comment]
Actually maybe thats right... I have a dependency on mermaid and mathjax, both of which are like 25mb a pop, then its just normal small files etc. I was just surprised as the windows installer comes out at 50mb (ish) and the linux zip file comes out at 150mb ish, just seemed 100mb was a large difference.

**Comment by kfranqueiro** [comment]
That does seem like a large difference.  Is the directory you're outputting to under the directory you're packaging, and if so, have you told electron-packager to `ignore` it?

**Comment by grofit** [comment]
the packaging is happening in unique folders the layout is:

```
_packages
|- raw
   |- windows-ia32
   |- windows-x64
   |- linux-ia32
   |- linux-x64
|- installers
```

The raw folders are passed in to other processes, so in this instance windows ones go to squirrel the linux ones go to a zip file processor for each arch type, then are dumped in installers.

Like I say upon reflection the app.asar may be legitimately 50mb if no compression is done on it. I assume the Electron/.exe file is 50mb as it contains the chromium browser within it, and the other so files seem normal.

So maybe its all just normal, and the windows installer super zips it all up or something...

**Comment by malept** [comment]
This sounds like the question has been answered. If it is not the case, the original reporter is free to reopen the issue.
