### ISSUE TITLE
`--out` should be added to the ignore list by default

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-packager#120]
If `--out` is specified and not `cwd` it should be added to the ignore list.

It makes no sense to include the `out` directory, so this would be a sane default and prevent people from mistakenly include it in their built app.

**Comment by sheerun** [comment]
+1

**Comment by pyro2927** [comment]
:+1: Would love to see this as well.  We've had build-sizes compound a few times before realizing it wasn't ignoring `--out` in between builds.

**Comment by malept** [comment]
This feature was merged in #255.
