### ISSUE TITLE
Missing documentation/unit tests about protocol options

### ISSUE THREAD

**Issue by renarsvilnis** [electron-userland/electron-packager#121]
Found out by looking at source code there are missing documentation about the `protocols` option which gets used in [electron-packager/mac.js](https://github.com/maxogden/electron-packager/blob/303de520cef5a46d61a7a8646e9d83aa079af20a/mac.js) for building electron apps that register custom url scheme on os. Example when opening `myapp://blip-blop` in browser it passes `myapp://blip-blop` string as an argument to [`open-url`](https://github.com/atom/electron/blob/master/docs/api/app.md#event-open-url) app module event.

**Comment by buddingmonkey** [comment]
:+1:

**Comment by maxogden** [comment]
Heres the usage:

`--protocol-name=\"MyApp URL\" --protocol=\"myapp\"`

This will cause your `app.on('open-url')` fn to fire when `myapp://` links are opened from e.g. Chrome
