### ISSUE TITLE
Parallel builds?

### ISSUE THREAD

**Issue by remexre** [electron-userland/electron-packager#123]
It takes roughly 15 minutes to build with `--all`, so I'd like to build each architecture's version in parallel. It maxes out one core out of eight, so it'd likely be possible to get a five-fold speedup by parallelizing.

I think this is possible with the [cluster](https://nodejs.org/api/cluster.html) module?

**Comment by kfranqueiro** [comment]
I've been under the impression all along that electron-packager is far more HDD-intensive than CPU-intensive (most of the time is spent extracting/copying files), so I'm not sure whether parallelization will actually improve anything if the bottleneck is the hard drive.  Maybe there's room for improvement where SSDs are concerned...

**Comment by tikiking1** [comment]
It looks like I'm able to get a two-fold speedup on my system. I've got an SSD on `/`, and an HDD on `/home`. I'm performing the build in `/home/tmp/<whatever>`, but I'm not sure if this uses system directories.

## `all`
```
[01:42:34] Starting 'package'...
Packaging app for platform linux ia32 using electron v0.31.0
Packaging app for platform win32 ia32 using electron v0.31.0
Packaging app for platform darwin x64 using electron v0.31.0
Packaging app for platform linux x64 using electron v0.31.0
Packaging app for platform win32 x64 using electron v0.31.0
[01:42:48] Finished 'package' after 14 s
```
## `[ "darwin-x64", "linux-ia32", "linux-x64", "win32-ia32", "win32-x64" ]`
```
[01:39:41] Starting 'package'...
[01:39:41] Starting 'package:darwin-x64'...
[01:39:41] Starting 'package:linux-ia32'...
[01:39:41] Starting 'package:linux-x64'...
[01:39:41] Starting 'package:win32-ia32'...
[01:39:41] Starting 'package:win32-x64'...
[01:39:41] Finished 'package' after 7.93 ms
Packaging app for platform linux ia32 using electron v0.31.0
Packaging app for platform linux x64 using electron v0.31.0
Packaging app for platform win32 ia32 using electron v0.31.0
Packaging app for platform win32 x64 using electron v0.31.0
Packaging app for platform darwin x64 using electron v0.31.0
[01:39:48] Finished 'package:win32-ia32' after 6.89 s
[01:39:48] Finished 'package:linux-x64' after 6.93 s
[01:39:48] Finished 'package:linux-ia32' after 6.97 s
[01:39:49] Finished 'package:darwin-x64' after 7.63 s
[01:39:49] Finished 'package:win32-x64' after 7.73 s
```

**Comment by tikiking1** [comment]
Oh, because it's relevant: `~/tmp` isn't a tmpfs, it's a normal directory.

**Comment by malept** [comment]
I've added something that looks like parallel builds when more than one target is selected at a time, in the form of `Promise.all` support. That's about the extent to which Electron Packager will natively support parallelization. In my opinion, anything more should be done in an external module (which could utilize the `cluster` module as referenced above).
