### ISSUE TITLE
Ability to write to info.plist or custom info.plist for OSX

### ISSUE THREAD

**Issue by buddingmonkey** [electron-userland/electron-packager#136]
The packager should be able to allow us to specify parameters (e.g. file extensions and protocols) or allow us to provide a custom info.plist so we can have tighter integration with the OS.

**Comment by herrmannplatz** [comment]
I also had to add other properties than the ones that electron packager provides and ended up forking electron-packager to add options. But this doesn't scale.

I kind of like the idea of specifying a custom plist, since it gives you the best control of what to add, without having to change the packager for every property. So instead of creating the plist on the fly, you would just copy this into the app folder.

**Comment by dylang** [comment]
what about an optional handler that would pass the `info.plist` generated by `electron-packager` as a javascript object which we can modify and pass back?

psedocode:

```js
packager({
...
plist: function(plist) {
  plist.CFBundleURLTypes = [{
    CFBundleURLName: 'OpenHelper',
    CFBundleURLSchemes: [ 'custom' ]
  }];
  return plist;
}
...
}, cb);
```

*Note: I don't know enough about `info.plist` to know if it can easily be expressed as a javascript object and then translated back to xml.*

**Comment by maxogden** [comment]
@dylang my general feedback on the idea is that this sounds like something that should be solved outside of this module first, and we can support an API for doing this that someone else can maintain :)

**Comment by dylang** [comment]
@maxogden Do you mean like [plist](https://github.com/TooTallNate/plist.js)? I didn't realize you were already using it.  I should have looked, very nice. It looks like it's making managing the plist much easier.

Or do you mean a module with an api specific to the available `info.plist` parameters? That seems like a lot more work, definitely a separate module, but a nice-to-have for the original purpose of this issue.

**Comment by maxogden** [comment]
@dylang ah sorry, I was talking about the latter part -- the specific info.plist configuration stuff

**Comment by dylang** [comment]
@buddingmonkey @herrmannplatz I just realized the feature I wanted, protocols (custom url handlers) already exists, it's just not yet documented (and possibly not officially supported):

https://github.com/maxogden/electron-packager/blob/master/mac.js#L62-#L69

Example usage:

```js
packager(
    ....
    protocols: [{
        name: 'Some Name',
        schemes: ['foo']  //foo://google.com will launch your app
    }]
);
```

**Comment by malept** [comment]
Re: protocols documentation, there is an issue at #121.

**Comment by buddingmonkey** [comment]
@dylang Protocols are a good start, but also file handlers would be nice. Even if we can't use a custom info.plist file, maybe we could specify additional parameters. This would allow for generic additions to the plist.

**Comment by dvcrn** [comment]
I think the custom info.plist parameters are definitely a good start. It would cover future changes to properties (including new properties) on apples side without having to change electron-packager. 

https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

**Comment by erkyrath** [comment]
See https://github.com/maxogden/electron-packager/pull/253

**Comment by malept** [comment]
Since #253 has been merged, I'm closing this issue.
