### ISSUE TITLE
Electron-packager not working when packing for all platforms in OSX. 

### ISSUE THREAD

**Issue by varghesethomase** [electron-userland/electron-packager#146]
The error comes in specific when packing all. And below attached is my set of npm packages.
 asar@0.6.1
├── babel-core@5.8.24
├── babel-eslint@3.1.30
├── babel-loader@5.3.2
├── chai@2.3.0
├── classnames@2.1.3
├── css-loader@0.12.1
├── debug@2.2.0
├── del@1.2.1
├── electron-debug@0.1.1
├── electron-packager@4.2.0
├── electron-prebuilt@0.26.1
├── electron-rebuild@0.2.5
├── eslint@0.22.1
├── eslint-plugin-react@2.7.1
├── extract-text-webpack-plugin@0.8.2
├── file-loader@0.8.4
├── flux@2.1.1
├── font-awesome@4.4.0
├── github-latest-release@0.1.1
├── halogen@0.1.10
├── html-loader@0.3.0
├── json-loader@0.5.2
├── keymirror@0.1.1
├── markdown-loader@0.1.7
├── minimist@1.2.0
├── mocha@2.3.2
├── moment@2.10.6
├── node-libs-browser@0.5.2
├── object-assign@2.1.1
├── proxyquire@1.7.2
├── raw-loader@0.5.1
├── react@0.13.3
├── react-dropdown-button@1.0.11
├── react-dropzone@2.1.0
├── react-fa-icon@0.1.4
├── react-gemini-scrollbar@1.1.1
├── react-hot-loader@1.3.0
├── react-notification-system@0.1.14
├── react-proxy-loader@0.3.4
├── react-router@0.13.3
├── react-textarea-autosize@2.5.1
├── sinon@1.16.1
├── stats-webpack-plugin@0.1.2
├── style-loader@0.12.3
├── superagent@1.3.0
├── url-loader@0.5.6
├── webpack@1.12.1
└── webpack-dev-server@1.10.1
[ { [Error: ENOENT, open '/var/folders/hs/nqmrs4751fqfh09czz8ncm4h0000gn/T/electron-packager-windows/Eduknow-win32/resources/app/node_modules/react-fa-icon/package.json']
    errno: -2,
    code: 'ENOENT',
    path: '/var/folders/hs/nqmrs4751fqfh09czz8ncm4h0000gn/T/electron-packager-windows/Eduknow-win32/resources/app/node_modules/react-fa-icon/package.json' },
  { [Error: ENOENT, lstat '/var/folders/hs/nqmrs4751fqfh09czz8ncm4h0000gn/T/electron-packager-windows/Eduknow-win32/resources/app/node_modules/react-notification-system/README.md']
    errno: -2,
    code: 'ENOENT',
    path: '/var/folders/hs/nqmrs4751fqfh09czz8ncm4h0000gn/T/electron-packager-windows/Eduknow-win32/resources/app/node_modules/react-notification-system/README.md' },
  { [Error: ENOENT, open '/var/folders/hs/nqmrs4751fqfh09czz8ncm4h0000gn/T/electron-packager-windows/Eduknow-win32/resources/app/node_modules/react-gemini-scrollbar/package.json']

Is it related to bug #133 ? But i dont find that package installed for me yet. TIA

**Comment by malept** [comment]
Per the [issue reporting instructions](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md):

> What [command line] arguments are you passing?

Additionally, have you tried using the latest version of electron-packager?

**Comment by varghesethomase** [comment]
To check if I had extract zip i did the grep. 
npm list | grep extract-zip
│ ├─┬ extract-zip@1.0.3
│ └─┬ extract-zip@1.0.
Here is the output.

**Comment by varghesethomase** [comment]
The electron-packager version is electron-packager@4.2.0
I use the packager function with arguments
var DEFAULT_OPTS = {
  dir: './',
  name: appName,
  asar: shouldUseAsar,
  ignore: [
    '/test($|/)',
    '/tools($|/)',
    '/release($|/)'
  ].concat(devDeps.map(function(name) { return '/node_modules/' + name + '($|/)' }))
}

var opts = assign({}, DEFAULT_OPTS, {
    platform: plat,
    arch: arch,
    out: 'release/' + plat + '-' + arch,
    overwrite: true
  })

  packager(opts, cb)

**Comment by malept** [comment]
Based on some information I got from #149, which seems to be a similar problem, I have some followup questions. Given all of the files that electron-packager is failing on,

* Do they exist?
* Are they symlinks?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in several months, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
