### ISSUE TITLE
Rename --version to --electron-version

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-packager#154]
There seem to be a disproportionate number of issues created over the confusion around what `--version` actually means. (See: #137, #140, #153.) I propose that the parameter be renamed so that it's obvious as to what the flag's value refers to: the version of Electron, not the version of the application.

This would obviously be a breaking change, requiring a major version bump.

**Comment by maxogden** [comment]
I'd rather try and fix this with docs first. The readme formatting could use some love, e.g. the usage section is currently a big wall of unicode text

**Comment by malept** [comment]
I figured as much. I just wanted to get this idea out there and documented.

I'll take a crack at making the README friendlier tonight, if I have some time.

Closing for now.

**Comment by malept** [comment]
I'm reopening this. No amount of docs has fixed this so far. In my opinion, this option violates [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).
