### ISSUE TITLE
Symlink errors

### ISSUE THREAD

**Issue by digitalnature** [electron-userland/electron-packager#158]
I'm getting errors like:
`[Error: EROFS, symlink 'Versions/Current/Resources'] errno: 56, code: 'EROFS', path: '...`

I'm not sure, but I think it's because the directory of the app is from Windows, but mounted in Linux (I'm running electron in a vm).

Anyway, npm has a command line option `--no-bin-link ` which fixes this error. Can electron-packager do this too?

**Comment by maxogden** [comment]
Not sure about a solution, but a workaround would probably be to zip up your thing on windows, and extract it to an actual linux fs, and then package it

**Comment by zeke** [comment]
`EROFS` means you're trying to install on a read-only filesystem. It's not possible to address this in electron-packager. Gonna close this out.
