### ISSUE TITLE
Specify already packed asar via a prebuiltAsar option

### ISSUE THREAD

**Issue by kurisubrooks** [electron-userland/electron-packager#161]
I have to do a bunch of things with asar manually in order to get my build to work correctly.
Is there a way you could add a CLI implementation to specify an already packed asar?

**Comment by malept** [comment]
Seems reasonable.

**Comment by maxogden** [comment]
Here's the current asar flag in the code https://github.com/maxogden/electron-packager/blob/437bb530570186a6141c55b2a967615180c5259a/common.js#L94

We could try overloading it. It's currently a boolean, so if it was a string we could try and read an asar file at the path in the string. if it's a boolean we would do what we do now. This might introduce some bugs with CLI parsing so we would have to be sure our CLI parser always turns `--asar=true` into `true` and not `'true'`.

The other option is to add another flag, e.g. `--asar-file=foo.asar`

**Comment by kurisubrooks** [comment]
The option to specify the file/file's directory would be very useful.

**Comment by malept** [comment]
Given the current state of the asar code, adding a new sub-property to `asar` would be best.

if `asar.filename` is specified, it should bypass [the asar creation code](https://github.com/electron-userland/electron-packager/blob/0ef914f/common.js#L239-L241) and just copy the specified asar file to [`app.asar`](https://github.com/electron-userland/electron-packager/blob/0ef914f/common.js#L75).

As always, please make sure that [there are appropriate docs and tests added](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#filing-pull-requests).

**Comment by jsg2021** [comment]
any movement on this? :)

**Comment by malept** [comment]
@jsg2021 I would be more than happy to review a PR to add this feature. If you need any more guidance than what I described in https://github.com/electron-userland/electron-packager/issues/161#issuecomment-252740910 (the code has changed a lot since then), please let me know.
