### ISSUE TITLE
Build to blank screen on osx

### ISSUE THREAD

**Issue by chrisburgin95** [electron-userland/electron-packager#183]
Every time I build my electron application it is successful but when I run the application Im presented with a blank screen. Im positive that it is finding my main.js and using it as modifications here result in changes in the built application. Any help with this would me much appreciated it.

Here is my build command
```
$ sudo electron-packager . foo --platform=all --arch=x64 --version=0.31.2 --overwrite 
```

Here is my main.js

``` javascript
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.

// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
    app.quit();
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 1400, height: 700});



  // and load the index.html of the app.
  mainWindow.loadUrl('file://' + __dirname + '/templates/index.html');

  // Open the DevTools.
  // mainWindow.openDevTools();

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});
```

**Comment by maxogden** [comment]
Try doing `console.log('file://' + __dirname + '/templates/index.html')` and make sure the path is correct

**Comment by chrisburgin95** [comment]
The correct file path is returned. The application runs correctly when use ``` electron .``` just not when compiled.

**Comment by gillyb** [comment]
I have the same problem... Would like some help...
Also running on mac, and the directory exists. When i run with electron, my app opens, but when packaging it starts a blank screen with no error.

**Comment by mspoulsen** [comment]
I have the exact same problem as gillyb running electron-packager 5.2.1 and using this command:
electron-packager . myapp --ignore="node_modules/(electron-packager|electron-prebuilt)" --platform=win32 --arch=ia32 --version=0.36.3 --overwrite --asar=false

**Comment by malept** [comment]
It seems that we're going to need someone to debug this for us.

**Comment by maxogden** [comment]
Need a failing test case from someone first

**Comment by sethlu** [comment]
Mind having a look at Console on OS X and see if any messages appear when the app launches?

**Comment by willwh** [comment]
Hi guys,

I'm running in to something similar too.

I'm using using shelljs in my main process (and sending data using ipc) 

When I start the app from a terminal:

```
/Applications/dcapp.app/Contents/MacOS  ./Electron
```
![image](https://cloud.githubusercontent.com/assets/398396/13364746/882842c8-dc85-11e5-95ed-ecf9cc31e723.png)

**Comment by kfranqueiro** [comment]
After poking around with your app, it appears that running your app via doubleclicking in Finder does not run with nearly the same PATH that running from a terminal does, so depending on where the `drupal` command ends up installed in your case, it could be that it ends up not finding it when run that way?

I'm not sure if the other users reporting this issue are in the same boat - do they use `shelljs` or `child_process.exec`/etc. in their apps?  Is there a difference running the packaged app via terminal vs. Finder for them?

**Comment by erkyrath** [comment]
Normally you'd run the app by typing `open /Applications/dcapp.app`, not `/Applications/dcapp.app/Contents/MacOS/Electron`.

**Comment by kfranqueiro** [comment]
@erkyrath in my testing, both have the same effect (both work, as opposed to opening directly from Finder).

**Comment by willwh** [comment]
I don't think this is a path issue. The which command should return the location of the arg you pass, if it's in your PATH..... Running my code with npm start works, and from the terminal. Thanks guys for taking a peek at this, I'll be back to poking at it tomorrow.

@erkyrath thx, I'm not that familiar with OSX :)

**Comment by malept** [comment]
@willwh I agree with @kfranqueiro, because last month I helped troubleshoot a similar environment variable problem on OSX. If you look at https://github.com/maxogden/electron-packager/issues/232#issuecomment-170225945, you will note that the `PATH` variable differs between opening it via Finder and via the terminal. In particular, the `/usr/local/{bin,sbin}` paths are added to `PATH` in the terminal. If the [Drupal Console docs](https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/installer.html) are any indication, `drupal` is likely installed in `/usr/local/bin` on your system. If this is the case, you should add `/usr/local/bin` to `PATH` before running `which`.

**Comment by willwh** [comment]
@kfranqueiro @malept thanks for sticking with me and explaining that!

Of course I had the binary for this aliased in my `.zshrc`.

`alias=~/DrupalConsole/bin/drupal`

However, after removing this (and source ~/.zshrc) - when I run ```which drupal``` in my terminal, I see the correct path: `/usr/local/bin/drupal' - although drupal console still doesn't seem to be working in my packaged app.

I'm going to try repackaging, do you have any other advice here? :)

Thank you once again!

**Comment by malept** [comment]
For your app, the short-term fix is to append `/usr/local/bin` to `process.env['PATH']` before you call `which('drupal')`. For a longer-term fix, I suggest creating a configuration option to set how you execute it, given that the docs I linked earlier say that it only exists in `/usr/local/bin` if you want to be able to execute it system-wide.

**Comment by willwh** [comment]
@malept thanks so much for the advice :)

I tried just setting shell.env.PATH += shell.sep + '/usr/local/bin'; in my main,js but still the same problem.

Any other ideas on how I might debug what's going on?

**Comment by malept** [comment]
The only advice I can give at this point is to start putting `console.log` statements everywhere.

**Comment by kfranqueiro** [comment]
You said you tried setting `shell.env.PATH`, but AFAIK `shell` is not a thing that exists...  Did you try setting `process.env.PATH` as @malept said?  That works for me.

**Comment by willwh** [comment]
@kfranqueiro thank you, sorry typo late at night :)

The interesting thing is, that still doesn't work for me, and indeed, if I drop some console.log(process.env.PATH) before and after that - I end up with /usr/local/bin in my $PATH twice (if I run `open /Applications/dcapp.app`

i.e. 

```
function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600});
  console.log(process.env.PATH);
  process.env.PATH += '/usr/local/bin';
  console.log(process.env.PATH);
```

Results in /usr/local/bin in my path twice.

I can't use console.log() to check things from the main process, so I am not sure what to do here.

@kfranqueiro when you say that "works for me" - you're able to open dcapp.app from finder / launch from the Applications directory by double clicking and it shows a desktop notification and the version of Drupal Console?

**Comment by malept** [comment]
> I can't use console.log() to check things from the main process, so I am not sure what to do here.

I believe you can if you open the DevTools Window. (Look at the [tutorial](http://electron.atom.io/docs/v0.36.8/tutorial/quick-start/) and search for `DevTools`.) You may have to do some IPC to get the data where you want it, though. I haven't tested.

**Comment by willwh** [comment]
This is what I am doing now :)

The interesting thing is, I have the following:

```
mainWindow.loadURL('file://' + __dirname + '/index.html');
mainWindow.webContents.openDevTools();
```
and I am trying to use IPC to send data between the main and renderer process.

[ipcRenderer code](https://github.com/willwh/dcapp/blob/master/js/client.js#L4-L10)
[ipcMain code](https://github.com/willwh/dcapp/blob/master/main.js#L57-L83)

As I've said, this works when opening the application from a terminal using `open /Applications/dcapp.app` - but not when run from finder.

So now I am thoroughly confused :)

I really appreciate your help.

**Comment by malept** [comment]
I meant, send the contents of `process.env.PATH` (for example) over IPC (over, for example, a `debug` channel) so you can `console.log()` and see it in the DevTools window.

**Comment by willwh** [comment]
@malept something like this? https://github.com/willwh/dcapp/commit/a758d9e66e768ca635dc7df27ff92a8e5b0a8f38

I get nothing in the DevTools window. I wonder if this is an issue with my implementation of the IPC stuff.

**Comment by willwh** [comment]
Thanks guys for all of your help here. I got IPC stuff working correctly now, and this indeed a path issue.

@malept I actually misread your first note; re: `/usr/local/{bin,sbin}`

So when launched from Finder, or the Icon, my path is `/usr/local/{bin,sbin}`

I tried adding the following inside my createWindow() function; `process.env.PATH = ['/usr/local/bin', process.env.PATH].join(':')` - but that doesn't seem to work.

Once I figure out *where* I should be setting the process.env.PATH in my code, I think I'll be able to call this done :)

(Just for testing purposes: `sudo ln -s /usr/local/bin/drupal /usr/bin/drupal` and my app works as expected, I am not sure why setting the process.env.PATH like above is not working.

**Comment by willwh** [comment]
I'm going to give this a quick test: https://github.com/sindresorhus/fix-path it sounds like it may solve my problem :)

**Comment by willwh** [comment]
Ah well, back to the drawing board I guess, this doesn't seem to work.

**Comment by malept** [comment]
This issue has kind of turned into a catch-all, so I'm going to close it.

## IF YOU HAVE THIS PROBLEM

* Read [our docs on filing bugs](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#before-opening-bug-reportstechnical-issues) and see if your **specific** problem already has another issue created for it (whether it's open or closed)
* If you believe you have a *different* set of problems, file a new issue and **follow the directions in the GitHub issue template**.

**Comment by onmyway133** [comment]
Not sure if this is related to your problem, but please check Console it shows some errors log if any strange things occur. Mine is because of Uncaught Error https://github.com/onmyway133/blog/issues/145
