### ISSUE TITLE
Callback for Filtering

### ISSUE THREAD

**Issue by mitsuhiko** [electron-userland/electron-packager#185]
Currently the only way to filter items to include or not is a regex.  This is especially frustrating because it's basically the wrong way round (instead of include it's an exclude) and there is no good way to reverse it.

For instance right now it's very hard to ignore *all* of `node_modules` *except* some specific ones.  It would be nice if we could provide a callback when using the programmable interface to it.

**Comment by maxogden** [comment]
Have you considered using a separate subfolder for your electron modules? E.g.

- `/myproject/package.json` - put your dev dependencies in here
- `/myproject/app/package.json` - put your electron dependencies in here

That way when you package your app you can just include everything in `/myproject/app` without having to worry about complex filtering.

If that doesn't work for you, another thing you can do now is implement your own app folder preparation logic, e.g. copy the folders you want into a 'build' folder and then use the programmatic API's `dir` option to point at that folder. This way you don't even need to use the `ignore` option.

**Comment by mitsuhiko** [comment]
The core of the issue is that anything that uses webpack will have dependencies that are in node modules that you do not want in the shipped build but some others you do want.
(The reason the regex does not really work is because of nested node modules and it being really hard to say: only ignore this folder if toplevel for instance).

At least in my case it's a lot more complex than that anyways and I have since stopped using electron-packager for the moment.  Right now it's actually easier for me to just manually package up electron as I'm changing a lot of other things anyways from a makefile.

**Comment by mitsuhiko** [comment]
If you are curious what this looks like to get an idea of the setup, the project is here: https://github.com/mitsuhiko/lektor/blob/a1abd505f637adec4bca663630b693b8c67251b3/gui/Makefile#L37-L77

**Comment by malept** [comment]
FWIW, a user contributed a PR to allow the `ignore` parameter to take a function (#247). Admittedly, you'd have to do the inverse of what you want since it's still `ignore` and not `only-include`.

**Comment by jlord** [comment]
Since the updates in #247 allow you to effectively do both default and inverse (as suggested here) and there have not been additional updates to this thread, I think this may be safe to close?

**Comment by malept** [comment]
I have no objection to that.
