### ISSUE TITLE
Rename Binary in OSX (CFBundleExecutable)

### ISSUE THREAD

**Issue by FirePanther** [electron-userland/electron-packager#195]
The name of the binary (in Contents > MacOS) is always Electron for me.
In the Info.plist the value of the key CFBundleExecutable is also Electron instead of the name.
The main problem for me is, when I add the app into the Login Items it says Electron:
![Login Items](http://i.dv.tl/avekc.jpg)
If I have multiple Electron apps I can't differentiate them.

**Comment by imns** [comment]
I'm also having the same issue.  It ignores the `<appname>` and names it `Electron.app`.

**Comment by malept** [comment]
@imns there is a PR to fix this (#244) that needs some tests written before we can merge it.
