### ISSUE TITLE
Add support for setting a Windows manifest different from the embedded Electron default

### ISSUE THREAD

**Issue by codisart** [electron-userland/electron-packager#197]
I used the winreg npm package for my app and I need elevated privileges for the uses I have.

I would like to associate a manifest file with an app build with electron (atom-shell) and packaged on windows with electron-packager but I can not find any way to do it easily.

An old app of mine was made with python and cx_freeze and it sufficed to put the file with the name app.exe.manifest in the same directory.

I can't understand why it doesn't work this time.

**Comment by codisart** [comment]
Hi,

I solved this problem.
So first to know is an external manifest won't count if an embedded manifest is already present. (see answer to http://superuser.com/questions/905103/what-does-it-mean-to-enable-windows-to-prioritise-external-manifests)
And it turns out that the electron.exe has already a manifest embedded and the package done with electron-package is mostly a rename of the electron executable.
So in order to embed a news manifest with the right privileges needed, I took the manifest in the electron repo (https://github.com/atom/electron/blob/master/atom/browser/resources/win/atom.manifest), edited the security section and used the mt.exe tool to add the new manifest https://msdn.microsoft.com/en-us/library/aa375649%28v=vs.85%29.aspx

And tadaa !

**Comment by malept** [comment]
To confirm, it sounds like if someone wanted to modify Electron's manifest, they would need to run `mt.exe` on a Windows machine with the Windows SDK?

**Comment by codisart** [comment]
Exactly.

**Comment by malept** [comment]
OK, I added the appropriate labels and changed the title. Is the new title more appropriate for the feature enhancement request?

**Comment by codisart** [comment]
It seems very fine to me !
But I don't see an easy way to allow this feature.

**Comment by malept** [comment]
This is all theoretical (and I am not going to implement it myself, since I do not own a Windows machine), but shouldn't you be able to add a `manifest=path/to/manifest` parameter, which if set, runs `mt.exe` probably close to the end of building an Electron app for Windows?

**Comment by maxogden** [comment]
meta note, for windows only features we should probably have a section in the readme that is like 'these are all windows only sorry'

**Comment by malept** [comment]
That is a good point. the optional arguments section should be divided into "all platforms" / "Windows Only" / "OS X only" (and then alphabetized within each subsection). But that's for another GitHub issue.

**Comment by malept** [comment]
Now that I've added support for CI in a Windows environment (#326), this seems more doable from a "write tests for this" perspective. I think a person who develops apps for Windows targets, on Windows hosts would be a good fit to work on this.

**Comment by codisart** [comment]
I could be interested to help, but if we follow your suggestion 

> This is all theoretical (and I am not going to implement it myself, since I do not own a Windows machine), but shouldn't you be able to add a win32-manifest=path/to/manifest parameter, which if set, runs mt.exe probably close to the end of building an Electron app for Windows?

What version of mt.exe should we get and where sould we put it ?

**Comment by malept** [comment]
If I understand your question correctly, you should assume that the user already has the Windows SDK (and thus `mt.exe`) installed (and possibly in `PATH`, I'm not sure. This is one of the reasons why I'm not working on it myself). "Getting" `mt.exe` is not possible, as when I researched this issue when it was filed, the Windows SDK did not appear to be redistributable.

I don't know which version of `mt.exe` to require - I would look at how Electron is compiled on Windows for hints.

**Comment by JimiC** [comment]
For future reference [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) download.

**Comment by yani-** [comment]
We've encountered this issue recently and wrote an article on how to update the manifest of electron using mt.exe. Not all mt versions will work: http://layer0.authentise.com/electron-and-uac-on-windows.html
