### ISSUE TITLE
Unable to run packaged app on OS X

### ISSUE THREAD

**Issue by otakustay** [electron-userland/electron-packager#211]
I used `electron-packager-interactive` to simply build my app for OS X:

```shell
? Overwrite output directory ? Yes
? Use asar source packaging ? No
? Select Electron app source directory: /Users/otakustay/Dev/icarus
? Select Electron app output directory: /Users/otakustay/Dev/icarus/releases
? Select Application name: icarus
? Select App Bundle Id (optional):
? Select App Version(optional): 0.0.1
? Select Electron icon file:
? Select Electron version release: 0.35.1
? Select platforms: darwin
? Select architecture: all
Electron packager settings:
{ dir: '/Users/otakustay/Dev/icarus',
  name: 'icarus',
  platform: 'darwin',
  arch: 'all',
  version: '0.35.1',
  out: '/Users/otakustay/Dev/icarus/releases',
  'app-bundle-id': '',
  'app-version': '',
  overwrite: true,
  asar: false,
  icon: '',
  app_version: '0.0.1',
  bundle_id: '',
  appname: 'icarus',
  sourcedir: '/Users/otakustay/Dev/icarus',
  ignore: '/Users/otakustay/Dev/icarus/releases' }
Packaging app for platform darwin x64 using electron v0.35.1
✓ Application packaged successfully to "/Users/otakustay/Dev/icarus/releases/icarus-darwin-x64"
```

However the released `.app` quits immediately after opened, but use electron to directly run the `app` folder works perfectly:

```shell
~/Dev/icarus(branch:master*) » electron /Users/otakustay/Dev/icarus/releases/icarus-darwin-x64/icarus.app/Contents/Resources/app
[2015-12-06 17:34:31.441] [INFO] main - Start app
[2015-12-06 17:34:31.444] [TRACE] main - All data will be saved at /Users/otakustay/Library/Application Support/Icarus Comic Reader
[2015-12-06 17:34:31.536] [TRACE] main - Main window opened with size 800 x 600
[2015-12-06 17:34:32.007] [INFO] router - Register 7 routes
```

I tried to trace the error, it seems that all `require('./xxx')` stops working and generate a "Cannot find module ./xxx" exception, all absolute path such as `require('fs')` or require('underscore') is OK

Is there any point I missed in order to make it run?

**Comment by otakustay** [comment]
I tried to simplify the problem and finally find out that `babel-register` causes the issue, these are what I get in `uncaughtException` event:

```
Error: Couldn't find preset "es2015" relative to directory "/Users/otakustay/Dev/icarus/releases/icarus-darwin-x64/icarus.app/Contents/Resources/atom.asar/browser/api/lib"
```

I'm not quite experienced in `.asar` format but its weired for babel to resolve presets there, when I run `electron ./app` manually this line of code would never be executed

**Comment by otakustay** [comment]
Currently I tell babel to ignore any modules in any `.asar` files and it runs correctly, maybe this is the best solution?

**Comment by malept** [comment]
I'm not sure what electron-packager can do in this situation - this seems to be a problem with the interaction between the babel and asar modules.
