### ISSUE TITLE
Unable to Build for Windows on OS X when sourcedir is "."

### ISSUE THREAD

**Issue by narayananramu** [electron-userland/electron-packager#218]
I tried all possible arguments in CLI yet I still get  "... and 1 more" while building for Windows on OS X. I have also install rcedit, wine. Can anyone clearly document building for Windows on OS X.

**Comment by malept** [comment]
Could you please answer the questions in the [issue reporting documentation](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md) so that we may better help you with your problem?

**Comment by narayananramu** [comment]
Electron Packager - 5.1.1 
CLI

electron-packager . FooBar --platform=win32 --arch=ia32 --version=0.36.0 --icon=assets/win/icon.ico

**Comment by malept** [comment]
What's the exact console output when you run the `electron-packager` command?

**Comment by narayananramu** [comment]
<img width="1119" alt="screen shot 2015-12-14 at 2 28 45 am" src="https://cloud.githubusercontent.com/assets/5837582/11769321/740c38f4-a20a-11e5-9c77-7ccb1bb23910.png">

**Comment by malept** [comment]
I have never seen that error before. Have you tried building a package for OS X instead? (I want to know if it's specific to Windows as the target platform.)

**Comment by narayananramu** [comment]
For OS X it is working perfectly, is there any requirements for building windows package I mean dependencies other than Wine and rcedit for OS X ? There is any other better documentation/tutorial for the same.

**Comment by martianyi** [comment]
same error here, on OSX if using `electron-packager ./ ElectronTest --out=dist --platform=darwin --arch=x64 --version=0.36.7 --asar --overwrite --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager` it works fine, but if I use `electron-packager . ElectronTest --out=dist --all --asar --overwrite --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager`,then it shows
 ```
electron-packager . ElectronTest --out=dist --all --asar --overwrite --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager


... and 1 more
```
and stucks.

I didn't install anything like Wine or rcredit though.

**Comment by drakmail** [comment]
Have almost same issue: 

```
➜  universal-sms electron-packager . --all
Unable to determine application name or Electron version. Please specify an application name and Electron version.
Cannot find module 'package.json' from '/Users/drakmail/Develop/drakmail'(Properties not found yet: dependencies.electron-prebuilt,devDependencies.electron-prebuilt)
➜  universal-sms pwd
/Users/drakmail/Develop/drakmail/universal-sms
```

```
➜  universal-sms ls
bin          db.gdb       index.html   js           main.js      node_modules package.json sender.js    storage.js
```

**Comment by malept** [comment]
@drakmail this is a different error, you need to either add the electron-prebuilt module as a dependency in package.json or specify the Electron version as a parameter. (See readme for details)

**Comment by drakmail** [comment]
@malept Thanks, it's really helps!

**Comment by gvzq** [comment]
When I followed the instructions by using: 
`electron-packager . --all` 
It didn't work! I figured I need to do it manually..

This works in terminal:
`electron-packager ./ App --out=dist --platform=all --arch=all --asar --overwrite --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager
`

**Comment by malept** [comment]
@gvzq I have a comment and a question:

* Per [the docs](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore), `--ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager` is already ignored by default.
* Are you saying that you need to type `./` and not `.`  to correctly specify the app's source directory?

**Comment by gvzq** [comment]
Sorry if I wasn't clear. Running `electron-packager ./ --all` does not execute properly due to a EISDIR error. 

```
electron-app usr$ electron-packager ./ --all
Packaging app for platform linux ia32 using electron v1.3.3
EISDIR: illegal operation on a directory, rename '/var/folders/jk/3cmm8ls96bnc00gfys3vqky80000gn/T/electron-packager/linux-ia32/-linux-ia32/electron' -> '/var/folders/jk/3cmm8ls96bnc00gfys3vqky80000gn/T/electron-packager/linux-ia32/-linux-ia32'
```

**Comment by malept** [comment]
@gvzq this is a different error than this GitHub issue, could you please file a separate issue? (Making sure you read [our docs on filing bugs](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#before-opening-bug-reportstechnical-issues) and follow the directions in the GitHub issue template) It would be much appreciated.

**Comment by gvzq** [comment]
ok @malept

**Comment by kevinsawicki** [comment]
The `... and 1 more` message is a bug in nugget, the library used to download Electron, https://github.com/maxogden/nugget/issues/16

If you make your terminal window bigger then you should see more output about the download happening.

**Comment by kevinsawicki** [comment]
The `... and 1 more` message is a bug in nugget, the library used to download Electron, https://github.com/maxogden/nugget/issues/16

If you make your terminal window bigger then you should see more output about the download happening.

**Comment by malept** [comment]
I'm inclined to close this since this is a dependency bug, then.

**Comment by ggojedap** [comment]
I had the same problem with the same error "... and 1 more" trying to package for win32 from Mac. In my case the solution was to add Wine to PATH.
