### ISSUE TITLE
Not currently possible to ignore devDependencies with npm3

### ISSUE THREAD

**Issue by maxogden** [electron-userland/electron-packager#235]
If you are packaging an app and using npm3, there is no way to easily ignore devDependencies because [npm3 flattens dependencies](https://docs.npmjs.com/how-npm-works/npm3), so there is no way to know ahead of time what things are necessary to include in the `--ignore` list.

I just wanted to mention it here in case someone runs into this issue. The fix is to use the `--yes-prune` flag. Maybe we should consider defaulting this to `true` in the next major version? Is there a downside (other than backwards compat) to defaulting it to true?

**Comment by malept** [comment]
> Maybe we should consider defaulting this to `true` in the next major version?

No objections from me.

We should probably start keeping a `changelog.md` (or `news.md`) for these sorts of breaking changes. (See: http://keepachangelog.com/)

**Comment by malept** [comment]
(See also: part of #35)
