### ISSUE TITLE
`err` callback doesn't seem to always be an Error

### ISSUE THREAD

**Issue by paulcbetts** [electron-userland/electron-packager#252]
The `err` object passed back from the callback is sometimes what seems to be an array of Objects of unknown shape, instead of an Error

```
# Cause EACCES to be thrown
chmod 000 ./path/to/one/of/my/files
```

Then later:

```js
packager(opts, (err, target) => {
  console.log(err instanceof Error);
  >> false

  console.log(err instanceof Array);
  >> true

  console.log(JSON.stringify(err[0]));
  >> {"errno":-13,"code":"EACCES","syscall":"stat","path":"/path/to/one/of/my/files"}
});
```

**Comment by malept** [comment]
Seems like this could be fixed one of two ways:

1. Fix the documentation so that it says the type of `err` varies depending on what threw it
2. Normalize all of the thrown errors

I'm more inclined towards 1.

**Comment by maxogden** [comment]
Heres where the array comes from https://github.com/AvianFlu/ncp/blob/6820b0fbe3f7400fdb283c741ef88b6d8e2d4994/lib/ncp.js#L255 Kinda weird they do that IMO when arrs.length === 1.

**Comment by malept** [comment]
Seems like yet another reason to replace `ncp`.

**Comment by maxogden** [comment]
agreed :) shouldn't even be that hard, `tar-fs` is a great replacement.
just haven't had time

**Comment by paulcbetts** [comment]
Can we actually fix this, instead of just documenting it?

**Comment by malept** [comment]
That would be #151.

**Comment by paulcbetts** [comment]
@malept Awesome, into it
