### ISSUE TITLE
Release 6.0.0

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-packager#266]
I'm moving the discussion about what the next version bump should be from #223 to here. From the comments thread:

> > not sure if this should also mean a major version bump
>
> I'm not sure either. At minimum, we need to clarify that `--all` and `--platform=all` means that all supported platforms are going to be built (and similar for `--arch=all`, I don't want to have the same conversation whenever it is we're unblocked on the `arm7` PR). I would like to do this after this PR is merged.

So the question remains: **Is the next version going to be 5.3.0 or 6.0.0?** Either way, I've made a milestone that has all of the issues I want to close/merge before it's released. (I'd link it but the ID seems to be the name and I'm going to change that once we get a consensus.)

**Comment by malept** [comment]
I'm going to go with 6.0.0 - a backwards incompatible change has been made to both `--platform=all` and `--all`.

**Comment by maxogden** [comment]
:thumbsup:

**Comment by malept** [comment]
OK, I've merged everything I wanted to for 6.0.0. I finally made an NPM account last night, so @maxogden could you add me to the list of collaborators there? It's the same username as here.

**Comment by maxogden** [comment]
Done :)

**Comment by havenchyk** [comment]
@malept when can we expect 6.0? Do you need any help?

**Comment by malept** [comment]
@havenchyk a complication came up, which I think merits a release delay. See the discussion in #285.

**Comment by ledinhphuong** [comment]
:thumbsup: Great to know.
