### ISSUE TITLE
Create issue_template.md and pull_request_template.md

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-packager#267]
See: https://github.com/dear-github/dear-github/issues/125

I have ideas for how to write these in a way that aren't specific to one class of issue/PR or user, I will populate this issue with them later. (Others, feel free to chime in with your opinions.)

**Comment by maxogden** [comment]
hah, great minds think alike. I went ahead and committed one first, but
feel free to edit

On Wednesday, February 17, 2016, Mark Lee <notifications@github.com> wrote:

> See: dear-github/dear-github#125
> <https://github.com/dear-github/dear-github/issues/125>
>
> I have ideas for how to write these in a way that aren't specific to one
> class of issue/PR or user, I will populate this issue with them later.
> (Others, feel free to chime in with your opinions.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/electron-packager/issues/267>.
>


-- 
Sent from my phone

**Comment by malept** [comment]
It appears that HTML comments are allowed in GFM (there is one at the top of this comment). We should use them to our advantage in the issue/PR templates.

**Comment by malept** [comment]
Should figure out how to word something along the lines of "If possible, a GitHub gist with a failing testcase (preferred), or steps to reliably reproduce the problem"

**Comment by maxogden** [comment]
basically "we can only help you if you provide us with something we can run to reproduce your problem"

**Comment by positlabs** [comment]
We need a codepen analog that supports node modules!! How cool would that be?

**Comment by malept** [comment]
> We need a codepen analog that supports node modules!! How cool would that be?

That kind of exists with Travis CI. Doesn't really help with OSX specific problems because Travis doesn't currently support Node on their OSX machines without a bit of contortion.

**Comment by malept** [comment]
https://github.com/maxogden/electron-packager/commit/f2de30b92481a02c473236775fc7ff7239a52f29 has some updated formatting, uses HTML comments, and changes the wording a bit.

**Comment by malept** [comment]
Given #251, I think the pull request template should mention that WIP PRs should have their titles prepended with `[WIP]`.

**Comment by malept** [comment]
Need to add "What version of Node and NPM are you running?" - see #348
