### ISSUE TITLE
Feature Request: non-patented FFMPEG Option

### ISSUE THREAD

**Issue by arcticShadow** [electron-userland/electron-packager#270]
Hi, 
In the last few days, Electron has been released with ffmpeg [dynamically linked,](https://github.com/atom/electron/releases/tag/v0.36.8) with the ability to swap out FFMPEG with an instance that does not contain patented codecs. 

Would it be possible to provide a feature in this packager to swap out this library during the build process. A quick scan of the source shows that the electorn-downloader pulls in the electorn prebuilt. and extracts it, so it seems like it would be trivial to add a second download step to grab the ffmpeg binary  and replace the existing one. 

I'd be happy to look at a PR if this feature holds merit.

**Comment by maxogden** [comment]
Seems like a good idea, but my concerns would be:

- how much code it would add here
- if we can add an api to let people define third party packaging steps
- can it be implemented in a third party that uses o/

**Comment by arcticShadow** [comment]
I don't imagine that much code would be added here. Although, I do like the idea of extending the build process to 3rd party apps. This would potentially open up quite a big customisation opportunity. 

I'll have a think about how this can be implemented, and try do a code dive to figure out the where and how.

**Comment by maxogden** [comment]
Cool sounds good!

**Comment by arcticShadow** [comment]
Done some digging into how this could be achieved. 

I think the best route to enable 3rd party build steps will be: 
* Plugin loader system. All plugins defined as options will be loaded during bootstrap phase. 
* add a "PostBuild" method to common.js (or possibly, a generic method, that takes a build step as a param, and an object/array of options)
* In each linux/mac/win file, after the package/copy process, but before any signing or other final tasks, call the above methods from common, and pass in any relevant args. 
* 3rd party plugin makes changes, and returns to the platform specfic file to continue. 


This feels like it could be a good use of generators. Thoughts?

**Comment by malept** [comment]
Brief searching indicates that generators have been in Node since ~0.11. Is this correct?

**Comment by arcticShadow** [comment]
That sounds right. It would be behind the `--harmony` flag though. Sometimes I forget what is and is not ES5 safe code.

**Comment by malept** [comment]
Hmm. I'm not sure if that's allowable, then.

**Comment by kfranqueiro** [comment]
It's listed as being included with no flags required at this point (though it's unclear to me whether this list pertains to both 4.x and 5.x): https://nodejs.org/en/docs/es6/

**Comment by malept** [comment]
If that's the case and we add code that uses generators, we're going to have to specify a newer Node requirement. I believe the current minimum is 0.12.

**Comment by kfranqueiro** [comment]
Yeah, I just ran a quick test and it's fine with Node 4 but needs the flag on 0.12.

**Comment by kfranqueiro** [comment]
I guess I'm kind of wondering what it'd look like with vs. without generators and whether it's worth introducing them for this one thing.

**Comment by malept** [comment]
I'd want to know how many users use Node 0.12 vs newer versions. Does NPM's website give those sorts of statistics?

**Comment by arcticShadow** [comment]
Can't say i have seen those sort of stats.  I'm not even sure how they could be collected.

Seems like generators will overly complicate the issue. And honestly, I was just looking for an excuse to use them.

**Comment by malept** [comment]
In theory, NPM would send what version of Node it's using when it fetches a package. This is basically how it works in the Python packaging ecosystem, and the team that manages that publishes stats every so often about which Python versions are being used to download packages.

**Comment by arcticShadow** [comment]
Good point - i hadnt thought about other parts of our ecosystem collecting stats

**Comment by maxogden** [comment]
IMO the API should integrate with anywhere we use run-series: https://github.com/maxogden/electron-packager/blob/f2de30b92481a02c473236775fc7ff7239a52f29/index.js#L9. For example it would be easy to allow user defined functions inside series like this one https://github.com/maxogden/electron-packager/blob/f2de30b92481a02c473236775fc7ff7239a52f29/index.js#L81-L91

That way we can just use callbacks which is consistent with all the existing code and works everywhere.

The only question is which points do we need to expose the ability for the user to add their own functions. 

I could imagine it being as simple as functions in the options, e.g.

```
opts.afterExtract = function (done) {}
opts. beforeMove = function done() {}
}
packager(opts)
```

E.g. `afterExtract` would go after [this](https://github.com/maxogden/electron-packager/blob/f2de30b92481a02c473236775fc7ff7239a52f29/index.js#L133-L135) and `beforeMove` would go before [this](https://github.com/maxogden/electron-packager/blob/f2de30b92481a02c473236775fc7ff7239a52f29/common.js#L133-L140)

**Comment by MarshallOfSound** [comment]
https://github.com/electron-userland/electron-packager/pull/354 adds the `afterExtract` option.  Then you just need a small function that requests the patent free FFMPEG from the url in the format

```js
`https://github.com/electron/electron/releases/download/v${electronVersion}/ffmpeg-v${electronVersion}-${platform}-${arch}.zip`
```

**Comment by arcticShadow** [comment]
Awww @MarshallOfSound Do you miss us so much you still want to contribute code ;-)

**Comment by MarshallOfSound** [comment]
New PR --> #403

**Comment by malept** [comment]
I'm closing this because it looks like @MarshallOfSound has implemented it as a plugin for electron-packager: https://www.npmjs.com/package/electron-packager-plugin-non-proprietary-codecs-ffmpeg

**Comment by MarshallOfSound** [comment]
@malept Could it be worth adding that package to the docs?  Possibly a list of plugins (if others start being made)

**Comment by malept** [comment]
@MarshallOfSound Added it to the "related" section of the readme: https://github.com/electron-userland/electron-packager/commit/48b112650f8c36128d90b98bc4b1b5de8664d068

**Comment by avmalyutin** [comment]
Plugin `electron-packager-plugin-non-proprietary-codecs-ffmpeg` is currently available in [npm](https://www.npmjs.com/package/electron-packager-plugin-non-proprietary-codecs-ffmpeg) but, unfortunately, not available on [github](https://github.com/orionhealth/electron-packager-plugin-non-proprietary-codecs-ffmpeg#readme).

@MarshallOfSound Was repository of plugin deleted by accident or there was a reason for that? Or there are good alternatives so the plugin is obsolete now?

p.s. Sorry to bump an old issue but it is an only possible place to raise a quiestion.

**Comment by baparham** [comment]
@avmalyutin [This repo](https://github.com/amilajack/electron-packager-plugin-non-proprietary-codecs-ffmpeg) seems to be the only living relative of that code.

At this point though, perhaps it needs to be adapted to [Electron Forge](https://www.electronforge.io/) so that it's more likely to get first class support from the electron community. Surely @amilajack doesn't have the publish keys to the original npm repo from @MarshallOfSound either, so a new derivative may be needed anyway. I've also tried to implement something similar for electron-builder in https://github.com/electron-userland/electron-builder/pull/7247 but perhaps there's a more common approach that can be taken.

**Comment by erickzhao** [comment]
I believe @~MarshallOfSound's fork of @~amilajack's original code lives here on GitHub: https://github.com/marshallofsound/electron-packager-plugin-non-proprietary-codecs-ffmpeg#readme

**Comment by solarispika** [comment]
Package `electron-packager-plugin-non-proprietary-codecs-ffmpeg` depends on [`7zip`](https://www.npmjs.com/package/7zip) which only supports Windows.
It adds a link in `node_modules/.bin` and code like `spawn('7z', ...)` in other script will find that executable, which is not suitable on non-Windows platform.
