### ISSUE TITLE
Seeking new maintainers

### ISSUE THREAD

**Issue by maxogden** [electron-userland/electron-packager#272]
I'd like to step down as a maintainer of this module. I'm happy to pinged with questions about the code but I don't have time for daily issue triaging, test maintenance, feature requests and release management. If anyone else is interested in maintaining, please get involved in the managing of pull requests and issues as per the [contributing.md](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md) and one of the existing maintainers will eventually add you as a maintainer as per the [open open source](http://openopensource.org/) method that is used to govern this module.

@malept @kfranqueiro as main contributors I'd like to get your feedback on what I should do ownership wise, either transfer the repo to one of your accounts or set up an organization for it.

**Comment by malept** [comment]
@maxogden, if I haven't said it already, many thanks for creating this module.

My suggestion is to set up an organization for this repository. I don't suppose we can set up Travis to publish to NPM when a release tag is created?

Also, we need to make the open open source governance method a bit more prominent in the docs. I think I've only seen it mentioned in issues.

**Comment by maxogden** [comment]
@malept thanks :)

Me and @mafintosh moved this, electron-download and electron-prebuilt to a new org electron-userland. I also now mention open open source more prominently in the readme, and on the org page. We'll still be around to help but won't be as involved on a daily basis. Cheers!

**Comment by develar** [comment]
@malept What about https://github.com/electronjs (I don't know anything, just ask) as an organization?

**Comment by malept** [comment]
@develar that's more of a question for @maxogden, not me.

**Comment by malept** [comment]
@maxogden perhaps we should invite @sethlu and ask to move https://github.com/sethlu/electron-osx-sign into the org (if you haven't done so already).

Also, I'm trying to fix the Coveralls integration. (Coveralls apparently does not like it when repositories move.)

**Comment by maxogden** [comment]
@develar the electronjs org was created by GitHub, and isn't following the open open source governance model. I'd rather have these live in a neutral org

**Comment by sethlu** [comment]
Sounds good! :+1: One question from me is if there be any change of license from BSD-2-Clause? I could move `electron-osx-sign` later today.

**Comment by malept** [comment]
@sethlu I'm not sure what you're asking regarding the license. The license for both electron-packager and electron-osx-sign look the same to me. The author line would obviously be different since there are different contributors.

**Comment by sethlu** [comment]
@malept I'm just slightly unsure if to switch to another license as moving it to an org. I'll be keeping it like that for now.

**Comment by malept** [comment]
@sethlu you're fine.

**Comment by sethlu** [comment]
@malept Just tried to move my repo to `electron-userland`; it seems that I may have to be an admin before completing the transfer: https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization.

**Comment by malept** [comment]
@sethlu I would do something about that myself, but I am not an owner in the org.

**Comment by maxogden** [comment]
sorry, you are now :)

On Sunday, February 28, 2016, Mark Lee <notifications@github.com> wrote:

> @sethlu <https://github.com/sethlu> I would do something about that
> myself, but I am not an owner in the org.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/electron-userland/electron-packager/issues/272#issuecomment-190041949>
> .
>


-- 
Sent from my phone

**Comment by malept** [comment]
@sethlu you should be able to transfer now :smile:

**Comment by sethlu** [comment]
@malept @maxogden Great, thanks! Just transferred the repo. I'll be updating the authors etc. later.

**Comment by malept** [comment]
FYI, I've left this issue open mostly because we are lacking a maintainer who can solve issues relating to building on the Windows host platform.

**Comment by malept** [comment]
Since nothing's happened in about 3 years, I'm closing this issue. This does not, however, mean that we're not still looking for new maintainers, particularly those who can debug on Windows platforms.

**Comment by JohnTitor** [comment]
@malept It may be a little late, but I'm interested in contributing and maintaining.

**Comment by malept** [comment]
@JohnTitor thanks for your interest! The best way to get started with contributing is going through the [open "help wanted"](https://github.com/electron/electron-packager/labels/help%20wanted%20%3Araised_back_of_hand%3A) issues and seeing if any fit your skillset.
