### ISSUE TITLE
Various errors in Mac Console

### ISSUE THREAD

**Issue by positlabs** [electron-userland/electron-packager#273]
I'm preparing to submit to the Mac app store, but I want to make sure there's no reason for rejection. There are various errors showing in Console. They seem harmless, and the app still functions normally

> Which version of electron-packager are you using?

5.2.1 on master

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

```
{
		dir: './',

		name: 'GifGoat',
		icon: './build/mac-extras/icons/icon.icns',

		platform: 'mas',
		arch: 'x64',
		version: 'v0.35.6',

		'app-copyright': 'Posit Labs 2016',

		'app-version': pkg.version,
		'build-version': pkg.version,
		
		asar: true,
		'asar-unpack-dir': 'bin/',

		'app-bundle-id': 'com.positlabs.gifgoat',
		'app-category-type': 'public.app-category.utilities',

		sign: '3rd Party Mac Developer Application: ...',
		'sign-entitlements': './build/mac-extras/parent.plist',
		'entitlements-inherit': './build/mac-extras/child.plist',

		prune: true,

		ignore: [
			'/bin/ffmpeg/linux($|/)',
			'/bin/ffmpeg/win32($|/)',
			'/dist($|/)',
			'/build($|/)',
			'/test($|/)',
		],

		out: './dist/',
		overwrite: true
	}
```

> What version of [Electron](http://electron.atom.io) are you building with?

v0.35.6

> What is the host platform are you running electron-packager on?

OSX 10.11.3

> What target platform(s)/architecture(s) are you building for?

mas, x64

> Is there a stack trace in the error message you're seeing?

![screen shot 2016-02-28 at 9 35 59 am](https://cloud.githubusercontent.com/assets/1918844/13380776/3f1082f0-ddff-11e5-85e9-a04c9309dcbb.png)

> Please provide either a failing testcase or detailed steps to reproduce your problem.

May not be necessary, but I can put one together if it is.

**Comment by malept** [comment]
I can't help with debugging this particular problem (@sethlu would be a better person to help), but I had a question on one thing:

> `version: 'v0.35.6',`

Do you have `electron-prebuilt` in `package.json`? I ask because specifying a version with a leading `v` should not work.

**Comment by positlabs** [comment]
Sorry, I copy/pasted the version without thinking. It's actually being pulled straight from the electron-prebuilt package.json. 

`		version: require('./node_modules/electron-prebuilt/package.json').version,
`

**Comment by malept** [comment]
As of [5.2.1](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#521---2016-01-17), you don't need to set that explicitly if you have `electron-prebuilt` in your `package.json`. But that's not likely relevant to the problem you're seeing.

**Comment by sethlu** [comment]
Here are some immediate thoughts I have:

- Never mind the `sandboxd` logs: There have been trials by others trying to get Chromium more compliant with the Mac App Store. However, the serials in the end of `org.chronium.Chronium.rohitfork.*` and `org.chronium.Chronium.iosurfacemgr.*`, due to `ipc`, are going to stay there until better fixes are made. It should not matter much on the overall performance.
- The log from `Finder` looks extremely long and there seems to be 5 apps, one inside another?
- I haven't tried much with `asar` unpacking. The final line looks related to that setting I suppose? @malept

**Comment by malept** [comment]
@sethlu looks like it. Admittedly, I am not well versed in how the asar feature works.

**Comment by positlabs** [comment]
I was requiring electron-packager in a non-standard way, and I think it was causing some issues. I've `npm install`ed it like a responsible adult, and now the first error is resolved. 

The last error in that list is unrelated to asar. It's only there after signing/packaging. Probably another issue with sandboxing.

I suppose I'll ignore it for now since it seems harmless. Wish me luck on the next submission! Thanks for your help!
