### ISSUE TITLE
Cannot install from npm: "Refusing to install electron-packager as a dependency of itself"

### ISSUE THREAD

**Issue by zoiobnu** [electron-userland/electron-packager#277]
[npm-debug.txt](https://github.com/electron-userland/electron-packager/files/151105/npm-debug.txt)

I'm trying to install but give me this errors

Arch Linux x86_64
Kernel 4.4

**Comment by malept** [comment]
According to this line:

> 43 verbose cwd /home/zoio/Downloads/electron-packager

You're trying to run `npm install electron-packager` inside of this cloned git repository, which NPM does not want you to do. If you're trying to install electron-packager from the repository you cloned onto your local machine, look at the [`npm install` docs](https://docs.npmjs.com/cli/install), specifically the details around `npm install <folder>`.
