### ISSUE TITLE
AutoIgnore Dev Dependencies

### ISSUE THREAD

**Issue by ccorcos** [electron-userland/electron-packager#279]
Its a pain in the add to get all the dev dependencies into a regex to ignore -- all my webpack build stuff and their dependencies gets bundled otherwise. There are hundreds! It would be awesome if the default fucntionality was to use `npm ls --dev --parseable` to get all the deps that shouldnt depend on the build

> Which version of electron-packager are you using?

Using the latest verion. 0.35.6

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

> What version of [Electron](http://electron.atom.io) are you building with?

> What is the host platform are you running electron-packager on?

> What target platform(s)/architecture(s) are you building for?

> Is there a stack trace in the error message you're seeing?

> Please provide either a failing testcase or detailed steps to reproduce your problem.

**Comment by positlabs** [comment]
See #35 and related issues.
