### ISSUE TITLE
Build on/for OSX doesn't work from Gulp

### ISSUE THREAD

**Issue by z-ax** [electron-userland/electron-packager#281]
Greetings. I want to build app from Gulpfile.js, here's the code example:

```js
'use strict';

const gulp = require('gulp'),
    packager = require('electron-packager'),
    pkg = require('./app/package.json'),
    util = require('gulp-util');

// ...

gulp.task('build:osx', (callback) => {
    let opts = {
            platform: 'darwin',
            arch: 'all',
            asar: true,
            cache: './cache',
            dir: './app',
            icon: './app/img/icon.icns',
            ignore: 'tests',
            name: pkg.name,
            out: './build',
            overwrite: true,
            //prune: false,
            //tmpdir: './tmp',
            version: pkg.electronVersion,
            'app-version': pkg.version
        };

    util.log('Building', util.colors.cyan(opts.name), util.colors.magenta('v' + opts.appVersion));

    packager(opts, (err, appPath) => { util.log(' <- packagerDone()', err, appPath); });
});
```

> Which version of electron-packager are you using?

5.2.1

> What version of [Electron](http://electron.atom.io) are you building with?

0.36.9

> What is the host platform are you running electron-packager on?

OS X 10.11.3

> What target platform(s)/architecture(s) are you building for?

`darwin`

> Is there a stack trace in the error message you're seeing?

```
$ gulp build:osx
[20:59:36] Using gulpfile ~/Repo/test-app/gulpfile.js
[20:59:36] Starting 'build:osx'...
[20:59:36] Building test-app v0.3.1-1
Packaging app for platform darwin x64 using electron v0.36.9
```

The thing is at this point I used `gulp-electron`, all at least builds & runs, but decided to try this one because some stuff is not ideal - like icon of file `test-app.exe` for Windows.

Here I just see if it starts the `packager` (and downloads cached version of Electron if needed) and that's it. Callback isn't called at all (where I have console log). And exits silently.

Running Gulp with `--verbose` didn't show any additional lines.

Also, I tried at first options like `"app-version": ...`, or camel case. Just can't figure out why it has no output. Even if `./build` folder exists or not.

So, what am I doing wrong?

Thanks in advance.

**Comment by malept** [comment]
How long does it take for electron-packager to run?

**Comment by z-ax** [comment]
@malept, about 3-4s.
Just checked with v0.36.10 - same behaviour.
Node v5.7.1.

Forgot to tell: cached Electron is stored finely in `./cache` (directory is created if doesn't exist). But no `./build` dir created (and nothing built with existing dir).

**Comment by z-ax** [comment]
Hey, just checked with v6.0.0 and it's fine (except bug #300). Thanks for updates!
