### ISSUE TITLE
Packaging Windows binary from OS X using Asar, still lots of files

### ISSUE THREAD

**Issue by lmatteis** [electron-userland/electron-packager#282]
When I package the Windows binary from OS X, even with Asar parameter set to true (I'm doing it programmatically), it still returns lots of different files rather than a single executable:

![screen shot 2016-03-04 at 6 17 27 pm](https://cloud.githubusercontent.com/assets/535442/13543779/f659f856-e26e-11e5-9ce4-fd1c494e565c.png)

Any ideas how to get a single .exe binary with everything inside?

> Which version of electron-packager are you using?

I'm using `"electron-packager": "^5.2.0"`

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

I'm using the API. Here's the parameters:

```js
{ dir: './',
  name: 'FooBar',
  asar: true,
  ignore: 
   [ '/test($|/)',
     '/tools($|/)',
     '/release($|/)',
     '/node_modules/asar($|/)',
     '/node_modules/babel-core($|/)',
     '/node_modules/babel-eslint($|/)',
     '/node_modules/babel-loader($|/)',
     '/node_modules/babel-plugin-add-module-exports($|/)',
     '/node_modules/babel-plugin-webpack-loaders($|/)',
     '/node_modules/babel-polyfill($|/)',
     '/node_modules/babel-preset-es2015($|/)',
     '/node_modules/babel-preset-react($|/)',
     '/node_modules/babel-preset-react-hmre($|/)',
     '/node_modules/babel-preset-stage-0($|/)',
     '/node_modules/chai($|/)',
     '/node_modules/chromedriver($|/)',
     '/node_modules/co-mocha($|/)',
     '/node_modules/concurrently($|/)',
     '/node_modules/cross-env($|/)',
     '/node_modules/css-loader($|/)',
     '/node_modules/del($|/)',
     '/node_modules/electron-packager($|/)',
     '/node_modules/electron-prebuilt($|/)',
     '/node_modules/electron-rebuild($|/)',
     '/node_modules/eslint($|/)',
     '/node_modules/eslint-config-airbnb($|/)',
     '/node_modules/eslint-plugin-react($|/)',
     '/node_modules/express($|/)',
     '/node_modules/extract-text-webpack-plugin($|/)',
     '/node_modules/fbjs-scripts($|/)',
     '/node_modules/file-loader($|/)',
     '/node_modules/jsdom($|/)',
     '/node_modules/json-loader($|/)',
     '/node_modules/minimist($|/)',
     '/node_modules/mocha($|/)',
     '/node_modules/node-libs-browser($|/)',
     '/node_modules/react-addons-test-utils($|/)',
     '/node_modules/redux-devtools($|/)',
     '/node_modules/redux-devtools-dock-monitor($|/)',
     '/node_modules/redux-devtools-log-monitor($|/)',
     '/node_modules/redux-logger($|/)',
     '/node_modules/selenium-webdriver($|/)',
     '/node_modules/sinon($|/)',
     '/node_modules/style-loader($|/)',
     '/node_modules/url-loader($|/)',
     '/node_modules/webpack($|/)',
     '/node_modules/webpack-dev-middleware($|/)',
     '/node_modules/webpack-hot-middleware($|/)',
     '/node_modules/webpack-target-electron-renderer($|/)' ],
  icon: 'app/app.ico',
  version: '0.36.9',
  platform: 'win32',
  arch: 'x64',
  prune: true,
  'app-version': '0.1.1',
  out: 'release/win32-x64' }
```

> What version of [Electron](http://electron.atom.io) are you building with?

`"electron-prebuilt": "^0.36.9"`

> What is the host platform are you running electron-packager on?

OS X Yosemite, 10.10.5

> What target platform(s)/architecture(s) are you building for?

win32-x64

> Is there a stack trace in the error message you're seeing?

No errors, just undesired behavior. With Asar I thought I would get a single binary.

**Comment by malept** [comment]
Thanks for filing an issue! This was answered in another related issue (#152).

The short answer is that you need to either find or create a module that does this for you. As I understand it, asar is meant to bundle all of your source code, not the Electron binaries. We would be happy to consider a pull request to integrate a module that bundles the Electron binaries.
