### ISSUE TITLE
Avoid the double dash when passing command line arguments to the app

### ISSUE THREAD

**Issue by brrd** [electron-userland/electron-packager#283]
I noticed that once the app is packaged, command line arguments must be passed after a double dash: `$ ./myApp -- --arg1 --arg2`

On Windows, I even noticed that you need to add it twice: `$ ./myApp.exe -- -- --arg1 --arg2`

Is there a way to avoid this behaviour in order to use a simple `$ ./myApp --arg1 --arg2` instead?

> Which version of electron-packager are you using?

`"electron-packager": "^5.2.1"`

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

Please see: https://github.com/brrd/Abricotine/blob/845b4016bda252ea6f58846c63cf7529c169314b/scripts/packager.js#L42

> What version of [Electron](http://electron.atom.io) are you building with?

`"electron-prebuilt": "^0.35.0"`

> What is the host platform are you running electron-packager on?

Linux Ubuntu 12.04 64 bit and Windows 7 64 bits. I could not try it on OS X.

> What target platform(s)/architecture(s) are you building for?

Same as above.

> Is there a stack trace in the error message you're seeing?

None.

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Download one of the provided binaries: https://github.com/brrd/Abricotine/releases/tag/0.2.2

And run: 

* `$ ./Abricotine --debug` => not working
* then `$ ./Abricotine -- --debug` => working (the Debug menu appears)

**Comment by malept** [comment]
FWIW, on apps built for the Linux target platform I don't need to add the `--`. I tested on a 64-bit Linux app using Electron 0.36.2.

Does the Windows behavior still occur when you run the app without packaging it? If it does, then this is a bug in Electron itself, not electron-packager.

**Comment by brrd** [comment]
> I tested on a 64-bit Linux app using Electron 0.36.2

I tried again on Linux 64 with an upgraded Electron (0.36.10) and I got the same behaviour than before.

> Does the Windows behavior still occur when you run the app without packaging it?

Running `$ ./node_modules/.bin/electron . --debug` from the project directory works well (electron is installed as a dev-dependency).

**Comment by malept** [comment]
I can confirm that your app needs the extra `--` but mine still doesn't after upgrading to 0.36.10.

What happens if you set `asar` to `false`?

**Comment by brrd** [comment]
Oh wait a minute... I tried a simple `console.log(process.argv)` at the very beginning of my code and it outputs the correct arguments, so the issue is obviously coming from my app. (This looks like a bug with [`nconf` module](https://github.com/indexzero/nconf#argv), the module [I use](https://github.com/brrd/Abricotine/blob/master/app/abr-window.js#L34) to parse optional arguments such as `--debug` here.)

Well, this issue is probably not related to electron-packager. Sorry for this irrelevant report. 
Thanks for your help indeed!

**Comment by zinwalin** [comment]
> I noticed that once the app is packaged, command line arguments must be passed after a double dash: `$ ./myApp -- --arg1 --arg2`
> 
> On Windows, I even noticed that you need to add it twice: `$ ./myApp.exe -- -- --arg1 --arg2`
> 
> Is there a way to avoid this behaviour in order to use a simple `$ ./myApp --arg1 --arg2` instead?
> 
> > Which version of electron-packager are you using?
> 
> `"electron-packager": "^5.2.1"`
> 
> > What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> > you passing to the `packager()` function?
> 
> Please see: https://github.com/brrd/Abricotine/blob/845b4016bda252ea6f58846c63cf7529c169314b/scripts/packager.js#L42
> 
> > What version of [Electron](http://electron.atom.io) are you building with?
> 
> `"electron-prebuilt": "^0.35.0"`
> 
> > What is the host platform are you running electron-packager on?
> 
> Linux Ubuntu 12.04 64 bit and Windows 7 64 bits. I could not try it on OS X.
> 
> > What target platform(s)/architecture(s) are you building for?
> 
> Same as above.
> 
> > Is there a stack trace in the error message you're seeing?
> 
> None.
> 
> > Please provide either a failing testcase or detailed steps to reproduce your problem.
> 
> Download one of the provided binaries: https://github.com/brrd/Abricotine/releases/tag/0.2.2
> 
> And run:
> 
> * `$ ./Abricotine --debug` => not working
> * then `$ ./Abricotine -- --debug` => working (the Debug menu appears)

Any solution for this issue?

**Comment by malept** [comment]
I don't think this is an Electron Packager specific issue. You'll have better luck getting support from one of the community forums: https://electronjs.org/community
