### ISSUE TITLE
Do native modules compile for Windows using Wine on OS X?

### ISSUE THREAD

**Issue by lmatteis** [electron-userland/electron-packager#284]
Whenever I try the package on other platforms than mac, the window opens but I get a blank screen. On Mac I had to run this in order to make my native modules working https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

I'm wondering if, through Wine, this also happens when packaging my app. I should be able to compile the native modules using Wine no? Or do I actually need a Windows computer?

> Which version of electron-packager are you using?

I'm using `"electron-packager": "^5.2.0"`

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

I'm using the API. Here's the parameters:

```js
{ dir: './',
  name: 'FooBar',
  asar: true,
  ignore: 
   [ '/test($|/)',
     '/tools($|/)',
     '/release($|/)',
     '/node_modules/asar($|/)',
     '/node_modules/babel-core($|/)',
     '/node_modules/babel-eslint($|/)',
     '/node_modules/babel-loader($|/)',
     '/node_modules/babel-plugin-add-module-exports($|/)',
     '/node_modules/babel-plugin-webpack-loaders($|/)',
     '/node_modules/babel-polyfill($|/)',
     '/node_modules/babel-preset-es2015($|/)',
     '/node_modules/babel-preset-react($|/)',
     '/node_modules/babel-preset-react-hmre($|/)',
     '/node_modules/babel-preset-stage-0($|/)',
     '/node_modules/chai($|/)',
     '/node_modules/chromedriver($|/)',
     '/node_modules/co-mocha($|/)',
     '/node_modules/concurrently($|/)',
     '/node_modules/cross-env($|/)',
     '/node_modules/css-loader($|/)',
     '/node_modules/del($|/)',
     '/node_modules/electron-packager($|/)',
     '/node_modules/electron-prebuilt($|/)',
     '/node_modules/electron-rebuild($|/)',
     '/node_modules/eslint($|/)',
     '/node_modules/eslint-config-airbnb($|/)',
     '/node_modules/eslint-plugin-react($|/)',
     '/node_modules/express($|/)',
     '/node_modules/extract-text-webpack-plugin($|/)',
     '/node_modules/fbjs-scripts($|/)',
     '/node_modules/file-loader($|/)',
     '/node_modules/jsdom($|/)',
     '/node_modules/json-loader($|/)',
     '/node_modules/minimist($|/)',
     '/node_modules/mocha($|/)',
     '/node_modules/node-libs-browser($|/)',
     '/node_modules/react-addons-test-utils($|/)',
     '/node_modules/redux-devtools($|/)',
     '/node_modules/redux-devtools-dock-monitor($|/)',
     '/node_modules/redux-devtools-log-monitor($|/)',
     '/node_modules/redux-logger($|/)',
     '/node_modules/selenium-webdriver($|/)',
     '/node_modules/sinon($|/)',
     '/node_modules/style-loader($|/)',
     '/node_modules/url-loader($|/)',
     '/node_modules/webpack($|/)',
     '/node_modules/webpack-dev-middleware($|/)',
     '/node_modules/webpack-hot-middleware($|/)',
     '/node_modules/webpack-target-electron-renderer($|/)' ],
  icon: 'app/app.ico',
  version: '0.36.9',
  platform: 'win32',
  arch: 'x64',
  prune: true,
  'app-version': '0.1.1',
  out: 'release/win32-x64' }
```

> What version of [Electron](http://electron.atom.io) are you building with?

`"electron-prebuilt": "^0.36.9"`

> What is the host platform are you running electron-packager on?

OS X Yosemite, 10.10.5

> What target platform(s)/architecture(s) are you building for?

win32-x64

**Comment by malept** [comment]
In theory, you can build native node modules via Wine. However, this assumes that the following also runs without problems in Wine:

* Node.js
* electron-packager
* Either the command line Microsoft's C++ compiler, GCC's g++, or LLVM's clang

This is because, as far as I know, there is no way to cross-compile native node modules. You would need to recreate a build environment entirely in Wine.
