### ISSUE TITLE
Pass binaries option to electron-osx-sign

### ISSUE THREAD

**Issue by positlabs** [electron-userland/electron-packager#285]
I have some extra binaries that need signing. Currently, I'm signing them with a bash script, but ideally it would be all handled by `electron-packager`. 

Since this is already a feature of `electron-osx-sign`, it could be solved by adding an extra argument; `binaries` or maybe `osx-binaries` for clarity. This argument would then be passed to `electron-osx-sign`.

Let me know what you think and I'll create a PR.

**Comment by malept** [comment]
I don't have any reason to be against the feature in general. I'd call it `osx-binaries`.

However, I'm beginning to think there needs to be a better way to pass arguments to `electron-osx-sign`. That would be the fourth argument that just passes information to that module. Perhaps it should be named `sign-options`, and function like how `version-string` works for Windows targets. I would even be willing to delay releasing 6.0.0 (that I was going to release today) if it meant saner parameters moving forward.

CC: @sethlu

**Comment by positlabs** [comment]
Agreed. Makes sense to group them. 

I'm imagining something like this:
```
'osx-sign': {
  'bundle-identifier': {String},
  'entitlements': {path},
  'entitlements-inherit': {path},
  'binaries': {Array of paths}
}
```

**Comment by malept** [comment]
That seems reasonable - then for the hypothetical Windows version, you would have `windows-sign`.

If I were to work on this, I would reorganize the docs first, then implement.

**Comment by positlabs** [comment]
I'm pretty busy this week, but I can pick it up this weekend.

**Comment by sethlu** [comment]
It's a good point to group those options; however, we may need some extra lines of code for this to work with the command line as we are trying to put several arguments into one object like `electron-packager ... --osx-sign`? But this looks like a neat solution to cross-platform support.

I'm thinking about the integration of `opts.all`: If we're separating the different platforms' opts then someone using it should specify for each of the platforms the different params. Would it be better just to attach some prefixes so they still work with the command line arguments while keeping from nesting objects in `opts`? And then docs could be categorized for the various platforms.

@jasonhinkle and I have briefly discussed in https://github.com/electron-userland/electron-osx-sign/issues/13 on signing on the Windows platform.

**Comment by malept** [comment]
@sethlu here is an example of a set of options that are grouped together already, that's Windows-specific: https://github.com/electron-userland/electron-packager/blob/c2dd6c26c19223fff6e1ef0a411e3a7ce8e94ffe/usage.txt#L48-L59

**Comment by malept** [comment]
Moving the grouping discussion to #286.

**Comment by malept** [comment]
Per discussion in #286, this is getting pushed to post-6.0.0. Any `binaries` related questions should move back here.

**Comment by malept** [comment]
@sethlu do we still want to support this option in electron-packager?

**Comment by sethlu** [comment]
Hi @malept, sorry I've been traveling lately. I guess we could ignore `opts.binaries` because `electron-osx-sign` should discover this files by default. However, if anyone really encounters such issue, they could file it under `electron-osx-sign`... We should be able to resolve it then.

**Comment by malept** [comment]
OK, I will prepare a PR soon to prevent `binaries` from being passed via the `osx-sign` option.
