### ISSUE TITLE
Unable to package binary from F23x64 for win

### ISSUE THREAD

**Issue by Enelar** [electron-userland/electron-packager#287]
I were un-succeeded to get properly working binary. Windows binaries under wine/virtualbox failing with `A Javascript error occured in main process`. Even with i'm packaging empty file, or `electron-quck-start`.

> **Which version of electron-packager are you using?**

`electron-packager@5.2.1`

> **What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are you passing to the `packager()` function?**

```
> electron-quick-start@1.0.0 package /home/kberezin/code/electron-quick-start
> electron-packager ./ electron-quick-start --platform=win32 --arch=ia32 --out ./releases --version 0.34.1 --overwrite
```

> **What version of [Electron](http://electron.atom.io) are you building with?**

`We are using node 5.1.1, Chrome 47.0.2526.110, and Electron 0.36.8.`

> **What is the host platform are you running electron-packager on?**

`4.4.3-300.fc23.x86_64` (`Fedora 23 Workstation x64`)

> **What target platform(s)/architecture(s) are you building for?**

`Windows ia32/x64

> **Is there a stack trace in the error message you're seeing?**

`no, build succeed, i have empty console under windows`

> **Please provide either a failing testcase or detailed steps to reproduce your problem.**

```
Download any electron example
Trying to build for windows
See error in main process message box
Meditate
```

UPD: Same with `electron@0.36.8`

**Comment by malept** [comment]
According to your CLI arguments, you're building for Electron 0.34.1, not 0.36.8.

There's no other message than "A Javascript error occured in main process"?

Can you build and run a Linux app?

As an aside, have you gotten any Electron-based app (like Atom) running under Wine? I've tried unsuccessfully a few times.

**Comment by Enelar** [comment]
@malept, it was update. I rebuild-ed with 0.36.8 version.

If it would help, i will package for linux. But i ment unsatisfied dependencies. (first was libgtk-x11). Let me few minutes.

**Comment by malept** [comment]
> Atom said that he wants windows vista or later.

Right, you can set up Wine so that it declares itself, as, for example, Windows 7.

**Comment by Enelar** [comment]
@malept  lets pause wine research for the moment. my release dates are burning.

**Comment by Enelar** [comment]
I were succeed to run executiva at the f64, should i check i686?
Trying to run under virtual box (windows 7)

**Comment by malept** [comment]
If Linux 64bit works, 32bit will likely work as well.

I can't test in a non-Wine Windows environment for several hours.

**Comment by Enelar** [comment]
OCR:
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot ﬁnd module
'C:\Users\USER‘\Des|ctop\testapp-win32- ia32‘\resources\app\app\init.js'
at Function.Module._resohreFilename (moduleg'sz338:15)
at Function.Module._load (moduleg'sz289:25)
at Object.<anonymous>
(C:\Users\USER‘\Des|ctop\testapp-win32- i332‘\resources\atom.asar\browser\lib\init...:8)
at Module._compile (moduleg'sz425zﬁ)
at Object.Module._extensions..js (modulejs:432:10)
at ModuleJoad (moduleg'sz356:32)
at Function.Module._load (moduleg'sz313:12)
at Function.Module.runMain (moduleg'sz457:10)
at startup (nodeJ:151:18)
at node.js:1007:3
```

I saw issue without relative path require. I am using:
```
electron app/init.js
and then
require('./system')
```

**Comment by malept** [comment]
Just so that I understand you correctly (and so I can reproduce this when I have access to a Windows environment), I have to:

1. `git clone https://github.com/atom/electron-quick-start`
2. `npm install`
3. `npm install electron-packager --save-dev`
4. Add `other_file.js` and `require('other_file')` it (without a relative path?) in `main.js`
5. `electron-packager ./ QuickStart --platform=win32 --arch=x64`
6. Run app in Windows environment

**Comment by Enelar** [comment]
3.1 `mkdir app`
3.2 Move source code there
3.3 Change `package.json` start script to `electron app/main.js`

I got success binary, will research what cause. At least it possible for me.

**Comment by kevinsawicki** [comment]
This looks like a path require issue with the app code itself, not related to electron packager. You may want to inspect the `__dirname` value in the dev tools Console to check the directory path that relative paths will be resolved against from your app's main module.

Please comment if you are still able to reproduce this, and if so, please provide a sample app that reproduces the issue, thanks.

**Comment by Enelar** [comment]
@kevinsawicki sorry for late responce. As i told in topic, application that refused to compile was `electron-quick-start@1.0.0`. 

As far as i remember it was somehow affected by execution attempts through wine.
