### ISSUE TITLE
Unsupported platform mas; must be one of: darwin, linux, win32

### ISSUE THREAD

**Issue by kasik96** [electron-userland/electron-packager#288]
Hi :). I trying to package my Electron app, but i still geting error:
Unsupported platform mas; must be one of: darwin, linux, win32

I use this:
electron-packager ~/ProjectFolder Project --platform=mas --arch=x64 --app-bundle-id=com.me.project --app-category-type=public.app-category.business --version=0.35.6 --helper-bundle-id=com.me.project.helper --app-version=1.0.1

Any help with this? Thansk :)

**Comment by sethlu** [comment]
Hi @kasik96, please check https://github.com/electron-userland/electron-packager/issues/266. Platform `mas` should be supported in the next release of module.

**Comment by kasik96** [comment]
So that means im not able to make Electron App version to App Store?

**Comment by malept** [comment]
Until 6.0.0 is released (subscribe to #266 for updates), you need to install `electron-packager` from its git repository. For instructions on how to do that, please see the [`npm install` documentation](https://docs.npmjs.com/cli/install) for packages using a "git remote url".
