### ISSUE TITLE
CONTRIBUTING.md link on homepage goes to 404 page

### ISSUE THREAD

**Issue by gsaqui** [electron-userland/electron-packager#295]
The CONTRIBUTING.md link on the homepage goes to a 404 when I click on it.  Link goes to https://github.com/electron-userland/electron-packager/blob/master/contributing.md

> Which version of electron-packager are you using?
It's the github site

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?
NA

> What version of [Electron](http://electron.atom.io) are you building with?

NA

> What is the host platform are you running electron-packager on?

NA

> What target platform(s)/architecture(s) are you building for?
NA

> Is there a stack trace in the error message you're seeing?

NA

> Please provide either a failing testcase or detailed steps to reproduce your problem.
NA

**Comment by malept** [comment]
Thanks for reporting!
