### ISSUE TITLE
--icon option does not work under Electron 0.37.4 (darwin)

### ISSUE THREAD

**Issue by erkyrath** [electron-userland/electron-packager#300]
In Electron 0.37.4, the CFBundleIconFile entry in Electron.app/Contents/Info.plist has been renamed from atom.icns to electron.icns. The associated file in Electron.app/Contents/Resources has also been renamed.

The code in mac.js still copies the --icon argument file to atom.icns, so the file winds up in the wrong place.

(This is electron-packager 6.0.0, but previous versions behaved the same.)

I assume we want to continue supporting old versions of Electron as well as 0.37.4. The fix should therefore involve peeking at the CFBundleIconFile key to copy the file to the right place, *or* altering the CFBundleIconFile key to match the given --icon filename.

**Comment by industral** [comment]
Please update npm package as well. Thanks!

**Comment by malept** [comment]
I want #298 to be merged before a new release (because it suffers from the same problem).

**Comment by phaibin** [comment]
This is a critical bug. Please release a new npm package ASAP. Thanks!

**Comment by malept** [comment]
Two workarounds exist, until 6.0.1 is released:

* Install electron-packager using the GitHub syntax (see `npm install --help`)
* Package your Electron app using a version of Electron earlier than 0.37.4, for example 0.37.3.
