### ISSUE TITLE
Package error on Windows

### ISSUE THREAD

**Issue by vibolvireak** [electron-userland/electron-packager#302]
I'm not successfully packaging my app with electron-packager

I have install electron package with command `npm i electron-packager --save-dev`
and i start edit to my package.json on the script to include packager also run the command `npm run build` 
here is my npm-debug.log

`
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild testing@1.0.0
6 info build testing@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info testing@1.0.0 Failed to exec build script
9 verbose stack Error: testing@1.0.0 build: `electron-packager . myapp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid testing@1.0.0
11 verbose cwd C:\Users\admin\Documents\myapp
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error testing@1.0.0 build: `electron-packager . myapp`
17 error Exit status 1
18 error Failed at the testing@1.0.0 build script 'electron-packager . myapp'.
18 error This is most likely a problem with the testing package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron-packager . myapp
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs testing
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls testing
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

`

```
"scripts": {
    "start": "electron .",
    "build": "electron-packager . myapp"
},
```
info
**
nodejs v4.4.2 LTS 
"electron-packager": "^6.0.0",
"electron-prebuilt": "^0.37.4"**

**Comment by malept** [comment]
It looks like you didn't specify which target platforms you're building for. Take a look at our guide to [using electron-packager from the command line](https://github.com/electron-userland/electron-packager#from-the-command-line) to see how to specify that.
