### ISSUE TITLE
App name cannot have special path characters in it

### ISSUE THREAD

**Issue by mafrost** [electron-userland/electron-packager#308]
With a package.json with 

    "name": "@mycompany/test-project"

ENOENT: no such file or directory, rename
'/var/folders/8y/ycvpbtbn6nx_552nqm0hkllc0000gn/T/electron-packager/darwin-x64/@mycompany/test-project-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper' -> '/var/folders/8y/ycvpbtbn6nx_552nqm0hkllc0000gn/T/electron-packager/darwin-x64/@mycompany/test-project-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/@mycompany/test-project Helper'

> Which version of electron-packager are you using?

Using electron-packager version 6.0.0

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

Using command:

    electron-packager . --platform=darwin --arch=x64

This happens no matter which OS I try on and no matter what platform target I use.

> What version of [Electron](http://electron.atom.io) are you building with?

v0.36.9

> What is the host platform are you running electron-packager on?

OS X, Linux

> What target platform(s)/architecture(s) are you building for?

OS X, Linux, Windows

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Steps to reproduce:

1. Name your package to something with a '/' in it
2. Try to run packager

**Comment by malept** [comment]
As a workaround, you should set `productName` to `test-project` (or something without a slash).

**Comment by malept** [comment]
The options for fixing this bug are:

* Filter out special path characters (e.g., `:` and `\` on Windows, `/` on OSX/Linux) when constructing paths with `appname`
* Remove special path characters when constructing paths with `appname`

**Comment by develar** [comment]
Why do you use scoped name — do you need to publish package to npm?

**Comment by malept** [comment]
[sanitize-filename](https://www.npmjs.com/package/sanitize-filename) looks like a good choice to integrate into electron-packager.

**Comment by mafrost** [comment]
@develar : I work with a very large company that has special scoping even for its internal projects

**Comment by develar** [comment]
@mafrost But electron app is not published to npm or internal registry, right? So, why do you use scoped name?

**Comment by develar** [comment]
@malept I believed that in this particular case we should just remove prefix `@mycompany/` (npm package scope name). But it is not clear for me why scoped name is required here.

**Comment by mafrost** [comment]
We have a internal registry through Artefactory but I fail to see how it's relevant. If it's an allowed package name it should work, right?

**Comment by develar** [comment]
> but I fail to see how it's relevant

@mafrost It is an open source. Should be a good motivation, reasons to do something :) Sometimes it is better to help user and suggest a good solution instead of dirty workaround.

> have a internal registry through Artefactory 

Good to know, thanks.

@malept I will send PR to remove scope from name and escape name using `sanitise-filename`  tomorrow.

**Comment by philostler** [comment]
I just hit is identical issue.

**Comment by malept** [comment]
I made a first cut at fixing this in #455. It's a bit more involved than you'd think, particularly since there are a lot of files that use the Electron app's name. (And I want to have unit tests for as much of it as possible.)
