### ISSUE TITLE
6.0.1 Failing on OSX due to rcedit upgrade (missing DLL)

### ISSUE THREAD

**Issue by pvormittag** [electron-userland/electron-packager#314]
> Which version of electron-packager are you using?

6.0.1

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

Using API

> What version of [Electron](http://electron.atom.io) are you building with?

0.37.3

> What is the host platform are you running electron-packager on?

OSX 10.11.3

> What target platform(s)/architecture(s) are you building for?
All (using --all option)

> Is there a stack trace in the error message you're seeing?

Excerpt from `npm-debug.log` (local path masked with `****`).

```
Packaging app for platform linux ia32 using electron v0.37.3
Packaging app for platform win32 ia32 using electron v0.37.3
[17:43:42] 'release' errored after 14 s
[17:43:42] Error: err:module:import_dll Library MSVCP120.dll (which is needed by L"Z:\\****\\node_modules\\rcedit\\bin\\rcedit.exe") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\****\\node_modules\\rcedit\\bin\\rcedit.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\****\\node_modules\\rcedit\\bin\\rcedit.exe" failed, status c0000135
```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Works successfully with 6.0.0. I assume the issue is with the `rcedit` dependency update done for 6.0.1.

**Comment by malept** [comment]
Yep. I documented that in the readme, see the new paragraph under [Building Windows apps from non-Windows platforms](https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms). I'll add a note to NEWS as well.
