### ISSUE TITLE
electron-packager 6.0.1 requires an extra DLL to be installed for rcedit to work

### ISSUE THREAD

**Issue by mitchhentges** [electron-userland/electron-packager#317]
See [this Travis build](https://travis-ci.org/james-proxy/james/builds/121880443#L817).
(For that build, the stack trace isn't showing because I hadn't wired up `err` properly to gulp's callback. See the stack trace below).

When using version `electron-packager@6.0.1`, packaging my app doesn't do it for all the platforms. Instead, it only packages for apps up to `win32`, then fails due to a missing X server. The later platforms aren't attempted.

`v6.0.0` works as normal 

> Which version of electron-packager are you using?

`v6.0.1`

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

See the configuration in my [gulpfile.js](https://github.com/james-proxy/james/blob/master/gulpfile.js#L100).
```
{
    all: true,
    dir: 'package',
    platform: 'all',
    name: 'James',
    overwrite: true,
    icon: 'resource/icon.icns',
    version: electronVersion,
    out: 'binaries'
  }
```

> What version of [Electron](http://electron.atom.io) are you building with?

`v0.37.5`, though it also failed with `v0.37.2`. The electron version isn't affecting this.

> What is the host platform are you running electron-packager on?

Travis: so, a headless linux machine. This is reproducible on any linux machine that isn't running X.

> What target platform(s)/architecture(s) are you building for?

`win32`

> Is there a stack trace in the error message you're seeing?

```
 Error: Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.

    at formatError (/root/james/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/root/james/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/root/james/node_modules/orchestrator/index.js:264:8)
    at /root/james/node_modules/orchestrator/index.js:275:23
    at finish (/root/james/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/root/james/node_modules/orchestrator/lib/runTask.js:29:3)
    at /root/james/gulpfile.js:109:15
    at /root/james/node_modules/electron-packager/index.js:211:23
    at end (/root/james/node_modules/run-series/index.js:8:15)
    at done (/root/james/node_modules/run-series/index.js:11:10)
    at each (/root/james/node_modules/run-series/index.js:16:43)
    at /root/james/node_modules/electron-packager/win32.js:54:25
    at end (/root/james/node_modules/run-series/index.js:8:15)
    at done (/root/james/node_modules/run-series/index.js:11:10)

```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Two ways:
1. Use a project with Travis. Attempt to create an `electron` package for `win32` using `electron-packager@6.0.1`
2. Log into a headless linux machine. Attempt to package your app for `win32`

**Comment by malept** [comment]
node-rcedit 0.4.0 required a certain DLL to also be installed, see the [readme](https://github.com/electron-userland/electron-packager/blob/2469a6b695b4687f53d9c8A84b87e247f829b3e88/readme.md#building-windows-apps-from-non-windows-platforms) for more details.  However, in 0.5.0 it seems that they reverted this (https://github.com/atom/rcedit/pull/11). I'll release 6.0.2 shortly to update that dependency.

**Comment by mitchhentges** [comment]
So, fortunately (though not for my sanity, hah), I've already looked into this issue quite a bit.
The command that eventually fails is `rcedit.exe`. It is called directly with `wine` on Linux, and it is the source of the error:

```
root@james-build-test:~# wine rcedit.exe /root/james/electron-packager-bak/win32-ia32/James-win32-ia32/James.exe
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
root@james-build-test:~#

```
The difference in usage of [`rcedit`](https://github.com/atom/node-rcedit) between `v6.0.0` and `v6.0.1` is a different version: `v0.3.0` and `v0.4.0`. There is also a `v0.5.0` out, which I tested as well.

I'm pretty sure that the bug suddenly appearing in `electron-packer@6.0.1` is a _race condition_, and here's why: I'm able to reproduce the `Application tried to create a window` error _for all three versions `v0.3.0`, `v0.4.0` and `v0.5.0`._ Additionally, the error is only thrown _if there's a long enough delay between invocations of `rcedit.exe`_.

Here's a gif:
![ins4ffmfnk](https://cloud.githubusercontent.com/assets/7784737/14407370/939c15fe-fec6-11e5-8252-adb1192c44f7.gif)

**Comment by malept** [comment]
The pull request that should fix this is #315.

**Comment by mitchhentges** [comment]
But even `v0.5.0` dumps the error to the console:
```
root@james-build-test:~/node-rcedit# git checkout tags/v0.5.0
HEAD is now at de6b0a2... 0.5.0
root@james-build-test:~/node-rcedit# wine ./bin/rcedit.exe
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
Fatal error: You should specify a exe/dll file

**Comment by malept** [comment]
Perhaps the problem is that you're running `wine` with root (I hope, because you're running in a docker container). We run `rcedit` in our own Travis CI tests (and in my personal app's Travis CI tests), and I haven't seen that particular error.

**Comment by mitchhentges** [comment]
See this travis log: https://travis-ci.org/james-proxy/james/builds/121987938#L950
Looks like the missing library is part or most of it. Maybe the `$DISPLAY` error will be hidden if the other, more serious error isn't shown

**Comment by malept** [comment]
I am waiting for tests to pass before I release 6.0.2 - in the meantime you are free to `npm install` electron-packager from git and see if that works for you.

**Comment by mitchhentges** [comment]
Looks awesome, everything builds nicely with `v6.0.2`.
I'm guessing that `wine` would try to pop up a dialog if it wasn't run within the last ~5s or so, and that that `$DISPLAY` error isn't related to anything `rcedit.exe` specific.
Now that the dependency is bundled, everything is running without a hitch. Thanks!
