### ISSUE TITLE
Can't get ignore to work on Windows

### ISSUE THREAD

**Issue by ChrisTerBeke** [electron-userland/electron-packager#321]
running the following script on windows 8, 64bit:

```
node_modules\.bin\electron-packager . MyApp
    --platform=win32
    --arch=x64
    --version=0.33.2
    --ignore="Makefile|bower.json|Gruntfile.js|npm-debug.log|package|logs|bower_components|node_modules/bower|node_modules/electron-*|node_modules/tmp|node_modules/grunt|node_modules/grunt-*|node_modules/load-grunt-tasks|node_modules/node-sass-import-once|node_modules/eslint|node_modules/eslint-*"
    --icon="icon.ico"
    --app-copyright="Copyright 2016 Printr B.V."
    --app-version="1.1.0"
    --build-version="1.1.0"
    --overwrite
    --out=package/
```

but i keep getting packages that have all the files in them. Any idea what's going on?

**Comment by malept** [comment]
Without knowing what your `package.json` file looks like, my guess is that you should be doing two things:

1. `ignore` uses [JavaScript's regular expression syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) - what you're doing looks like a mix of regular expressions and glob syntax.
2. I think instead of all of the `node_modules` items in your `ignore` parameter, you want to use the [`prune`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#prune) parameter instead.

**Comment by ChrisTerBeke** [comment]
Hey, thanks for the quick reply.
I'm using a Makefile with this line to generate the ignore:

```
ELECTRON_IGNORE=$(shell node -e "console.log(require('./package.json').packageIgnore.join('|'))")
```

My scripts are roughly based on what [etcher.io](https://github.com/resin-io/etcher/blob/master/Makefile) does, for them it seems to work fine? Prune looks interesting, but I don't really want to install all the needed deps again before coding after making a release.

**Comment by malept** [comment]
> I don't really want to install all the needed deps again before coding after making a release.

I doublechecked the code. Unless you disabled `tmpdir` (and even then I'm not sure of that case), that [shouldn't](https://github.com/electron-userland/electron-packager/blob/a7334db0345cf53ed8f5366bef8e832dd9c627e4/common.js#L106) [happen](https://github.com/electron-userland/electron-packager/blob/a7334db0345cf53ed8f5366bef8e832dd9c627e4/common.js#L127-L131).

**Comment by ChrisTerBeke** [comment]
ok good to know. I added prune to my command to test it out, but doesn't make a difference (on Mac). On my Mac, the ignore works perfectly fine (ignoring everything in my package.json -> packageIgnore array).

```
"packageIgnore": [
    "Makefile",
    "bower.json",
    "Gruntfile.js",
    "npm-debug.log",
    "logs",
    "bower_components",
    "node_modules/bower",
    "node_modules/electron-*",
    "node_modules/tmp",
    "node_modules/grunt",
    "node_modules/grunt-*",
    "node_modules/load-grunt-tasks",
    "node_modules/node-sass-import-once",
    "node_modules/eslint",
    "node_modules/eslint-*"
  ],
```

which is then parsed by the line I posted here before. It just doesn't work on windows, although electron-packager should handle this platform independent right? I even saw a merged PR that fixes the slashes on Windows for ignore.

**Comment by ChrisTerBeke** [comment]
btw, the --prune works brilliantly to ignore the dev deps :) also with the new npm3 tree structure, so thanks for that suggestion!

**Comment by malept** [comment]
It works most likely because, for example, `node-modules/eslint-foo` is matched by `node_modules/eslint`.

The electron one should not be necessary, per the docs:

> The `out` directory is ignored by default, along with the `electron-prebuilt` and `electron-packager` Node modules, the `.git` directory, and `node_modules/.bin`.

Regarding:

> I even saw a merged PR that fixes the slashes on Windows for ignore.

I believe you're referring to [this](https://github.com/electron-userland/electron-packager/blob/a7334db0345cf53ed8f5366bef8e832dd9c627e4/common.js#L70-L73)?

**Comment by ChrisTerBeke** [comment]
It's indeed ignore some files/dirs by default. I was also referring to that issue yes. Playing around a bit more on windows now to see where the difference is when using --ignore.

**Comment by malept** [comment]
My point was that the ignores you have that end in `*` don't actually work, other ignores in your list are doing their job. But that is tangential to the Windows problem.

When I get some time, I need to set up Windows-based CI.

**Comment by ChrisTerBeke** [comment]
--prune also doesn't seem to do it's job on windows. Have all the deps still in the final package.

**Comment by malept** [comment]
Seems odd. It is literally running `npm prune --production` in the staging area for the package.

**Comment by ChrisTerBeke** [comment]
Just ran `npm prune --production` manually and that also doesn't work on my Windows install. Something weird is going on here...

**Comment by develar** [comment]
Just use [two package.json structure](https://github.com/electron-userland/electron-builder#two-packagejson-structure) and forget about ignoring.

**Comment by malept** [comment]
If `npm prune --production` isn't working, I think he has bigger problems than the `ignore` parameter.

I think I'm going to close this since this seems to be a problem with npm, not electron-packager.
