### ISSUE TITLE
LSOpenURLsWithRole error after changing the executable name (Gatekeeper issue)

### ISSUE THREAD

**Issue by gabriel** [electron-userland/electron-packager#323]
Changing the executable name in an app bundle can cause a Gatekeeper failure. This change was made
https://github.com/electron-userland/electron-packager/commit/aaeee768cfbcc7932a1413161afe2a3df28490eb which changes the executable name (in Contents/MacOS) from Electron to the app name.

This is due to a bug in Gatekeeper it seems: http://www.openradar.me/23614087

This happens when upgrading from <= 0.37.2 to 0.37.3 on OS X.

**Comment by malept** [comment]
I don't know how this should be resolved. There were a fair number of users who wanted #195 resolved, so I'm not currently inclined to revert it.

**Comment by gabriel** [comment]
Yeah it's a good fix to have, and I don't think it's worth reverting either. It's kind of a gnarly thing to diagnose so wanted to people to be aware of the potential issue.

**Comment by erkyrath** [comment]
I ran into this, and found that the error went away if I dragged the old version of the app to the trash (via the Finder) before installing the new version. (I don't know if this works for everybody.)

**Comment by malept** [comment]
OK, since there's nothing to do on this end, I'm going to close the issue (and hope that users who have this issue can search for it).

**Comment by gabriel** [comment]
So, we also figured out adding a symlink in Contents/MacOS is a possible workaround too.. We didn't want to break all our users on upgrade so we have for example:

/Applications/AppName.app/Contents/MacOS/Electron symlinked to /Applications/AppName.app/Contents/MacOS/AppName and it seems to be ok...

I don't know if it's worth patching the packager here to do the same, but it might prevent some headaches for people in the future.

**Comment by malept** [comment]
If anyone wants to implement this, keep in mind that you likely can't create symlinks on Windows.

**Comment by gabriel** [comment]
Yeah this would be a mac only thing

**Comment by savanain** [comment]
`sudo launchctl stop com.apple.security.syspolicy && sudo launchctl stop com.apple.security.syspolicy` did help for me after the name change.
