### ISSUE TITLE
Programmatic API options should follow Javascript naming conventions

### ISSUE THREAD

**Issue by JonathonAshworth** [electron-userland/electron-packager#325]
In the programmatic API documentation it lists hyphenated properties for the options object such as "app-copyright" and "app-version". These are not valid identifiers and should be camelCased instead, so that string identifiers and array-notation don't have to be used to reference them.

Likewise, the version-string object takes properties that are Capitalized, which is unusual for Javascript objects (though doesn't run into the same problem of having to be defined with a string identifier like the hyphenated ones).

**Comment by malept** [comment]
This is a reasonable request. Something to note for the person who decides to work on this: while camelCased identifiers are idiomatic for JavaScript APIs, they are *not* for the CLI flags. So, in `cli.js` there would need to be either a mapping or a function which consistently converted between the two styles. (The latter of which would obviously need unit tests.)

The other note I would make is that there should be a period of time where both versions of the converted APIs/flags are supported, and the old parameters noted as deprecated in the NEWS file.

**Comment by malept** [comment]
Another thing I am reminded of as I clean up some code is that a lot of the options / sub-options (such as `version-string`) are passthroughs to other modules. So in addition to this issue, I would suggest also filing issues in other repositories, for example, `node-rcedit` (to continue with the example).

**Comment by malept** [comment]
#410 reminded me of this issue. A quick search pointed me at [`camelize`](https://www.npmjs.com/package/camelize).
