### ISSUE TITLE
Build for Windows from OS X silently quits without Wine installed

### ISSUE THREAD

**Issue by z-ax** [electron-userland/electron-packager#329]
I know it's in requirements in README, but I want to suggest at least to drop a line in console if Wine is not installed on OS X.
Also, in this case process just halts, even if there are other platforms to build (like `darwin`).

> Which version of electron-packager are you using?
6.0.2

> What version of [Electron](http://electron.atom.io) are you building with?
0.37.6

> What is the host platform are you running electron-packager on?
OS X

> What target platform(s)/architecture(s) are you building for?
Windows

> Is there a stack trace in the error message you're seeing?
None.

**Comment by malept** [comment]
Weird. All of the bug reports I've seen where wine wasn't installed threw an `ENOENT` related exception.

Regardless, I would be happy to review a PR that makes the exception a bit more user-friendly.

**Comment by z-ax** [comment]
@malept seems like I was a bit incorrect with conclusions.

One of Macs which had no Wine installed, just can't build successfully while other Mac with same OS and package versions builds all successfully. And it just halts without any message like this:

```
Packaging app for platform darwin x64 using electron v0.37.6
```

And that's it, last line of the output.
Both Wine's are installed via Brew, same version (`wine --version` `wine-1.8.1`).
Tried with both cached Electron prebuilt and clean run.

Maybe, you have any idea?

**Comment by malept** [comment]
Would you mind trying running the git master version of electron-packager? There are some refactored areas of code which may affect this. (Although this is a bit of a long shot.)

**Comment by z-ax** [comment]
Just tried, almost the same:

```
The cache parameter is deprecated, use download.cache instead
The cache parameter is deprecated, use download.cache instead
The cache parameter is deprecated, use download.cache instead
Packaging app for platform win32 x64 using electron v0.37.6
Packaging app for platform darwin x64 using electron v0.37.6
```

More details: I run builds from two Gulp tasks, separated platforms to osx/win.
Via `packager = require('electron-packager')` and programmatic APIs.

Checked again everything, all versions and stuff are the same. Permissions also are fine (built previously with `gulp-electron`, just checked - builds finely).

**Comment by malept** [comment]
Hmmm. Would you mind doing some `console.log` based debugging to see where it stops executing code? I don't have a Mac on which to reproduce this.

**Comment by z-ax** [comment]
Alright! Seems like there's something with repo, or actually permissions, will check later.
But if you think there's something useful - surely I'll check with logs where needed.

Now I have a nice logs:
```
[01:53:07] Starting 'clean:app'...
[01:53:07] Finished 'clean:app' after 23 ms
[01:53:07] Starting 'build:osx'...
[01:53:07] Starting 'build:win'...
Downloading electron-v0.37.6-darwin-x64.zip
Downloading electron-v0.37.6-win32-x64.zip
[===============================>             ] 72.1% of 49.64 MB (413.59 kB/s)
DMG file created: "build/app-name-darwin-x64.dmg"
Downloading electron-v0.37.6-win32-x64.zip
Downloading electron-v0.37.6-win32-ia32.zip
[============================================>] 100.0% of 40.34 MB (1.6 MB/s)
Packaging app for platform win32 ia32 using electron v0.37.6
ZIP archive created: "build/app-name-win32-x64.zip"

ZIP archive created: "build/app-name-win32-ia32.zip"

[01:56:40] Finished 'build:win' after 3.53 min
```

P.S. I added a [https://github.com/annexare/PackDir](NPM package to actually pack dirs accordingly) (in the logs). It makes DMG on OS X as well, ZIP on the rest. Approach is pretty same as `gulp-electron` did, but with DMG and 7z console version bundled for Windows hosts (as far as there's no console archivers AFAIK).
