### ISSUE TITLE
node.dll missing on Windows

### ISSUE THREAD

**Issue by rhedin** [electron-userland/electron-packager#330]
Hi.  I built the electron-quick-start application on my Mac El Capitan.  I packaged it using electron-packager 6.0.2.  The application under abe-darwin-x64 worked spectacularly.  I copied the applications under abe-win32-ia32 and abe-win32-x64 to a Windows machine, where they both failed to start.  The complaint was "The program can't start because node.dll is missing from your computer.  Try reinstalling the program to fix this problem."  Seems like a simple matter of an item missing from the manifest, if I knew where to look.

> Which version of electron-packager are you using?
6.0.2

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?
This is the command line I entered:
electron-packager . --all --icon abe_in_profile.icns --overwrite

> What version of [Electron](http://electron.atom.io) are you building with?

Hmm.  In the package.json in the electron-quick-start directory, electron-prebuilt appears in the dev dependencies:
"devDependencies": {
    "electron-prebuilt": "^0.37.0"

> What is the host platform are you running electron-packager on?

MacBook Pro, OS/X 10.11.2

> What target platform(s)/architecture(s) are you building for?
Windows 7, 64-bit PC

> Is there a stack trace in the error message you're seeing?

no stack track

> Please provide either a failing testcase or detailed steps to reproduce your problem.
If you double-click the abe.exe file, you get a dialog box that says "The program can't start because node.dll is missing from your computer.  Try reinstalling the program to fix this problem."

**Comment by malept** [comment]
* Does `node.dll` exist in the same folder as `abe.exe`, when you create the app bundle on OSX?
* Does `node.dll` exist in the same folder as `abe.exe`, after you copy the app bundle folder to Windows?

**Comment by rhedin** [comment]
Ricks-MacBook-Pro:electron-quick-start $ find . -name 'node.dll'
./abe-win32-ia32/node.dll
./abe-win32-x64/node.dll
Ricks-MacBook-Pro:electron-quick-start $ 

Duh!  I need to copy the whole directory.  Is that what you're saying?  I just copied the abe.exe file.  I thought it was self-contained.

**Comment by malept** [comment]
It is not self-contained - according to the Electron developers in https://github.com/electron/electron/issues/914, this is not currently possible.

**Comment by rhedin** [comment]
Thank you very much for the info, Mark.  I will either have my user download the whole directory, or use electron-builder and make an installation program.
