### ISSUE TITLE
Where can I put parameter at execute electron ?

### ISSUE THREAD

**Issue by ukiuni** [electron-userland/electron-packager#334]
Hi.

Proxy setting don't go with electron-packager.

I write 
```
"scripts": {
    "start": "electron --proxy-server=http://localhost:8080 main.js"
}
```
to my package.json, and exec command "npm start", electron use proxy.
And build same application with electron-packager, electron don't use proxy.

electron-packager version is 5.1.1 and 7.0.0.

I builded with CLI, command is
```
node ./node_modules/electron-packager/cli.js . Slite --platform=darwin --arch=x64 --version=0.34.3 --icon=resources/icons.icns --ignore=\"node_modules/(electron-packager|electron-prebuilt)|build|resources\" --overwrite
``` 
electron-prebuilt version is 0.37.6.

I running it electron-packager on darwin and win32/x64.
And I'm building for darwin ,win32/x64 and win32/ia32.

Please help me.

**Comment by malept** [comment]
Apparently you can, I [searched the Electron documentation](http://electron.atom.io/docs/all/) and there is a programmatic way to set it, please read http://electron.atom.io/docs/v0.37.6/api/chrome-command-line-switches/.

If you want your users to pass a proxy flag, you're going to have to parse the arguments yourself and add it to Chrome using the method described in the Electron docs.

(Strictly speaking, this is not an electron-packager specific question.)

**Comment by ukiuni** [comment]
Thank you very much for the info, Mark.
