### ISSUE TITLE
Missing default menu on OSX

### ISSUE THREAD

**Issue by petrfelzmann** [electron-userland/electron-packager#337]
I pack the simplest app by this basic CLI command

`electron-packager ./myapp myapp --platform=darwin --arch=x64 --version=0.37.6`

and run the created `myapp-darwin-x64.app`. There is missing the default operating system menu (Edit, View, Window, Help) in the running application, which I consider as a bug.

When I run the same application directly from the source code `electron ./myapp` then the default menu is presented.

As the application I use the simple one from [Quick Start Electron documentation](http://electron.atom.io/docs/v0.37.6/tutorial/quick-start/#write-your-first-electron-app).

electron-packager v7.0.0
electron v0.37.6
OS X Yosemite 10.10.5

**Comment by petrfelzmann** [comment]
Additional info: this bug is not presented on Windows.

**Comment by malept** [comment]
electron-packager doesn't do anything to change the menu behavior. I looked upstream at Electron's issues, and according to https://github.com/electron/electron/issues/3787#issuecomment-164334741 this is by design.

**Comment by malept** [comment]
See also: https://github.com/electron/electron/issues/4227

**Comment by feifeipan** [comment]
@petrfelzmann have you fix the problem? cause i met the problem too. The menu is missing on mac os

**Comment by petrfelzmann** [comment]
See the comments and referenced issues. It is by design.
