### ISSUE TITLE
CFBundleExecutable can't have spaces

### ISSUE THREAD

**Issue by theflow** [electron-userland/electron-packager#339]
It looks like https://github.com/electron-userland/electron-packager/commit/f14c7ddf1b56e86fa729ce0ed5d93b96f52b4559 broke the packaging of my app.

I'm using an appname with a space in it and it looks like Mac doesn't like if that is used as the CFBundleExecutable. It works fine if I remove the space form the name.

"electron-packager": "7.0.1",
"electron-prebuilt": "0.37.6",
darwin, x64

**Comment by malept** [comment]
If someone could link to an Apple developer page that specifies what the valid characters are for that key, that would be helpful for whoever fixes this.

**Comment by develar** [comment]
@malept Cannot find any info. But since this issue is critical, I fixed it. Also, Squirrel.Windows bug fixed as well (https://github.com/electron-userland/electron-builder/issues/339).

**Comment by theflow** [comment]
Hi, sorry, looks like I jumped to conclusions on what was causing my issue. It was actually changing the app name that fixed my problem, not the spaces in it. I've raised a new issue describing the problem: https://github.com/electron-userland/electron-packager/issues/350

**Comment by malept** [comment]
I'm closing this issue then.
