### ISSUE TITLE
Electron packager fails on Mac OS X when packaging all

### ISSUE THREAD

**Issue by gaccawi** [electron-userland/electron-packager#346]
Previously electron-packager yeoman project worked "out of the box". I didn't have wine installed, but was able to create running versions of a simple sample application. This is no longer the case. 

> Which version of electron-packager are you using?
7.0.1

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?
`electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all`

> What version of [Electron](http://electron.atom.io) are you building with?

"version": "0.37.7"

> What is the host platform are you running electron-packager on?

MAC OS X El Capitan 10.11.4

> What target platform(s)/architecture(s) are you building for?
all

> Is there a stack trace in the error message you're seeing?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'build' ]
2 info using npm@3.8.7
3 info using node@v5.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle test-electron@0.0.0~prebuild: test-electron@0.0.0
6 silly lifecycle test-electron@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle test-electron@0.0.0~build: test-electron@0.0.0
8 verbose lifecycle test-electron@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle test-electron@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/g9a/workspace/test-electron/node_modules/.bin:/usr/local/bin:/Users/g9a/bin/Sencha/Cmd/5.1.3.61:/usr/local/php5/bin:/usr/local/ant//bin:/usr/local/sbin:/usr/local/bin:/usr/share/ant/bin:/opt/subversion/bin:/Users/g9a/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/munki:/usr/local/apache-maven/
10 verbose lifecycle test-electron@0.0.0~build: CWD: /Users/g9a/workspace/test-electron
11 silly lifecycle test-electron@0.0.0~build: Args: [ '-c',
11 silly lifecycle   'electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all' ]
12 silly lifecycle test-electron@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle test-electron@0.0.0~build: Failed to exec build script
14 verbose stack Error: test-electron@0.0.0 build: `electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:244:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid test-electron@0.0.0
16 verbose cwd /Users/g9a/workspace/test-electron
17 error Darwin 15.4.0
18 error argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run-script" "build"
19 error node v5.11.0
20 error npm  v3.8.7
21 error code ELIFECYCLE
22 error test-electron@0.0.0 build: `electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all`
22 error Exit status 1
23 error Failed at the test-electron@0.0.0 build script 'electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test-electron package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test-electron
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test-electron
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

> Please provide either a failing testcase or detailed steps to reproduce your problem.
nam install -g generator-electron
yo electron
run npm build

**Comment by malept** [comment]
Which version of electron-packager previously worked for you?

Could you try running the following in your `test-electron` directory and paste the output here?

```bash
$(npm bin)/electron-packager . --out=dist --prune --asar --overwrite --all
```

**Comment by gaccawi** [comment]
This resolves the issue. Now, I feel like an idiot. 

test-electron g9a$ $(npm bin)/electron-packager . --out=dist --prune --asar --overwrite --all
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
Packaging app for platform linux ia32 using electron v0.37.7
Packaging app for platform win32 ia32 using electron v0.37.7
Packaging app for platform darwin x64 using electron v0.37.7
Downloading electron-v0.37.7-linux-x64.zip
Downloading electron-v0.37.7-mas-x64.zip
[============================================>] 100.0% of 40.24 MB (22.99 MB/s)
Downloading electron-v0.37.7-win32-x64.zip
[============================================>] 100.0% of 49.64 MB (28.37 MB/s)
Packaging app for platform win32 x64 using electron v0.37.7
Wrote new apps to:
dist/TestElectron-linux-ia32
dist/TestElectron-win32-ia32
dist/TestElectron-darwin-x64
dist/TestElectron-linux-x64
dist/TestElectron-mas-x64
dist/TestElectron-win32-x64

**Comment by malept** [comment]
One of two things may be happening:

1. `app-version` does not like `0.0.0` as the app version for some reason (that would be a "bug" in code outside of electron-packager, most likely)
2. There's a bug in `generator-electron`.

**Comment by malept** [comment]
Try running the same command, but with `--app-version=0.0.0` at the end.

**Comment by gaccawi** [comment]
Different error:

test-electron g9a$ $(npm bin)/electron-packager . --out=dist --prune --asar --overwrite --all --app-version=0.0.0
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
The strict-ssl parameter is deprecated, use download.strictSSL instead
Packaging app for platform linux ia32 using electron v0.37.7
Packaging app for platform win32 ia32 using electron v0.37.7
spawn wine ENOENT

**Comment by z-ax** [comment]
@gaccawi, obviously, you need to have Wine installed.

**Comment by malept** [comment]
@gaccawi OK, that makes sense. `app-version` for win32 targets requires node-rcedit, which the readme states requires wine installed on OSX/Linux. That's probably the error you got when you ran `npm build`, but the stderr error output wasn't printed. I suggest seeing if the generator-electron project can fix the output problem.
