### ISSUE TITLE
How to set the CFBundleDevelopmentRegion (dev-region)?

### ISSUE THREAD

**Issue by lipis** [electron-userland/electron-packager#352]
We are updating from version 5 to 7 and it looks like the one thing that is missing from the generated `Info.plist` is the [`CFBundleDevelopmentRegion`](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-130430) that we used to set via `--dev-region` using the [grunt-electron](https://github.com/sindresorhus/grunt-electron).

Am I missing something?

**Comment by malept** [comment]
I've never heard of `--dev-region`. You probably want to use [`extend-info`](https://github.com/electron-userland/electron-packager/blob/v7.0.1/docs/api.md#extend-info).

**Comment by lipis** [comment]
Thanks.. I'll check it out
