### ISSUE TITLE
C++ addon works incorrectly after being packed on Windows

### ISSUE THREAD

**Issue by milktea736** [electron-userland/electron-packager#356]
Hi all,

I build a c++ addon with node-gyp which is dependent on some dynamic-link libraries.
It works fine when I execute "electron main.js", but fail when I click the packed application icon.

I'm using electron-packager@7.0.1, node-gyp@3.3.1 and electron-prebuilt@0.37.7\.
The electron-packager CLI arguments are: --platform=win32 --arch=x64 --version=0.37.7
My host version is  Windows 10, x64. 

I don't get any error message in the developer tool window. Is there any hint to solve this problem?
Thanks.

**Comment by malept** [comment]
In other issues I have seen references to the electron-rebuild node module. Perhaps looking into that will help?

**Comment by milktea736** [comment]
Hi @malept, 

Thanks for you reply,  electron-rebuild module seems that is used to re-build the module to fit electron version. (related to NODE_MODULE_VERSION,  I'm not pretty sure.) But my addon works when I command "electron main.js", implies that the module version is compatible with electron. I have no idea what happened and got stuck on this for few days.

**Comment by malept** [comment]
I think it's a node_modules require path problem. See #217.

**Comment by milktea736** [comment]
Hi @malept,

I tested it, it's not a path problem(I just go through the "can't find module" stage few days ago). My addon was required correctly and even make a callback to print a string in developer tool window now. I also had a test on the dependency of my addon (if any required dll is missed, the electron will crash).

**Comment by malept** [comment]
I'm out of ideas then. Perhaps someone else can help.

**Comment by malept** [comment]
It would help others if you had a minimal testcase (perhaps based on https://github.com/electron/electron-quick-start) with detailed instructions for how to reproduce this problem.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in over two months, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with a minimal testcase as mentioned in an earlier comment, and I'll reopen.
