### ISSUE TITLE
`--arch` should default to host arch

### ISSUE THREAD

**Issue by sindresorhus** [electron-userland/electron-packager#36]
Good defaults again. Less config.

**Comment by jden** [comment]
It's not clear to me that this is the best default. It's not the broadest compatibility-speaking. If you're building for your own machine, then it should default to whatever your current arch is (granted, in 2015, it's likely x64, but I digress). If you're running electron-packager to cross-build for a different target arch, then it could be anything that electron supports.

**Comment by maxogden** [comment]
if any thing we should default to `require('os').arch`, but even there it's
a little confusing UX wise

**Comment by sindresorhus** [comment]
I think defaulting to the system arch would be weird as we're talking about packaging the app, not running. You'd want it to be predictable between computers.

I just want less config. And having x64 as default means I wouldn't have to spell it out on my OS X and Linux targets.

**Comment by maxogden** [comment]
there are a good percentage of 32 bit linux users still, so im on the fence
about this, seems like it could make it more confusing for linux 32/
windows users

**Comment by sindresorhus** [comment]
I don't see what's confusing. It's just about a documented default. If you want to compile for 32bit too you just then add the `--arch` option.

**Comment by maxogden** [comment]
@sindresorhus its just that adding a mac/linux centric default for no good reason just feels weird to me personally, i'd rather fix your problem of not wanting to have to specify complex config with other options like https://github.com/maxogden/electron-packager/issues/40

**Comment by zeke** [comment]
It seems like the best option is use a default that will work for all users. It looks like the `--all` option shipped in #40 may have allayed some of the config frustration. @sindresorhus are you cool with closing this?

**Comment by sindresorhus** [comment]
Still makes sense. Not everyone can use the `--all` option and without, electron-packager requires a *lot* of config that could have good defaults. But I switched to `electron-builder`, so I don't really care anymore.

**Comment by malept** [comment]
I would rather default to whatever the arch is of the host (which, admittedly, is likely to be x64).

**Comment by malept** [comment]
Defaulting to the host arch has the added benefit of less config when your Electron app requires native modules.
