### ISSUE TITLE
Not able to create OSX package

### ISSUE THREAD

**Issue by bansalvks** [electron-userland/electron-packager#360]
I am trying to create package for mac machine

> Which version of electron-packager are you using?
7.0.1

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?
electron-packager . --out=dist/osx --platform=darwin --arch=x64

> What version of [Electron](http://electron.atom.io) are you building with?

0.35.2

> What is the host platform are you running electron-packager on?

windows

> What target platform(s)/architecture(s) are you building for?
osx 64x

> Is there a stack trace in the error message you're seeing?

> Please provide either a failing testcase or detailed steps to reproduce your problem.
c:\Users\vikas\Desktop\electron apps\creating-your-first-desktop-app-with-elect
ron>electron-packager . --out=dist/osx --platform=darwin --arch=x64
The strict-ssl parameter is deprecated, use download.strictSSL instead
Cannot create symlinks; skipping darwin platform

**Comment by malept** [comment]
To quote @kfranqueiro in https://github.com/electron-userland/electron-packager/issues/164#issuecomment-154578802: 
> From what I recall when I tested this (I run Windows 8 and tested on a win7 VM), you normally cannot even run electron-packager targeting darwin without admin privileges due to symlinks (which electron-packager detects and skips), and if you do run with admin privileges, yes, I've found it impossible to archive correctly without running into errors. I'm not sure if there's a way around it besides packaging for OS X on OS X or Linux.
