### ISSUE TITLE
Packaged Electron application behaves different than one ran from command line

### ISSUE THREAD

**Issue by stegmanh** [electron-userland/electron-packager#361]
Our Electron application spawns a web server that our Electron client communicated with. The server is a basic node server that listens on some arbitrary port, and the Electron UI if you will communicates with it. When running Electron from the command line for example `electron main.js` starts the server just fine. Once I package with Electron packager however, the UI component works fine but it no longer launches the web server. Something odd I have noticed though is that if I go into the package contents and run the Unix executable, the server starts up just fine.

I should also not that I have tried multiple ways of spawning this server. I have tried to 'require' the server as well as spawn a process that runs the node file, neither work.

> Which version of electron-packager are you using?

Latest Version

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

> What version of [Electron](http://electron.atom.io) are you building with?

`  'arch' : 'x64',
  'dir' : {{Hardcoded Directory}},
  'platform' : 'darwin'`

> What is the host platform are you running electron-packager on?

OSX, x64, El Capitan 10.11.4

> What target platform(s)/architecture(s) are you building for?

Targeting OSX, x64

> Is there a stack trace in the error message you're seeing?

No error messages (Is there any way I can get debugging information?)

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Described in the description

**Comment by malept** [comment]
Thanks for filing an issue. An example GitHub repository (possibly based off of [electron-quick-start](https://github.com/electron/electron-quick-start)) would be helpful for someone who wants to diagnose what the problem is.

**Comment by stegmanh** [comment]
@malept 

I built an example, and it seems to work fine. I'm now thinking the issue might be with bundling SQLite3 or some other package?

Thank you for your time
