### ISSUE TITLE
electron-packager dereferencing symlinks

### ISSUE THREAD

**Issue by guidupuy** [electron-userland/electron-packager#362]
This is more of a question, really: why does electron-packager dereference symlinks when copying app code? I have a situation where this causes problems - is there a known workaround I could use other than using a post build script to reinstate dereferenced symlinks?

**Comment by malept** [comment]
> why does electron-packager dereference symlinks when copying app code?

I followed the `git blame` trail and found the reason: https://github.com/electron-userland/electron-packager/pull/42

> is there a known workaround I could use other than using a post build script to reinstate dereferenced symlinks? 

That's currently the only way to do it. I would be happy to review a PR that adds an app copy option, per https://github.com/electron-userland/electron-packager/pull/42#issuecomment-103987791 (that defaults `dereference` to `true`, doesn't override `ignore`, etc...).

**Comment by fleex** [comment]
Not sure #43 was a good idea in the first place... There *are* cases where dereferencing symlinks breaks things (in my case, a native MacOSX library), and I do believe this should really be an option (defaulting to `true` if you think that's the most likely scenario).

**Comment by guidupuy** [comment]
Not sure #43 was a good idea in the first place... There *are* cases where dereferencing symlinks breaks things (in my case, a native MacOSX library), and I do believe this should really be an option (defaulting to `true` if you think that's the most likely scenario). I'll look into it.

**Comment by malept** [comment]
This should definitely be an option, given that there are two different cases for this. To avoid breaking backward compatibility, I would prefer that it would default to `true`. If there's enough support for it in the future, it can default to `false`.
