### ISSUE TITLE
cannot run any command without receiving error 

### ISSUE THREAD

**Issue by heaversm** [electron-userland/electron-packager#363]
Unexpected Token illegal

occurs when running any electron-packager command

> Which version of electron-packager are you using?

7.0.1

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

`electron-packager` and `electron-packager . --all`

> What version of [Electron](http://electron.atom.io) are you building with?

1.0.1

> What is the host platform are you running electron-packager on?

mac osx 10.9.5 (darwin x64)

> What target platform(s)/architecture(s) are you building for?

mac osx 10.9.5 (darwin x64)

> Is there a stack trace in the error message you're seeing?

```/usr/local/lib/node_modules/electron-packager/common.js:67
  return `${opts.name}-${opts.platform}-${opts.arch}`
         ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-packager/cli.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Install electron via node: `npm install electron-prebuilt -g`
Install electron packager via node: `npm install electron-packager -g`
Create an app that successfully compiles when running `electron . ` from project directory
Attempt to package by running `electron-packager . --all`
Receive above error in terminal

**Comment by malept** [comment]
You're running Node < 4.0.

Node 4.0 or greater is required as of electron-packager 7.0.0, per:

* [the NEWS file](https://github.com/electron-userland/electron-packager/blob/v7.0.0/NEWS.md#700---2016-04-17)
* [the installation instructions](https://github.com/electron-userland/electron-packager#installation)
* the [`engines` section of `package.json`](https://github.com/electron-userland/electron-packager/blob/v7.0.0/package.json#L42-L44)
