### ISSUE TITLE
App unable to launch

### ISSUE THREAD

**Issue by mashhoodr** [electron-userland/electron-packager#365]
I have built a simple Electron app using Menubar and after packaging it (using electron-packager@5.1.0) when I run it on OSX, it gives error:

`The application "NAME.app" can't be opened.`

The app works fine when I build and run it locally using `electron .` Also when I try running it from inside the .app file it works as well.

node: 5.11.0
npm: 3.8.6
menubar: 4.1.0
electron-packager: 5.1.0
electron: 1.0.1
plaform: osx 10.11.4
build command: `./node_modules/.bin/electron-packager ./ --platform darwin --arch all`

How can I investigate the cause of this issue?

**Comment by malept** [comment]
The first thing you should do is use the latest version of electron-packager (at the time of this comment, that is 7.0.1).

Per the issue template that is shown when you create a new issue:

> What is the host platform are you running electron-packager on?

I assume it's OSX?

**Comment by mashhoodr** [comment]
Yes, I have its OSX 10.11.4

I will try upgrading to 7.0.1

**Comment by davidferguson** [comment]
I've just had this issue - and as far as I can see it's down to the naming of the executable inside the .app package.

To fix this, you need to right-click on _**NAME.app**_, `Show Package Contents`.
Open `Contents`, `MacOS`, and rename the file in there to **`Electron`**.

The app should now open fine.

Tested under Mac OS X 10.11.3, Electron 1.1.0, Electron-packager 7.0.1

**Comment by malept** [comment]
Perhaps it has something to do with https://github.com/electron-userland/electron-packager/issues/323 ?

**Comment by davidferguson** [comment]
That would seem likely - running the command `open myapp.app` in Terminal gives the error:
`LSOpenURLsWithRole() failed with error -10810 for the file myapp.app`

**Comment by mashhoodr** [comment]
thanks @davidferguson and @malept 

turns out my issue was that the APP was named `some-name.app` which was causing the build to break. Changing it to `somename.app` works!

**Comment by malept** [comment]
I wasn't aware that Mac apps couldn't have hyphens in the name.

**Comment by davidferguson** [comment]
My app name doesn't have a hyphen in it's name, and still has this issue. I needed to change the name of the executable in the MacOS folder and then in Info.plist for it to work again.

**Comment by malept** [comment]
@davidferguson yes, I think your problem is different from @mashhoodr's problem.

**Comment by davidferguson** [comment]
I think that both @mashhoodr and I had the same issue as #323. It says that a fix is having the executable in a different location fixes this issue, so renaming the executable (like I did) and also renaming the .app (like @mashhoodr did) would fix the issue.
Therefore I don't actually think this issue is any different to #323, and doesn't have anything to do with hyphens in the name.

**Comment by mashhoodr** [comment]
I can confirm that simply renaming the app also fixes the issue, and it does have the hyphen still. Thanks for the heads up @davidferguson
