### ISSUE TITLE
Ignore node_modules: there are approx 150-200 node modules by default

### ISSUE THREAD

**Issue by robinne** [electron-userland/electron-packager#366]
The instructions state to ignore modules you don't need. Downloading quick start (https://github.com/electron/electron-quick-start), there are over 150 node_modules present. Safe to assume these are all necessary? Thanks

**Comment by malept** [comment]
electron-quick-start only has devDependencies. You can remove those quite easily from the bundled app by adding the `--prune` parameter when running `electron-packager`.
