### ISSUE TITLE
fail to run electron-packager

### ISSUE THREAD

**Issue by iszRoyHunag** [electron-userland/electron-packager#367]
OS: ubuntu 12.04
electron: v0.37.8

when I run electron-packager on ubuntu, command as below:
electron-packager --help 
and result as below:
/usr/local/lib/node_modules/electron-packager/common.js:67
  return `${opts.name}-${opts.platform}-${opts.arch}`
         ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-packager/cli.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

I followed this to install the electron-package
# for use in npm scripts
npm install electron-packager --save-dev

# for use from cli
npm install electron-packager -g

If anyone can help me?
Thanks in advance.

> Which version of electron-packager are you using?

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

> What version of [Electron](http://electron.atom.io) are you building with?

> What is the host platform are you running electron-packager on?

> What target platform(s)/architecture(s) are you building for?

> Is there a stack trace in the error message you're seeing?

> Please provide either a failing testcase or detailed steps to reproduce your problem.

**Comment by malept** [comment]
You're running Node < 4.0.

Node 4.0 or greater is required as of electron-packager 7.0.0, per:

* [the NEWS file](https://github.com/electron-userland/electron-packager/blob/v7.0.0/NEWS.md#700---2016-04-17)
* [the installation instructions](https://github.com/electron-userland/electron-packager#installation)
* the [`engines` section of `package.json`](https://github.com/electron-userland/electron-packager/blob/v7.0.0/package.json#L42-L44)

**Comment by iszRoyHunag** [comment]
thanks very much malept
