### ISSUE TITLE
Electron 1.1.0 for Windows needs vcruntime140.dll

### ISSUE THREAD

**Issue by kaepora** [electron-userland/electron-packager#368]
`electron-packager`, under Windows, is linking against `msvcp140.dll`, whereas `electron 1.1.0` needs `msvcp140.dll` and `vcruntime140.dll`. This causes all built apps to not run on Windows if using `electron 1.1.0` (which is currently the latest version).

This issue can be fixed by manually placing `msvcp140.dll` and `vcruntime140.dll`, obtained via the [Visual C++ Redistributable for Visual Studio 2015 ](https://www.microsoft.com/en-us/download/details.aspx?id=48145), in the root directory of the built Electron application.

> Which version of electron-packager are you using?

7.0.1.

> What version of [Electron](http://electron.atom.io) are you building with?

1.1.0.

> What is the host platform are you running electron-packager on?

Windows 10 x64.

> What target platform(s)/architecture(s) are you building for?

Windows 10 x64.

**Comment by develar** [comment]
https://github.com/electron/electron/pull/5538 1.1.0 electron is broken.

**Comment by malept** [comment]
As @develar mentioned, this is not an electron-packager bug, but rather an upstream Electron bug. However, I'm going to keep this open until Electron releases a new version.

**Comment by kaepora** [comment]
@malept Wise move.

**Comment by maxogden** [comment]
@kaepora whoa just realized cryptocat is using this, awesome!

**Comment by kaepora** [comment]
@maxogden :smiley: Yes, I'm very satisfied with, and a big fan of, Electron and Cryptocat is doing very well since adopting the framework.

**Comment by malept** [comment]
Electron 1.1.1 was released 6 days ago, so I'm closing this.
