### ISSUE TITLE
Why my electron-packing does not package my vue.js

### ISSUE THREAD

**Issue by mydansun** [electron-userland/electron-packager#373]
At First I executed npm install vue --save

My packager script is electron-packager . launcher --platform=win32 --arch=x64 --version=1.0.0 --out=dist/ --overwrite --ignore=node_modules/electron-* --ignore=node_modules/.bin --ignore=.git --ignore=launcher.json --ignore=.jshintrc --ignore=dist --prune

But when I run the exe after packaging, I got a error told me that Vue is not found. Why??

**Comment by malept** [comment]
If I had to guess (since there's not much for me to go on), it's probably related to the module not being in one of the places it looks for modules. See https://github.com/electron-userland/electron-packager/issues/217

**Comment by johnmuhl** [comment]
Does vue.js happen to put the require-able files in `dist`? If so the `--ignore=dist` may be causing your trouble.
