### ISSUE TITLE
Electron icon for windows x64

### ISSUE THREAD

**Issue by coelho-extremosistemas** [electron-userland/electron-packager#377]
I am trying to generate a package of electron, with new version 1.1.2 of electron, but icon of executable file ".exe", not change to my file.png at windows 8.1.
In the older version of electron, 1.0.2 it's ok.

electron-packager version 7.0.2
electron-packager . --ignore=\"(examples|LICENCE)\" --icon=appccs.png --platform=win32 --arch=x64 --version=1.1.2 --overwrite --prune
electron-prebuilt version 1.1.2
window 8.1 x64

**Comment by malept** [comment]
Please tell me if this is correct: you're not able to set the icon using Electron 1.1.2 (but it works on 1.0.2 with the same electron-packager version). You're building for the Windows x64 target on a Windows x64 host.

Additionally, you have an `appccs.ico` file in the same directory as your `appccs.png` file.

If all of what I stated is true, it sounds like a bug in Electron rather than electron-packager. You should see if there's a bug filed there.

**Comment by coelho-extremosistemas** [comment]
Yes, Mr. Malept, thanks

**Comment by malept** [comment]
I'm going to mark this as invalid (since it is an Electron bug rather than an electron-packager bug).

**Comment by paulcbetts** [comment]
Sorry to bounce this back to you, but this has to be an electron-packager bug, Electron has no control over who calls rcedit on it to set the icon, that's entirely electron-packager's sitch

**Comment by develar** [comment]
Obviously icon must valid ICO file and has size at least 256x256. But not PNG (`appccs.png`). Consider using electron-builder — icon file validated prior to pass to electron-packager (electron-packager is a little bit low level tool).

**Comment by malept** [comment]
It is really odd that the same version of electron-packager would produce different results with different Electron versions. I think a minimal testcase would be appreciated for someone with a Windows machine handy to confirm this issue.

**Comment by malept** [comment]
@paulcbetts Perhaps it has something to do with the Windows toolchain change in Electron?

**Comment by coelho-extremosistemas** [comment]
Hi @develar , I change .png to .ico, but not effect

**Comment by paulcbetts** [comment]
@coelho-extremosistemas Can you upload a sample of a file that didn't work?

**Comment by coelho-extremosistemas** [comment]
I found a problem in my package.json:
I use this:
`{
  "name": "extremo",
  "version": "6.5.47",
  "description": "Custom browser for Extremo Sistemas",
  "main": "main.js",
  "scripts": {
    "postinstall": "npm rebuild --fallback-to-build --runtime=electron --target=1.1.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell --build-from-source",
    "test": "echo \"Error: no test specified\" && exit 1",
    "package": "electron-packager . --ignore=\"(examples|LICENSE|.mk|MakeFile|.svn|.md|.gypi|.vcxproj|.tlog|build/Release/obj|.gyp|test|src|.yml|usb/libusb|ChangeLog)\" --icon=appccs.ico --platform=win32 --arch=x64 --version=1.1.2 --overwrite --prune",
    "package_linux": "electron-packager . --ignore=\"(examples|LICENSE|.mk|Makefile|.svn|.md|.gypi|.vcxproj|.tlog|build/Release/obj|test|src|.yml|usb/libusb|ChangeLog)\" --icon=appccs.png --platform=linux --arch=x64 --version=1.1.2 --overwrite"
  },
  "dependencies": {
    "printer": "^0.2.1",
    "serialport": "^3.1.2",
    "usb": "^1.1.2",
    "usbinfo": "0.0.5"
  },
  "devDependencies": {
    "electron-packager": "^7.0.2",
    "electron-prebuilt": "^1.1.2",
    "electron-rebuild": "^1.1.4",
    "node-gyp": "^3.3.1",
    "node-pre-gyp": "^0.6.28"
  },
  "repository": {
    "type": "git",
    "url": "http://www.consistem.com.br"
  },
  "author": "Marcio Jota Coelho",
  "license": "ISC"
}`

The problem. I need rebuild node-modules, with new version of Electron, But I don't change version in postinstall to 1.1.2

**Comment by malept** [comment]
I guess I'm going to close this again, then.

**Comment by coelho-extremosistemas** [comment]
Yes.. close this, I am sorry for my fail
