### ISSUE TITLE
platform options - (possibilities)

### ISSUE THREAD

**Issue by coelho-extremosistemas** [electron-userland/electron-packager#378]
I am use the script tag, in pakage.json to build a distributed version of electron with electron package. I would like to know to use a something variable to pass platform option. 
I need to build my project in linux, windows and mac, because I use node-modules needed to rebuild.

I use this lines:
    "package": "electron-packager . --icon=appccs.ico --platform=win32 --arch=x64 --version=1.1.2 --overwrite --prune",
    "package_linux": "electron-packager . --icon=appccs.png --platform=linux --arch=x64 --version=1.1.2 --overwrite"

I call this scripts with:
npm run package -> to windows
npm run package_linux -> to linux

It's possible refractory this?

**Comment by malept** [comment]
I am unsure what you're asking. Perhaps it's related to #359?

**Comment by MarshallOfSound** [comment]
If I understand what you want correctly something like this might work (this code is untested)

```json
scripts: {
     "package": "electron-packager . --icon=appccs.ico --arch=x64 --version=1.1.2 --overwrite --prune",
}
```

```bash
npm run package -- --platform=win32
npm run package -- --platform=linux
```

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in more than two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
