### ISSUE TITLE
spawn /bin/sh NOENT

### ISSUE THREAD

**Issue by karfield** [electron-userland/electron-packager#380]
I'm using electron-packager's API to pack the bundle, it comes out:

```
Packaging app for platform darwin x64 using electron v1.1.2
pack 
Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

```

> Which version of electron-packager are you using?

the packager: 7.0.2

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

```
 {
        name: 'MyApp',
        'app-version': '1.0.0',
        dir: projDir,
        asar: true,
        prune: true,
        arch: arch,
        platform: plat,
        version: _.trim(packageJson.devDependencies['electron-prebuilt'], '^$~'),
        out: `release/${plat}-${arch}`,
        ignore: (dir) => {
            console.log('pack', dir);
            if (_.startsWith(dir, '/dist/') || _.startsWith(dir, '/artworks/')) {
                return false
            }
            if (_.startsWith(dir, '/node_modules/')) {
                var name = /\/node_modules\/([^\/]+)($|\/.*)/.exec(dir)[1]
                return !_.isEmpty(packageJson.dependencies[name])
            }
            return true
        }
    }
```

> What version of [Electron](http://electron.atom.io) are you building with?

electron: 1.1.2

> What is the host platform are you running electron-packager on?

platform: darwin (Mac OS X: 10.11.4)
arch: x64

> What target platform(s)/architecture(s) are you building for?

platform: darwin
arch: x64

> Is there a stack trace in the error message you're seeing?

see above

> Please provide either a failing testcase or detailed steps to reproduce your problem.

**Comment by malept** [comment]
Thanks for filing an issue, but there's not enough information here to see what the problem is. Could you provide a minimal testcase (you can use [electron-quick-start](https://github.com/electron/electron-quick-start) as a base) so that someone can reproduce your problem?

**Comment by sergeybekrin** [comment]
I faced same problem. This happens because of missing package.json in built app.

Solution is dead simple, add check for empty path in ignore function:
```js
ignore: (path) => {
    if (path === '') {
        return false;
    }

    /* Rest of checks */
}
```

I believe this happens because ignore function first call check empty path (directory itself) and ignores everything else.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in more than two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
