### ISSUE TITLE
How to package electron app into one big executable file, not a directory include many files

### ISSUE THREAD

**Issue by netroby** [electron-userland/electron-packager#383]
How to package electron app into one big executable file, not a directory include many files.
We want to using electron to develop a app for our business client ,but do not want to let them see our resource files. so we need to build a single file executable file from source

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-packager#related — https://github.com/electron-userland/electron-builder

**Comment by malept** [comment]
That's not the only answer. You can use the [`asar`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#asar) option to "conceal your source code from cursory inspection" (as it says in the [application packaging tutorial for Electron](http://electron.atom.io/docs/tutorial/application-packaging/)).

**Comment by peer2peer** [comment]
How to unpack a single exe file produced by Electron builder?

**Comment by dexter4life** [comment]
You can use this instead https://github.com/electron/windows-installer
