### ISSUE TITLE
pac mac app error

### ISSUE THREAD

**Issue by willin** [electron-userland/electron-packager#385]
```shell
electron-packager . --asar --overwrite --platform=darwin --arch=x64 --prune=true --out

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.generateFinalPath (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.electron-packager_npminstall/electron-packager/7.
0.2/electron-packager/common.js:70:15)
    at checkOverwrite (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.electron-packager_npminstall/electron-packager/7.0.2/electr
on-packager/index.js:146:34)

    at /Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.electron-packager_npminstall/electron-packager/7.0.2/electron-packager/inde
x.js:165:32
    at /Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.electron-packager_npminstall/electron-packager/7.0.2/electron-packager/inde
x.js:84:9
    at next (/Users/willin/.nvm/versions/node/v6.2.0/lib/node_modules/.electron-packager_npminstall/rimraf/2.5.2/rimraf/rimraf.js:74:7)
    at FSReqWra%
```

> Which version of electron-packager are you using?

```
"electron-packager": "^7.0.2",
```

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

```bash
electron-packager . --asar --overwrite --platform=darwin --arch=x64 --prune=true --out=out --osx-sign.identity='Developer ID Application: GitHub' --ignore=node_modules
```

> What version of [Electron](http://electron.atom.io) are you building with?

```
"electron-prebuilt": "^1.2.0",
```

> What is the host platform are you running electron-packager on?

v6.2.0
osx 10.11.5

> What target platform(s)/architecture(s) are you building for?

osx x64

**Comment by willin** [comment]
nice job

**Comment by willin** [comment]
a new one

```bash
electron-packager . --asar  --overwrite --platform=win32 --arch=ia32 --prune=true --out=
out --version-string.CompanyName='GitHub, Inc.'  --ignore=node_modules
Packaging app for platform win32 ia32 using electron v1.2.0
spawn wine ENOENT
```

**Comment by malept** [comment]
@willin for your first problem, you specified the `--out` parameter without the path that you want your application bundles to be created in.

For your second problem, please see https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms

**Comment by sethlu** [comment]
@malept I think that @willin used the following for packaging:

```sh
electron-packager . --asar --overwrite --platform=darwin --arch=x64 --prune=true --out=out --osx-sign.identity='Developer ID Application: GitHub' --ignore=node_modules
```

So `out` is specified to `out`. But yea I agree; there should be some extra considerations in #386.

**Comment by malept** [comment]
@sethlu I think he just used `--out` which made `opts.out` evaluate to `true`, which explains the error:

> `TypeError: Path must be a string. Received true`

**Comment by sethlu** [comment]
@malept That makes sense as well. However, the restriction to `--out` now only accepting strings should be quite handy.
