### ISSUE TITLE
Question: What strucutre should I use for app?

### ISSUE THREAD

**Issue by bnb** [electron-userland/electron-packager#388]
Hello!

Just wondering how I would end up packaging [npm-gui](https://github.com/bnb/npm-gui). Currently, the electron app's file is in [`/electron`](https://github.com/bnb/npm-gui/tree/master/electron), and the actual app is being built like a normal Express webapp. How would I go about using the current electron app's main file,  [`/electron/npm-gui-app.js`](https://github.com/bnb/npm-gui/blob/master/electron/npm-gui-app.js), as the main file for the build and then boot up the Express app?

> Which version of electron-packager are you using?

Latest

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

    `electron-packager ./ --platform=darwin --arch=x64 --overwrite`

> What version of [Electron](http://electron.atom.io) are you building with?

1.1.1

> What is the host platform are you running electron-packager on?

OS X

> What target platform(s)/architecture(s) are you building for?

OS X (unsigned)

> Is there a stack trace in the error message you're seeing?

Nope

**Comment by malept** [comment]
I think you have two options:
* Run a non-blocking subprocess of node that runs the express app
* Spawn a thread that runs the express app - the main thread handles the Electron UI.

**Comment by bnb** [comment]
@malept Okay, thanks. Would you happen to know of any documentation or modules to accomplish either of these?

**Comment by malept** [comment]
Not offhand, sorry.
