### ISSUE TITLE
executable files not working on windows atleast

### ISSUE THREAD

**Issue by yeganehaym** [electron-userland/electron-packager#389]
i build my execution files for all platforms but windows apps doesn't open
i checked task manager and it was show up for a second and terminated
i didn't test about other platforms yet

> Which version of electron-packager are you using?

^7.0.2

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?
electron-packager . myapp --platform=all --arch=all

> What version of [Electron](http://electron.atom.io) are you building with?

  "electron-prebuilt": "^1.1.3"

> What is the host platform are you running electron-packager on?

win 10 64bits
node 4.4.5

> What target platform(s)/architecture(s) are you building for?
all plats but windows is matter

> Is there a stack trace in the error message you're seeing?

everything is OK apparently 

```
Packaging app for platform linux ia32 using electron v1.1.3
Packaging app for platform win32 ia32 using electron v1.1.3
Cannot create symlinks; skipping darwin platform
Packaging app for platform linux x64 using electron v1.1.3
Cannot create symlinks; skipping mas platform
Packaging app for platform win32 x64 using electron v1.1.3
Wrote new apps to:
E:\Projects\electron\dbtest\myapp-linux-ia32
E:\Projects\electron\dbtest\myapp-win32-ia32
E:\Projects\electron\dbtest\myapp-linux-x64
E:\Projects\electron\dbtest\myapp-win32-x64
```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

**Comment by malept** [comment]
Does the app work without packaging?

**Comment by yeganehaym** [comment]
yes,its working with "electron ." command

**Comment by malept** [comment]
How do you start the packaged app? Double-clicking it in explorer?

**Comment by yeganehaym** [comment]
yes, doesn't show anything on screen when i click on it
but task manager show the process for a second and then it's terminated

**Comment by malept** [comment]
Try running it via the command line and see if there is any output.

**Comment by yeganehaym** [comment]
nothing

**Comment by yeganehaym** [comment]
![elec](https://cloud.githubusercontent.com/assets/5742917/15933939/f6640d06-2e76-11e6-8362-dfd6cb3785d5.png)

**Comment by malept** [comment]
Can you try packaging [electron-quick-start](https://github.com/electron/electron-quick-start) and see if that does the same thing?

**Comment by yeganehaym** [comment]
i'll tell you later,
my net has a problem now unfortunately

**Comment by yeganehaym** [comment]
i tested
it worked by your example

**Comment by malept** [comment]
It seems that there's something specific about your app that causes it to fail. You should create a minimal testcase (using the electron-quick-start app that you tested with as a base) to figure out what that is.

**Comment by englishextra** [comment]
@yeganehaym It would be useful to see what fixes made your app finally start

**Comment by yeganehaym** [comment]
solved
that was my bad and i wasted your time
i have a sql.txt file and i forgot it about
when the app reached to this line
`var sqlStr=fs.readFileSync("./sql.txt");`
sql.txt wasn't exist and stopped app
i must place it on it
is there something to pack other files in this lib?

**Comment by malept** [comment]
electron-packager uses a blacklist to determine what files get copied. Basically so long as your file doesn't match any of the regular expression patterns in the blacklist and it's in the application directory, it should be copied into your application bundle.

**Comment by englishextra** [comment]
@yeganehaym Thanks for describing your fix. I just use electron-packager and plan to update from older version. That's why I asked you to share your experience.

**Comment by yeganehaym** [comment]
@englishextra i know, we should help each other to have a useful page to someone maybe like me

**Comment by paula23andrea** [comment]
Hi!!
I found this issue and it looks like a similar problem i have.
I am using electron-packager for generate .exe for my app.

The app in ubuntu runs perfect, but in Windows crash with this error:

> Error: Cannot find module 'C:\my\path\to\app\resources\app\..\node_sqlite3.node' 

But the file exists in the path.

I don't know what would be the cause of this error. I'm noobie with Electron.

Mi package.json:

`{
  "name": "tm-electron-tests",
  "version": "1.0.0",
  "description": "Desktop App Time Manager",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "package": "electron-packager ./ TimeManagerApp --all --version 1.3.6 --overwrite --icon=./resources/Icon.png"
  },
  "author": "Time Manager",
  "license": "ISC",
  "dependencies": {
    "async": "^2.0.1",
    "bootstrap": "^3.3.7",
    "cheerio": "^0.22.0",
    "electron-prebuilt": "^1.3.6",
    "electron-pug": "^1.5.1",
    "electron-rebuild": "^1.2.1",
    "fibers": "^1.0.14",
    "jquery": "^3.1.0",
    "knex": "^0.12.0",
    "modal-dialog": "^1.6.3",
    "moment": "^2.17.0",
    "promise": "^7.1.1",
    "sqlite3": "^3.1.4",
    "yadcf-npm": "^0.8.9"
  },
  "devDependencies": {
    "electron-packager": "^8.4.0"
  }
}`

Thank you!

**Comment by malept** [comment]
@paula23andrea since you're using a native module, you need to run electron-packager (and electron-rebuild) in Windows to build a bundle for Windows.
