### ISSUE TITLE
Inferred name/version error message should be more specific

### ISSUE THREAD

**Issue by nihakue** [electron-userland/electron-packager#390]
When I run `electron-packager . --all` with the following directory structure:
```
.
├── assets
│   ├── clefs.png
│   ├── free_bar.png
│   └── note.png
├── dist
│   ├── Note.js
│   └── app.js
├── index.html
├── index.js
├── node_modules
├── npm-debug.log
├── package.json
└── src
    ├── css
    │   └── app.css
    └── js
        ├── Note.js
        └── app.js
```
I get the following error:
>Unable to infer name or version. Please specify a name and version.
Cannot find module 'package.json' from '/Users/gabriel/Code'(Properties not found yet: dependencies.electron-prebuilt,devDependencies.electron-prebuilt)

What I'm confused about is the "cannot find module..." bit, because process.cwd() should return /Users/gabriel/Code/sight, but electron-packager is looking in the parent dir. Am I missing something completely obvious?

[Here's my package.json](https://gist.github.com/nihakue/2790e8a7d4ca038c1bbb1367f7fb5698)

> Which version of electron-packager are you using?

"electron-packager": "^7.0.3",

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

 `electron-packager . --all` 

but also

 `electron-packager . --platform mas --arch x64` or any others 

> What version of [Electron](http://electron.atom.io) are you building with?

v1.2.1

> What is the host platform are you running electron-packager on?

OSX 10.11.5 x64

> What target platform(s)/architecture(s) are you building for?

all/any

> Is there a stack trace in the error message you're seeing?

no

> Please provide either a failing testcase or detailed steps to reproduce your problem.

run  `electron-packager . --all` on my machine. 📦

**Comment by malept** [comment]
You need to specify the Electron version, either in the command line (`--version`) or in `package.json` (usually found in `devDependencies` as `electron-prebuilt`). The error message should be clearer about that.

**Comment by nihakue** [comment]
Ah, of course. Not sure if I skimmed the docs too quickly or there's info missing that should be there, but it's fixed now.

I guess the resolve dir being wrong is caused by node-resolve searching the  pdw, not finding version in the package.json there, and then moving to parent and failing there (thus the dir sent to err.message is the parent dir)?

**Comment by malept** [comment]
> I guess the resolve dir being wrong is caused by node-resolve searching the pdw, not finding version in the package.json there, and then moving to parent and failing there (thus the dir sent to err.message is the parent dir)?

That is correct.
