### ISSUE TITLE
How to unpack an app?

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-packager#392]
I am trying to get the source files of an electron app. Just wondering if it's possible to unpack an app if I have the packed files.

Here is the structure of packed app -

```
myapp
        ├── LICENSE
        ├── LICENSES.chromium.html
        ├── content_shell.pak
        ├── myapp
        ├── icudtl.dat
        ├── libgcrypt.so.11
        ├── libnode.so
        ├── locales
        ├── natives_blob.bin
        ├── resources
        ├── snapshot_blob.bin
        └── version
```

> What version of [Electron](http://electron.atom.io) are you building with?

1.2.2

> What is the host platform are you running electron-packager on?

Ubuntu 14.04 - 64 bit

> What target platform(s)/architecture(s) are you building for?
linux-x64

**Comment by malept** [comment]
You want to look at [`asar`](https://github.com/electron/asar), not electron-packager. This application only deals with packing (via `asar`, incidentally), not unpacking.

**Comment by akashnimare** [comment]
@malept Thanks man.
