### ISSUE TITLE
FFMPEG stops working after packed

### ISSUE THREAD

**Issue by ErraticFox** [electron-userland/electron-packager#393]
After I run the packager, ffmpeg no longer works. Why is this? I included it in the files.

> Which version of electron-packager are you using?

7.0.3

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

`electron-packager . Telsar --ignore=node_modules/electron-* --platform=win32 --arch=x64 --icon=app.ico --overwrite`

> What version of [Electron](http://electron.atom.io) are you building with?

3.9.5

> What is the host platform are you running electron-packager on?

Win10 x64

> What target platform(s)/architecture(s) are you building for?

Win x86/x64

> Is there a stack trace in the error message you're seeing?

none

> Please provide either a failing testcase or detailed steps to reproduce your problem.

none

**Comment by malept** [comment]
I'm not sure where you're getting 3.9.5 - that Electron version hasn't come out yet.

**Comment by malept** [comment]
Are you trying to use a custom version of FFmpeg, as opposed to the built-in version?

**Comment by ErraticFox** [comment]
I meant 1.2.2. For some reason npm said that so I put it. I am unable to find any documentation with the bundled version of ffmpeg for electron.

**Comment by malept** [comment]
I should be more specific, how are you using ffmpeg? Via some Node module? (If so, which one?)

**Comment by malept** [comment]
Evidently, 3.9.5 is your NPM version.

**Comment by ErraticFox** [comment]
No, just bundling the executable.

**Comment by malept** [comment]
The executable, as in `ffmpeg.exe`?

**Comment by ErraticFox** [comment]
yes

**Comment by ErraticFox** [comment]
yes

**Comment by malept** [comment]
Without being able to see the code, and assuming that `ffmpeg.exe` exists in the output folder, my guess is that you need to figure out a way to reference `ffmpeg.exe` relative to the file that you're calling it from, as opposed to assuming it's always in the same place.
