### ISSUE TITLE
Packaged App Crashes on Start

### ISSUE THREAD

**Issue by Meadowcottage** [electron-userland/electron-packager#398]
The app I have built works and runs correctly in developer via `npm start`. But when I try to package the app, it packages correctly with no errors. But when the packaged app is run, the app's window open's and then immediately closes.

<img src="https://i.gyazo.com/1dfabfae2f1a22efe892f900274fcc0d.gif">

Platform: Windows 10 x64
Target Platform: Windows 10 x64
Repository: [devRant.io](https://github.com/Meadowcottage/Devrant.io)
Packager Version: 7.0.4
Electron Version: 1.2.2
CLI SCRIPT: `electron-packager . --overwrite --prune --out=../build --ignore='node_modules' --platform=win32 --arch=x64 --icon=../icon/favicon.ico --version-string.FileDescription=devRant.io`
Error Messages: None(No console available to view).

**Comment by malept** [comment]
I see you're also packaging for OSX. Does that work?

**Comment by Meadowcottage** [comment]
Yes, the OSX packages with no error and the app runs without problems. It is just win32 packages like this

**Comment by malept** [comment]
Is there any output if you try running the `.exe` in a console?

**Comment by Meadowcottage** [comment]
No. I run the executable and the the window opens, closes and the console just moved down to the next line. No error messages or any output.

**Comment by malept** [comment]
I can't debug this at the moment, but I would suggest putting `console.log` statements all over `main.js` to see what code did or did not get run.

**Comment by Meadowcottage** [comment]
Okay, I will run some tests and see what does and doesn't run.

**Comment by Meadowcottage** [comment]
[UPDATE] I tested packaging the app with another `main.js` file (Stock main.js file from Electron quick start repo) and the issue still remains.
Assumtion now is that there is some error when packaging.

**Comment by malept** [comment]
Could you try moving your icon so that it's in the same folder as `main.js`? Also, I'm not sure the `icon` parameter of `BrowserWindow` accepts a `.ico` file.

**Comment by Meadowcottage** [comment]
Okay it appears me assigning it the `.ico` file in my `main/js` appeared to be the issue.
I've changed it to be `.png` instead and the app now runs perfectly.
Thanks.
