### ISSUE TITLE
Icon not working on darwin with electron 1.2.2

### ISSUE THREAD

**Issue by r1si** [electron-userland/electron-packager#399]
As issue #300, again with the last version of electron (1.2.2) Icon didn't work on darwin.
If I explore the package the icns file call atom.icns instead electron.icns

> Which version of electron-packager are you using?

7.0.4

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

use API packager function

> What version of [Electron](http://electron.atom.io) are you building with?

1.2.2.

> What is the host platform are you running electron-packager on?

darwin OSX el capitan

> What target platform(s)/architecture(s) are you building for?

all , but the bug still on darwin

> Is there a stack trace in the error message you're seeing?

(node:37556) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> Please provide either a failing testcase or detailed steps to reproduce your problem.

Compile with icon parameters

**Comment by malept** [comment]
I can't reproduce this. I just built my app with Electron 1.2.3, and in `Foo.app/Contents/Info.plist`, the value of `CFBundleIconFile` is `electron.icns`, and `Foo/Contents/Resources/electron.icns` exists as the file I passed in as the icon. Perhaps you did not save the `.icns` file with the correct image sizes?

**Comment by r1si** [comment]
hi @malept Thanks you ! 
The problem is that I have installed an old version of electron-packager :(... 

The last version was installed with -g arguments but my compile script still grab the local one with an old version :S 

Thanks a lot !

Elia
