### ISSUE TITLE
Win32: do I need to distribute the whole folder or simply the .exe file?

### ISSUE THREAD

**Issue by PierBover** [electron-userland/electron-packager#404]
I'm on OSX and packaged a Win32 electron app. The packager has created a folder with a lot of things in it.

Do I have to distribute the whole folder in a .zip or is it enough to distribute the `.exe` file?

I'm on OSX so I can't try for myself.

**Comment by malept** [comment]
You have to distribute the entire folder. There are related projects which create Windows installers for you (see the bottom of the readme for an example of one).
