### ISSUE TITLE
in osx, --icon for windows doesn't work

### ISSUE THREAD

**Issue by rico345100** [electron-userland/electron-packager#405]
I installed wine, but it still not working. This is what I tried:

`$ electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico`

icon-win.ico is 256x256, png converted from web converter here (https://iconverticons.com/online/) and here(http://convertico.com/), both won't work.

this is the error messages:

`Packaging app for platform win32 x64 using electron v1.2.3
spawn wine ENOENT

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:win"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! kurz_io_client@1.0.0 build:win: `electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kurz_io_client@1.0.0 build:win script 'electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico'.
npm ERR! This is most likely a problem with the kurz_io_client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kurz_io_client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls kurz_io_client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rico345100/Desktop/development/1_kurz_io/client/npm-debug.log`

and this is what in npm-debug.log:
`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:win' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prebuild:win', 'build:win', 'postbuild:win' ]
5 info prebuild:win kurz_io_client@1.0.0
6 info build:win kurz_io_client@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info kurz_io_client@1.0.0 Failed to exec build:win script
9 verbose stack Error: kurz_io_client@1.0.0 build:win: `electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid kurz_io_client@1.0.0
11 verbose cwd /Users/rico345100/Desktop/development/1_kurz_io/client
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:win"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error kurz_io_client@1.0.0 build:win: `electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico`
17 error Exit status 1
18 error Failed at the kurz_io_client@1.0.0 build:win script 'electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico'.
18 error This is most likely a problem with the kurz_io_client package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron-packager . Kurz.io --ignore='node_modules/(.bin|electron-packager|electron-prebuilt)' --platform=win32 --arch=x64 --icon=icon-win.ico
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs kurz_io_client
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls kurz_io_client
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

`

> Which version of electron-packager are you using?
i'm using 7.0.3

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?
--ignore='node_modules/(.bin|electron-packager|electron-prebuilt)'
--platform=win32
--arch=x64
--icon=icon-win.ico`

> What version of [Electron](http://electron.atom.io) are you building with?

electron-prebuilt 1.2.0 is what i'm using

> What is the host platform are you running electron-packager on?

latest version of OSX, x64.

> What target platform(s)/architecture(s) are you building for?
Windows 8.1 x64

> Is there a stack trace in the error message you're seeing?

I described above.

> Please provide either a failing testcase or detailed steps to reproduce your problem.
Tried converting .png to .ico two different converter, won't work. Placed same name of .png file in same directory, won't work. Tried --icon with .png won't work. Installed wine, won't work.

**Comment by malept** [comment]
Per the [README](https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms), on non-Windows host platforms such as OS X and Linux, Wine needs to be installed in order for the icon and other application metadata to be set on the Electron app executable.

**Comment by malept** [comment]
Ah, I somehow missed the first line. Make sure `wine` is installed in a folder that's in your `PATH`.
