### ISSUE TITLE
On windows8 --icon doesn't work 

### ISSUE THREAD

**Issue by amtrek** [electron-userland/electron-packager#406]
>Electron packager: 7.0.4

> What CLI arguments are you passing? 
electron-packager . "MyAppName" --platform=win32 --arch=x64 --icon=logo.ico 

> What version of [Electron](http://electron.atom.io) are you building with?
1.2.0

> What is the host platform are you running electron-packager on?
Windows 8, x64

> What target platform(s)/architecture(s) are you building for?
Windows 32, x64

> Is there a stack trace in the error message you're seeing?
no error message

> Please provide either a failing testcase or detailed steps to reproduce your problem.
Place the logo.ico inside the app folder or next to the app folder (change to --icon=../logo.ico), then package the application, the icon is still electron icon. 

I also installed node-rcedit as well. Kindly advise ?

**Comment by kfranqueiro** [comment]
`--icon` works for me on Windows 8, at least testing via https://github.com/kfranqueiro/electron-dojo-boilerplate (updating the electron-packager version in package.json and the electron version in Gruntfile.js).

Are you sure the icon is valid?

**Comment by amtrek** [comment]
Hello, I am fairly new to this. I am pretty sure the icon is valid but I don't use the boilerplate. 
My package json is pretty lean, the icon was specified through the command line.

Package json
{
  "name": "Temperature_Monitoring_Application",
  "version": "1.0.0",
  "description": "A minimal application to display returned temperature",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js"
  },
  "keywords": [
    "Electron",
    "Temperature Monitoring",
  ],
  "author": "Author",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron-prebuilt": "^1.2.0"
  },
  "dependencies": {
    "chokidar": "^1.5.1",
    "jsonfile": "^2.3.1",
    "moment": "^2.13.0",
    "screen": "^0.2.10"
  }
}

**Comment by malept** [comment]
@amtrek 

We're going to need more information about your setup to help you, in particular:

* Which version of electron-packager are you using?
* What CLI arguments are you passing?
* What is the host platform are you running electron-packager on? Please supply name, version, and architecture.
* What image sizes are included in your `.ico` file?

**Comment by malept** [comment]
@matiastucci have you tried different and/or multiple sizes?

**Comment by matiastucci** [comment]
Nope, I'll do that. Also, should I do `--icon=icon.ico` (without the quotes)? I tried both, just in case

**Comment by malept** [comment]
> Also, should I do `--icon=icon.ico` (without the quotes)?

Shouldn't matter.

**Comment by matiastucci** [comment]
Hmm, seems that when I ran it in windows is working. I was running the script from OS before.

**Comment by malept** [comment]
(*I assume you mean OSX.*) If that is the case, it sounds like a bug with using [rcedit](https://github.com/atom/rcedit) under Wine, not electron-packager.

**Comment by matiastucci** [comment]
yeah, that was a typo.
Ah, ok. Thanks!

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in over two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
