### ISSUE TITLE
Does not apply changes on CSS file

### ISSUE THREAD

**Issue by empirefx** [electron-userland/electron-packager#409]
Using https://github.com/electron/electron-quick-start, i've just modify this line ..

`mainWindow.loadURL('http://bar.dev/')`

Its works with **npm start**, But when i use **electron-packager**, its just render a old css, doesn't apply the changes. Why?

**Comment by malept** [comment]
What do you mean by "old css"? Does it shows the `index.html` page that's bundled with `electron-quick-start`, or an old revision of a CSS file that's on `bar.dev`? If it's the second one, I'm unsure how that's a bug specific to electron-packager.

**Comment by empirefx** [comment]
My bad, its a electron bug thats caches pages contents.
