### ISSUE TITLE
is there packager ignore file to ignore a list of modules?

### ISSUE THREAD

**Issue by craigcosmo** [electron-userland/electron-packager#412]
I understand we we use ignore flag `--ignore modules_name` in the command line. However when there many many modules to ignore, writing a script for command is tough task, and it's verbose. So I guess there must be an ignore file just like `.gitignore`. Am I right?

**Comment by malept** [comment]
There are two answers to this question:

1. The `prune` option removes all node_modules that are (directly or indirectly) part of `devDependencies` but not `dependencies` in `package.json`.
2. For additional ignore capabilities, there is a pull request (albeit getting stale) to add an `.electronignore` file, but per the conversation in that PR, I would rather add ignores to `package.json`: #376
