### ISSUE TITLE
Can't build on Travis anymore because of Wine 1.6 requirement

### ISSUE THREAD

**Issue by elisee** [electron-userland/electron-packager#413]
Hi,

As you probably noticed, the recent release of rcedit@0.5.1 doesn't work with Wine 1.4 on a headless server like Travis CI. It generates this error:

    Application tried to create a window, but no driver could be loaded.
    Make sure that your X server is running and that $DISPLAY is set correctly.

[This commit](https://github.com/electron-userland/electron-packager/commit/04b38af3426d35b14e80be3cb151030369171f03) seems to have dealt with that by pinning it back to v0.5.0.

But [the commit right after it](https://github.com/electron-userland/electron-packager/commit/cad839fd160d0d8c872355bdeeeddea655be6038) went back to rcedit 0.5.1, indicating that Wine 1.6 is required instead. I assume this is because Wine 1.6 works in headless mode with rcedit 0.5.1?

Assuming this is correct, [Travis's APT package whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) includes wine (1.4) but not wine1.6, so electron-packager@7.2.0 doesn't work there.

Is there any particular feature / bugfix in rcedit@0.5.1 that is required for electron-packager, such that we can't stay on rcedit@0.5.0 for now? There's [an issue open on Travis's side](https://github.com/travis-ci/apt-source-whitelist/issues/191) to allow installing more recent versions of Wine but it's been open for a long time.

Thanks!

EDIT: If anybody hits the same issue, as a workaround, you can explicitly install rcedit@0.5.0 and electron-packager@7.1.0. See https://github.com/superpowers/superpowers-app/commit/7b726e7d7adc2eed8d1d30043b50e96b7693a3d4

**Comment by malept** [comment]
> I assume this is because Wine 1.6 works in headless mode with rcedit 0.5.1?

My suspicion is that there's a missing implemented function / DLL in Wine 1.4 and the window that pops up is saying that it can't find something. You'd have to run Linux with X and Wine 1.4 to know for sure, though.

> Is there any particular feature / bugfix in rcedit@0.5.1 that is required for electron-packager

Yeah, this seems fairly important: https://github.com/atom/rcedit/issues/17. Pinning the version was always going to be a temporary measure.

I would suggest using the Trusty CI environment. I personally haven't found any significant performance difference between the Precise containers and the Trusty dist.
