### ISSUE TITLE
ignore parameter regex doesn't work as expected 

### ISSUE THREAD

**Issue by kgentes** [electron-userland/electron-packager#421]
I have a working electron-packager build. But adding an array of regex's for the 
`-ignore`
switch produces some unexpected results. I did go to [ignore help](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore) and read the details of the docs before submitting this issue. 

My problem specifically, is that an individual regex array element seems to be used as a partial match pattern for any file name. This is confusing because you can't force begin/end of the regex by using the typical regex ^ or $ markers .  For example, I can use the following array in my ignore option:

```
        electronignore: [
            // directories to ignore
            '.idea',
            'ci',
            'ClientSide',
            'typings',
            'node_modules/electron-download',
            'node_modules/electron-osx-sign',
            'node_modules/electron-rebuild',
            // top level files to ignore
            '.gitignore',
            '.jshintrc',
            '.jscsrc',
            'gulp.config.js',
            'gulpfile.js',
            'README',
            'tsconfig.json',
            'tslint.json',
            'typings.json',
            'webpack.config.js'
        ],
```

it works fine to properly ignore the directories and files as they are listed. However, the one element
`'ci'`
**also** causes the electron-builder to ignore several files (such as 'myRecipe', 'bigRecipe.rec' etc, whic are a few levels lower in my build tree) that include the two letter phrase "ci" in their file names. This was a bit of a shocker to me initially, since all the examples I see show people ignoring directories and file names without marking begin/end for the file/directory names. So, to avoid this from happening, I tried bounding the regex to exact match of the entire file/directory name using the markers, as in:
```
        electronignore: [
            // directories to ignore
            '^.idea$',
            '^ci$',
            '^ClientSide$',
            '^typings$',
            'node_modules/electron-download',
            'node_modules/electron-osx-sign',
            'node_modules/electron-rebuild',
            // top level files to ignore
            '^.gitignore$',
            '^.jshintrc$',
            '^.jscsrc$',
            '^gulp.config.js$',
            '^gulpfile.js$',
            '^README$',
            '^tsconfig.json$',
            '^tslint.json$',
            '^typings.json$',
            '^webpack.config.js$'
        ],

```
But that doesn't work either. In fact, that made it so that none of my patterns matched and nothing was ignored. As a final attempt, I tried just adding / to the end of directory names, thinking that might work, but alas, it fails too (as in):
```
        electronignore: [
            // directories to ignore
            '.idea/',
            'ci/',
            'ClientSide/',
            'typings/',
            'node_modules/electron-download',
            'node_modules/electron-osx-sign',
            'node_modules/electron-rebuild',
            // top level files to ignore
            '.gitignore',
            '.jshintrc',
            '.jscsrc',
            'gulp.config.js',
            'gulpfile.js',
            'README',
            'tsconfig.json',
            'tslint.json',
            'typings.json',
            'webpack.config.js'
        ],
```

I know Regex reasonably well, so I am confused on how the `-ignore` is employing these patterns against the file and directory names.

> Which version of electron-packager are you using?

   "electron-packager": "7.2.0",

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

I am passing the following, with `electronignore `being defined as variously mentioned above...
```
var opts = {
    name: pkg.name,
    platform: 'win32',
    arch: 'x64',
    dir: config.root,                       // source location of app
    out: config.electronbuild,              // destination location for app os/native binaries
    ignore: config.electronignore,          // don't include these directories in the electron app build
    icon: config.icon,
    asar: false,                             // compress the entire source in an asar/zip blob
    //'asar-unpack-dir': config.electroncompiled, // don't use asar to pack the native compiled modules
    overwrite: true,
    version: electronVersion,               // Tell the packager what version of electron to build with
    'app-copyright': pkg.copyright,         // copyright info
    'app-version': pkg.version,             // The version of the application we are building
    'version-string': {                     // Windows Only config data
        CompanyName: pkg.authors,
        ProductName: pkg.name,
        FileDescription: pkg.description,
        OriginalFilename: pkg.name + '.exe'
    }
};
```

> What version of [Electron](http://electron.atom.io) are you building with?

  "electron-prebuilt": "1.2.6",

> What is the host platform are you running electron-packager on?

Windows 7 // win32/ 64 bit

> What target platform(s)/architecture(s) are you building for?

 win32/ 64 bit

> Is there a stack trace in the error message you're seeing?

nope.. just bad file matching as described above..

> Please provide either a failing testcase or detailed steps to reproduce your problem.

above..

**Comment by malept** [comment]
It would help to know what your repository's directory/file tree looks like.

**Comment by malept** [comment]
A couple of other things:

* If you use `prune: true`, you don't need to ignore the `node_modules` you specified.
* [This is the ignore regex](https://github.com/malept/gmusicprocurator-app/blob/85e688267329848d0927e550db3a584fdf2c31b4/Makefile#L13) I currently use to ignore files/directories, and works well. I should change it to have multiple `ignore` parameters.

**Comment by kgentes** [comment]
Here is the raw source tree (before I run NPM INSTALL or any buildling) : 
```
C:\git\utility
+--.idea
|  +--inspectionProfiles
|  \--libraries
+--ClientSide
|  +--api
|  |  +--files
|  |  \--folders
|  \--app
|     +--browser
|     +--images
|     |  \--icons
|     +--shared
|     \--visualization
\--ServerSide
   +--test
   |  \--testfiles
   |     \--XML_MANY_FEATURES
   \--xsdFiles

```

**Comment by malept** [comment]
The docs say that the API requires an array of `RegExp` objects, you have an array of strings. Try converting that last `electronignore` array into `RegExp`s.

**Comment by kgentes** [comment]
**I changed my array to be of regexes as follows.** 

```
        electronignore: [
            // main directories to ignore
            '^(\.idea|ci|ClientSide|typings)$',
            // sub-directories to ignore
            '^node_modules/electron-(download|osx-sign|rebuild)$',
            // top level files to ignore
            '^(\.gitignore|\.jshintrc|\.jscsrc|gulp\.config\.js|gulpfile\.js|README|tsconfig\.json|tslint\.json|typings\.json|webpack\.config\.js)$',
        ],
```

**That fails every time on all files. If I remove the ^ and $ markers, it works for everything, but we are back to the initial problem of the files with the "ci" phrase being also ignored:**

```
        electronignore: [
            // main directories to ignore
            '(\.idea|ci|ClientSide|typings)',
            // sub-directories to ignore
            'node_modules/electron-(download|osx-sign|rebuild)',
            // top level files to ignore
            '(\.gitignore|\.jshintrc|\.jscsrc|gulp\.config\.js|gulpfile\.js|README|tsconfig\.json|tslint\.json|typings\.json|webpack\.config\.js)',
        ],
```

Finally, I tried:

```
        electronignore: [
            // main directories to ignore
            '\b(\.idea|ci|ClientSide|typings)',
            // sub-directories to ignore
            'node_modules/electron-(download|osx-sign|rebuild)',
            // top level files to ignore
            '\b(\.gitignore|\.jshintrc|\.jscsrc|gulp\.config\.js|gulpfile\.js|README|tsconfig\.json|tslint\.json|typings\.json|webpack\.config\.js)',
        ],
```

But that gave me no results as well.  Basically, if these are true Regex objects, the it should recognize ^ or $, as well as \b . But it appears to me that the only thing being recognized is the escape \ for the dot . character, the pipes | for alternation and the open ( and close ) parens for grouping.

I even tried placing it in one regex string (instead of an array) and this fails to ignore anything at all:

`        electronignore: '\b(\.idea|ci|ClientSide|typings|node_modules/electron-(download|osx-sign|rebuild)|\.gitignore|\.jshintrc|\.jscsrc|gulp\.config\.js|gulpfile\.js|README|tsconfig\.json|tslint\.json|typings\.json|webpack\.config\.js)',`


I'm losing my mind here :\

**Comment by malept** [comment]
They're still strings. Try, for example:

```javascript
{
  electronignore: [
    /\b(\.idea|ci|ClientSide|typings)/,
    // etc.
  ]
}
```

**Comment by kgentes** [comment]
**doh. you're right. I've now tried this... it works a little.. but the escape \ does not work to just escape the . character when inside of the \b() enclosure.**

```
       electronignore: [
            /\b(\.idea|ci|ClientSide|typings)/,
            /\b(\.gitignore|\.jshintrc|\.jscsrc|gulp\.config\.js|gulpfile\.js|README|tsconfig\.json|tslint\.json|typings\.json|webpack\.config\.js)/
        ],
```

**to overcome that, I had to do the following:**

```
        electronignore: [
            /\.idea/,
            /\b(ci|ClientSide|typings)/,
            /(\.gitignore|\.jshintrc|\.jscsrc|gulp\.config\.js|gulpfile\.js|README|tsconfig\.json|tslint\.json|typings\.json|webpack\.config\.js)/
        ],
```


**which finally worked. However, I fear that Regex's that have a . in them  will partial match other files in the tree since they are not wrapped in a \b() ....**

**Comment by malept** [comment]
There's probably something weird to do with word boundaries and a literal `.` in `RegExp`s. You'd have to do some testing there.

**Comment by kgentes** [comment]
Yes. the `\b` is a word boundary, and since filenames can contain characters that are not part of the definition of a non-word boundary character , it can't be used as a reasonable pattern match for an entire file name.

The point I guess I am making is that **this implementation of a Regex for the `-ignore` option appears not to be a interpreted as a true regex object, or it would take the ^ and $ characters as beginning and end markers for the data**, which I have tested and it does not.

This is kind of crucial because if this is not supporting begin/end markers for the pattern match, then one can never be sure that a Regex pattern match will equate to the ENTIRE directory or file name, since it appears to be matching things partially as well.  This creates two issues:

1. First, if a file name is replicated in a lower portion of the tree, then it could become a match for the pattern even though it wasn't intended (as in, you want to ignore the folder "ignore" at the top level, but not at the next level down).
2. Second, without the ability to mark the beginning/end of a pattern to a string (file/directory name), then partial matches are always going to be an issue if they are on file names with non-word bound characters. For example, trying to ignore the pattern `/\b(ci)/`  would work for `ci` but would also work for `ci-component` and `ci.txt` , which is a problem.

The -ignore docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)) point to the reg expressions for Mozilla [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) which says that this implementation of regex is supposed to support begin/end markers ( ^ and $ respectively).

Unless I am missing something, this should match a complete filename/directory called "ci":

`/^ci$/`

But it currently does not.

**Comment by malept** [comment]
The `ignore` option is basically a wrapper around the `filter` parameter of [node-fs-extra's `copy` method](https://github.com/jprichardson/node-fs-extra#copy). Both `electron-packager` and `fs-extra.copy` resolve paths to be absolute.

So in your example,

```javascript
/^ci$/
```
should be written as:
```javascript
/\/ci$/
```
and it should ignore any directory that ends in `/ci`. This is based on reading [how `copy` works](https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/ncp.js).

**Comment by malept** [comment]
That being said, I would not be opposed to reviewing a pull request that changes the `ignore` option to only deal with relative file names. This would require:

* Making sure that both the `RegExp` mode and the callback `Function` mode of `ignore` utilize relative paths
* Making sure that the tests still pass (and adding some tests to make sure that absolute paths aren't matching)
* documentation changes making it explicit that `ignore` matches on relative paths instead of absolute paths (NEWS entry as well as API/CLI docs)
* a major version bump, as this breaks backwards compatibility, particularly for the users who use the callback `Function` mode (I'd handle this part)

Let me know if you want to do this, I want to rearrange some code related to this and I don't want to cause any unnecessary merge conflicts.

----

I've updated the docs to be more explicit about how `ignore` works.

**Comment by kgentes** [comment]
Appreciate that. Since the thing I am working on is literally my first Node project (and my first venture into using open source stuff), I'd be overwhelmed trying to tackle something like this at the moment. (In fact, I had to look up what "pull request" meant, evidence enough that I am swimming in new waters here). I wouldn't be opposed to participating at some point, for sure. What would you suggest is a good way to ramp up on this stuff for a newbie like myself?

**Comment by malept** [comment]
> What would you suggest is a good way to ramp up on this stuff for a newbie like myself?

In general, there's a bunch of "getting started with open source contributing" blog posts all over the Internet.

In the context of this project, I wrote up a paragraph about that in the [contributing document](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#contribution-suggestions). Out of the list of issues mentioned, I would look for the ones that look the easiest. I *think* the easiest one at the moment is #121.
