### ISSUE TITLE
Cannot load native extension when using asar

### ISSUE THREAD

**Issue by codehz** [electron-userland/electron-packager#424]
ELECTRON_ASAR.js:158
Uncaught Error: The specified module could not be found.
\\?\C:\Users\<User Name>\AppData\Local\Temp\<RANDOM>.tmp.node

And I can found it in this path..

I think the `\\?\` is unnecessary..

**It appears only when I use this option --asar=true**

> Which version of electron-packager are you using?

7.3.0

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

electron-packager . "VizMusicPlayer" --out=dist/win --platform=win32 --arch=x64 --version=1.2.7 --icon=build/icon.ico --asar=true

> What version of [Electron](http://electron.atom.io) are you building with?

1.2.7

> What is the host platform are you running electron-packager on?

Windows 10 x64

> What target platform(s)/architecture(s) are you building for?

Windows x64

> Is there a stack trace in the error message you're seeing?

(RUNTIME, Electron Renderer Process)
```
ELECTRON_ASAR.js:158
Uncaught Error: The specified module could not be found.
\\?\C:\Users\<User Name>\AppData\Local\Temp\<RANDOM>.tmp.node
```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

https://github.com/VizMusicPlayer/VizMusicPlayer

**Comment by develar** [comment]
So... do you use electron-builder or electron-packager — https://github.com/electron-userland/electron-builder/issues/580 ? It seems it is your app issue, not packaging tool issue.

**Comment by codehz** [comment]
Still Not Work
ELECTRON_ASAR.js:158 Uncaught Error: The specified module could not be found.
\\?\D:\x\desktop\VizMusicPlayer\dist\win\Viz Music Player-win32-x64\resources\app.asar.unpacked\node_modules\sharp\build\Release\sharp.node

I think `\\?\` is the core problem...."\\?\" prefix should be delete

**Comment by malept** [comment]
Try electron-packager 7.2.0 and use `--asar-unpack` instead of `--asar.unpack`. There was a change to asar options in 7.3.0 but it shouldn't have impacted functionality.

**Comment by malept** [comment]
Also, with electron-packager 7.3.0, don't specify `--asar=true` and `--asar.unpack=*.node` at the same time.

**Comment by codehz** [comment]
I have used below(7.3.0)
```
> electron-packager . "Viz Music Player" --app-version=0.0.1 --prune --out=dist/win --platform=win32 --arch=x64 --version=1.2.7 --icon=build/icon.ico --version-string.CompanyName="CodeHz.one" --versio
n-string.ProductName="Viz Music Player" --version-string.FileDescription="Viz Music Player" --overwrite --asar.unpack=*.node
```
(same as before)
and now using 7.2.0 try below
```
> electron-packager . "Viz Music Player" --app-version=0.0.1 --prune --out=dist/win --platform=win32 --arch=x64 --version=1.2.7 --icon=build/icon.ico --version-string.CompanyName="CodeHz.one" --versio
n-string.ProductName="Viz Music Player" --version-string.FileDescription="Viz Music Player" --overwrite --asar=true --asar-unpack=*.node
```
(Not work, same as before)
and this
```
> electron-packager . "Viz Music Player" --app-version=0.0.1 --prune --out=dist/win --platform=win32 --arch=x64 --version=1.2.7 --icon=build/icon.ico --version-string.CompanyName="CodeHz.one" --versio
n-string.ProductName="Viz Music Player" --version-string.FileDescription="Viz Music Player" --overwrite --asar=true --asar-unpack=*.node
```
The last one does work, but it does not used asar...

**Comment by malept** [comment]
I'm not seeing a difference between the second and third command.

**Comment by codehz** [comment]
Sorry, I have removed `--asar` , but forget to update comment....

**Comment by malept** [comment]
Yes, for electron-packager 7.2.0 and below, it is required to use `--asar` if you want asar support.

This seems like a problem with the [`asar`](https://github.com/electron/asar) module. Electron Packager does not transform the options that are passed to the `asar` module at all.

**Comment by drFabio** [comment]
I can confirm that is an Asar issue not electron-packager issue, I am using asar programatically and having the same behaviour

**Comment by vuamitom** [comment]
Please note that this same error can be thrown if dll dependencies are not found for the native node module. 

Details are in last comment on 

electron/asar#129
