### ISSUE TITLE
Asar bug 

### ISSUE THREAD

**Issue by Alcan-Phoenix** [electron-userland/electron-packager#425]
Hello, 
i have  created a simple test app to test electron packager , when i do a normal packaging (no asar) it work just fine, however when i add "--asar=true" and i run the app, the app just blink, and does not show anything else,  and when i delet "app.asar" in y resources folder and relace it with a a simple "app" folder, it work fine, can you please help me ?
PS: i work with electron1.2.5 ad my node modules are "asar , electron-packager , electron-prebuilt , gulp, gulp-run, gulp-asar, gulp-clean " , My OS is Windows 8.1,
 Here is my "Index.js" :
----------------------------------
```
const electron = require('electron')
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600, icon: __dirname + './icon/logo256.ico', webPreferences: {
    nodeIntegration: false
  }})
  mainWindow.setMenu(null);

  // and load the index.html of the app.
  mainWindow.loadURL(`file://${__dirname}/../assets/proj/Ajouter.html`)

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})
```

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

*  Which version of electron-packager are you using?



* What are the exact CLI arguments that you are passing?

**Comment by Alcan-Phoenix** [comment]
first of all thanks for your replay , my electron-packager is "version": "7.3.0" , and it does not give me any CLI arrgument ,,, it just blink for less than a second, and then get closed ,, thats all , but when i remove "../resources/app.asar" to "../resources/app" it work fine , this is the commad i use to package my app: electron-packager ./ --platform=win32 --arch=ia32 --version=1.2.5 --icon=.app/icon/logo256.ico --asar=true

**Comment by malept** [comment]
By CLI argument, I meant the exact command you ran (which you provided). What architecture are you trying to run on? I noticed you are building for the ia32 architecture.

**Comment by Alcan-Phoenix** [comment]
i try to make it for windows 32bit, ia32 and x64 both does the same error

**Comment by Alcan-Phoenix** [comment]
do i need to add something in my index.js? or did i miss something on that command ? 
electron-packager ./ --platform=win32 --arch=ia32 --version=1.2.5 --icon=.app/icon/logo256.ico --asar=true

**Comment by malept** [comment]
If you run the created executable in cmd.exe, is there any output?

**Comment by Alcan-Phoenix** [comment]
i tried it , but it gives no output , maybe am just missing something in the code ,,, or i dont know :/

**Comment by malept** [comment]
I don't know whether `loadURL` can handle `/../` (up one directory), I think you need to make it an absolute path. Also I'm not sure if you can set an `.ico` file in `BrowserWindow`.

**Comment by Alcan-Phoenix** [comment]
but why it work normal when i dont use "asar" ? the problem is only with ".asar" archive

**Comment by kfranqueiro** [comment]
From [the docs](http://electron.atom.io/docs/api/web-contents/#webcontentsloadurlurl-options):

> the url must contain the protocol prefix, e.g. the `http://` or `file://`

**Comment by Alcan-Phoenix** [comment]
@krishnaIndia  thank you for your replay, but i think the problem is with the "asar" not the protocol prefix or the web content

**Comment by malept** [comment]
If I remember correctly, when you use the asar archive, it accesses the file in a different way. That's why using a relative path may not work correctly.

**Comment by Alcan-Phoenix** [comment]
am totaly lost, maybe i should install a module, or maybe add some block of code to index.js ,,,, or maybe both ? !

**Comment by Alcan-Phoenix** [comment]
ummm it magicly work now, but i have no idea why, i have delet the path of the *icone* and i have changed the order of files ad folders,,, not sure why ,,, but it work ,
thank you so much @malept for your help

**Comment by malept** [comment]
Since this question isn't specific to electron-packager (but to using Electron and asar together), I modified the labels accordingly.

**Comment by arenacheck** [comment]
I only had the same problem with the icon file. But I think it´s with everything else that got a path outside of the electron project. As example my windows line:
start "" electron-packager ./ "PROJEKT NAME HERE" --platform=win32 --arch=all --asar=true --icon="./website/images/icon.ico" packageManager=npm

Before I had the icon somewhere else on my C:\ disk and this caused the bugs. Same should be for everything else, src etc. Make sure that all files are inside of your electron project.
