### ISSUE TITLE
Can't build package by error "no such file or directory"

### ISSUE THREAD

**Issue by zombieJ** [electron-userland/electron-packager#426]
by execute `$ electron-packager ./ booker --platform=win32 --arch=ia32`
returns
```
Packaging app for platform win32 ia32 using electron v1.2.5
ENOENT: no such file or directory, link 'C:\softwares\cygwin\tmp\electron-packager\win32-ia32\booker-win32-ia32\electron.exe' -> 'C:\softwares\cygwin\tmp\electron-packager\win32-ia32\booker-win32-ia32\booker.exe'
```

> Which version of electron-packager are you using?
7.3.0

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?
`electron-packager ./ booker --platform=win32 --arch=ia32`

> What version of [Electron](http://electron.atom.io) are you building with?
1.2.5

> What is the host platform are you running electron-packager on?
Running on windows7 x64

> What target platform(s)/architecture(s) are you building for?
windows x32

> Is there a stack trace in the error message you're seeing?
No

> Please provide either a failing testcase or detailed steps to reproduce your problem.
just run the command and return the error. I check the path and find the file `electron.exe` not exist. Clean up the tmp folder still not work.

**Comment by malept** [comment]
Are you running electron-packager inside cygwin?

**Comment by zombieJ** [comment]
@malept both `Cygwin` & `Command Line` throws the same error.
Cygwin error folder path: `C:\softwares\cygwin\tmp`
Command error folder path : `C:\Users\zombieJ\AppData\Local\Temp`

**Comment by malept** [comment]
My suspicion is that there's something wrong with the electron-1.2.5-win32-ia32.zip file that electron-download retrieved (perhaps it didn't download completely, or something). I suggest clearing the electron-download cache directory and trying again. (I'd normally give more complete instructions but I'm not currently in a place to look up information easily, check the electron-download repository for where the cache directory defaults to on Windows.)

**Comment by zombieJ** [comment]
@malept , thanks for your help. Clean the cache fix the issue. I think this issue can be closed.
