### ISSUE TITLE
Windows packager fails with unsupported flags on 3.3.9 version with Electron 1.2.7

### ISSUE THREAD

**Issue by oniseijin** [electron-userland/electron-packager#429]
Fails to package

electron-packager: 3.3.9

Commands: 
 (From gradle Exec, worked in previous versions)
 args  '.', "EDM", "--platform=win32", "--app-version=v" + project.version, "--arch=x64","--out=dist/", "--version=" + electron_version, "--icon=static/images/koan_circle.ico", '--overwrite' , "--ignore=gradle*", "--ignore=idea*" , "--ignore=git*"

electron version: 1.2.7
running on: Linux and OSX
Building for: Win32

Stacktrace:
<pre>
Downloading electron-v1.2.7-win32-x64.zip
[============================================>] 100.0% of 52.59 MB (59.65 kB/s)
Packaging app for platform win32 x64 using electron v1.2.7
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:advapi:EventRegister {5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x404aa7, 0x486060, 0x486078
fixme:advapi:EventSetInformation 2, 0x4833ca, 43
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
Fatal error: Unable to parse version string
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
 undefined
</pre>

**Comment by oniseijin** [comment]
Hmm, version string was v0.1.4; fails, changing to 0.1.4 and it was fine; strange

**Comment by malept** [comment]
It's probably a limitation of the Windows executable metadata - it probably expects the application version to be in the format N.N.N or similar.
