### ISSUE TITLE
--ignore regex works on Mac but fails on Windows

### ISSUE THREAD

**Issue by SimplyAhmazing** [electron-userland/electron-packager#432]
When I invoke `electron-packager` and pass the ignore flag like so `--ignore="(node_modules/electron-prebuilt|backend|test|*.md$)"` it works fine on Mac and the proper files get ignored.

Yet when I run electron-packager with this same ignore flag and regex on windows I get an error saying `node_modules` is not a recognized command (or the name of the first pattern in my ignore regex)..

Alternatively I've tried `--ignore=node_modules/some-lib --ignore=test --ignore=foo` -- this works fine on Mac but when run on windows it doesn't do any ignoring...

What am I missing on passing the ignore flag with a regex string for Windows OS?

> Which version of electron-packager are you using?
v7.3.0

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are

`electron-packager ./ MyApp --arch=x64 --platform=win32|darwin --asar=true --overwrite=true --icon=path/to/icon --ignore=[not sure how this works on windows]`
> you passing to the `packager()` function?
no

> What version of [Electron](http://electron.atom.io) are you building with?
v1.2.4

> What is the host platform are you running electron-packager on?
Windows, x64

> What target platform(s)/architecture(s) are you building for?
Windows, x64

> Is there a stack trace in the error message you're seeing?
No stack trace

> Please provide either a failing testcase or detailed steps to reproduce your problem.

`electron-packager ./ MyApp --arch=x64 --platform=win32--asar=true --overwrite=true --icon=path/to/icon --ignore="(node_modules/electron-prebuilt|backend|test|*.md$)"`

**Comment by malept** [comment]
A couple of things:

* Per the [docs for `ignore`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore), `electron-prebuilt` is ignored by default.
* Your regex for Markdown files is incorrect, it should be `\.md$` (remove the `*` since this is a regex and not a glob)

**Comment by malept** [comment]
Also, instead of using `|` with one regular expression, specifying `--ignore` multiple times might work out better.

**Comment by englishextra** [comment]
@SimplyAhmazing 

Just to share, this is how I handle the ignore regexp:

```
:: electron-packager ./www englishextra-app --out=./.dist --ignore="(cdn|fonts\/englishextra-ui-icons-fontfacekit\/demo\.css|fonts\/englishextra-ui-icons-fontfacekit\/fontface\.css|fonts\/englishextra-ui-icons-fontfacekit\/demo\.html|fonts\/englishextra-ui-icons-fontfacekit\/demo\.js|libs\/koala-config\.json|libs\/article\/css\/bundle\.css|libs\/article\/js\/bundle\.js|libs\/contents\/css\/bundle\.css|libs\/contents\/img\/contents-banner-aids-640x336\.svg|libs\/contents\/img\/contents-banner-articles-640x336\.svg|libs\/contents\/img\/contents-banner-cup-640x336\.svg|libs\/contents\/img\/contents-banner-ege-640x336\.svg|libs\/contents\/img\/contents-banner-gg-640x336\.svg|libs\/contents\/img\/contents-banner-gia-640x336\.svg|libs\/contents\/img\/contents-banner-grammar-640x336\.svg|libs\/contents\/img\/contents-banner-irrverbsscr-640x336\.svg|libs\/contents\/img\/contents-banner-languagelink-640x336\.svg|libs\/contents\/img\/contents-banner-more-640x336\.svg|libs\/contents\/img\/contents-banner-oup-640x336\.svg|libs\/contents\/img\/contents-banner-reading-640x336\.svg|libs\/contents\/img\/contents-banner-rosolymp-640x336\.svg|libs\/contents\/img\/contents-banner-tests-640x336\.svg|libs\/contents\/img\/contents-banner-transcripts-640x336\.svg|libs\/contents\/img\/sprite\.fw\.png|libs\/contents\/img\/\.mogrify\.bat|libs\/contents\/js\/bundle\.js|res|\.dir\.bat|\.dir\.txt|config\.xml|favicon\.ico|icon\.icns|icon\.png)" --overwrite --prune --platform=win32 --arch=ia32 --cache=./.electron --icon=./www/favicon.ico --version=0.36.5
```

**Comment by malept** [comment]
Hmm. You shouldn't need to escape `/` but it's worth trying.

**Comment by englishextra** [comment]
@malept escaping `/`— just a useful habbit

**Comment by SimplyAhmazing** [comment]
Thanks @malept - the multiple flags ended up working! Also thanks @englishextra
