### ISSUE TITLE
Wrong Mac OS App icon name

### ISSUE THREAD

**Issue by sdussaut** [electron-userland/electron-packager#434]
When icon flag is set on the command line and building for OSX (I did not test any other platform for now), the icon is copied as `atom.icns` while in the Info.plist the `CFBundleIconFile` key points to `electron.icns`, resulting in the wrong icon being displayed for the bundled app.

For reference, I am running electron-packager v7.4.0 (the latest to date), electron v1.2.8 and build on OSX 10.11.6.
Here is the command line I use for packaging:

`electron-packager ./builds --platform=darwin --arch=x64 --icon=./builds/media/img/app.icns --prune --asar --out=/Users/[user]/Desktop/`

Thanks for that very useful tool!

**Comment by malept** [comment]
Hi, thanks for filing an issue. Unfortunately, I can't reproduce this. These are the steps I used:

1. `git clone https://github.com/electron/electron-quick-start && cd electron-quick-start`
2. `npm install --save-dev electron-packager`
3. `wget https://github.com/electron-userland/electron-packager/raw/master/test/fixtures/monochrome.icns`
4. `$(npm bin)/electron-packager . --icon=monochrome.icns --out=/tmp/test-icon`
5. To make sure that `CFBundleIconFile` points to `electron.icns`: `grep -r --binary-files=without-match -A1 CFBundleIconFile /tmp/test-icon`
6. To make sure that `monochrome.icns` and `electron.icns` are the same: `md5sum monochrome.icns /tmp/test-icon/electron-quick-start-darwin-x64/electron-quick-start.app/Contents/Resources/electron.icns` (the two 32 character hex strings should be the same)

Could you please provide a minimal testcase and command line that reliably reproduces this problem?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
