### ISSUE TITLE
Should we disable CI building on every non-master push?

### ISSUE THREAD

**Issue by zeke** [electron-userland/electron-packager#436]
Travis is currently building on every push. Does anyone need that feature? If not, lets disable it and only build PR pushes.

![screen shot 2016-08-03 at 11 45 27 am](https://cloud.githubusercontent.com/assets/2289/17377735/e72c1bb6-596f-11e6-997a-8759fd5dff07.png)

**Comment by malept** [comment]
(_I clarified the question because we're not going to disable building pushes to master, and also we use AppVeyor for Windows builds._)

I don't have an opinion either way. If we decide to do so, we (probably meaning I) need to make sure that AppVeyor also follows that convention.

**Comment by zeke** [comment]
Thanks, @malept
