### ISSUE TITLE
electron-packager-7.5.0 can't find dist/package.json

### ISSUE THREAD

**Issue by acostela** [electron-userland/electron-packager#439]
I use this packager every day inside a CI server and everything worked fine until last nightly. Without changing any code it started to fail. The only difference is that the previous nightly was using electron-packager-7.4.0. After update I get. Error: Cannot find module 'dist\package.json'. I attach complete error.

![image](https://cloud.githubusercontent.com/assets/1210953/17431183/f99277ac-5af8-11e6-8cd5-a946f3da1cbf.png)

I'm using windows 8.1 npm v3 

Thank you so much

**Comment by simonkern** [comment]
Same here on OS X. 7.4.0 is working fine for me, but 7.5.0 throws:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at getNameAndVersion (/usr/local/lib/node_modules/electron-packager/index.js:52:13)
    at packager (/usr/local/lib/node_modules/electron-packager/index.js:207:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-packager/cli.js:22:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

**Comment by simonkern** [comment]
Might have something to do with:

https://github.com/electron-userland/electron-packager/commit/c508500a7108f7c66cb29c4af9a81ad5233c1194#diff-168726dbe96b3ce427e7fedce31bb0bcL8

**Comment by maxkueng** [comment]
I have the same problem.

It looks like the path returned on [index.js#52](https://github.com/electron-userland/electron-packager/blob/3029682cfe4d67381bd5913b34127fa8c0b98250/index.js#L52) by `path.join(dir, 'package.json')` is just `"package.json"` instead of `"./package.json"` even though `dir` equals `"."`. So Node is going to look for a module called "package.json" in `node_modules` which doesn't exist.

**Comment by maxkueng** [comment]
@jhen0409 wow that was faster than I could save the comment!

**Comment by magneticnoodle** [comment]
Hi guys, I am also running the same issue. Have anyone found any temporary fix at the moment?
![screenshot from 2016-08-06 18-38-26](https://cloud.githubusercontent.com/assets/19518296/17456530/fdbc6498-5c04-11e6-8778-f36f414898f6.png)
