### ISSUE TITLE
Fix infer electron test introduced in 7.5.0

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-packager#441]
Since #435 was merged, tests for Node 4 in all host platforms intermittently raise an exception at the new infer Electron test.

Examples:

* [Windows](https://ci.appveyor.com/project/electron-userland/electron-packager/build/1.0.181/job/eeydexhmw188r27n#L615)
* [OS X](https://travis-ci.org/electron-userland/electron-packager/jobs/149960137#L275)
* [Linux](https://travis-ci.org/electron-userland/electron-packager/jobs/149908996#L2326)

CC: @zeke

**Comment by zeke** [comment]
ack. investigating.

**Comment by malept** [comment]
I took a couple of minutes to look into it this morning. Here's how I reliably reproduced the problem:

1. Switch to Node 4 environment (I used nodeenv)
2. Take an existing checkout of electron-packager (<= 7.4.0) and run `git pull && npm install`
3. Run `node test/basic.js`, *not* `npm test`

This intermittent error may have actually been an indicator for the problem in #439, but I'll need to see what CI says about that. In the meantime, I committed https://github.com/electron-userland/electron-packager/commit/bcc7cace97e17acbb03cc5d10e16e732532f1687 which at least gives a better exception.

**Comment by malept** [comment]
:disappointed: still happening: https://travis-ci.org/electron-userland/electron-packager/jobs/150300592#L273

I'm dropping it from the 7.5.1 milestone but I'd still like this to get fixed ASAP.

**Comment by zeke** [comment]
Following these steps:

```
n 4.4.7
git checkout tags/v7.4.0
rm -rf node_modules
npm i
node test/basic.js
```

I have run the tests several times and am not able to produce an error.

**Comment by malept** [comment]
If I've learned anything from debugging intermittent test failures in general, it's that running a test in a testsuite vs. a single file has a tendency to be different, if a) your test runner does not isolate your tests properly, or b) you don't write your setup/teardown functions to isolate your tests properly.

My suspicion is that the failure will happen more often when running `npm test` rather than `node test/basic.js`.

**Comment by malept** [comment]
I don't consider this fixed (because it still happens intermittently), so I'm reopening.

**Comment by malept** [comment]
Regarding the reproduction steps in https://github.com/electron-userland/electron-packager/issues/441#issuecomment-238031674 - they reliably reproduced the error until *after* https://github.com/electron-userland/electron-packager/commit/bcc7cace97e17acbb03cc5d10e16e732532f1687 was committed. Now it's just an intermittent error.

To assist in debugging this issue, I removed the use of `tap-spec`, which I suspect is hiding the real reason why it's failing.

**Comment by malept** [comment]
Well, that's significantly more helpful:

https://travis-ci.org/electron-userland/electron-packager/jobs/151815017#L252-L283

**Comment by kevinsawicki** [comment]
Can this be closed now? It doesn't seem to be happening once #452 was merged with the `npm install --no-bin-links` change.

**Comment by malept** [comment]
Sounds good.

**Comment by zeke** [comment]
Thanks for the help getting this fixed.
