### ISSUE TITLE
Electron Win32 on 32bit architecture not working

### ISSUE THREAD

**Issue by arifbutt1964** [electron-userland/electron-packager#444]
Hi,
I am using Windows 7 and have downloaded the prebuilt Electron windows versions using the electron packager, this created 2 folders: 
"electron_tutorial_one-win32-ia32"
"electron_tutorial_one-win32-x64"

The x64 is working OK on windows 64 bit machines but the ia32 version is not working on Win7 32 bit machines, giving an error that it is not compatible, see the attached file error description.

I have also tried to copy the Libeay32.dll but did not help...

![image](https://cloud.githubusercontent.com/assets/20858615/17481513/0ae8af12-5d97-11e6-8d35-b437e85ab4d2.png)

Kindly assist

Regards
Arif
arifbutt1964@gmail.com

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager for the `win32` target platform and the `ia32` target architecture, with the environment variable `DEBUG=electron-packager`.

* What command line arguments are you passing?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by arifbutt1964** [comment]
Hi 

I am using the electron package interactive epi which is a wrapper for electron packager and here is the console out put for win32 & i32...

![image](https://cloud.githubusercontent.com/assets/20858615/17482426/2db56aae-5d9b-11e6-9b9d-12002457022e.png)

Thanks
Arif

**Comment by malept** [comment]
Could you run `SET DEBUG=electron-packager` before running `epi`?

Also, have you tried earlier or later versions of Electron?

**Comment by arifbutt1964** [comment]
I have already set SET DEBUG=electron-packager on command line before running the epi

No I have not tried the earlier version or later one... should I?

Arif

**Comment by arifbutt1964** [comment]
how to do if I have to install the later/earlier version of electron?

Arif

**Comment by malept** [comment]
It sounds like you're running an old version of electron-packager. What is the output when you run `npm ls -g electron-packager` ?

> No I have not tried the earlier version or later one... should I?

I ask because there are newer releases of Electron than 1.2.2. Try 1.2.8 or 1.3.2.

> how to do if I have to install the later/earlier version of electron?

Specify a different Electron version when electron-packager-interactive asks for "Electron version release".

**Comment by arifbutt1964** [comment]
OK let me try

**Comment by arifbutt1964** [comment]
there is so deep tree of folders... which one to take?

C:\newver\releases\electron_tutorial_one-win32-ia32\resources\app\releases\electron_tutorial_one-win32-ia32\resources\app\myapp.exe-win32-ia32

**Comment by arifbutt1964** [comment]
Sorry... it is producing the same ERROR

**Comment by malept** [comment]
It looks like you need to adjust "ignore".

Could you find out which version of electron-packager you have installed? The command to find out is in [an earlier comment](https://github.com/electron-userland/electron-packager/issues/444#issuecomment-238264846).

**Comment by arifbutt1964** [comment]
electron v 1.3.2

**Comment by malept** [comment]
Please run this and paste the output:

```
npm ls -g electron-packager
```

**Comment by arifbutt1964** [comment]
![image](https://cloud.githubusercontent.com/assets/20858615/17484740/d00bd15e-5da4-11e6-9922-32421c3d2733.png)

**Comment by arifbutt1964** [comment]
C:\Program Files\nodejs>npm ls -g electron-packager
C:\Users\Administrator\AppData\Roaming\npm
├── electron-packager@7.0.4
└─┬ electron-packager-interactive@0.0.7
  └── electron-packager@7.3.0

**Comment by arifbutt1964** [comment]
I cannot ignore this... once I press OK button then nothing happens

**Comment by malept** [comment]
That's not what I mean by "ignore". There is a parameter in electron-packager that lets you avoid the nesting that you saw in https://github.com/electron-userland/electron-packager/issues/444#issuecomment-238267842. But that's not important at the moment.

**Comment by arifbutt1964** [comment]
ok so I wait for your feedback

**Comment by arifbutt1964** [comment]
Hi there, is there any update on the above issue... can we expect any resolution soon?

Regards
Arif

**Comment by malept** [comment]
The main problem is that I need to set up a Windows 7 + 32 bit environment and I haven't found the time to do so yet. The other problem is that I need a very small example project to use to reproduce the problem. That would be very helpful to use to debug.

**Comment by arifbutt1964** [comment]
Its very easy to regenerate just run the epi and select win32 and ia32 options with a directory specification, in my case I made c:\newver and c:\newver\releases folders as the following screen:

![image](https://cloud.githubusercontent.com/assets/20858615/17559639/66207bba-5f38-11e6-865b-d40341fad6a0.png)

this will generate a folder **C:\newver\releases\electron_tutorial_one-win32-ia32\resources\app\releases\electron_tutorial_one-win32-ia32\resources\app\myapp.exe-win32-ia32**

Then simply run the myapp.exe.exe file and see the error:

regards
Arif

**Comment by malept** [comment]
That part you already gave, the part that I'm missing is the application code that you're using.

**Comment by arifbutt1964** [comment]
no code just using as default

**Comment by arifbutt1964** [comment]
if u want i ca arrange ateam viewer session for u on win32 win7 machine

**Comment by malept** [comment]
Can you install the [`electron`](https://www.npmjs.com/package/electron) node module onto the windows 7 32-bit machine and try to run the app that way?

**Comment by arifbutt1964** [comment]
ok i will do that tomorrow... will update u then

**Comment by arifbutt1964** [comment]
will epi install electron also?

**Comment by malept** [comment]
No. (Not directly.)

**Comment by arifbutt1964** [comment]
ok

**Comment by malept** [comment]
I finally got a virtual machine of 32-bit Windows 7 running. I cannot reproduce this problem.

Detailed reproduction steps:

1. Load Windows 7
2. Install latest version of Node 4 (4.4.7 at the time of this comment)
3. Download zip of [electron-quick-start](https://github.com/electron/electron-quick-start) (mostly because I didn't feel like trying to install Git)
4. Unzip electron-quick-start
5. Open a `cmd.exe` window
6. `cd` to your unzipped `electron-quick-start`
7. Run `npm install`
8. Run `node_modules\.bin\electron .` (the final space then period is important) - an Electron window should show up with Node/Chromium/Electron versions and a devtools pane.
9. Close that window.
10. Run `npm install --save-dev electron-packager`
11. Run `SET DEBUG=electron-packager`
12. Run `node_modules\.bin\electron-packager . --platform=win32 --arch=ia32 --app-version=0.0.1 --out=dist` _(the `--app-version=0.0.1` flag isn't necessary, but it was in your screenshot)
13. Run `explorer dist\electron-quick-start-win32-ia32`. It should open up a new folder view of your bundled example app.
14. Double click on `electron-quick-start` (possibly `electron-quick-start.exe` depending on your folder settings). You should see the same thing as in step 8.

I'm not using electron-packager-interactive here because this isn't a bug for that.

**Comment by arifbutt1964** [comment]
OK I will try to do this ... it seems that some of the files are missing in the package and therefore it is not running once installed on new machines.
But if it works then it means that we will have to perform all the above steps on every win32 based machine.
I was thinking for a more flexible workout such as only perform the prebuilt installation with installing the npm etc ...

Anyways lets see how it goes

Regards
Arif

**Comment by malept** [comment]
> But if it works then it means that we will have to perform all the above steps on every win32 based machine.

That was to prove that I can create 32-bit Windows executables successfully in general.

For completeness, here is a *detailed* set of reproduction steps without having to install Node or Electron onto Windows 7:

1. Load Linux machine with Node and Git installed
2. Open a command line prompt and run the commands in steps 3 through 7, in order:
3. `git clone https://github.com/electron/electron-quick-start && cd electron-quick-start`
4. `npm install --save-dev electron-packager`
5. `DEBUG=electron-packager $(npm bin)/electron-packager . --platform=win32 --arch=ia32 --app-version=0.0.1 --out=dist`
6. `cd dist/electron-quick-start-win32-ia32`
7. `zip -r ../test-app-win32-ia32.zip .`
8. Transfer `test-app-win32-ia32.zip` to Windows machine
9. In Windows, right-click `test-app-win32-ia32.zip` and Select `Extract All...`
10. Pick a folder to extract to and make sure "Show extracted files when complete" is selected
11. In the newly open, uncompressed folder, double-click `electron-quick-start` (or `electron-quick-start.exe`, depending on your folder settings). You should see the window described in Step 8 of the [original reproduction steps](https://github.com/electron-userland/electron-packager/issues/444#issuecomment-239076055).

Using these steps, I still cannot reproduce your problem.

**Comment by arifbutt1964** [comment]
OK, however I was actually running a Windows 7 64bit machine with Node and git installed... let me try this on Linux machine this time...

Thanks
Regards
Arif

**Comment by malept** [comment]
For building on a Windows 7 64 bit machine, it's the same as the [original reproduction steps](https://github.com/electron-userland/electron-packager/issues/444#issuecomment-239076055), except after step 12:

1. Compress the `electron-quick-start-win32-ia32` into a ZIP file
2. Follow steps 8 through 11 of the [second set of reproduction steps](https://github.com/electron-userland/electron-packager/issues/444#issuecomment-239171075)

**Comment by arifbutt1964** [comment]
I am doing a linux based steps:

step 1 to 4 are done OK, but now on step 5 I am getting this error

[root@xms /]# DEBUG=electron-packager $(npm bin)/electron-packager . --platform=win32 --arch=ia32 --app-version=0.0.1 --out=dist
-bash: /node_modules/.bin/electron-packager: No such file or directory

[root@xms /]#


Kindly assist

**Comment by malept** [comment]
instead of `$(npm bin)/electron-packager`, use `node_modules/.bin/electron-packager`. It seems your npm isn't configured correctly for whatever reason on what I hope is a Docker container.

**Comment by arifbutt1964** [comment]
I see the following:

[root@xms electron-packager]# pwd
/electron-quick-start/node_modules/electron-packager

[root@xms electron-packager]# cd node_modules

[root@xms node_modules]# ls
asar   electron-download  extract-zip  lodash.get  plist   resolve
debug  electron-osx-sign  fs-extra     minimist    rcedit  run-series

**Comment by malept** [comment]
Perhaps it's not a good idea to use the Linux reproduction steps if you're not familiar with Linux. `.bin` is a hidden directory because it starts with a `.`.

**Comment by arifbutt1964** [comment]
I am still getting :+1: 
[root@xms electron-packager]# node_modules/.bin/electron-packager
-bash: node_modules/.bin/electron-packager: No such file or directory
[root@xms electron-packager]#

**Comment by malept** [comment]
You're in the wrong directory. You are in `/electron-quick-start/node_modules/electron-packager`, you need to be in `/electron-quick-start`.

**Comment by arifbutt1964** [comment]
[root@xms electron-quick-start]# pwd
/electron-quick-start

[root@xms electron-quick-start]# node_modules/.bin/electron-packager . --platform=win32 --arch=ia32 --app-version=0.0.1 --out=dist

/electron-quick-start/node_modules/electron-packager/cli.js:5
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by malept** [comment]
It appears that you're running Node < 4.0.

Node 4.0 or greater is required as of electron-packager 7.0.0, per:

* [the NEWS file](https://github.com/electron-userland/electron-packager/blob/v7.0.0/NEWS.md#700---2016-04-17)
* [the installation instructions](https://github.com/electron-userland/electron-packager#installation)
* the [`engines` section of `package.json`](https://github.com/electron-userland/electron-packager/blob/v7.0.0/package.json#L42-L44)

----

I don't have any more time today to debug this. I strongly suggest trying the Windows reproduction steps (either 32-bit or 64-bit).

**Comment by arifbutt1964** [comment]
OK
thanks

**Comment by arifbutt1964** [comment]
OK I am successfully done with the windows steps... now trying the dist in windows 32 machine

**Comment by arifbutt1964** [comment]
OKAY ... running successfully ... Thanks a lot.. really appreciate it...

Regards
Arif

**Comment by arifbutt1964** [comment]
Hi There

We would like to run google speech to text (STT) application with gRPC
support in electron...
Kindly let us know how we can do it and to download it and build it...

Sample site  https://dictation.io/speech


Thnx

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.
