### ISSUE TITLE
Confusing documentation about version-string option

### ISSUE THREAD

**Issue by albertvazquezm** [electron-userland/electron-packager#447]
Hi,

In API documentation, params are kebab-case. Wich is not allowed in a javascript object. I can replace it by camelCase, but the exe description and product name is not updated and don't know if it's error about format or just a bug in electron-packager.

My config looks like: (some fields omitted)

`let options = {`
 `    dir: './dist',`
 `         versionString: {`
      `         CompanyName: config.authors, `
       `        FileDescription: config.description,`
     `          OriginalFilename: config.title,`
     `          ProductName: config.title,`
                `InternalName: config.title`
 ` }`
`};`

And the exe gets that config:

First highlighted field is File Description and the second one is Product Name (Sorry for Spanish OS) :)

![electron-exe-notupdating](https://cloud.githubusercontent.com/assets/10158320/17584149/515139c2-5fb5-11e6-99f1-10e15de2e18d.PNG)

Thanks!

**Comment by malept** [comment]
"kebab-case" parameters are allowed in a JavaScript object, you just need to write them as strings, for example:

```javascript
{
  "version-string": {
    ProductName: "My Product",
    // etc.
  }
}
```

Changing `version-string` to be more `Object`-friendly has been reported in #325 (and also #331).

**Comment by albertvazquezm** [comment]
It worked for me, thank you!
