### ISSUE TITLE
Code signing on Mac OS-X fails?

### ISSUE THREAD

**Issue by reiberdatschi23** [electron-userland/electron-packager#453]
Hi,

Using latest electron-packager to generate an Mac App out of our electron app. Works perfectly. But calling mac codesign on our app yields in this error:

$ codesign -s "Developer ID Application: Gravit GmbH" Gravit.app

Gravit.app: code object is not signed at all
In subcomponent: /dist/electron/Gravit-darwin-x64/Gravit.app/Contents/Frameworks/Electron Framework.framework

I have no clue what this means, shouldn't code signing work out of the box for an electron packaged app on mac?

**Comment by pfrazee** [comment]
@reiberdatschi23 did you ever figure this out?

**Comment by malept** [comment]
It doesn't look like the issue reporter was using the [`osx-sign`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#osx-sign) option to sign the app, but rather calling `codesign` directly.

**Comment by reiberdatschi23** [comment]
@pfrazee yes I was too dumb.. forgot to not only install wine but also mono on osx ;)

**Comment by reiberdatschi23** [comment]
@pfrazee nope sry we have switched to use the mac codesign utility directly which works perfectly.

**Comment by pfrazee** [comment]
Yeah, I ended up solving my issues by switching to electron-builder.
