### ISSUE TITLE
creating with --arch=all from project directory includes previous build in subsequent build

### ISSUE THREAD

**Issue by quantumproducer** [electron-userland/electron-packager#456]
**Please describe your issue:**

electron-packager . QuantumPilot --platform=win32 --arch=all

Will build the 32 bit version
And then build the 64 bit version with the 32 bit version inside of the 64 bit version's resources folder.

I think this is best resolved by issuing a warning to the user when they run electron-packager in "." current directory with multiple architectures as specified by `arch=all`

```
~/code/electron-quick-start:.electron-packager . QuantumPilot --platform=win32 --arch=all
Packaging app for platform win32 ia32 using electron v0.36.11
Packaging app for platform win32 x64 using electron v0.36.11
Wrote new apps to:
/Users/quantum/code/electron-quick-start/QuantumPilot-win32-ia32
/Users/quantum/code/electron-quick-start/QuantumPilot-win32-x64

~/code/electron-quick-start:.ls QuantumPilot-win32-x64/resources/app/QuantumPilot-win32-ia32/
LICENSE					msvcp120.dll
LICENSES.chromium.html			msvcr120.dll
QuantumPilot.exe			natives_blob.bin
content_resources_200_percent.pak	node.dll
content_shell.pak			pdf.dll
d3dcompiler_47.dll			resources
ffmpeg.dll				snapshot_blob.bin
icudtl.dat				ui_resources_200_percent.pak
libEGL.dll				vccorlib120.dll
libGLESv2.dll				version
locales					xinput1_3.dll
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager . QuantumPilot --platform=win32 --arch=all
```

**Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good
starting point.**

See above. Expected result: the ls Quantumpilot-win32-x64/resources/app/Quantumpilot-win32-ia32 should show nothing .

I understand why this is happening, I think a warning message to the user would be sufficient. If this is viewed as a bug in the electron-packager workflow, then perhaps writing all output files to a temporary directory and moving those into the target directory when finished would fix the issue.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run the `electron-packager` command you specified with the environment variable `DEBUG=electron-packager` set. Please paste it in the block where it says "Put the console output here".

**Comment by quantumproducer** [comment]
Hi malept, do you mean

```
DEBUG=electron-packager
electron-packager . Quantumpilot --platform=win32 --arch=all
```

The output is

```
Packaging app for platform win32 ia32 using electron v0.36.11
Packaging app for platform win32 x64 using electron v0.36.11
Wrote new apps to:
/Users/quantum/code/electron-quick-start/Quantumpilot-win32-ia32
/Users/quantum/code/electron-quick-start/Quantumpilot-win32-x64
```

If this is the correct way of running with the debug set, I will put into the main post.

**Comment by malept** [comment]
You want to put `DEBUG=electron-packager` on the same line as your electron-packager command.

**Comment by quantumproducer** [comment]
Like this?

```
~/code/electron-quick-start:.DEBUG=electron-packager electron-packager . QuantumPilot --platform=win32 --arch=all
Packaging app for platform win32 ia32 using electron v0.36.11
Packaging app for platform win32 x64 using electron v0.36.11
Wrote new apps to:
/Users/quantum/code/electron-quick-start/QuantumPilot-win32-ia32
/Users/quantum/code/electron-quick-start/QuantumPilot-win32-x64
~/code/electron-quick-start:.
```

**Comment by malept** [comment]
Yes, but you seem to be using an older version of electron-packager. Please use the newest version.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two months, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
