### ISSUE TITLE
Finder.app can't remove the output folder on OSX

### ISSUE THREAD

**Issue by kaansoral** [electron-userland/electron-packager#458]
The output folder can't be removed, the Finder.app asks the user password, but even with the password provided, the folder is there to stay, the contents can be removed, the folder can be renamed, but it can't be removed

Here is the output of ls-al

```
Kaans-MacBook-Pro:electron kaan$ ls -al
total 56
drwxr-xr-x   9 kaan  staff   306 Aug 18 04:49 .
drwxr-xr-x  36 kaan  staff  1224 Aug 17 14:34 ..
-rw-r--r--@  1 kaan  staff  8196 Aug 18 04:44 .DS_Store
-rw-r--r--   1 kaan  staff   361 Aug 17 11:54 index.html
-rw-r--r--   1 kaan  staff   203 Aug 18 04:28 info.txt
-rw-r--r--   1 kaan  staff  1713 Aug 17 14:54 main.js
drwxr-xr-x   2 kaan  staff    68 Aug 18 04:37 normalfolder
-rw-r--r--   1 kaan  staff   100 Aug 18 04:27 package.json
drwxr-xr-x   3 kaan  staff   102 Aug 18 04:41 stuckfolder
```

(Originally stuckfolder was called "Project Name-darwin-x64")

Disclaimer, my UNIX knowledge is limited, between the normalfolder and stuckfolder, the only difference is the link count, stuckfolder has 3

Is there anything in the build process that could cause this situation?

I'm very paranoid, I'm sure most OSX users are paranoid like me, when you are asked for the system password on a regular operation, it's pretty demotivating

**Comment by malept** [comment]
Thanks for filing a bug! This is the same issue as #375.
