### ISSUE TITLE
Simplify package.json inference

### ISSUE THREAD

**Issue by zeke** [electron-userland/electron-packager#461]
Following up on https://github.com/electron-userland/electron-packager/pull/449#issuecomment-240865736

Currently there's a bit of code in `index.js` that uses `get-package-info` to look for package.json files from which to infer default values for electron version, product name, etc. This technique of recursing up directories can produce unpredictable results depending on the directory structure of a given user.

As @malept said:

> Not that I want to drag this PR out any longer, but should we have a test for the case where no app-version is specified and (for some reason) there is no version in any of the package.json files found?

Looking for the *first* parent package.json file instead of *all* parent package.json files will enable us to reliably test that scenario. Writing up this issue because I came across a battle-tested package that does what we want: https://www.npmjs.com/package/find-root

**Comment by malept** [comment]
One of the things we should consider when we redo the `getMetadata` method (and related) is to move it to `common.js`, so it can be unit tested without needing to run the whole `packager` workflow.

**Comment by rahatarmanahmed** [comment]
Have there been unpredictable results? AFAIK the only issue I've heard of is the unhelpful error that is returned in that case where the version can't be found in any package.json files. That is something that can be addressed in https://github.com/rahatarmanahmed/get-package-info/issues/21

**Comment by malept** [comment]
@rahatarmanahmed there have been odd results on Windows, see #497.

**Comment by rahatarmanahmed** [comment]
@malept I've just added debug messages so we can use  `DEBUG=get-package-info` for more info on what files are being checked. It's a patch release so should be included in new installs.

I'm working on knocking this issue out by using `read-pkg-up` package instead of `resolve`.

**Comment by rahatarmanahmed** [comment]
Ok, published `1.0.0` of `get-package-info`, which now returns a better error that lets us know when props can't be found.

From the README:

> If all the properties cannot be found in parent package.json files, then getPackageInfo() will reject it's promise (or callback with err argument) with an Error. err.missingProps will have an array of the properties that it could not find, and err.result will contain all the props that were found.
>
> If any other error occurs(like I/O or runtime errors), getPackageInfo() will reject with that error itself.

I'll work on a PR using this new info later tonight.

**Comment by rahatarmanahmed** [comment]
@zeke I'm noticing that my changes back from https://github.com/electron-userland/electron-packager/pull/446/files removing the 2nd call to `getPackageInfo` didn't end up in master. Was it lost in the rebase or was there a reason to keep the 2nd call?

**Comment by zeke** [comment]
@rahatarmanahmed I recall merging your PR and then have to back out the changes. I forget the exact details but I think this was the reason:

![screen shot 2016-10-12 at 8 54 46 pm](https://cloud.githubusercontent.com/assets/2289/19336193/525a5440-90be-11e6-9b1e-41d95414ac61.png)

See https://github.com/electron-userland/electron-packager/pull/445#r73960207

**Comment by rahatarmanahmed** [comment]
@zeke I did add info to the response as to which prop/package it comes from, so that should have been correct.

**Comment by zeke** [comment]
@rahatarmanahmed not sure what happened then. Feel free to bring back changes as you see fit. If the build passes, I won't object. :)

**Comment by rahatarmanahmed** [comment]
Cool cool. Another question: seems like y'all never did get to writing a test for if both `--app-version` and `version` in package.json are not available. What is supposed to be the behavior for that case? I think currently it exits w/ an error. If it's not a required field, it should now be possible to continue the build even if it fails to find `version`. Is that something we want?

**Comment by malept** [comment]
There have been a couple of pull requests that make adding `electron` (FKA `electron-prebuilt`) not required to be set in `dependencies` or `devDependencies` (although no one's actually finished the PRs). I'm a bit conflicted about whether that is a good default. Offhand, it seems dangerous, given that basically defaults the dependency to `"electron": "*"`.
