### ISSUE TITLE
App version breaks cross platform builds 

### ISSUE THREAD

**Issue by tejohnso** [electron-userland/electron-packager#466]
Using circle ci

On 7.6.0 
`electron-packager . "app" --version=1.3.1 --platform=win32 --arch=ia32` works fine

On 7.7.0 it gives
"Wine is required to use the app-copyright, app-version, build-version, icon, and 
version-string parameters for Windows targets."

**Comment by malept** [comment]
Per the [release notes for 7.7.0](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#770---2016-08-20), `app-version` is now inferred from your app's `version` in `package.json`. In your CI, you now need to install Wine (unless you remove `version` from your `package.json` file).
