### ISSUE TITLE
Error: Failed to find Electron vv1.3.4

### ISSUE THREAD

**Issue by FelixRilling** [electron-userland/electron-packager#473]
Hello,

I'm using electron-packager to build my electron app.
I used The CLI to build the application until now, without issues.
Now I wanted to switch to the Programming API to make the build process easier to automate, however I'm having trouble with the version argument:
If I supply "v1.3.4" as version property (which I think is the correct formatting), It begings building,, but the throws:
```shell
Packaging app for platform win32 x64 using electron v1.3.4

Error: Failed to find Electron vv1.3.4 for win32-x64 at https://github.com/electron/electron/releases/download/vv1.3.4/electron-vv1.3.4-win32-x64.zip
    at Request.<anonymous> (C:\xampp\htdocs\bae\node_modules\nugget\index.js:170:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (C:\xampp\htdocs\bae\node_modules\request\request.js:954:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at TLSSocket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
```

I saw that the version was malformed to `vv1.3.4`, which of course is not the right value. Then I assumed that I would need to omit the "v" for the property, which resulted in this error:
```
 Fatal error: Unable to parse version string
```

Now I assume that the formatting "v1.x.x" was correct, however still failed. Can someone help me with that? 

The content of the js file:
```js

"use strict";

const packager = require("electron-packager");
const packageJson = require("./package.json");


const options = {
    "name": packageJson.name,
    "app-version": packageJson.version,
    "build-version": packageJson.version,
    "version": "v1.3.4",
    "dir": "./app",
    "out": "./releases/",
    "arch": packageJson.build.arch,
    "platform": packageJson.build.platforms,
    "asar": false,
};

console.log(options);

packager(options, function(err, appPaths) {
    if (err) {
        throw err;
    } else {
        console.log(`Built ${packageJson.name}`);
    }
});


````
I enabled the DEBUG envoriment var for electron-packager and electron-download, the output stays the same

I'm using
- Node 6.4
- npm 3.10.3
- electron-prebuilt 1.3.4
- electron-packager 7.6.0

On Windows 10 64bit

**Comment by malept** [comment]
Per [the API docs about the `version` option](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#version), you need to omit the `v`.

**Comment by FelixRilling** [comment]
Thanks for the answer, I looked into the docs and adjusted my code. However, I'm still getting an error using `"1.3.4"` as version property, however only when building for windows.

My code now is:

````js
"use strict";

const packager = require("electron-packager");
const packageJson = require("./package.json");


const options = {
    "name": packageJson.name,
    //"app-version": packageJson.version,
    //"build-version": packageJson.version,
    "version": "1.3.4",
    "dir": "./app",
    "out": "./releases/",
    "all": true,
    //"arch": packageJson.build.arch,
    //"platform": packageJson.build.platforms
};

console.log(options);

packager(options, function(err, appPaths) {
    if (err) {
        throw err;
    } else {
        console.log(`Built ${packageJson.name}`);
    }
});

```
Which now outputs;

```shell
Packaging app for platform linux ia32 using electron v1.3.4
Packaging app for platform win32 ia32 using electron v1.3.4

C:\my\path\to\app\build.js:23
        throw err;
        ^
 Fatal error: Unable to parse version string
```
Could you help me with this?

**Comment by malept** [comment]
You likely either do not have the version in package.json set at all, or it does not follow the semantic versioning format.

**Comment by FelixRilling** [comment]
Unless I'm missimg something, the version of electron is set correctly in the package.json(which is in the same dir as the build.js)

The dependency section looks like this:

```json

  "devDependencies": {
    "babel-preset-es2016": "^6.11.3",
    "electron-packager": "^7.6.0",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-concat": "^2.6.0",
    "gulp-connect": "^5.0.0",
    "gulp-cssbeautify": "^0.1.3",
    "gulp-filter": "^4.0.0",
    "gulp-html-prettify": "0.0.1",
    "gulp-pug": "^3.0.4",
    "gulp-sass": "^2.3.2",
    "gulp-task-loader": "^1.4.4",
    "main-bower-files": "^2.13.1"
  },
  "dependencies": {
    "electron": "1.3.4",
    "electron-prebuilt": "1.3.4"
  }
```

I'm very sorry If I'm just being stupid, but I can't seem to figure it out.

**Comment by malept** [comment]
What is the value of the `version` key of `package.json`? (The app version)

**Comment by FelixRilling** [comment]
Oh!
That was the problem, I had "v1.7.2" as version key, I didnt know that the electron builder takes this version too! after switching to "1.7.2" It worked. Thanks!
