### ISSUE TITLE
packager detects 'electron-prebuilt' instead of 'electron' in the package.json

### ISSUE THREAD

**Issue by imcaffrey** [electron-userland/electron-packager#476]
> Note As of version 1.3.1, this package is published to npm under two names: electron and electron-prebuilt. You can currently use either name, but electron is recommended, as the electron-prebuilt name is deprecated, and will only be published until the end of 2016.

But packager currently detects 'electron-prebuilt' not 'electron' in the package.json.

Installed packager with `npm install electron-packager -g`.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

**Comment by imcaffrey** [comment]
Hi. Thanks for replying.
I can only describe what happened but I cannot run any command at the moment coz I just don't have access to a computer. QAQ
I was running 'electron-packager ./ --platform=win32 --arch=x64' (something like that for Windows 10 packaging.... Not remembering quite clear.)
After running I get the message that cannot get the version of the electron in the package.json
So I dig into the package.json and found that the proj included electron instead of electron-prebuilt.
After I changed electron to electron-prebuilt, the package process goes as expected without errors.
So I guess the packager was checking electron-prebuilt but as said in the readme this name is deprecated.
Hope it helps.

**Comment by malept** [comment]
My suspicion is that you have an old version of Electron Packager installed, that's why I asked for more details.

**Comment by imcaffrey** [comment]
Hmm, the latest commit was 2176894a5be5da17a362bf3f20678641a78f4b69.... Indeed an old version.
Console ouput with debug on.
```
Unable to determine application name or Electron version. Please specify an application name and Electron version.
Cannot find module 'package.json' from '/home/ubuntu'(Properties not found yet: dependencies.electron-prebuilt,devDependencies.electron-prebuilt)
```
Upgrading to @7.7.0.... Then I got this again.
If changing `electron": "^1.3.4"` to `"electron-prebuilt": "^1.3.4"`, it works.
repo link: https://github.com/Moeditor/Moeditor
But it seems that other people who package this repo aren't facing this strange thing..... Wonder why,

**Comment by malept** [comment]
Strange. Please run `DEBUG=electron-packager electron-packager ./ --platform=win32 --arch=x64` and paste the output. The debug output should be useful in figuring out what your problem is.

**Comment by imcaffrey** [comment]
Still 
> Unable to determine application name or Electron version. Please specify an application name and Electron version.
Cannot find module 'package.json' from '/home/ubuntu'(Properties not found yet: dependencies.electron-prebuilt,devDependencies.electron-prebuilt)

I can share the c9.io environment if you offer an account.

**Comment by malept** [comment]
I find it highly odd that you're not getting any debug output. Could you please run the following commands, and paste the output of each?

* `npm list electron-packager`
* `npm list -g electron-packager`

**Comment by imcaffrey** [comment]
:+1:
Finally I got it from ` npm list -g electron-packager`.
Only from this I learned that my version in `-g` is wrong( it was 7.1.0).
:sob: Hope it will be easier to check the version in the future.(such as `-v` or `-V`)
Thank you for your help in so many days. I'm closing this issue now.
:tada:

**Comment by malept** [comment]
I've never liked the fact that `--version` doesn't give the electron-packager version. I think in a future major version I'm going to change it so it's more like other command line tools (I've reopened #154 as a result).
