### ISSUE TITLE
PowerPC Linux support?

### ISSUE THREAD

**Issue by ablakely** [electron-userland/electron-packager#478]
Is there any way to add PowerPC support?

Trying to build atom on my PowerPC linux machine but I'm getting an error saying that powerpc is unsupported.

**Comment by malept** [comment]
[Electron](https://github.com/electron/electron) does not currently support PowerPC architectures. If you would like Electron to support that architecture, you would be better off filing a feature request on [Electron's issue tracker](https://github.com/electron/electron/issues).

For future reference, Electron Packager only supports the target platforms and architectures that Electron supports.
