### ISSUE TITLE
Electron Packager using previously edited files not current ones

### ISSUE THREAD

**Issue by musician2000** [electron-userland/electron-packager#482]
Hi 

I have a really odd issue that has just started happening, I have python script that is called as a function as part of my app. All works great when I build the app, however I made a change recently to the python file to change the functionality. Now when I run a build by doing

` electron-packager . myapp --platform=darwin --arch=x64 --version=0.36.0 --overwrite --icon myapp.icns`

It seem to use the old version of the python file?? not the one I updated. If I do 

`npm start `

the app loads up and the python script is working as expected using the latest code. Is there a cached version that the electron-packager uses? How can I clear that?

Thanks for your help 

Regards
Chris

**Comment by malept** [comment]
My suggestion is to add the flags `--ignore=__pycache__ --ignore='\.py[co]$'`. My suspicion is that you're bundling an old Python bytecode file.

**Comment by musician2000** [comment]
Hi, thanks for the quick feedback, I just tried that with the extra flags in it, still same issue, works fine when I do npm start, but not using electron-packager and running the app?? really odd.

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by musician2000** [comment]
ok using the latest quick start and copying my file across I have a new issue. It now says when I load it up it cannot find the xxx.py file in the console. However when I run it using npm build it works fine. I am doing the following to load execute the python

`exec('python test1232.py -p ' + ClientName)`

have also tried

`exec('./python test1232.py -p ' + ClientName)`

I had a look inside the app that the electron-packager made, my .py file is in there. When calling a file that is in a built app using electron packager do I need to specify the path differently somehow? 

As I said this code  `exec('python test1232.py -p ' + ClientName)` works fine when doing nam start.

**Comment by malept** [comment]
Yeah, it sounds like you need to specify a more specific path to your script. The current working directory is different when you run `exec()` from `npm start` vs running a packaged Electron app.

**Comment by musician2000** [comment]
What should the path be to pick this up from the inside the app? in the un-packaged app its in the root folder same level as index.html, main.js etc.. is there a better way to call python scripts?

**Comment by malept** [comment]
My suggestion is to poke around the filesystem inside your Electron app, then use that path when you're using the packaged version. (That is pretty much what I would do to find the answer.)

**Comment by musician2000** [comment]
That would mean I need one version of code for electron packager with that path in and another for running it under npm start, that's not great right? But will try out what ur suggesting if that's the final answer.

**Comment by malept** [comment]
I'm not aware of another solution. Perhaps if you ask in the greater [Electron community](https://github.com/electron/electron#community),  you'll get a better answer.
