### ISSUE TITLE
Diferent browsers for diferent build. Has no sense.

### ISSUE THREAD

**Issue by raultrysw** [electron-userland/electron-packager#486]
This is not an issue, just a suggest :).
I wrote an aplication where I implemented the IndexedDB api on it, but i want to use that aplication in windows and in linux, but I got a problem with this....
If i open my windows version program and I use the program and IndexedDB begins to been not empty, but next I open the linux version program, I dont have the changes I made on the other program.
My question is... Not is better to keep the "same IndexedDB" for all versions? It is necessary I guess, and, If i am wrong, what other thing can i make? Would be correct to save the changes in a JSON file?

**Comment by malept** [comment]
Thanks for the suggestion, but this isn't an enhancement that Electron Packager can make. What you're generating is fundamentally two different applications that runs identical web application code.

If you want to synchronize data between all of the copies of your application, you're going to need to have a separate web app that runs on a server that does the syncing. This is how bookmark/extension synchronization works in web browsers like Firefox and Chrome.

**Comment by raultrysw** [comment]
Well, i wanted to know what about if I get available my program to export the data to a json file where the information is saved and the other binary retrive that information from this file?. Is it good or is it there something better?

**Comment by malept** [comment]
You could do that.

Since this isn't an Electron Packager specific question, I suggest asking it in the greater [Electron community](https://github.com/electron/electron#community), where you'll probably get a better answer.
