### ISSUE TITLE
Arch values with spaces causes Error

### ISSUE THREAD

**Issue by raybooysen** [electron-userland/electron-packager#487]
With this config:

```
options = {
  arch: 'x64, ia32'
}
```

The packager will error as `ias32` is not the same as `ia32`, there is a space after the comma.  Happy to commit a PR, to sanitise the options when they're passed in.  Is this something the project would accept?

**Comment by malept** [comment]
Out of curiosity, is there a reason why you're specifying it that way instead of as an Array?

Whether it would get accepted depends on a couple of things:

* what you mean by "sanitized"
* you write tests for your changes

**Comment by raybooysen** [comment]
I'm specifying it as comma separated because the documentation says it supported it.  

Sanitized -> I mean simple string trimming
Tests -> Definitely

**Comment by raybooysen** [comment]
Just to be complete, here is the snippet from the docs: 

```
Arbitrary combinations of individual architectures are also supported via a comma-delimited string or array of strings.
```

**Comment by malept** [comment]
I think I would rather have it split on the regular expression `/, */` than trim each value. But other than that, it sounds fine.

**Comment by raybooysen** [comment]
Sure, sounds sensible
