### ISSUE TITLE
output folder

### ISSUE THREAD

**Issue by gtk2k** [electron-userland/electron-packager#488]
--out=dist/win
this option result
dist/win/[appname]-[platform]-[arch]/*

but,I want result
dist/win/*

How to setting?

**Comment by malept** [comment]
The only way to do that currently is to move the files after the packager has finished running, for example in your `package.json`:

```json
{
  "scripts": {
    "win": "electron-packager --platform=win32 --arch=x64 --out=dist && mv dist/app-win32-x64 dist/win"
  }
}
```

(I'm not actually sure if that works when the host platform is Windows, I've forgotten how to move files on the command line there...)

**Comment by tomachinz** [comment]
thats not a bad idea. i will use this method.  mv dist/app-win32-x64 dist/win after. nice.

**Comment by tomachinz** [comment]
actually the option flag is called out not output so try:

 --out ./dist/electron

maybe you need the space? or ="" quote if you want to use equals? not sure.

**Comment by tomachinz** [comment]
I'm using both 'pkg' and 'electron-packager'. pkg uses --output and packager --out. kinda annoying. handy to know sorta.
