### ISSUE TITLE
log

### ISSUE THREAD

**Issue by AndyMoreland** [electron-userland/electron-packager#489]
**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Could you please fill out the information so we know what your issue is about?

**Comment by AndyMoreland** [comment]
Whoops. I have no idea how this got opened. Feel free to close it!
