### ISSUE TITLE
electron-packager error on win10

### ISSUE THREAD

**Issue by maciakt** [electron-userland/electron-packager#495]
**Please describe your issue:**
I issue this command "electron-packager . demoElectronApp --overwrite" for the electron-quick-start demo and I get the following error (also same error when i use node 6.6.0)

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

1664 verbose stack Error: EINVAL: invalid argument, read
1664 verbose stack     at C:\Users\MY_USER\AppData\Roaming\nvm\v4.5.0\node_modules\npm\lib\utils\gently-rm.js:286:7
1664 verbose stack     at C:\Users\MY_USER\AppData\Roaming\nvm\v4.5.0\node_modules\npm\node_modules\iferr\index.js:13:50
1664 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
1665 verbose cwd F:\temp\electron-packager\win32-x64\demoElectronApp-win32-x64\resources\app
1666 error Windows_NT 10.0.10586
1667 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prune" "--production"
1668 error node v4.5.0
1669 error npm  v3.10.6
1670 error code EINVAL
1671 error EINVAL: invalid argument, read
1672 error If you need help, you may report this error at:
1672 error     <https://github.com/npm/npm/issues>
1673 verbose exit [ 1, true ]
```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by maciakt** [comment]
this same electron-quick-start demo does get packaged successfully on a win7 machine

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output running `electron-packager` after you run `SET DEBUG=electron-packager` in your command line window. This will tell us a number of things about your system that will be helpful to people trying to debug your problem.

**Comment by malept** [comment]
This feels like a problem with `npm prune` rather than Electron Packager. Try running `npm prune --production` on  your app and see if you get the same error.

**Comment by maciakt** [comment]
@malept I ran npm prune --production on its own and did indeed get the same error related to " error EINVAL: invalid argument, read".  I will look into why npm prune is behaving badly.  Thank you for the insight and direction on why I can't get this working on my windows 10 machine.

**Comment by maciakt** [comment]
UPDATE: I re-installed node.js on my win10 machine, re-ran the packager and it now works like it did on the other win7 machine I was using.  I was using NVM before to manage a node 4.x and 6.x setup and that might be what was causing the problem.
