### ISSUE TITLE
Hangs on some Windows hosts due to getPackageInfo

### ISSUE THREAD

**Issue by ragFOEX** [electron-userland/electron-packager#497]
Using Node 4.5, electron-packager 8.0.0, electron-prebuilt 1.4.1, electron-winstaller 2.3.4

There is a problem building/packaging on some windows systems, but not on all windows systems. I found win7 and win10 and darwin working, but other win7 systems and a win8 system simply hang.

**Here is the console Output**

```
C:\PVBrowser>npm run pack-win

> PVBrowser@0.1.3 pack-win C:\PVBrowser
> electron-packager . PVBrowser --overwrite --platform=win32 --arch=ia32 --icon=assets/win/PVBrowserbrowserLogo.ico --pr
une=true --out=out --version-string.CompanyName='PVA' --version-string.FileDescription='PV Browser' --version-string.Pro
ductName='PV Browser'

  electron-packager Electron Packager 8.0.0 +0ms
  electron-packager Node v4.5.0 +0ms
  electron-packager Host Operating system: win32 (x64) +16ms
  electron-packager Packager Options: {"_":[".","PVBrowser","Browser'","Browser'"],"all":false,"deref-symlinks":true,"do
wnload":{"strictSSL":true},"overwrite":true,"prune":true,"platform":"win32","arch":"ia32","icon":"assets/win/PVBrowserbr
owserLogo.ico","out":"out","version-string":{"CompanyName":"'PVA'","FileDescription":"'PV","ProductName":"'PV"},"dir":".
","name":"PVBrowser","protocols":[]} +0ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: ia32 +0ms
^CBatchvorgang abbrechen (J/N)? j

```

Where you can see the ctrl+c above it hangs forever.

Any ideas how I can narrow it down? This happens on a customer system where I don't have direct access to.

**Comment by malept** [comment]
I would suggest setting DEBUG to `*` (`SET DEBUG=*`) which will turn on debug logging for all dependent modules which support it, and then analyzing the logs.

**Comment by ragFOEX** [comment]
Output with DEBUG=* is exactly the same as above.

After some trial and error I found the solution: instead of using electron-prebuilt in dependencies of my package.json I switched now to using electron and that worked as expected.

Seems that getPackageInfo gets into some kind of endless loop when looking for dependencies.electron before falling back to look for dependencies.electron-prebuilt. See https://github.com/electron-userland/electron-packager/blob/master/index.js#L32

My blocking point is resolved (or rather work arounded).

**Comment by malept** [comment]
@ragFOEX Is there something special about the location of the source code in the affected systems? Perhaps the drive is mounted in a non-standard way or something like that?

CC: @zeke

**Comment by ragFOEX** [comment]
They've tried 2 PC's. Both are standard Desktop systems, one Win7, the other Win8. Location was the C drive, so normal mounting. No blanks in directory names and so on (as can be seen in the debug output on top)

**Comment by malept** [comment]
Perhaps different permissions on the folder? Or for some reason is there a `package.json` in the C: root directory?

**Comment by malept** [comment]
Could you make sure `get-package-info` is at `0.1.1` and re-run `electron-packager` with `DEBUG=*`? @rahatarmanahmed released a new version of `get-package-info` with debug support.

**Comment by malept** [comment]
There is a new version of Electron Packager (8.2.0) that might have solved your problem. Please upgrade and follow the instructions in https://github.com/electron-userland/electron-packager/issues/497#issuecomment-253326507 if it still doesn't work.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
