### ISSUE TITLE
Build version should default to app version on Windows

### ISSUE THREAD

**Issue by kevinsawicki** [electron-userland/electron-packager#498]
**Please describe your issue:**

On Mac, both plist version keys are set to the `app-version` option when present, https://github.com/electron-userland/electron-packager/blob/9134f7be4678fdf0144bbb6b00f2da4756566415/mac.js#L109-L111 so you can just set the `app-version` option when you want the app version and build version to have the same value, but you can still override `build-version` when needed.

This is not happening on Windows, https://github.com/electron-userland/electron-packager/blob/9134f7be4678fdf0144bbb6b00f2da4756566415/win32.js#L36-L42

Perhaps on Windows, the `file-version` and `product-version` should both default to `app-version` initially but `file-version` should still be overrideable by `build-version` when it is present.

This would make the `app-version` defaulting to the `package.json` `version` value introduced in #449 be more consistent on Windows and Mac.

**Comment by malept** [comment]
I don't have a problem with adding this feature.
