### ISSUE TITLE
error with ubuntu 16.10 

### ISSUE THREAD

**Issue by ljoli** [electron-userland/electron-packager#507]
**Please describe your issue:**
I take electron-quick-start and put electron-packager command in package.json : 
{
	"name": "electron-quick-start",
		"version": "1.0.0",
		"description": "A minimal Electron application",
		"main": "main.js",
		"scripts": {
			"start": "electron .",
			"build": "electron-packager . --platefrom=linux --arch=x64 MyApp"
		},
		"repository": "https://github.com/electron/electron-quick-start",
		"keywords": [
			"Electron",
		"quick",
		"start",
		"tutorial",
		"demo"
		],
		"author": "GitHub",
		"license": "CC0-1.0",
		"devDependencies": {
			"electron": "^1.4.1",
			"electron-packager": "^8.1.0",
			"electron-prebuilt": "^0.25.2"
		}
}

And in my console I have the following error : 
/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/node_modules/generate-function/README.md' },
  ... 2035 more items ] undefined

npm ERR! Linux 4.8.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 build: `electron-packager . --platefrom=linux --arch=x64 MyApp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 build script 'electron-packager . --platefrom=linux --arch=x64 MyApp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . --platefrom=linux --arch=x64 MyApp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

Do you have any idea ?

**Comment by malept** [comment]
Looks like you misspelled "platform".

**Comment by englishextra** [comment]
yeah-yeah build": "electron-packager . --platefrom=linux --arch=x64 MyApp"

**Comment by ljoli** [comment]
Ok, I see my error !! 
BUT When I wrote correctly that does not work : 

npm ERR! Linux 4.8.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 build: `electron-packager . --platfrom=linux --arch=x64 MyApp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 build script 'electron-packager . --platfrom=linux --arch=x64 MyApp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . --platfrom=linux --arch=x64 MyApp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

**Comment by malept** [comment]
It's still misspelled. Switch around the r and the o.

**Comment by englishextra** [comment]
Gosh

**Comment by ljoli** [comment]
yes @malept :  thas is right. 
I copy the good line now, and I have an error too. 

ron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/electron-packager/linux-x64/MyApp-linux-x64/resources/app/node_modules/generate-object-property/index.js' },
  ... 1840 more items ] undefined

npm ERR! Linux 4.8.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 build: `electron-packager .  --platform=linux --arch=x64 MyApp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 build script 'electron-packager .  --platform=linux --arch=x64 MyApp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager .  --platform=linux --arch=x64 MyApp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

**Comment by malept** [comment]
@ljoli please run the electron-packager command outside of the NPM scripts feature and paste the console output. NPM scripts do not provide sufficient debug information.

**Comment by englishextra** [comment]
```
This module requires Node.js 4.0 or higher to run.
```
https://github.com/electron-userland/electron-packager

and the loig says

```
npm ERR! npm v3.10.8
```

**Comment by malept** [comment]
@englishextra I don't know what you're referring to, the npm output indicates that the user is running Node 6.8.1.

**Comment by ljoli** [comment]
yes @malept : you are right, my node js is above 4.0

**Comment by englishextra** [comment]
aha then it says Make sure you have the latest version of node.js and npm installed.

**Comment by ljoli** [comment]
OK so, I do the output command : 
electron-packager . --platform=linux --arch=x64 MyAp
And at the end : 
➜  electron-quick-start git:(master) ✗ tree -L 2  /tmp/electron-packager/linux-x64
/tmp/electron-packager/linux-x64
└── MyApp-linux-x64
    ├── blink_image_resources_200_percent.pak
    ├── content_resources_200_percent.pak
    ├── content_shell.pak
    ├── electron
    ├── icudtl.dat
    ├── libffmpeg.so
    ├── libnode.so
    ├── LICENSE
    ├── LICENSES.chromium.html
    ├── locales
    ├── natives_blob.bin
    ├── resources
    ├── snapshot_blob.bin
    ├── ui_resources_200_percent.pak
    ├── version
    └── views_resources_200_percent.pak

3 directories, 14 files

is it normal to find my application in  TMP directory ?
Why we can't use in script mode ?

**Comment by englishextra** [comment]
Can you provide the full line of your command in terminal

**Comment by malept** [comment]
@ljoli that is normal.

You can use npm scripts mode, it just won't tell you the error message.

Did you get an error message when you ran electron-packager manually?

**Comment by ljoli** [comment]
Yes , like i said before i use the command : 
electron-packager . --platform=linux --arch=x64 MyApp  

@malept : Ok, so it's better to debug with output command. 
No, I have no error with the above command above that is strange

**Comment by malept** [comment]
Please run `DEBUG=electron-packager electron-packager . --platform=linux --arch=x64 MyApp` and paste the output here, preferably in a preformatted block.

**Comment by englishextra** [comment]
Would be nice to see (the repo) what you are building to further investigate.

**Comment by ljoli** [comment]
I put all log in the attached file  output.txt
[output.txt](https://github.com/electron-userland/electron-packager/files/531294/output.txt)

**Comment by englishextra** [comment]
What is your command in terminal. The line, please

**Comment by malept** [comment]
Delete the folder MyApp-linux-x64 in your app directory and also /tmp/electron-packager and try again.

**Comment by englishextra** [comment]
malpert this wont help

**Comment by malept** [comment]
@englishextra the terminal command has been given multiple times.

**Comment by englishextra** [comment]
are you reffering to "electron-packager . --platefrom=linux --arch=x64 MyApp"

**Comment by malept** [comment]
@englishextra I believe it will help. There seems to be a recursion problem when copying the app.

**Comment by englishextra** [comment]
thanks I believe it's because neither you nor me have a clear view of what the source structure of the app is

**Comment by malept** [comment]
@englishextra see also line 4 of the debug output.

**Comment by englishextra** [comment]
This looks like a recreating on and on. weird.

**Comment by malept** [comment]
If deleting the output app bundle directory doesn't work, I suspect there is a bad symlink somewhere.

**Comment by ljoli** [comment]
OK , I delete all MyApp-linux-x64 . And now i have an trace like : 

➜  electron-quick-start git:(master) ✗ DEBUG=electron-packager electron-packager . --platform=linux --arch=x64 MyApp       

  electron-packager Electron Packager 8.1.0 +0ms
  electron-packager Node v6.8.1 +3ms
  electron-packager Host Operating system: linux (x64) +1ms
  electron-packager Packager Options: {"_":[".","MyApp"],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":false,"prune":true,"platform":"linux","arch":"x64","dir":".","name":"MyApp","protocols":[]} +0ms
  electron-packager Target Platforms: linux +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring app-version from version in package.json +7ms
  electron-packager Inferring target Electron version from electron dependency or devDependency in package.json +11ms
  electron-packager Application name: MyApp +1ms
  electron-packager Target Electron version: 1.4.3 +0ms
  electron-packager Ignored path regular expressions: +0ms [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ]
  electron-packager Downloading Electron with options {"strictSSL":true,"platform":"linux","arch":"x64","version":"1.4.3"} +3m
Packaging app for platform linux x64 using electron v1.4.3
  electron-packager Creating /tmp/electron-packager/linux-x64-template +311ms
  electron-packager Extracting /root/.electron/electron-v1.4.3-linux-x64.zip to /tmp/electron-packager/linux-x64-template +1ms
  electron-packager Initializing app in /tmp/electron-packager/linux-x64/MyApp-linux-x64 from /tmp/electron-packager/linux-x64-template template +2s
  electron-packager Ignored paths based on the out param: +2ms [ '/home/loni/Documents/test_electron/electron-quick-start/MyApp-darwin-ia32',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-darwin-x64',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-darwin-armv7l',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-linux-ia32',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-linux-x64',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-linux-armv7l',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-mas-ia32',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-mas-x64',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-mas-armv7l',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-win32-ia32',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-win32-x64',
  '/home/loni/Documents/test_electron/electron-quick-start/MyApp-win32-armv7l' ]
  electron-packager Running npm prune --production +1s
  electron-packager Renaming electron to MyApp in /tmp/electron-packager/linux-x64/MyApp-linux-x64 +3s
  electron-packager Moving /tmp/electron-packager/linux-x64/MyApp-linux-x64 to /home/loni/Documents/test_electron/electron-quick-start/MyApp-linux-x64 +1ms
Wrote new app to /home/loni/Documents/test_electron/electron-quick-start/MyApp-linux-x64
➜  electron-quick-start git:(master) ✗ ls
index.html  LICENSE.md  main.js  MyApp-linux-x64  node_modules  npm-debug.log  out  package.json  README.md  renderer.js

**Comment by malept** [comment]
Looks like it worked to me.

**Comment by englishextra** [comment]
Yeah, malept, a recursion is obvoius, you are right

**Comment by malept** [comment]
It seems like the problem got resolved, so I'm going to close this.
