### ISSUE TITLE
Cannot find module lokijs

### ISSUE THREAD

**Issue by XaBerr** [electron-userland/electron-packager#508]
I have tried adding the "lokijs" module to my project by importing it as all other modules in main.ts.
When I run my application with the command `electron build/` everything works fine however when I try to compile it with the command `electron-packager build/ lightRoom --out=releases/ --platform=win32 --arch=ia32 --asar.unpackDir=config.json --app-version=0.0.1 --overwrite --icon=src/img/icon.ico` and to run the application manually gives me an error. The error is not reported to console me but it happens when I try to open the executable by double clicking.
What can I do?

__main.ts__
```
//##################_IMPORT_#######################
const electron = require('electron')
const loki = require('lokijs')
const fs = require('fs')
import { app, BrowserWindow, ipcMain } from 'electron'
import { Config } from "../app/db-classes"
```
__package.json__
```
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "lokijs": "^1.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "electron-packager": "^7.3.0",
    "electron-prebuilt": "^1.2.7",
    "gulp": "^3.9.1",
    "gulp-if": "^2.0.1",
    "gulp-postcss": "^6.1.1",
    "gulp-pug": "^3.0.3",
    "gulp-typescript": "^2.13.6",
    "gulp-uglify": "^1.5.4",
    "lite-server": "^2.2.2",
    "lost": "^7.0.3",
    "npm-run-all": "^2.3.0",
    "postcss-autoreset": "^1.1.5",
    "postcss-cli": "^2.5.2",
    "postcss-cssnext": "^2.7.0",
    "postcss-nested": "^1.0.0",
    "postcss-simple-vars": "^3.0.0",
    "pug": "^2.0.0-beta3",
    "pug-cli": "^1.0.0-alpha6",
    "shx": "^0.1.2",
    "typescript": "^1.8.10",
    "typings": "^1.3.1",
    "yargs": "^4.8.1"
  }
```

__error__
![screenshot 2016-10-19 16 13 54](https://cloud.githubusercontent.com/assets/16030020/19522332/20c4f2d8-9617-11e6-92fa-edb5ef5e53ff.png)

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by XaBerr** [comment]
In electron-quick-start seems work...
I've done (win7 x64)
- comand stuff:
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install && npm start
npm install lokijs --save
npm install electron-packager --save-dev
```
- add to my main.js
`const loki = require('lokijs')`
- add to my package.json
`"compile": "electron-packager . e-q-s --out=releases/ --platform=win32 --arch=ia32"`
- run in cmd:
`npm run compile`
- I try app with double click and it work...
Now I don't know why quick-start works and my app not...

**Comment by XaBerr** [comment]
ah nailed!<br>
The problem occurs when I move my sources in a `build/electron` type path and `build/` I post a config like this the following just for run `electron build/`. Now the problem is: how I solve this?
```
{
  "name"    : "lightRoom",
  "version" : "0.1.0",
  "main"    : "./electron/main.js"
}
```

**Comment by malept** [comment]
Do you have one or two `package.json` files?

**Comment by XaBerr** [comment]
I had two, one real in my root folder, the second was a fake just to compile (in build/). Now I'm scerando to change the code so keep only the real!

**Comment by XaBerr** [comment]
Solved, just keep main package.json and change its main attribute!
