### ISSUE TITLE
Social logins stops workring after packaging | request origin from file.

### ISSUE THREAD

**Issue by bastiankhalil** [electron-userland/electron-packager#516]
Using electron-packager to package an Angular 2 application that contains Facebook and google logins authorization keeps the request origin as it is from file Not from browser.

Google login gives : 

```
400. That’s an error.
Error: invalid_request
Invalid parameter value for origin: Missing authority: file://
```

**What command line arguments i am passing?**

```
npm run electron-prepare && electron-packager electron-dist --platform=win32 --arch=x64 --version=1.4.3  --overwrite
```

**Comment by malept** [comment]
This isn't a problem specific to Electron Packager. Apache Cordova has a similar problem, see: https://stackoverflow.com/questions/16995314/google-sign-in-from-javascript-invalid-parameter-value-for-origin/23316449

You're more likely to get a better answer by either seeing how Cordova/Phonegap applications solve the problem, or by asking [the Electron community at large](https://github.com/electron/electron#community).
