### ISSUE TITLE
Uncaught Error (in package): Cannot find module

### ISSUE THREAD

**Issue by barbalex** [electron-userland/electron-packager#517]
**Please describe your issue:**
[This app](https://github.com/barbalex/kapla2) works fine in dev mode.
When I package it it opens, the window remains white and in the console this error appears:

    Uncaught Error: Cannot find module 'lodash'

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

this error is repeated hundreds of times:

https://gist.github.com/barbalex/88d03ac08246102370d152cba69bacdd

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

    cross-env NODE_ENV=production node -r babel-register -r babel-polyfill package.js

This is the package.js file: https://github.com/barbalex/kapla2/blob/master/package.js

I am using https://github.com/chentsulin/electron-react-boilerplate.git as boilerplate for my app.
The error occurs on Windows 10 as well as maxOs Sierra. On Windows a different module was missed.

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

Sorry, I have no idea how to reproduce this error that way.

Maybe this helps:

Clone [my repo](https://github.com/barbalex/kapla2), npm i, npm run dev > see how it should work
npm package, start app > see error in console

**Comment by malept** [comment]
Could you try the changes to `package.js` in https://github.com/chentsulin/electron-react-boilerplate/pull/371/files, and also try setting [`derefSymlinks`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#derefsymlinks) to `false`?

**Comment by barbalex** [comment]
I tried applying these changes. With derefSymlinks false or true. But the error remains :-(

Interestingly I get a completely different output when using `DEBUG=electron-packager` on my Windows machine than on macOS: https://gist.github.com/barbalex/43100d47b5438549a3754006e86f09e5

**Comment by barbalex** [comment]
Nope: The output in the console when using `DEBUG=electron-packager` is similar on macOS and Windows.

What is different is the output when not using `DEBUG=electron-packager`:

Windows: 

    PS C:\Users\alex\kapla2> npm run package

    > Kapla@1.0.0 package C:\Users\alex\kapla2
    > cross-env NODE_ENV=production node -r babel-register -r babel-polyfill package.js

    start pack...
    Packaging app for platform win32 x64 using electron v1.4.4
    win32-x64 finished!

macOS:

https://gist.github.com/barbalex/88d03ac08246102370d152cba69bacdd
repeated probably a few hundred times.

But the error is the same on Windows and macOS.

**Comment by malept** [comment]
This is why you have the lodash problem: https://gist.github.com/barbalex/43100d47b5438549a3754006e86f09e5#file-log-L30

It's a problem with your boilerplate. Try removing this line: https://github.com/barbalex/kapla2/blob/540e82e97ddbcf801cb37a72d0e7498536b85a0d/package.js#L58

**Comment by malept** [comment]
> https://gist.github.com/barbalex/88d03ac08246102370d152cba69bacdd
> repeated probably a few hundred times.

What console output immediately precedes the start of that?

**Comment by barbalex** [comment]
> What console output immediately precedes the start of that?

this here: https://gist.github.com/barbalex/51164bf76250a6283d3dd5c9a2b4f624

**Comment by malept** [comment]
> this here: https://gist.github.com/barbalex/51164bf76250a6283d3dd5c9a2b4f624

Is that with `DEBUG=electron-packager` set?

Unrelated: why are you running it as root?

**Comment by barbalex** [comment]
You seem to have hit the mark: After removing `.concat(depsExternal)` my app starts without missing lodash. And it shows the first screen.

But I get this new error:

    jquery.js:3846jQuery.Deferred exception: Cannot read property 'componentWillUpdate' of null TypeError: Cannot read property 'componentWillUpdate' of null
        at _render (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:48573:60)
        at emit (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:44082:45)
        at _$init (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:47217:19)
        at callDownwards (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:46627:26)
        at callDownwards (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:46630:28)
        at callDownwards (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:46630:28)
        at callDownwards (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:46630:28)
        at _create (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:45183:14)
        at init (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:44539:9)
        at mightThrow (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:31048:30)
        at process (file:///C:/Users/alex/kapla2/release/win32-x64/Kapla-win32-x64/resources/app/dist/bundle.js:31116:13) undefined
    goldenlayout.js:582Uncaught Error: Can't create config, layout not yet initialisedtoConfig @ goldenlayout.js:582GeschaefteLayout._this.saveGeschaefteState @ (index):76(anonymous function) @ (index):57emit @ goldenlayout.js:254_propagateEventToLayoutManager @ goldenlayout.js:3347(anonymous function) @ goldenlayout.js:79
    goldenlayout.js:4745Uncaught TypeError: Cannot read property 'componentWillUpdate' of null_render @ goldenlayout.js:4745emit @ goldenlayout.js:254_$init @ goldenlayout.js:3389callDownwards @ goldenlayout.js:2799callDownwards @ goldenlayout.js:2802callDownwards @ goldenlayout.js:2802callDownwards @ goldenlayout.js:2802_create @ goldenlayout.js:1355init @ goldenlayout.js:711mightThrow @ jquery.js:3570process @ jquery.js:3638

And after that no new components show any more.

**Comment by barbalex** [comment]
> Is that with `DEBUG=electron-packager` set?

No. With it, the output looks the same as this here from the Windows machine: https://gist.github.com/barbalex/43100d47b5438549a3754006e86f09e5

**Comment by malept** [comment]
> But I get this new error:
> [...] `Error: Can't create config, layout not yet initialisedtoConfig` [...]

Without knowing more about your app (I can't debug it right now) you should probably look into seeing where the config is being created and whether you have permissions to write it there.

**Comment by malept** [comment]
I have no idea why you would get `ENAMETOOLONG` only when `DEBUG` is not set.

**Comment by barbalex** [comment]
> Unrelated: why are you running it as root?

Hm. How do you see that? On Windows my Account has administrator rights. Could that be the reason?

**Comment by barbalex** [comment]
Sorry for being a bit of a noob: Having removed `.concat(depsExternal)`, could it be that some dependencies like goldenlayout have not been correctly built?

**Comment by barbalex** [comment]
...or are these only the dependencies that I've set as external in `webpack.config.base.js` ?

**Comment by malept** [comment]
> > Unrelated: why are you running it as root?
>
> Hm. How do you see that?

https://gist.github.com/barbalex/51164bf76250a6283d3dd5c9a2b4f624#file-log_on_macos-L1

>  On Windows my Account has administrator rights. Could that be the reason?

Probably not. It was just just something odd that I saw. You shouldn't need to run as root unless there's a very specific reason you're doing so.

> Having removed `.concat(depsExternal)`, could it be that some dependencies like goldenlayout have not been correctly built?
> ...or are these only the dependencies that I've set as external in webpack.config.base.js ?

The latter.

**Comment by barbalex** [comment]
Oh, the sudo for packaging: That is because otherwise I get a `permission denied` error on my mac.

Well, I guess I will try to find the remaining problem in my apps code now. I am just a little hesitant, because this error does not appear in dev mode.

THANKS A LOT FOR GREAT HELP!!!

**Comment by barbalex** [comment]
Oh, I forgot: You mentioned it was a problem of the boilerplate. And the lines I removed to solve the problem do come from it. Shall I create an issue at https://github.com/chentsulin/electron-react-boilerplate?

**Comment by malept** [comment]
> Oh, I forgot: You mentioned it was a problem of the boilerplate. And the lines I removed to solve the problem do come from it. Shall I create an issue at https://github.com/chentsulin/electron-react-boilerplate?

Sure. Fair warning, they may tell you you're doing something wrong. I'm not very familiar with how webpack/react works, I just know how to stop the error you were seeing 😄
