### ISSUE TITLE
Allow yarn to be used instead of npm

### ISSUE THREAD

**Issue by soredake** [electron-userland/electron-packager#518]
Lines like this preventing normal use with yarn:
`child.exec('npm prune --production', {cwd: appPath}, cb)`
`exec('npm install --no-bin-links'`

**Comment by malept** [comment]
That's preventing yarn completely replacing npm, sure. In the meantime you should be able to symlink `npm` to `yarn` and in theory it should "just work".

**Comment by soredake** [comment]
yarn prune has no --production option
yarn install has no --no-bin-links option, so just symlink is not the solution (while sed -i /npm --option/yarn --option, but it is not so convenient)

**Comment by malept** [comment]
Then it sounds like yarn support specifically is blocked on `prune --production` being added. That is an important part of how we package Electron apps.

**Comment by soredake** [comment]
https://github.com/yarnpkg/yarn/issues/696#issuecomment-253031239

**Comment by malept** [comment]
The above yarn issue relates to `prune`. This one relates to `--no-bin-links`: https://github.com/yarnpkg/yarn/issues/929

Those two issues block proper yarn support. However, I have spec'd out how to implement generic NPM-compatible package manager support in https://github.com/electron-userland/electron-packager/issues/515#issuecomment-257167905, and I am happy to review pull requests that implement this (and, obviously, follow the [contributing guidelines](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#filing-pull-requests)).

**Comment by soredake** [comment]
https://github.com/yarnpkg/yarn/pull/1651

**Comment by soredake** [comment]
https://github.com/yarnpkg/yarn/issues/696#issuecomment-258418656

**Comment by jrobeson** [comment]
`--no-bin-links` did finally happen, but still no resolution for the other issue.
