### ISSUE TITLE
Windows/win32 targets on non-Windows hosts do not support wine64

### ISSUE THREAD

**Issue by amelkikh** [electron-userland/electron-packager#519]
**Please describe your issue:**
Trying to pack for Win 64-bit Electron Api Demos under Linux Mint Rose (64-bit).
I installed from source Wine-1.9.22 --enable-win64
But, wine was configured with option `--enable-win64` installs bin `wine64` not `wine`. 

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Packaging app for platform win32 x64 using electron v1.4.4
Could not find "wine" on your system.

Wine is required to use the app-copyright, app-version, build-version, icon, and 
win32metadata parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "pack-win64"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ElectronAPIDemos@1.2.0 pack-win64: `electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ElectronAPIDemos@1.2.0 pack-win64 script 'electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ElectronAPIDemos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ElectronAPIDemos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ElectronAPIDemos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-api-demos/npm-debug.log
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

`npm run pack-win64`

```
"pack-win64": "electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'",
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

---

**Comment by malept** [comment]
If you symlink `wine64` to `wine`, does it work?

**Comment by amelkikh** [comment]
No,

`developer@work-PC /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-api-demos $ npm run pack-win64

> ElectronAPIDemos@1.2.0 pack-win64 /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-api-demos
> electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'

Packaging app for platform win32 x64 using electron v1.4.4
rcedit.exe failed with exit code 1. wine: '/home/developer/.wine' is a 32-bit installation, it cannot support 64-bit applications.

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "pack-win64"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ElectronAPIDemos@1.2.0 pack-win64: `electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ElectronAPIDemos@1.2.0 pack-win64 script 'electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ElectronAPIDemos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ElectronAPIDemos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ElectronAPIDemos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-api-demos/npm-debug.log`

**Comment by malept** [comment]
Try removing (or moving, if you have apps/data in there that you need) the `$HOME/.wine` directory and try again.

The hardcoded `wine` call isn't in Electron Packager but rather in [node-rcedit](https://github.com/electron/node-rcedit). I suggest filing a bug there if you want to be able to use the `wine64` executable without symlinking.

**Comment by amelkikh** [comment]
Thanks

**Comment by amelkikh** [comment]
I did as you suggested, but the problem persists
`mv ~/.wine ~/.wine64`

```
developer@work-PC /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-api-demos $ npm run pack-win64

> ElectronAPIDemos@1.2.0 pack-win64 /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-api-demos
> electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'

Packaging app for platform win32 x64 using electron v1.4.4
rcedit.exe failed with exit code 1. wine: WINEARCH set to win32 but '/home/developer/.wine' is a 64-bit installation.

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "pack-win64"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ElectronAPIDemos@1.2.0 pack-win64: `electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ElectronAPIDemos@1.2.0 pack-win64 script 'electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ElectronAPIDemos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . ElectronAPIDemos-x64 --asar --asar-unpack=protocol-link.html --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon/win/app.ico --prune=true --out=out --version-string.CompanyName='GitHub, Inc.' --version-string.FileDescription='Electron API Demos' --version-string.ProductName='Electron API Demos'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ElectronAPIDemos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ElectronAPIDemos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-api-demos/npm-debug.log
```

**Comment by malept** [comment]
Good to know that that is not a valid workaround. The options at this point are:

* Wait for node-rcedit to be changed
* Install 32-bit wine

**Comment by malept** [comment]
Since this is a node-rcedit bug that I [just filed there](https://github.com/electron/node-rcedit/issues/22), I'm closing this bug.
