### ISSUE TITLE
is it possible to pack into a SINGLE .exe file?

### ISSUE THREAD

**Issue by abioneperhobby** [electron-userland/electron-packager#521]
Hi,

thanks for this tool.

under windows i'm able to pack electron app to a folder with .exe file,

but i'm not able to understand if is it possible to pack everything into a SINGLE .exe file.

i read

http://electron.atom.io/docs/tutorial/application-distribution/ but with asar package i'm able to pack the application, not electron.

my need is to pack everything inside a single exe file to make distribution easier.

is this possible?

thanks.

**Comment by malept** [comment]
This is not currently possible. I gave a more detailed answer in #243.

**Comment by abicorios** [comment]
Yes, it is possible by `electron-forge make`
See  https://github.com/electron-userland/electron-forge
By default in Windows the single exe is created by squirrel. After running it is extracted in C:\Users\user\AppData\Local\your_new_app, and rewrite it in each run. But user see alone executable, and almost all software work in a similar way.
