### ISSUE TITLE
ARM not correctly detected

### ISSUE THREAD

**Issue by Regaddi** [electron-userland/electron-packager#523]
**Please describe your issue:**

Hi,
when trying to build [Atom](https://atom.io) on a armv7l machine (Nexus 5 with MaruOS 0.3, Debian Jessie, Qualcomm Snapdragon S800) electron-packager exits with the console output below.

I think this is due to the way, electron-packager checks für armv7l architecture.

In [common.js](https://github.com/electron-userland/electron-packager/blob/master/common.js#L154) you're directly checking for `armv7l` which is not the guaranteed output from nodes `process.arch` command.
A better check might include `process.config.variables.arm_version`, which should return `'7'` in case of `armv7l`.

I'd suggest to extend the check for `armv7l` to:

```
arch === 'armv7l' || arch == 'arm' && process.config.variables.arm_version === '7'
```

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Running electron-packager on /home/maru/atom/out/app with app name "atom"
Error: Unsupported arch=arm; must be one of: ia32, x64, armv7l
    at Object.validateListFromOptions (/home/maru/atom/script/node_modules/electron-packager/targets.js:29:16)
    at packager (/home/maru/atom/script/node_modules/electron-packager/index.js:234:23)
    at Promise (/home/maru/atom/script/lib/package-application.js:141:5)
    at runPackager (/home/maru/atom/script/lib/package-application.js:140:10)
    at module.exports (/home/maru/atom/script/lib/package-application.js:17:10)
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
  {
    'app-bundle-id': 'com.github.atom',
    'app-copyright': `Copyright © 2014-${(new Date()).getFullYear()} GitHub, Inc. All rights reserved.`,
    'app-version': CONFIG.appMetadata.version,
    'arch': (() => {
      if (process.platform === 'linux') {
        return process.arch
      } else {
        return process.platform === 'win32' ? 'ia32' : 'x64'
      }})(),
    'asar': {unpack: buildAsarUnpackGlobExpression()},
    'build-version': CONFIG.appMetadata.version,
    'download': {cache: CONFIG.electronDownloadPath},
    'dir': CONFIG.intermediateAppPath,
    'extend-info': path.join(CONFIG.repositoryRootPath, 'resources', 'mac', 'atom-Info.plist'),
    'helper-bundle-id': 'com.github.atom.helper',
    'icon': getIcon(),
    'name': appName,
    'out': CONFIG.buildOutputPath,
    'overwrite': true,
    'platform': process.platform,
    'version': CONFIG.appMetadata.electronVersion,
    'version-string': {
      'CompanyName': 'GitHub, Inc.',
      'FileDescription': 'Atom',
      'ProductName': 'Atom'
    }
  }
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
I appreciate the suggestion, however the `arch` param corresponds to a subset of Node's arch identifiers used in their [binary downloads](https://nodejs.org/en/download/current/), rather than the possible values of `process.arch`. I think that the Atom packaging script should be fixed to handle ARM host builds better. If we take the change that you're suggesting, it's going to get pretty ugly in Electron Packager once Electron supports ARMv8. (This was why I was against allowing `arm` as a valid arch in the first place.)

**Comment by Regaddi** [comment]
Not sure, if this is the right way to solve this issue.
You're effectively saying, that you want to outsource all the ARM version checks to every app, that might want to use `electron-packager`.
This leads imho to a forced redundancy.
Nevertheless, I try to get this fixed at atom itself.

**Comment by malept** [comment]
I'm saying that if this is how `process.arch` works, then it's not the best way to set the `arch` parameter for Electron Packager. Your suggestion only works when both the host and target arch is ARMv7, and that makes documenting how the parameter works much more complex. _(I would also be concerned about figuring out a way to write a test for this case.)_

**Comment by Regaddi** [comment]
Okay, got the point. In my specific case I am building for my own system from source.
