### ISSUE TITLE
Snaps support?

### ISSUE THREAD

**Issue by peteruithoven** [electron-userland/electron-packager#525]
The new Linux packaging format Snaps should make it easier to distribute apps across multiple Linux distributions. It also supports release channels, which could make updating a breeze for users. 
I'm loving the Electron apps I'm using, but each one seems to struggle with updates. Some have ppa repositories, but that's not supported by all linux distributions and let's be honest, not user friendly at all. 

I'm curious how the people behind Electron feel about this.

More info: 
http://snapcraft.io/
https://www.youtube.com/watch?v=j40tNL3t4gw

**Comment by develar** [comment]
Planned and will be supported this year. Please see https://github.com/electron-userland/electron-builder/issues/509 

AppImage is already supported and recommended instead of `deb`.

In the electron-builder, not electron-packager because of #33.

JFYI — if understand correctly, it is possible to build Snaps only on Linux.

**Comment by peteruithoven** [comment]
Thanks for pointing me into the right direction, I searched in this and the Electron repo on snap, snaps and snappy but there was no pointer to that one. I guess now there is.

**Comment by develar** [comment]
@peteruithoven If you somehow related to Snaps dev team, it will be cool to provide some info about multi-platform status — is it possible to build Snaps not only on Linux (I am aware of Docker and electron-builder even provides Docker images (https://github.com/electron-userland/electron-builder/wiki/Docker).

**Comment by peteruithoven** [comment]
I'm afraid I'm just a user, but I'll do a little digging.

**Comment by fcole90** [comment]
I think it should be possible, please check [docker/snapcraft](https://hub.docker.com/r/didrocks/snapcraft/) and tell me if it's what you were looking for.

**Comment by fcole90** [comment]
This [link](https://github.com/chihchun/snapcraft-docker) should provide more infromation.

**Comment by peteruithoven** [comment]
@fcole90 Thanks!

**Comment by DrSensor** [comment]
Any progress for this?

**Comment by malept** [comment]
Snaps are not in the scope of Electron Packager. However, the [`electron-installer-snap`](https://github.com/electron-userland/electron-installer-snap) module uses the output of Electron Packager to create snaps. Alternatively, [Electron Forge](https://github.com/electron-userland/electron-forge) (as of v5.0.0) uses both Electron Packager and `electron-installer-snap` internally to build snaps, and also has support to publish them to the Snap Store.
