### ISSUE TITLE
Gulp example with pipe to zip final build

### ISSUE THREAD

**Issue by gino8080** [electron-userland/electron-packager#526]
Hello could please someone expose an example of a gulp task that permit the pipe flow

something like: (sorry i'm a gulp newbie)

```
gulp.task('build', function() {

    var options = { ...    }
    packager(options, function done_callback(err, appPaths) {
      console.error(err)
     console.log(appPaths)
    })

})
.pipe("zip file.")
.pipe("send messge...")

```
thank you!

**Comment by malept** [comment]
You can probably get some inspiration from https://github.com/azu/electron-zip-packager, but you're better off asking this question in the greater [Electron community](https://github.com/electron/electron#community).
