### ISSUE TITLE
Problems installing wine via homebrew on macOS Sierra 10.12

### ISSUE THREAD

**Issue by dgabrielli76** [electron-userland/electron-packager#528]
**Please describe your issue:**
My aim is to build my app for windows platform. I am on Mac OS (Sierra, OS X 10.12 to be precise).
Referring to the [documentation](https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms) I try to install `wine` on my mac but the install says that they do not provide support for this pre-release version.

Is the documentation to install `wine` deprecated or am I making something wrong?

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Could not find "wine" on your system.

Wine is required to use the app-copyright, app-version, build-version, icon, and 
win32metadata parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.
```

**Comment by malept** [comment]
> but the install says that they do not provide support for this pre-release version.

Which install are you referring to? How are you installing wine, and what is the precise console output when you do so?

**Comment by dgabrielli76** [comment]
The install in question is the wine install. 
I install wine using homebrew with this command:
```
brew install wine
```
And this command gives this console output: 
```
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```
I understand that the problem is coming from wine and not from you, but I don't know how to build my app for windows without this installation...
Thanks for your help!

**Comment by malept** [comment]
Looks like you need to upgrade Homebrew: https://github.com/Homebrew/homebrew-core/issues/6359

**Comment by dgabrielli76** [comment]
Thanks for your help it works!
Sorry for this issue that is not really linked to you...
Thank you again!
