### ISSUE TITLE
Unable to set Icon from web for --win

### ISSUE THREAD

**Issue by loreberti89** [electron-userland/electron-packager#529]
I have `"electron-packager": "^8.2.0"` in my package.json and I tried to make a package of electron app with these command:

`electron-packager ./ app --win --icon=https://www.google.it/images/branding/product/ico/googleg_lodp.ico`

and

`electron-packager ./ app --win --icon="https://www.google.it/images/branding/product/ico/googleg_lodp.ico"`
but the icon is not setted and it set default atom icon.

**Comment by malept** [comment]
The icon path must be a local path. In your build process, you should download the icon locally first.

I have clarified this in the documentation in https://github.com/electron-userland/electron-packager/commit/d6130917c352a63caeadb00e73a4da9ec7b5ed2d.
