### ISSUE TITLE
Photon Unable to find valid app

### ISSUE THREAD

**Issue by ShahNewazKhan** [electron-userland/electron-packager#531]
**Please describe your issue:**

I am having issues with a Photon app .exe file created by electron-packager, when I run the the .exe file I get the "Unable to find valid app" error message. 

I believe the issue is that the Photon filestructure:

photon/
├── sass/
├── fonts/
├── dist/
│    ├── css/
│    ├── fonts/
│    └── template-app/
└── docs/
 |___ package.json

The package.json in / points to the /dist/template-app package.json and runs dist/template-app/app.js.

Is there a different file-structure I need to implement for electron-packager to work? I do not get any errors and the win-32 files are compiled properly.

Thanks in advance for your help!

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by ShahNewazKhan** [comment]
Hi malept,

The project I used was the [ photon](https://github.com/connors/photon/archive/v0.1.2-alpha.zip) source code package with some changes to the /dist/app.js file.

Here is the console output for my cmd arguments `electron-packager . --platform=win32` :

PS C:\Users\i841069\Desktop\projects\electron\blinkr> electron-packager . --platform=win32 --asar=false --overwrite
  electron-packager Electron Packager 8.3.0 +0ms
  electron-packager Node v4.4.7 +4ms
  electron-packager Host Operating system: win32 (x64) +3ms
  electron-packager Packager Options: {"_":["."],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":true,"pru
ne":true,"platform":"win32","asar":"false","dir":".","protocols":[]} +1ms
  electron-packager Target Platforms: win32 +4ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Inferring application name from productName in C:\Users\i841069\Desktop\projects\electron\blinkr\package.json +206
ms
  electron-packager Inferring app-version from version in C:\Users\i841069\Desktop\projects\electron\blinkr\package.json +6ms
  electron-packager Inferring target Electron version from electron-prebuilt in C:\Users\i841069\Desktop\projects\electron\blinkr\pack
age.json +22ms
  electron-packager Application name: Blinkr +10ms
  electron-packager Target Electron version: 0.33.9 +4ms
  electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ] +5ms
  electron-packager Downloading Electron with options {"strictSSL":true,"platform":"win32","arch":"x64","version":"0.33.9"} +1s
Packaging app for platform win32 x64 using electron v0.33.9
  electron-packager Creating C:\Users\i841069\AppData\Local\Temp\electron-packager\win32-x64-template +616ms
  electron-packager Extracting C:\Users\i841069\.electron\electron-v0.33.9-win32-x64.zip to C:\Users\i841069\AppData\Local\Temp\electr
on-packager\win32-x64-template +12ms
  electron-packager Initializing app in C:\Users\i841069\AppData\Local\Temp\electron-packager\win32-x64\Blinkr-win32-x64 from C:\Users
\i841069\AppData\Local\Temp\electron-packager\win32-x64-template template +2s
asar parameter set to an invalid value (false), ignoring and disabling asar
  electron-packager Ignored paths based on the out param: [ 'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-darwin-ia
32',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-darwin-x64',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-darwin-armv7l',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-linux-ia32',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-linux-x64',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-linux-armv7l',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-mas-ia32',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-mas-x64',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-mas-armv7l',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-win32-ia32',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-win32-x64',
  'C:\\Users\\i841069\\Desktop\\projects\\electron\\blinkr\\Blinkr-win32-armv7l' ] +14ms
  electron-packager Running npm prune --production +31s
  electron-packager Renaming electron.exe to Blinkr.exe in C:\Users\i841069\AppData\Local\Temp\electron-packager\win32-x64\Blinkr-win3
2-x64 +10s
  electron-packager Running rcedit with the options {"version-string":{},"file-version":"0.1.2","product-version":"0.1.2"} +35ms
  electron-packager Moving C:\Users\i841069\AppData\Local\Temp\electron-packager\win32-x64\Blinkr-win32-x64 to C:\Users\i841069\Deskto
p\projects\electron\blinkr\Blinkr-win32-x64 +604ms
Wrote new app to C:\Users\i841069\Desktop\projects\electron\blinkr\Blinkr-win32-x64`

**Comment by malept** [comment]
Ah yes, you need to set the `"main"` key in `package.json`. I suggest taking a look at http://electron.atom.io/docs/tutorial/quick-start/#main-process.

**Comment by ShahNewazKhan** [comment]
Thanks for the insight, do I need to set the main in the package.json in the / of the photon app or in the /dist/tempalte-app folder?

**Comment by malept** [comment]
It's a problem that there are two different package.json files. We recommend only having one if you want to use Electron Packager. I recommend doing some experimentation in order to merge the two and have your app build properly. I'm not familiar with the photon project so I'm not comfortable saying how difficult it would be to modify it.
