### ISSUE TITLE
Fixed port number?

### ISSUE THREAD

**Issue by mertyildiran** [electron-userland/electron-packager#532]
Each time my meteor app starting with a different port number. How can I configure `electron-packager` to fixed port number like [http://localhost:3000/](http://localhost:3000/)

**Comment by malept** [comment]
This seems like a meteor question rather than an Electron Packager question.

**Comment by mertyildiran** [comment]
@malept No, only the package I have created with `electron-packager` has this issue. Actually I realised that it's running on [http://localhost:11237](http://localhost:11237) but I want to run my app on [http://localhost:3000/](http://localhost:3000/). How can I change the port to 3000.

**Comment by mertyildiran** [comment]
@malept Could it be related with [electrify](https://github.com/arboleya/electrify) because I'm generating electron app from meteor using electrify.

**Comment by malept** [comment]
Yes, it sounds like an issue for the electrify repository. I don't see how Electron Packager has anything to do with setting a port number.
