### ISSUE TITLE
Error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by delebash** [electron-userland/electron-packager#536]
Windows 7x64
Node 6.1.0
Npm 3.10.9
electron-packager v8.3.0

I only get the above error when running a packaged app and only with electron-prebuilt versions below 1.22

I know how to debug a non-packaged app using phpstorm, but I am not sure how to debug a packaged app.

I am not sure of the exact relationship between electron and electron-prebuilt but as I understand it electron is a stand-in replacement for electron-prebuilt and looking at the release dates both electron and electron-prebuilt releases 1.22 happened on the same day and in the release notes chrome was updated to  51.0.2704.84. This might the case with electron-prebuilt as well and may be the source of the problem

Any help in tracking this down would be appreciated.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. **Please include the stack trace of the error**.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by delebash** [comment]
**package.json script args**

> "build-win": "electron-packager . musicwrapper --debug=electron-packager --platform=win32 --arch=ia32 --version=1.2.2 --overwrite --out ./build/win",

If --version=1.0.2 with corresponding electron-prebuilt it works.  Using the above --version=1.2.2 it does not.

 Compile command `npm run-script build-win`

I do not get the above error when running it in debug mode. the app runs as expected. 

**Here is the console output**

> λ 2016-12-03T18:24:14.388Z - info: Logger initialized. Writing info/warnings/errors to stdout. Writing all logs to "C:\Users\Daniel\AppData\Roaming\google-music-electron\verbose.log"
> 2016-12-03T18:24:14.426Z - info: App ready. Opening Google Music window nodeIntegration=false, webSecurity=true, height=698, icon=F:\Development\GitHub\delebash\Electron\google-music-electron-master\build\win\musicwrapper-win32-ia32\resources\app\lib\assets/icon-32.png, preload=F:\Development\GitHub\delebash\Electron\google-music-electron-master\build\win\musicwrapper-win32-ia32\resources\app\lib/browser.js, skip-taskbar=undefined, width=1024, x=109, y=null, http_parser=2.7.0, node=6.1.0, v8=5.1.281.59, uv=1.9.0, zlib=1.2.8, ares=1.10.1-DEV, modules=48, openssl=1.0.2h, electron=1.2.2, atom-shell=1.2.2, chrome=51.0.2704.84, version=2.13.0

Link to project
https://github.com/delebash/tunein-music-wrapper.git

**Comment by malept** [comment]
A few additional questions:

* You must be getting the error as a popup, since it's not in your console output. Is this correct? If so, can you copy/paste all of the stack trace from it (or screenshot the popup, but that's not ideal).
* Can you pinpoint exactly which version of Electron (by which I mean `electron-prebuilt`) where it starts to fail for you? For example, does 1.2.1 work?

**Comment by delebash** [comment]
electron-prebuilt releases jump from 1.0.2 to 1.2.2 nothing in-beween
https://github.com/electron-userland/electron-prebuilt/releases?after=v1.2.3

![image](https://cloud.githubusercontent.com/assets/2220160/20862025/7462cb08-b96d-11e6-9148-8441c6d0701d.png)
 
I see if I can get a stack trace.

Thanks

**Comment by malept** [comment]
A few things to help you debug:

* The stacktrace is in your screenshot. Windows appears to cut it off horizontally (note the **...** near the end of three of the lines), try making the error popup wider before screenshotting it, so you can see exactly which file is being referenced.
* You can optionally set `--version=1.2.1` or whatever (valid) Electron version you want in the package.json script args. There are versions between 1.0.2 and 1.2.2 (see [Electron releases](https://github.com/electron/electron/releases?after=v1.2.3)), but I don't recall why there weren't electron-prebuilt releases made for them.
* `--debug=electron-packager` is not a valid flag for Electron Packager. You have to run `SET DEBUG=electron-packager` in Windows before running  `npm run-script build-win`.

**Comment by delebash** [comment]
Thanks for the info on how to use the DEBUG setting.

I can't resize the popup

 I will get back to you on the exact version # of electron that it fails on.  My confusion was about the difference between electron-prebuilt and electron. I will just use electron instead of electron-prebuilt and let you know.

I am not trying to get you to debug my app, it is just that the app runs fine if I just run it via electron .  verses compiled. I am happy to track down the error myself but I am just not familiar with debugging a compiled exe.  My code is in phpstorm so I guess I would install VS, move my code over there, compile it and attach to the running exe.  I will research this some more.

I am ok with compiling it on a lower version that works.  I just thought there where security fixes that would make it better to compile it using the latest stable release.

Thanks for the help.

Here is the console output

> > google-music-electron@2.13.0 build-win F:\Development\GitHub\delebash\Electron\google-music-electron-master                                            
> > electron-packager . musicwrapper --debug=electron-packager --platform=win32 --arch=ia32 --version=1.2.2 --overwrite --out ./build/win                  
>                                                                                                                                                          
>   electron-packager Electron Packager 8.3.0 +0ms                                                                                                         
>   electron-packager Node v6.1.0 +2ms                                                                                                                     
>   electron-packager Host Operating system: win32 (x64) +1ms                                                                                              
>   electron-packager Packager Options: {"_":[".","musicwrapper"],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":true,"prune":
> true,"debug":"electron-packager","platform":"win32","arch":"ia32","version":"1.2.2","out":"./build/win","dir":".","name":"musicwrapper","protocols":[]} +
> 1ms                                                                                                                                                      
>   electron-packager Target Platforms: win32 +0ms                                                                                                         
>   electron-packager Target Architectures: ia32 +0ms                                                                                                      
>   electron-packager Inferring app-version from version in F:\Development\GitHub\delebash\Electron\google-music-electron-master\package.json +11ms        
>   electron-packager Application name: musicwrapper +1ms                                                                                                  
>   electron-packager Target Electron version: 1.2.2 +0ms                                                                                                  
>   electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',                                                                   
>   '/node_modules/electron-prebuilt($|/)',                                                                                                                
>   '/node_modules/electron-packager($|/)',                                                                                                                
>   '/\\.git($|/)',                                                                                                                                        
>   '/node_modules/\\.bin($|/)',                                                                                                                           
>   '\\.o(bj)?$' ] +0ms                                                                                                                                    
>   electron-packager Downloading Electron with options {"strictSSL":true,"platform":"win32","arch":"ia32","version":"1.2.2"} +102ms                       
> Packaging app for platform win32 ia32 using electron v1.2.2                                                                                              
>   electron-packager Creating C:\Users\Daniel\AppData\Local\Temp\electron-packager\win32-ia32-template +3ms                                               
>   electron-packager Extracting C:\Users\Daniel\.electron\electron-v1.2.2-win32-ia32.zip to C:\Users\Daniel\AppData\Local\Temp\electron-packager\win32-ia3
> 2-template +1ms                                                                                                                                          
>   electron-packager Initializing app in C:\Users\Daniel\AppData\Local\Temp\electron-packager\win32-ia32\musicwrapper-win32-ia32 from C:\Users\Daniel\AppD
> ata\Local\Temp\electron-packager\win32-ia32-template template +946ms                                                                                     
>   electron-packager Ignored paths based on the out param: [ 'F:\\Development\\GitHub\\delebash\\Electron\\google-music-electron-master\\build\\win' ] +22
> ms                                                                                                                                                       
>   electron-packager Running npm prune --production +4s                                                                                                   
>   electron-packager Renaming electron.exe to musicwrapper.exe in C:\Users\Daniel\AppData\Local\Temp\electron-packager\win32-ia32\musicwrapper-win32-ia32 
> +6s                                                                                                                                                      
>   electron-packager Running rcedit with the options {"version-string":{},"file-version":"2.13.0","product-version":"2.13.0"} +3ms                        
>   electron-packager Moving C:\Users\Daniel\AppData\Local\Temp\electron-packager\win32-ia32\musicwrapper-win32-ia32 to build\win\musicwrapper-win32-ia32 +
> 263ms                                                                                                                                                    
> Wrote new app to build\win\musicwrapper-win32-ia32

**Comment by malept** [comment]
There is no difference between `electron` and `electron-prebuilt`, except for the name and that `electron-prebuilt` will no longer have Electron releases published to it at the end of this year.

**Comment by malept** [comment]
Interestingly enough, I built your app on Linux and the error gets printed to the console, rather than a popup. Hope this helps:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at basename (path.js:1355:5)
    at Command.parse (/tmp/tunein-music-wrapper/build/musicwrapper-linux-x64/resources/app/node_modules/commander/index.js:446:30)
    at Object.exports.parse (/tmp/tunein-music-wrapper/build/musicwrapper-linux-x64/resources/app/lib/cli-parser.js:46:11)
    at Object.<anonymous> (/tmp/tunein-music-wrapper/build/musicwrapper-linux-x64/resources/app/lib/google-music-electron.js:22:39)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

(At first glance it appears that you need to modify the CLI parser to not require at least one argument - I ran `musicwrapper something` and it ran fine.)
