### ISSUE TITLE
Add an option to supress output

### ISSUE THREAD

**Issue by DenkerAffe** [electron-userland/electron-packager#538]
Currently the module prints some stuff on the console, like "packaging app for ...". It would be nice if I could pass an option  which disables this behaviour.

**Comment by malept** [comment]
[Electron Forge](https://github.com/MarshallOfSound/electron-forge) actually could use this.

**Comment by malept** [comment]
I have a pull request in https://github.com/electron-userland/electron-packager/pull/541.

**Comment by DenkerAffe** [comment]
Awesome, thanks a lot!
