### ISSUE TITLE
Exporting Desktop app architecture error

### ISSUE THREAD

**Issue by miftari0** [electron-userland/electron-packager#539]
**Please describe your issue:**

i was trying to make and Windows app but it goes fine till the arch selection whenever i try it just shows me this error:
![pic](https://cloud.githubusercontent.com/assets/24373737/21027139/cfd24042-bd8f-11e6-92ca-10813b4645ff.jpg)

```
C:\Users\simel\Downloads\App>epi
? Overwrite output directory ? Yes
? Use asar source packaging ? Yes
? Select Electron app source directory: C:\Users\simel\Downloads\App
? Select Electron app output directory: C:\Users\simel\Downloads\App\releases
? Select Application name: Hello World!
? Select App Bundle Id (optional):
? Select App Version(optional): 0.0.1
? Select Electron icon file: C:/Users/simel/Downloads/App/fb.png
? Select Electron version release: 1.2.2
? Select platforms:
? Select architecture:

✗ Error: Must specify arch
```

**Comment by malept** [comment]
This sounds like an electron-packager-interactive bug to me.

**Comment by malept** [comment]
Yep, we added optional arch support in [8.0.0](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#800---2016-09-03), as of the writing of this comment, -interactive is [pinned to 7.x](https://github.com/Urucas/electron-packager-interactive/blob/12d0afbd2dc1f3dfc90aff86badd197e6aa50a78/package.json#L36).

**Comment by malept** [comment]
For what it's worth, I filed a pull request: https://github.com/Urucas/electron-packager-interactive/pull/18

**Comment by miftari0** [comment]
How can i update electron to 8.0.0

**Comment by malept** [comment]
@miftari0 you have two workaround options:

* Use the existing released `electron-packager-interactive` and specify a target architecture (do not leave it blank) until the maintainer of `electron-packager-interactive` merges my pull request to update its dependency of Electron Packager (not Electron) to version 8.x.
* Install my branch of `electron-packager-interactive`  that is the basis for the pull request. This requires you to install an NPM module from a git branch, the instructions for which can be found at [the NPM website](https://docs.npmjs.com/cli/install).
