### ISSUE TITLE
How can I pack the dependencies with bower?

### ISSUE THREAD

**Issue by kyssproject** [electron-userland/electron-packager#542]
**Please describe your issue:**

I am trying to pack my electron app in a Windows 10 environment and with electron-packager. This is my package.json

```
{
  "name": "test",
  "productName": "test",
  "version": "1.0.0",
  "author": "test",
  "description": "test",
  "devDependencies": {
    "asar": "^0.12.3",
    "electron-packager": "^8.3.0",
    "electron-prebuilt": "^1.4.8",
    "gulp": "^3.9.1",
    "gulp-bower": "0.0.13",
    "rcedit": "^0.7.0"
  },
  "dependencies": {
    "highcharts": "^5.0.5",
    "jquery": "^3.1.1",
    "remote": "^0.2.6"
  },
  "scripts": {
    "package": "electron-packager ./app ha --platform=win32 --arch=x64  --asar=true",
  }
}
```

Then when I run npm run package, dependencies are not there and the program fails when it want to use highcharts. In the .exe directory there's no node_modules folder.

The thing is that I don't fully understand how does it work. I have installed angular through bower, but I am indeed referring to the scripts that are in my app, so I guess that's why I can use angular. I don't really know what role bower plays here honestly, and if this is interfering with the packaging. 

I have tried to add the  --ignore=bower.json in the package script, since the bower.json has an ignore to dependencies

```
{
  "name": "test",
  "description": "",
  "main": "",
  "license": "MIT",
  "homepage": "",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "^1.5.9",
    "angular-material": "^1.1.1"
  }
}
```

But it hasn't changed anything.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
module.js:455 Uncaught (in promise) Error: Cannot find module 'highcharts'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\...\test-win32-x64\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
   ...
```

So I suspect that I am doing something wrong here, but I am uncapable of finding out what, When running "electron app" the applications runs without problem,

Thanks!

**Comment by kyssproject** [comment]
If I create the folder node_modules in the resources folder (inside .exe folder), and copy there the highcharts folder, then it works.

Is it the way it is supposed to work??

**Comment by malept** [comment]
I don't suggest using NPM *and* Bower in the same Electron app. If you decide that you must, you'll probably need to adjust Node's module search path to look in your `bower_components` folder so that `require` works the way you want it to.

**Comment by kyssproject** [comment]
I have changed the app and installed everything fresh (on a new computer) without bower, but I am facing the same problem which is: no dependencies are installed in the .exe package.

I can solve that by manually creating a node-modules folder into the resources folder, but I'd say this is not the expected behavior.

My package.json

```
{
  "name": "test",
  "license": "GPL-3.0",
  "productName": "test_electron",
  "version": "1.0.0",
  "author": "test",
  "description": "test",
  "repository": {
    "type": "git",
    "url": "git://github.com/username/repository.git"
  },
  "devDependencies": {
    "electron": "^1.4.12",
    "electron-packager": "^8.4.0"
  },
  "dependencies": {
    "angular": "^1.6.0",
    "angular-resource": "^1.6.0",
    "angular-route": "^1.6.0",
    "angular-sanitize": "^1.6.0",
    "highcharts": "^5.0.6"
  },
  "scripts": {
    "start": "./node_modules/.bin/electron app",
    "package": "electron-packager ./app test_test --platform=win32 --arch=x64  --asar=true",
  }
}
```

**Comment by kyssproject** [comment]
Now I have understood. My problem was that I was mixing "folders". Since I had the app in the /app folder, these modules should have been installed under the /app folder and not under the main / folder. Once done, the node-module requirements are well packaged.

Thanks!

**Comment by evildancer** [comment]
I have same problem. I don't understood your solution.Can you be in detail?

**Comment by malept** [comment]
It would help if you provided an example repo that contained your problem.

**Comment by ssjzhong** [comment]
@malept thanks for your project, It's great.

We meet the similar issue, can you help? 

We have one Angular 2+ app and hosted in Electron. Below are the code structure:
```
--dist
--node_modules
--src
   --app(Here are source code of Angular 2+)
   --electron
        - package.json(for electron)
        - electron.js(electron entry will import some 3rd party JS like **electron-log**)
--angular-cli.json
--package.json(For angular 2+ app)
```

First, we build the Angular project using web-pack to dist folder and copy the electron source code to dist  folder. 
Then we can run electron-packager on the path `.\dist`.

The question is that the packager won't install the 3rd party JS module which defined in `./src/electron/package.json`. 

If I copy the packages to the `dist` folder manully, It works.

So can you please advice a correctly way to use electron packager for this case?

**Comment by malept** [comment]
@ssjzhong without any more context, my guess is that you'd probably need to run `npm install --production` inside of the `electron` folder that you copied to `dist`, before running `electron-packager dist`.

For future reference, it's probably better to go to the [community forums](https://github.com/electron/electron#community) rather than old issues, because I have limited time to help troubleshoot users' problems (in addition to maintaining the project itself), and there are more people looking at the community sites.

**Comment by ssjzhong** [comment]
@malept Thank you very much.  

Thanks for your advice, will got to community.

A quick question here, for the sub-folder, Running `npm install --production` is the best way? Do you have any plan to support getting the node_module from the parent path.

**Comment by malept** [comment]
> Do you have any plan to support getting the node_module from the parent path.

No, the cost (new complex code that needs to be maintained) outweighs the benefits (a use case for a small fraction of the userbase).
