### ISSUE TITLE
Packaged app crashes when app name ends with string " Helper"

### ISSUE THREAD

**Issue by schrockwell** [electron-userland/electron-packager#545]
If the `productName` of a package ends with the string "Helper", the packaged Electron app crashes on launch. 

**Steps to reproduce (macOS 10.12):**
```
git clone https://github.com/atom/electron-quick-start && cd electron-quick-start
$EDITOR package.json # Add "productName": "My App Helper"
npm install
npm install --save-dev electron-packager
$(npm bin)/electron-packager .
# Now run My App Helper.app which will crash
```

Changing the `productName` to something else (e.g. "My App") and running `electron-packager` again will make it launch successfully.

My gut says this has something to do with how the "Chrome Helper" processes are located and launched, but I don't know enough about the Electron internals to provide insight beyond that.

If you dig into `My App Helper.app/Contents/MacOS/My App Helper` and launch the executable directly, you get the following stack trace:

```
[27438:1219/152214:FATAL:atom_main_delegate_mac.mm(50)] Unable to find helper app
0   Electron Framework                  0x0000000108e40813 _ZN4base8internal14NarrowingRangeIilE3minEv + 434723
1   Electron Framework                  0x0000000108e580c7 _ZN4base8internal14NarrowingRangeIilE3minEv + 531159
2   Electron Framework                  0x0000000108c3c6d0 _ZN4atom16AtomMainDelegate24OverrideChildProcessPathEv + 288
3   Electron Framework                  0x0000000108dc84cb _ZN9brightray12MainDelegate20BasicStartupCompleteEPi + 107
4   Electron Framework                  0x0000000108c3bf4d _ZN4atom16AtomMainDelegate20BasicStartupCompleteEPi + 237
5   Electron Framework                  0x00000001094fc4d0 _ZN4base8internal14NarrowingRangeIilE3minEv + 7495392
6   Electron Framework                  0x00000001094fbece _ZN4base8internal14NarrowingRangeIilE3minEv + 7493854
7   Electron Framework                  0x0000000108c39947 AtomMain + 71
8   Electron Quick Start Helper         0x0000000108c2ef26 main + 38
9   libdyld.dylib                       0x00007fffcafdf255 start + 1
```

**Comment by malept** [comment]
Could you see if it's just `My App Helper` that crashes, or if it's `My AppHelper` that also crashes?

I can review a pull request that checks the application name (not just `productName`) to see if it ends in "Helper" (or whatever the earlier investigation turns up). (I don't really have time to write it myself this week.)

I think you should also report this upstream (electron/electron). I have no idea if this is fixable there, but it would be nice to know either way.

**Comment by schrockwell** [comment]
The crash only occurs if the last full word is `Helper`, i.e. `My AppHelper` does not crash, but `My App Helper` does.

What should happen if the string is found in the application name – just a console warning, or should the whole build fail?

**Comment by malept** [comment]
I think the whole build should fail, because you're going to need to rename the app anyway (and having an app named differently on different platforms is not ideal).
