### ISSUE TITLE
silent install parameter for windows installer

### ISSUE THREAD

**Issue by chantisnake** [electron-userland/electron-packager#549]
Hi, I was wondering, do the packager automatically create an silent install parameter (for example `/S` or `/quiet`) for windows installer?

**Comment by malept** [comment]
Electron Packager does not create Windows installer files, it only customizes your app and prepares it for packaging into an installer. What you want is [Electron Forge](https://github.com/electron-userland/electron-forge), and the windows installer configuration details is [here](https://github.com/electron/windows-installer#usage).
