### ISSUE TITLE
Problem with packaging up my project. Angular2 Navigation is broken

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-packager#551]
When I run my Angular 2 Electron project with ng build or ng serve it works 100% all the routers and everything just works.
It was when I started trying to package up my app with electron-packager, builder, and forge where I get the routes no longer working. Instead of loading up the Index.html then immediately navigating to my home component it stays at the index.

Can Anyone direct me onto why this is happening?

**Comment by malept** [comment]
I think the relevant thread is https://github.com/electron-userland/electron-forge/issues/66#issuecomment-270547794.

**Comment by AhadCove** [comment]
Well I ran into the same problem using forge, for now I just want to get it working using the normal packager

**Comment by MarshallOfSound** [comment]
I'm happy to keep following up in #66 as it seems to be the kind of thing that should be documented for Angular users in Electron Compile.  But this is definitely not a `electron-packager` issue 👍
