### ISSUE TITLE
Trying to add entitlements and icon to osx-flat for app store

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-packager#555]
Im currently trying to upload my app to the app store, but I am running into the sandbox error. 
I know this has to do with my entitlement not being added. Also for some reason the Icons are not being found in the .pkg also.

enittlements.mas.plist:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
  </dict>
</plist>
```

Cli command:
```
    electron-osx-flat ..Path/App.app --entitlements=entitlements.mas --out=releases/store/ --icon=src/assets/icons/mac/icon.icns --overwrite

```

I am using electron-packager to package my .app file

**Comment by BenLaKnet** [comment]
How did fixed your problem, please.
I have the same issue with electron-builder, electron-osx-sign and after electron-osx-flat.
