### ISSUE TITLE
Modify info.plist App helper

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-packager#556]
I keep running into the error when submitting to the app store and can't get by it. 
The error is:

`ERROR ITMS-90296: "App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: [( "com.site.app.pkg/Payload/App.app/Contents/Frameworks/App Helper EH.app/Contents/MacOS/QuizzUmmah Helper EH", "com.site.app.pkg/Payload/App.app/Contents/Frameworks/App Helper NP.app/Contents/MacOS/App Helper NP", "com.site.app.pkg/Payload/App.app/Contents/Frameworks/App Helper.app/Contents/MacOS/App Helper", "com.site.app.pkg/Payload/App.app/Contents/MacOS/App" )] Refer to App Sandbox page at https://developer.apple.com/devcenter/mac/app-sandbox/ for more information on sandboxing your app."`

So I am trying to add the value:
com.apple.security.app-sandbox=true
to the app helper info.plist, but I keep running into I am not allowed to modify, because im not original owner.

**Comment by malept** [comment]
Mac App Store apps aren't my area of expertise, but there's something about app sandboxes in Electron's [Mac App Store Submission Guide](http://electron.atom.io/docs/tutorial/mac-app-store-submission-guide/).

**Comment by AhadCove** [comment]
I will try this now, I stayed away at first because I didn't understand the whole script thing. Thank you I will let you know how it goes

**Comment by dmitrykurochka** [comment]
@AhadCove Have you resolved an issue?
Because I faced the same issue

**Comment by AhadCove** [comment]
Yeah @dmitrykurochka 
Make a parent entitlement and a child entitlement:

parent.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
</dict>
</plist>

```

child.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>

```

When you're building the app refer to the entitlements with the flag

```
--entitlements=parent.plist --entitlements-inherit=child.plist
```

**Comment by soundar78** [comment]
@AhadCove, by this 

> When you're building the app refer to the entitlements with the flag

you mean referring the entitlements here?
`codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"`

cos i tried this
`codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" --entitlements-inherit "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"` 

 and still ran into that error.

if possible, could you please guide me like where exactly i should refer the entitlements with a example?

**Comment by AndyNormore** [comment]
![image](https://user-images.githubusercontent.com/1661561/57966052-de779400-791a-11e9-9509-8796013ad2d7.png)

GOT IT -- The signing is kind of specific I guess, and this PATICULAR file wasn't being signed. So I added a line to make sure this one specifically was being signed and BAM, worked and uploaded <3
