### ISSUE TITLE
give warnings when using an invalid arch/platform combination

### ISSUE THREAD

**Issue by seiyria** [electron-userland/electron-packager#562]
**Please describe your issue:** I accidentally was using --arch=ia32 and --platform=darwin and was getting absolutely no output from electron-packager. Turns out I have to use --arch=x64.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
posys seiyria$ ./node_modules/.bin/electron-packager . --platform=darwin --arch=ia32
posys seiyria$ ./node_modules/.bin/electron-packager . --platform=darwin --arch=x64
Packaging app for platform darwin x64 using electron v1.4.14
Wrote new app to /Users/seiyria/GitHub/posys/Posys-darwin-x64
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

--arch=ia32 --platform=darwin

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

It should work on any electron-packager usage, but [the project I'm using it on is here](https://github.com/seiyria/posys).

**Comment by malept** [comment]
Thanks for the suggestion! I'd rather give warnings than errors.

**Comment by seiyria** [comment]
A warning would be fantastic too. Anything to let me know that I'm doing something dumb is better than silence!
