### ISSUE TITLE
Building app without connection

### ISSUE THREAD

**Issue by Leonardonline** [electron-userland/electron-packager#566]
I'm under company proxy and it isn't possible to download big zip files, especially from command line.
It is possibile to build application without internet connection?

I try to explain my question.

I have downloaded all that need to build on another computer with the same OS (win7) and I take all the folders, 
In the pc without connection I tried to build but  I get the following error:

```
Downloading electron-v1.4.15-win32-ia32.zip
Error: GET https://github.com/electron/electron/releases/download/v1.4.15/electron-v1.4.15-win32-ia32.zip returned 403
```

I passed these arguments:

```
electron-packager . --overwrite --platform=win32 --arch=ia32 --out=out --version-string.CompanyName='CompanyNameStartPackager' --version-string.FileDescription='FileDescriptionStartPackager' --version-string.ProductName='ProductNameStartPackager'
```

**Comment by englishextra** [comment]
@Leonardonline you need to specify --download.cache=your_cache_folder_path and have already packaged all platforms you need so that you should have electron zip files in that folder, then you can copy that folder to non connection machine's project folder

**Comment by Leonardonline** [comment]
@englishextra I took advantage of the lunch break to try to download as you suggested and ...it works! 
THANK YOU
