### ISSUE TITLE
Can't package App on Win32 works fine with Darwin

### ISSUE THREAD

**Issue by lenmyles** [electron-userland/electron-packager#569]
So I decided to test out electron. I made a simple project and packaged it for Darwin(MacOS) it took a few tries but i got it to work. I also tried to package it for Windows but it doesn't work. 
Here is my script: electron-packager . WANO --platform=win32 - this works fine when I try to package it for MacOS but when I try for windows it does not work.

Here is the Debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'v' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly mapToRegistry name wano-g
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'wano-g',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'wano-g',
7 silly mapToRegistry   name: 'wano-g',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/wano-g
9 verbose request uri https://registry.npmjs.org/wano-g
10 verbose request no auth needed
11 info attempt registry request try #1 at 4:19:27 PM
12 verbose request id 1f54a0d60fe8be60
13 http request GET https://registry.npmjs.org/wano-g
14 http 404 https://registry.npmjs.org/wano-g
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '2',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Sat, 28 Jan 2017 05:49:28 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-mel6523-MEL',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1485582567.534983,VS0,VE957',
15 verbose headers   vary: 'Accept-Encoding' }
16 silly get cb [ 404,
16 silly get   { 'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '2',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Sat, 28 Jan 2017 05:49:28 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     age: '0',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-mel6523-MEL',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1485582567.534983,VS0,VE957',
16 silly get     vary: 'Accept-Encoding' } ]
17 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/wano-g
17 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
17 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
17 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
17 verbose stack     at emitTwo (events.js:106:13)
17 verbose stack     at Request.emit (events.js:191:7)
17 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
17 verbose stack     at emitOne (events.js:96:13)
17 verbose stack     at Request.emit (events.js:188:7)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
18 verbose statusCode 404
19 verbose pkgid wano-g
20 verbose cwd /Users/(removed)/Desktop/WANOMac
21 error Darwin 16.1.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "v"
23 error node v6.9.4
24 error npm  v3.10.10
25 error code E404
26 error 404 Registry returned 404 for GET on https://registry.npmjs.org/wano-g
27 error 404
28 error 404 'wano-g' is not in the npm registry.
29 error 404 You should bug the author to publish it (or use the name yourself!)
30 error 404 Note that you can also install from a
31 error 404 tarball, folder, http url, or git url.
32 verbose exit [ 1, true ]

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. **If you are using `npm run` to execute `electron-packager`, run the `electron-packager` command without using `npm run` and make a note of the output, because `npm run` does not print out error messages when a script errors.** Please include the stack trace if one exists.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
