### ISSUE TITLE
Can't package the electron app

### ISSUE THREAD

**Issue by KamyarGhajar** [electron-userland/electron-packager#571]
hi,
This was working before but I don't know what has changed...maybe it is because of the npm update I don't know...I get this error when I try to packege for all archs with: 
`electron-packager . --all`

```
Packaging app for platform linux ia32 using electron v1.4.15
Command failed: npm prune --production
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "prune" "--production"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! path /private/var/folders/52/wcyhdpbs6x75zhchxh0vpc_m0000gn/T/electron-packager/linux-ia32/abtalk-linux-ia32/resources/app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/private/var/folders/52/wcyhdpbs6x75zhchxh0vpc_m0000gn/T/electron-packager/linux-ia32/abtalk-linux-ia32/resources/app/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/private/var/folders/52/wcyhdpbs6x75zhchxh0vpc_m0000gn/T/electron-packager/linux-ia32/abtalk-linux-ia32/resources/app/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/52/wcyhdpbs6x75zhchxh0vpc_m0000gn/T/electron-packager/linux-ia32/abtalk-linux-ia32/resources/app/npm-debug.log
```

**Comment by malept** [comment]
Pardon the obvious question, but does your app have a `package.json` file in the directory where you're running Electron Packager from?

**Comment by KamyarGhajar** [comment]
Your welcome @malept and thanks for the answer.
Yes it does. As I've said it was working before, on the same project, but now it's not...even I did `npm init` again to setup the `package.json` file and then added the dependecies to the json file to install them again...but the error persistes

**Comment by KamyarGhajar** [comment]
I have made a build folder and from there I run the command for the parent directory that has the `package.json` file and is the project's root folder.

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by Kasperfred** [comment]
@malept I have a similar problem.

As requested, I setup a small Electron app based on the quick start. The steps I took were as following:

I install the electron-quick-start using its guide:
```
# Clone this repository
git clone https://github.com/electron/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
```

Then I installed electron-packager:
`npm install --save-dev electron-packager`
While installing, it complained about using an outdated node.js version:
```
npm WARN engine electron-packager@8.5.1: wanted: {"node":">= 4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine get-package-info@1.0.0: wanted: {"node":">= 4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine read-pkg-up@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine find-up@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine read-pkg@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine locate-path@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine load-json-file@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine path-type@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine path-exists@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine p-locate@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine strip-bom@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine p-limit@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
```
Nevertheless, the installation was successful and when I ran `npm start`, the welcome window opened saying I was running node 6 - something.

I then edited the package.json file by adding `"build": "electron-packager . -all"` in the scripts section after "start". 

I then ran `npm run-script build` where it failed, again, complaining about the node version:

```
> electron-packager . -all

CANNOT RUN WITH NODE 0.12.2
Electron Packager requires Node 4.0 or above.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@0.1.0 build: `electron-packager . -all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@0.1.0 build script 'electron-packager . -all'.
npm ERR! This is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . -all
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kasper\Desktop\test\electron-quick-start\npm-debug.log
```

The npm-debug.log file is attached to this comment if it's any help. 
[npm-debug.txt](https://github.com/electron-userland/electron-packager/files/751711/npm-debug.txt)

**Comment by malept** [comment]
@kasperfred this is a different problem that what the issue reporter is describing. You are definitely running Node 0.12, from your `npm run-script build` output:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
```

Electron *itself* I think runs Node 6.

**Comment by englishextra** [comment]
@kasperfred electron-packager needs your global Node 4.0 or above to package your app
And electron comes with its own nodejs which is important for your app, and not for packager.
So, I guess the package.json should be demonstrated here.
@malept Do I miss smth?

**Comment by malept** [comment]
> electron-packager needs your global Node 4.0 or above to package your app
And electron comes with its own nodejs which is important for your app, and not for packager.

@englishextra did I not say that in my comment?

I don't think he needs to show his package.json, it's pretty clear that he needs to upgrade Node on his system.

**Comment by englishextra** [comment]
@malept Pretty sure you got me wrong, the same I did say above - it's global Node needs updating.

As for package.json I asked to have a look at - that's because:
```
5 error install Couldn't read dependencies
```

**Comment by malept** [comment]
@englishextra

> `5 error install Couldn't read dependencies`

It's pretty clear what that error means from the successive error messages:

```
15 error package.json ENOENT, open 'C:\Users\Kasper\Desktop\test\package.json'
15 error package.json This is most likely not a problem with npm itself.
15 error package.json npm can't find a package.json file in your current directory.
```

**Comment by englishextra** [comment]
@malept You're right - I didn't notice the last lines. I should learn to read debug-logs.

Thanks.

**Comment by KamyarGhajar** [comment]
@malept I've setup everything from ground-up (npm, project, packager,...) and it works fine now with `mkdir` a `build` folder in the project and in that directory I run: 
`electron-packager .. --all`
not:
`electron-packager . --all`
