### ISSUE TITLE
Packager copys empty module

### ISSUE THREAD

**Issue by TheNoim** [electron-userland/electron-packager#573]
**Please describe your issue:**

When I am package my application with electron packager, the packager copys empty module to the packaged application.
This is how it looks inside the node_module in the packaged application (watchjs)
http://imgur.com/a/Rqwoe
This is how it looks like in my source node_modules and how it should look like:
http://imgur.com/a/5QqPS
I already tried to remove the node_modules and reinstall it. Both with npm itself and yarn. 

http://imgur.com/a/Pdwu6
Obvious when watchjs empty is.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**
No errors

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
{
        dir: ".",
        all: true,
        "app-version": require('./package.json').version,
        asar: false, // It also happens when asar is true
        icon: "./Icon",
        ignore: [
            'src/', // node_modules is outside of the src directory, and I am minifying all files to build/ with gulp
            'bower.json',
            '.bowerrc',
            'yarn.lock',
            'builds/'
        ],
        arch: 'all',
        platform: 'all',
        platforms: 'all',
        "app-bundle-id": 'io.noim.dsbclient',
        out: './builds',
        prune: true, // I tried this, because I tought maybe this could fix it, but it doesen't.
        electronVersion: '1.4.13', // First I thought it was a electron problem
        derefSymlinks: true
    }
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**
My dependencies: 
```
"dependencies": {
    "auto-launch": "^5.0.1",
    "debug-menu": "^0.4.0",
    "dsbiserv": "^1.3.0", // requires watchjs
    "electron": "^1.4.15",
    "electron-ipc-socket": "^1.2.4",
    "electron-is-dev": "^0.1.2",
    "electron-json-storage": "^3.0.1",
    "electron-packager": "^8.5.1",
    "electron-rebuild": "^1.5.7",
    "validator": "^6.2.1",
    "watchjs": "^0.0.0" // I added it because i hoped this would fix it.
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.22.0",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-clean": "^0.3.2",
    "gulp-htmlmin": "^3.0.0",
    "gulp-inline": "^0.1.3",
    "gulp-minify-css": "^1.2.4",
    "gulp-sequence": "^0.4.6",
    "gulp-uglify": "^2.0.1"
  }
```
My project structure:
http://imgur.com/a/yQPma

**Comment by MarshallOfSound** [comment]
@TheNoim Your problem is you are ignoring the `src/` pattern.  This is matching that src folder in your `node_modules` directory.

You need a more explicity regexp / pattern that only matches at the **start** of the tested path.

**Comment by TheNoim** [comment]
@MarshallOfSound damit, you are right. What could i use to prevent this ?

**Comment by MarshallOfSound** [comment]
Well I use this magic

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/gulpfile.babel.js#L56

But that's just me 😆 Basically you just need a stricter ignore pattern 👍
