### ISSUE TITLE
Are there options to specify target OSX verion?

### ISSUE THREAD

**Issue by vvinton** [electron-userland/electron-packager#574]
Folks, this is probably the questions rather than issue - is there a possibility to specify target osx version you want to run application at?

Right now it builds for version 10.10 and what I would like to do - run app at version 10.6.4 - is that achievable, or only option is to upgrade mac os?

Vitaliy

**Comment by MarshallOfSound** [comment]
Chromium itself only supports version `10.9` and higher as does Electron.

> only option is to upgrade mac os?

^^ that is your only viable path 👍
