### ISSUE TITLE
How to install required package from MSI for windows

### ISSUE THREAD

**Issue by askucher** [electron-userland/electron-packager#577]
How to install required package for windows from MSI

I have package deps 

```
Dependencies
This library need

ALSA tools installed on the machine (sudo apt-get install alsa-utils) for Linux
SoX Tools installed on the machine for Windows or OSX
```
I need to install them with Electron App

How to do that ?

**Comment by englishextra** [comment]
```
https://sourceforge.net/projects/sox/files/sox/14.4.2/
```

**Comment by malept** [comment]
This is offtopic for Electron Packager, because it doesn't handle creating installers.

However, with [Electron Forge](https://github.com/electron-userland/electron-forge) (which uses Electron Packager), you can build installers/packages that handle dependencies. Specifically for Windows, it looks like you should be using https://github.com/mongodb-js/electron-squirrel-startup. I haven't used it myself, so if you have questions about it, please feel free to ask in one of the [Electron community forums](https://github.com/electron/electron#community).

**Comment by askucher** [comment]
@englishextra Some npm packages require to do:  

```
sudo apt-get install something 
```

So, the question is how to do that with Electron Packager?
But looks like Electron Forge is close to answer

**Comment by englishextra** [comment]
@askucher Learn to formulate what you want to achieve, when come here pose your question. You didn't specify what is your app about to do, and what is it in aid of.

**Comment by malept** [comment]
@englishextra This project follows the Electron community's [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md), I would ask you to please be more respectful and empathetic towards issue reporters.

**Comment by englishextra** [comment]
@malept Hope this applies to issuereporters as well.

**Comment by malept** [comment]
@englishextra it does. This issue reporter did not violate the code of conduct.

**Comment by englishextra** [comment]
>>This issue reporter did not violate the code of conduct.

Which I didn't either. It was me who got arrogance here. Let's Face it. I am here to share my experience and nothing else.

**Comment by malept** [comment]
@englishextra what you said in https://github.com/electron-userland/electron-packager/issues/577#issuecomment-277915907 can be interpreted by a reasonable person like you're scolding the issue reporter for not being able to state their question fully-formed and using the issue reactions in possibly a different way than you do.

From the code of conduct, comments should strive to be (picking the relevant ones in this case):
> * Using welcoming and inclusive language
> * Being respectful of differing viewpoints and experiences
> * Showing empathy towards other community members

English might not be your first language, so I'm going to give you the benefit of the doubt and assume that you did not mean your comment to have malicious intent. However, I would ask you in the future to reread comments before you post to make sure that what you say cannot reasonably be interpreted in a negative way.

This is the last comment I'm going to post on this matter.

**Comment by englishextra** [comment]
@malept  Thanks.

I guess, This is not about the code of conduct, it's about the Electron project spirit.
```
This is the last comment I'm going to post on this matter.
```
Never say never.
