### ISSUE TITLE
electron-packager throws me an error: spawn C:\Windows\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by Akronae** [electron-userland/electron-packager#582]
**Please describe your issue:**
Hi, i'm actualy doing a local chat, using socket.io & electron. Everythings works fine, but when i try to compile my app (client side (obviously) ) electron-packager give me an error.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
C:\Users\alexr\Documents\prog\js\Shou>electron-packager ./client/main.js app.exe --platform=win32 --arch=ia32 --electron-version=1.4.15
Packaging app for platform win32 ia32 using electron v1.4.15
spawn C:\Windows\system32\cmd.exe ENOENT
```
``

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
./client/main.js app.exe --platform=win32 --arch=ia32 --electron-version=1.4.15
```
I haven't use the API

**What i did**
First i check for this path, and well i get cmd.exe !
Then i check for sys variables, and i get `ComSpec = C:\Windows\system32\cmd.exe`.
I don't know what to do next..

**Computer info**
OS: WIndows 10
node: 7.4.0
npm: 4.0.5

Thanks !

**Comment by englishextra** [comment]
```
 --electron-version=1.4.15
```
github.com/electron-userland/electron-packager/blob/master/usage.txt

**Comment by Akronae** [comment]
Sorry i forgot "=". But electron-packager give me the same output

**Comment by englishextra** [comment]
[usage.txt](https://github.com/electron-userland/electron-packager/blob/master/usage.txt) cgeck the order of the arguments at the top of the usage.txt

**Comment by Akronae** [comment]
I have read all the .txt.. and i may be dumb but it's what i did.. :/

```
electron-packager <sourcedir> <appname> [options...]
electron-packager ./client/main.js app.exe --platform=win32 --arch=ia32 --electron-version=1.4.15

```
So i read the whole file, and i place the arguments in the reading order

`electron-packager ./client/main.js app.exe --arch=ia32 --platform=win32 --electron-version=1.4.15
`
And it still the same output.. :(

**Comment by englishextra** [comment]
I'd suggest to download this example and use it as a template for a starter:

[electron-quick-start](https://github.com/electron/electron-quick-start)

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

In your `cmd.exe` command prompt, run `SET DEBUG=electron-packager`, then run your electron-packager command and paste the output here.

**Comment by Akronae** [comment]
When i do
`
cd client
electron-packager ./ app.exe --arch=ia32 --platform=win32 --electron-version=1.4.15
`
indeed of
`electron-packager ./client/main.js app.exe --arch=ia32 --platform=win32 --electron-version=1.4.15
`

It's works fine !
I will output debug log for that you can fixe this issue

**Comment by malept** [comment]
Oh, I see what the problem is. You set the first argument as the path to the main script. Per the documentation, the first argument is `sourcedir`:

```
sourcedir          the base directory of the application source
```

**Comment by Akronae** [comment]
sh*t, sorry i skipped the 1st grade x)
