### ISSUE TITLE
opts.name is not work fine on Windows

### ISSUE THREAD

**Issue by Riokai** [electron-userland/electron-packager#583]
My config is:

```js
{
  dir: './',
  name: 'Ping',
  asar: shouldUseAsar,
  'app-copyright': '拉扎斯网络科技（上海）有限公司',
  'app-version': pkg.productVersion,
  'version-string': pkg.productVersion,
  'build-version': pkg.productVersion,
  'app-bundle-id': 'com.rajax.ping',
}
```

But name is `electron` on Windows and I hope remove "origin file name" key, What should  I do?

![1](https://cloud.githubusercontent.com/assets/7970372/22736228/29a7e68e-ee38-11e6-9d59-3784c8b18cea.png)
![2](https://cloud.githubusercontent.com/assets/7970372/22736232/2b2b8718-ee38-11e6-8f06-e21502f1dfed.png)

**Comment by MarshallOfSound** [comment]
@Riokai To set the meta data for your application on windows, you need to use the `win32Metadata` option when using the API.

See https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#win32metadata

**Comment by Riokai** [comment]
Got it, Thanks!

**Comment by malept** [comment]
@MarshallOfSound FYI, it's `win32metadata` 😁
