### ISSUE TITLE
64Bit MSI is not 64Bit

### ISSUE THREAD

**Issue by Arcath** [electron-userland/electron-packager#584]
When deploying an MSI through a GPO you have a couple of options for ensuring that the right architecture is deployed to the right machines. The core of this is that the MSI needs to say that it is a 32/64 bit installer.

The only option in a GPO for an MSI is `Make this 32-bit X86 application to Win64 machines`.

Because the generated MSI from `electron-packager` is 32bit no matter what I can't stop the 64Bit installer from installing on 32 Bit machines.

I could use WMI filters but it means having 2 GPOs.

Is this a Squirrel problem or an electron-packager issue?

**Comment by MarshallOfSound** [comment]
@Arcath `electron-packager` does not generate MSI files?  Perhaps you meant to raise this on https://github.com/electron/windows-installer?

**Comment by Arcath** [comment]
I did yes! Sorry about that. I made my build script ages ago and haven't touched it since.
