### ISSUE TITLE
use electron-packager packaging .exe error

### ISSUE THREAD

**Issue by caishengmao** [electron-userland/electron-packager#586]
When packaging .exe in windows error:The version parameter is deprecated, use electronVersion (or --electron-version  in the CLI) instead
how to solve?

**Comment by MarshallOfSound** [comment]
@caishengmao 

The solution is in the message

> use electronVersion (or --electron-version in the CLI) instead

**Comment by caishengmao** [comment]
why?

**Comment by MarshallOfSound** [comment]
Because the syntax was changed in a recent PR to be less confusing "--version" usually returns the version of the CLI tool you are using.  This change makes it more logical

**Comment by malept** [comment]
Additionally, this is not an error, this is a warning message.

**Comment by caishengmao** [comment]
@malept   
this is error massage,run 'npm run build' Can't pack.
D:\wamp\hfx_mac\app>npm run build

> macIm@1.0.0 build D:\wamp\hfx_mac\app
> electron-packager . fetion_0215_1 --platform=win32 --arch=ia32 --overwrite --i
con=./imgs/icon-ott-pc.ico --out=../dist --ignore=.git --version 1.2.4

The version parameter is deprecated, use electronVersion (or --electron-version
in the CLI) instead
Unable to determine Electron version. Please specify an Electron version

For more information, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#v
ersion



npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! macIm@1.0.0 build: `electron-packager . fetion_0215_1 --platform=win32
--arch=ia32 --overwrite --icon=./imgs/icon-ott-pc.ico --out=../dist --ignore=.gi
t --version 1.2.4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macIm@1.0.0 build script 'electron-packager . fetion_0215
_1 --platform=win32 --arch=ia32 --overwrite --icon=./imgs/icon-ott-pc.ico --out=
../dist --ignore=.git --version 1.2.4'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the macIm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . fetion_0215_1 --platform=win32 --arch=ia32 --ov
erwrite --icon=./imgs/icon-ott-pc.ico --out=../dist --ignore=.git --version 1.2.
4
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs macIm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls macIm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wamp\hfx_mac\app\npm-debug.log

**Comment by MarshallOfSound** [comment]
@caishengmao Please replace `--version` with `--electron-version` as the message states.

**Comment by caishengmao** [comment]
@MarshallOfSound   hi, I use the 
electron version: 1.2.4  
node version: 6.9.0
electron-packager:5.8.0 
Can you tell me how to replace --electron-version? Thank you!
![Uploading image.png…]()

**Comment by MarshallOfSound** [comment]
@caishengmao Literally just change it in the "build" script of your package.json?

**Comment by caishengmao** [comment]
@MarshallOfSound  no. You mean is not defined  electron version  in the 'build' scriptof the package.json ?

**Comment by caishengmao** [comment]
@MarshallOfSound  Finally solved,Thank you for your guidance.

**Comment by vonch** [comment]
你的解决了吗？半天我也没看懂啥意思
