### ISSUE TITLE
How to extract JavaScript from Electron exe?

### ISSUE THREAD

**Issue by Daniel15** [electron-userland/electron-packager#591]
If I have an executable packed using electron-packager, is there a command I can run to extract the original files out of it?

**Comment by MarshallOfSound** [comment]
This depends entirely on the way `electron-packager` was used to package the application and for the "obscurity is the best security" idea I don't want to start giving out pointers on how to code dive a packaged and released Electron app 😆 

If you can perhaps share what you are trying to achieve I can try to help out

**Comment by Daniel15** [comment]
> If you can perhaps share what you are trying to achieve I can try to help out

Mainly to ensure that any Electron apps I'm using don't contain any malicious code, given some of them don't have signed installers. That and peeking into other apps to see exactly what they're doing. Basically the same reasons you'd use a dissasembler or decompiler for compiled languages.

Anyways, I worked out that the app is just in an `asar` file in the `resources` directory. I initially thought it was directly embedded in the `.text` section of the executable.

**Comment by atishagrawal** [comment]
I got an electron app developed Linux from a freelancer. He gave me a compiled app which is running fine on Linux 64 bit. But it is not running on Linux 32 Bit. On asking him, he said he cannot do it.
I need your help in this, can you please tell me a way by which I can decompile the 64Bit app and recompile it for 32 bit?
