### ISSUE TITLE
How to ignore filenames with brackets

### ISSUE THREAD

**Issue by mecake** [electron-userland/electron-packager#594]
Is there some way to ignore folder with bracket character in name?

> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "D:\\Node.js\\node.exe" "D:\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "run" "pack"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! testapp@1.0.1 pack: `electron-packager . --all --asar=false --out=build/ --overwrite=true --ignore=(dev)`
> npm ERR! Exit status 255
> npm ERR!
> npm ERR! Failed at the testapp@1.0.1 pack script 'electron-packager . --all --asar=false --out=build/ --overwrite=true --ignore=(dev)'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the testapp package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron-packager . --all --asar=false --out=build/ --overwrite=true --ignore=(dev)
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs testapp
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls testapp
> npm ERR! There is likely additional logging output above.

**Comment by malept** [comment]
Could you please give an example? The ignore syntax is just [regular expression syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).

**Comment by mecake** [comment]
Sure. This brackets:

`--ignore=(dev)`

Square brackets are crashing node too.

`--ignore=[dev]`

**Comment by malept** [comment]
FWIW, `()` are generally called parentheses.

Both of those kinds of brackets are considered to be special characters in regular expression syntax (which I linked to earlier). You need to escape them with backslashes (`\`). Depending on how particular NPM is, you may have to use multiple backslashes to get it working.

**Comment by mecake** [comment]
Escaping does not solve the problem.

`--ignore=\(dev\)`
= Error

`--ignore=\\(dev\\)`
= Error

And even this
`--ignore=\\\\\\\\(dev\\\\\\\\)`
= Error

The fun part is when I'm run this command
`electron-packager . --all --out=build/ --ignore=.bat --ignore=(dev)`
directly through Windows CMD, app packs as expected. 

But when the same command runs through
`node run pack`
then comes an error.

Strange sh*t...

**Comment by malept** [comment]
I don't know how backslashes interact with NPM + CMD on Windows. If you want to avoid trying to debug that, I suggest either replacing the `electron-packager` command with a Node script that uses the [Electron Packager API](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md), or use [Electron Forge](https://github.com/electron-userland/electron-forge) (it's built on top of Packager, and you can import existing Electron projects).

**Comment by malept** [comment]
Another possible solution is to rename the folder so that there's no parentheses/brackets.

**Comment by Judzhin** [comment]
--ignore=dev
or
--ignore="dev"

**Comment by malept** [comment]
@Judzhin Since `ignore` values from the command line are regular expressions, that can be problematic if one of the files in your app (such as a necessary file in your `dependencies`) contains the string `dev`.
