### ISSUE TITLE
detect existing atom-shell zip if node_modules/atom-shell is already installed

### ISSUE THREAD

**Issue by maxogden** [electron-userland/electron-packager#6]
currently if you have atom-shell and atom-shell-packager in the same module you will have to download atom shell twice. this module should check and see if the zip is already in the atom-shell folder before downloading

**Comment by fritx** [comment]
:+1:

**Comment by malept** [comment]
I'm not sure if this is still relevant.

**Comment by malept** [comment]
I don't think this is relevant anymore, both electron(-prebuilt) and electron-packager both use electron-download, which caches Electron zips. I'm reasonably sure the same Electron version+platform+arch zip won't get downloaded twice beause of this.
