### ISSUE TITLE
 Packaged out to run in linux command line mode?

### ISSUE THREAD

**Issue by milu2003** [electron-userland/electron-packager#606]
This is running in command line mode. The console has nothing and no error：

![image](https://cloud.githubusercontent.com/assets/15957433/23581373/60931150-014d-11e7-8d90-0b3e4481774b.png)

This is running in gui mode, the console has output, the software is running normally：

![image](https://cloud.githubusercontent.com/assets/15957433/23581415/3310cae6-014e-11e7-81cb-9bf839bed614.png)

My software is based on electron, I now want to pack out, running on the linux platform, the command line mode, How to do it?

**Comment by malept** [comment]
Why are you trying to run Electron as root?

**Comment by milu2003** [comment]
@malept 


I do not understand your question, do you want to ask why you want to run in the command line mode?

**Comment by malept** [comment]
Also, could you please explain the difference between "command line mode" and "gui mode"? Electron is a GUI-based application framework, it doesn't make any sense if you're trying to run an Electron without an X11 (or I guess Wayland) environment running.

**Comment by malept** [comment]
>> Why are you trying to run your packaged Electron app as root?
>
> I do not understand your question

In your first screenshot, you're running your `test` Electron app as the root user. That's generally a bad idea.

**Comment by milu2003** [comment]
@malept 

Yes, I am very strange to do so. In fact, my project wants to run on the window, mac platform, so need gui. But I now want him to run on the linux platform, but the linux platform is generally command line mode

If you do not need gui, electron is not necessary. So, I have a program can choose, is the nodejs project packaged into a separate program. There is a project that can do this. Is nexe.


But this project is not mature enough, can not meet my requirements.

So I can only use electron-packager

**Comment by milu2003** [comment]
@malept 

> In your first screenshot, you're running your test Electron app as the root user. That's generally a bad idea.

If not root operation, it should be what users to run? I do not know much about linux.

**Comment by milu2003** [comment]
I said the gui model refers to this：

![image](https://cloud.githubusercontent.com/assets/15957433/23581591/a388624a-0151-11e7-8c32-47dbb12d55ad.png)


Use the command 
```
init 5
```
 to switch

and  command line
Use the command 
```
init 3
```
 to switch

**Comment by malept** [comment]
> If not root operation, it should be what users to run? I do not know much about linux.

You would run as an unprivileged user.

> Yes, I am very strange to do so. In fact, my project wants to run on the window, mac platform, so need gui. But I now want him to run on the linux platform, but the linux platform is generally command line mode
>
> If you do not need gui, electron is not necessary.

According to my tests, you cannot run Electron apps in "command line mode" (meaning, not inside an X or Wayland environment like your latest screenshot). Here's how I tested it:

* `git clone https://github.com/electron/electron-quick-start && cd electron-quick-start`
* Run `npm install`
* Replace the contents of `main.js` with:

```javascript
console.log('This will not run');
```

* Run `DISPLAY=:nonexistent $(npm bin)/electron .; echo $?`

This only prints out `1` (the exit code), which means that Electron could not start up correctly and had to exit.

It sounds like you're going to have to figure out another way to support non-GUI users (for example, a separate app without using Electron), or reconsider supporting them all together.

**Comment by milu2003** [comment]
ok。There is a project that can be done nexe, but not so mature. no solution anymore

thanks
