### ISSUE TITLE
Accessing the registry not working when app is packaged

### ISSUE THREAD

**Issue by nickwinger** [electron-userland/electron-packager#607]
Hi,

i'm having a strange issue reading the registry on windows 7 when the app is packaged.
No asar.
Using the library: https://www.npmjs.com/package/electron-machine-id
When not packaged it works, when packaged ist cannot find the registry entry that the library is looking for.
Why ???
exec seems to work, as the command gets executes, but the command does not find the registry key

**Comment by malept** [comment]
This appears to be a problem with `electron-machine-id`: https://github.com/automation-stack/node-machine-id/issues/9
