### ISSUE TITLE
win32metadata should have sensible defaults

### ISSUE THREAD

**Issue by MarshallOfSound** [electron-userland/electron-packager#611]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

`win32metada` should have reasonable defaults so that Squirrel shortcut creation works out of the box as expected.

Currently, https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#win32metadata defaults to an empty object AFAIK and therefore the default metadata from Electron is left intact.

This results in lots of questions like "Why is my Squirrel shortcut called 'Electron'?".  This can be solved by simply providing logical defaults for the `win32metadata` option as follows below. Where "p" === "package.json"

| Key | Mapped Value |
|-----|-----------------|
| ProductName | `config.name or p.productName or p.name` |
| InternalName | `config.name or p.productName or p.name` |
| OriginalFilename | `config.name or p.productName or p.name` |
| FileDescription | `p.description` |
| CompanyName | `p.author` |

This is just a proposal, feedback on this welcome 👍

**Comment by malept** [comment]
I like this, I've been waiting for someone who has a Windows machine to write something that I can understand for sensible defaults for the metadata fields 😅 

About `CompanyName`: per https://github.com/electron-userland/electron-forge/issues/160 we should probably be more specific about this, since it can be an Object.

**Comment by jacobq** [comment]
I have Windows instances available so let me know if I can be any help.

**Comment by malept** [comment]
@jacobq I think this one doesn't absolutely require Windows instances, but if you're volunteering them, a) seeing if you can reproduce #590 and/or #597 and b) figuring out what's going on in either would be greatly appreciated 😅

**Comment by malept** [comment]
> About `CompanyName`: per electron-userland/electron-forge#160 we should probably be more specific about this, since it can be an Object.

The person who implements this should use the `parse-author` module like in electron-userland/electron-forge#161.
