### ISSUE TITLE
Failed to build Win32/Win64 version Linux

### ISSUE THREAD

**Issue by gameslayer** [electron-userland/electron-packager#613]
I am able to build every version exept for Win32 & Win64 version as it give me a error 

rcedit.exe failed with exit code 1. wine: /home/corey/.wine is not owned by you

How do I fix this issue?

**Comment by malept** [comment]
Sounds like you need to check the owner of the `/home/corey/.wine` folder and modify it to be, I assume, `corey`.

**Comment by gameslayer** [comment]
Nope the permissions are mine and didn't start happening until updates to Electron, Wine works fine also..

![screenshot 2017-03-08 17 06 16](https://cloud.githubusercontent.com/assets/8393780/23693746/b7ef8b1e-0421-11e7-8074-7d4c16093b78.png)

**Comment by gameslayer** [comment]
I also noticed after changing the rule from --all to --platform=all actually allows it to build the rest of the platforms besides Win32 & Win64 as well as it trying to build in /tmp and giving me permission errors forcing me to run my build script with sudo to build in the selected folder..

**Comment by malept** [comment]
If you have to use `sudo` to run Electron Packager, there's something odd about the permissions in your filesystem. Do you do anything strange like use NFS or some other network-based file system?

**Comment by gameslayer** [comment]
No I don't use NFS or anything with my file system it's been the same it's a Electron bug from the updated version while before the update everything was fine when building my electron apps.

**Comment by malept** [comment]
In order to help you with your problem, we're going to need more information about it. In particular:

* What version of Electron Packager were you using when this worked successfully? What version of Electron Packager are you using now?

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

**Comment by gameslayer** [comment]
Um not sure on what the last version was but I am using the current version of electron-packager for electron v1.6.1, how would I check?

the script I am currently using to build is this once I have cd into the folder:

electron-packager . --platform=all  --icon=node_modules/icon.png --overwrite ExampleApplication

**Comment by malept** [comment]
I assume you would use version control plus `npm list | grep electron-packager` to find the Packager version that last worked for you.

**Comment by gameslayer** [comment]
I figured out a fix by saving my files for the application, deleting node_modules, uninstalling nodejs and completely reinstalling nodejs and electron fixed the issue and can sucessfully build all version tho another minor bug is is none of the builds save any of the files or the files I put into it for the application to work for example index.html, png files for icon ect but placing all the files in there make it's it run properly
