### ISSUE TITLE
Cannot force install platform specific NPM dependency

### ISSUE THREAD

**Issue by sfyfe31** [electron-userland/electron-packager#615]
I'm making a cross-platform Electron app. When run on Windows, I need to inspect the registry, so I'm using [regedit](https://github.com/ironSource/node-regedit).

I'm doing my development on macOS, so in order to install and use the dependency for development, I had to run `npm i -f regedit --save`, in order to force it to install on the unintended platform.

However, when I then come to package my app, I get:
```
Error installing a Node dependency into the Electron Build Directory:

Error: Unsupported platform for regedit@2.2.6
```

I can't see anything in the API docs, which would allow me to force install any NPM dependencies during packaging. Is there a workaround for this? I assume I could do the packaging on Windows itself, but given that it is possible to force install with NPM's `-f` flag, I'd rather not have to do that.

**Comment by malept** [comment]
Does this error occur during the prune step?

**Comment by sfyfe31** [comment]
`Installing production dependencies into Electron Build Package`
