### ISSUE TITLE
rcedit unable to load file

### ISSUE THREAD

**Issue by GianlucaBortoli** [electron-userland/electron-packager#616]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

While packaging my application, `rcedit` fails and exits the whole procedure.

**Build machine**
The builds are run inside a clean VM using Jenkins, wiping out all the workspace of the job before doing anything else. The VM's characteristics and the installed software are the following: 
* Ubuntu 14.04 x64
* Java version: 1.8.0_101
* NodeJS v6.9.1
* NPM v4.2.0
* Wine 1.6.2

**Console output of electron-packager**

```
[31mError from `electron-packager` when building app...[0m
Error: rcedit.exe failed with exit code 1. Fatal error: Unable to load file
    at ChildProcess.<anonymous> (/home/agile-test/jenkins-agent/workspace/agile-configurator-win/node_modules/rcedit/lib/rcedit.js:60:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**The parameters passed to the `packager()` function**
```javascript
{
        arch: 'ia32',
        asar: process.env.APP_MODE !== 'debug',
        dir: path.join(__dirname, 'app'),
        icon: path.join(__dirname, 'app/icons/Agile'),
        ignore: new RegExp(ignoredModulesRegex),
        out: path.join(__dirname, 'builds'),
        overwrite: true,
        platform: process.env.PLATFORM_TARGET || 'all',
        'app-copyright': `Copyright (C) ${new Date().getFullYear()} Praim Srl`,
        name: 'name',
        productName: 'product',
        'build-version': '1.0.0.0',
        win32metadata: {
            CompanyName: 'company',
            InternalName: 'internal',
            OriginalFilename: 'executable.exe',
            FileDescription: 'description',
            ProductName: 'product'
        }
}
```

**More info**
This situation doesn't happen all the time. This means that, from time to time, the build fails unexpectedly and apparently for no reason, while the next one builds successfully without changing anything in the code of the application.
This is the reason why I choose to run the builds using Jenkins and inside an always clean workspace, but it seems not to be enough.

Any idea about what could cause this error?

**Comment by malept** [comment]
This code in rcedit causes the error: https://github.com/electron/rcedit/blob/b80739978f2fa3b0244784c21920aa72403563af/src/rescle.cc#L429-L433

It looks like the exe gets corrupted somehow?

**Comment by GianlucaBortoli** [comment]
I had a look ad that portion too, but I cannot think about a way that the exe gets corrupted

**Comment by GianlucaBortoli** [comment]
I recently changed the VM where the builds are run to achieve better I/O performances and the problem automagically disappeared (or at least none of the builds failed due to this in 10 days).
Probably the VMWare ESX hypervisor, which sometimes provided very low I/O speeds on disks, was the real problem.
Can this explain the problem I was seeing before?

**Comment by malept** [comment]
That is pretty likely. I'm closing this issue in that case.
