### ISSUE TITLE
Pack for another computer

### ISSUE THREAD

**Issue by miguelsmuller** [electron-userland/electron-packager#622]
Hello everyone..
I'm trying to run an app on a machine that has no node, has no npm, has no development tool but I can not.

I always get an error saying that there is no tool to run the app.

I'm using ubuntu.
My project is this one: [https://github.com/miguelsmuller/centro-de-estudos](https://github.com/miguelsmuller/centro-de-estudos)

**Comment by malept** [comment]
You can't run Electron Packager on a machine without Node, as it's written with Node and not a compiled language.

Your workflow should look like this:

1. Access a machine with Node installed
2. Install Electron Packager using the instructions in the readme
3. Run Electron Packager on your Electron app
4. Copy the output directory for the given platform/arch onto the machine without Node that you wish to run your Electron app
5. Run your Electron app

**Comment by miguelsmuller** [comment]
That's exactly what I did. However, on the machine that needs to run the app, the following error occurs.


![captura de tela de 2017-03-21 13-33-10](https://cloud.githubusercontent.com/assets/4589909/24158474/3775472a-0e3b-11e7-86b0-bc6297ae08cb.png)

As the text is in pt-br translated it would look something like this:

> It was not possible to display "centro-de-estudos".
> There is no application installed for the executable files.
> Do you want to search for an application that can open these files?

**Comment by malept** [comment]
Are you trying to run it from a FAT32 formatted drive? It sounds like the executable doesn't actually have executable permissions.

**Comment by miguelsmuller** [comment]
Yes. It was permission problem. Thanks a lot for the help @malept.
