### ISSUE TITLE
Override default ignores

### ISSUE THREAD

**Issue by gerhardberger** [electron-userland/electron-packager#623]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I've seen that not so long ago `.o` and `.obj` files have become ignored by default. However I couldn't find a way to override these ignores, because my app needs `.obj` files.

Is there any way to achieve this? If not, I would be happy to contribute some functionality to override or disable the default ignores in some way.

**Comment by malept** [comment]
There's a way to do this listed in the [API docs](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore):

> Alternatively, [the `ignore` parameter] can be a predicate function that, given an absolute file path, returns `true` if the file should be ignored, or `false` if the file should be kept. _This does not use any of the default ignored directories listed above._

Obviously, you can't do this on the command line. If you don't want to write our own build script, you can use [Electron Forge](https://github.com/electron-userland/electron-forge) (which uses Electron Packager), and then use the JS file config method listed in the Forge docs.
