### ISSUE TITLE
'can't find module sqlite3' in the publish app that used electron-packager,but does well in development environment

### ISSUE THREAD

**Issue by Sindcs** [electron-userland/electron-packager#624]
* [ ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
when i use 'sqlite3' in electron i have rebuilt it success and use it success in developmet environmet,but when i use electron-package to pack the app,the app does't get well when run the 'sqlite3',it show the wrong 'can't find module sqlite3 '.but i run it well in development.what shoul i do to slove this problem.thanks 

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

cant't find module 'sqlite3'
error

Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by AlyxMoon** [comment]
I think I'm running into a similar issue here. My problem is that I have a nested dependency being left out when I package my app. I've only noticed one so far however.

The module causing problems is `request`, once packaged it is missing its dependency `form-data`. As far as I've been able to tell, no other dependencies by anything else are being left out, just this.

Dependencies listed in my package.json:
```
  "devDependencies": {
    "babel-core": "^6.14.0",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.23.0",
    "chai": "^3.5.0",
    "chai-immutable": "^1.6.0",
    "css-loader": "^0.27.3",
    "electron": "^1.6.2",
    "electron-packager": "^7.4.0",
    "ignore-styles": "^5.0.1",
    "jsdom": "^9.12.0",
    "mocha": "^3.2.0",
    "mocha-standard": "^1.0.0",
    "node-sass": "^4.5.1",
    "react-addons-test-utils": "^15.4.2",
    "sass-loader": "^6.0.3",
    "sinon": "^2.0.0",
    "standard": "^9.0.2",
    "style-loader": "^0.16.0",
    "webpack": "^2.3.1",
    "webpack-dev-server": "^2.4.2"
  },
  "dependencies": {
    "immutable": "^3.8.1",
    "electron-json-storage": "^3.0.4",
    "jszip": "^3.1.1",
    "moment": "^2.18.1",
    "react": "^15.4.2",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-bootstrap": "^0.30.8",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.3",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "redux": "^3.6.0",
    "request": "^2.74.0"
  }
```

My script to package (I have one for each OS where only platform flag is different. All OS packages are being affected):
```
electron-packager . --overwrite --prune=true --platform=win32 --arch=all --out=dist --icon=assets/icons/icon.ico --ignore=assets --ignore=test --ignore=src --ignore=data/* --ignore=.gitignore --ignore=README.md
```

If relevant, here are the dependencies listed in the `request` module, while `form-data` is indeed listed its being left out in the package:
```
    "aws-sign2": "~0.6.0",
    "aws4": "^1.2.1",
    "caseless": "~0.12.0",
    "combined-stream": "~1.0.5",
    "extend": "~3.0.0",
    "forever-agent": "~0.6.1",
    "form-data": "~2.1.1",
    "har-validator": "~4.2.1",
    "hawk": "~3.1.3",
    "http-signature": "~1.1.0",
    "is-typedarray": "~1.0.0",
    "isstream": "~0.1.2",
    "json-stringify-safe": "~5.0.1",
    "mime-types": "~2.1.7",
    "oauth-sign": "~0.8.1",
    "performance-now": "^0.2.0",
    "qs": "~6.4.0",
    "safe-buffer": "^5.0.1",
    "stringstream": "~0.0.4",
    "tough-cookie": "~2.3.0",
    "tunnel-agent": "^0.6.0",
    "uuid": "^3.0.0"
```

**Comment by MarshallOfSound** [comment]
@AlyxMoon Can you share your electron package config 👍

**Comment by AlyxMoon** [comment]
@MarshallOfSound Sorry I'm not entirely sure what you mean by that, can you clarify?

**Comment by MarshallOfSound** [comment]
@AlyxMoon Either the object you pass to the Electron Packager API or the CLI args you pass to it

**Comment by AlyxMoon** [comment]
@MarshallOfSound  Sure, I run it as a script through npm.
```
"package:win": "electron-packager . --overwrite --prune=true --platform=win32 --arch=all --out=dist --icon=assets/icons/icon.ico --ignore=assets --ignore=test --ignore=src --ignore=data/* --ignore=.gitignore --ignore=README.md"
```

**Comment by MarshallOfSound** [comment]
@AlyxMoon I'm like 99% sure you've just got a rogue ignore 👍 In particular this one `--ignore=src` will ignore all src directories in the tree, not just your top level one 👍 

You probably need a more precise ignore regexp.  Try removing all your ignores and seeing if the app works 👍

**Comment by AlyxMoon** [comment]
@MarshallOfSound Indeed that did the trick.

Well, sorry for butting in on this thread then. I don't know if this is what was causing OP's problem, but overzealous ignores was causing the issue for me, I hadn't considered that the ignore flag would cause problems with things in node_modules.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

**Comment by ccpwcn** [comment]
I have this error too.
Say it again: In development mode, it's running well, after electron-packager packeged, cannot find module sqlite3

**Comment by mizozobu** [comment]
In my case, it was `--asar`. As soon as removed it, it all worked fine.

**Comment by malept** [comment]
You cannot use native modules and asar at the same time without using `--asar.unpackDir` (via the CLI).
