### ISSUE TITLE
return promise

### ISSUE THREAD

**Issue by jimmywarting** [electron-userland/electron-packager#627]
so we can use async/await instead of callback

**Comment by malept** [comment]
It's kind of a big undertaking to convert the entire project to do so. In the meantime, you can use the [pify](https://www.npmjs.com/package/pify) module, which is what [Electron Forge](https://github.com/electron-userland/electron-forge) uses to interact with Packager.

**Comment by malept** [comment]
This would also be a breaking change and thus require a major version bump.

**Comment by jimmywarting** [comment]
It doesn't have to be a breaking change if there is no callback return a promise instead of calling the callback so you can do both

**Comment by malept** [comment]
This is a breaking change because other users might rely on the existing behavior. [`fs-extra`](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#300--2017-04-27) recently underwent a major version bump to do the same thing.
