### ISSUE TITLE
Send packaged app via Email

### ISSUE THREAD

**Issue by Bharwcb** [electron-userland/electron-packager#629]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Command line arguments**

```
electron-packager . --overwrite myApp --platform=darwin --arch=x64
```

Just trying to figure out how to send this app via email.. Gmail does not let me attach it.  Thank you in advance!

**Comment by malept** [comment]
You would zip up the `myApp-darwin-x64` out directory and then attach that zip file.

**Comment by Bharwcb** [comment]
Thanks @malept .. really appreciate it.

**Comment by Bharwcb** [comment]
Actually @malept, do you have any experience in errors after sending a packaged electron app?

I'm getting a`EROFS: read-only file system, mkdir '/private/var/folders/.../myApp.app/Contents/Resources/app' at Object.fs.mkdirSync`

So something about sending the packaged app does not allow the `mkdirSync` function to run.

**Comment by malept** [comment]
I'm not a macOS expert, but if I had to guess, it's one of two things:

* You're trying to run an app directly from the email, instead of saving it somewhere first. I can't imagine macOS lets you do that.
* macOS sandboxing is preventing you from doing that.

**Comment by MarshallOfSound** [comment]
@Bharwcb That error is because on newer version of macOS gatekeeper launches your app in a virtual read only file system area.  So you can't write to `__dirname` or `app.getPath()` or anything like that.  All files should be written to `os.tmpdir()` or you get that error 👍
