### ISSUE TITLE
Packaged dependencies are invalid

### ISSUE THREAD

**Issue by tkggusraqk** [electron-userland/electron-packager#632]
[electron package setting](http://i4.buimg.com/4851/2fb769c9edd48474.png)
[err module](http://i4.buimg.com/4851/5cb541962a0ed958.png)

--prune = false is invalid

**Comment by MarshallOfSound** [comment]
@tkggusraqk Can you post your package.json file 👍

**Comment by tkggusraqk** [comment]
@MarshallOfSound 
{
  "name": "weichat",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "start": "electron .",
    "packager": "electron-packager ./app WKF --platform=win32 --out=./Outapp --version 1.0.0 --asar=true --prune=false --overwrite --icon=./app/logo.ico"
  },
  "author": "cxj",
  "license": "ISC",
  "devDependencies": {
    "asar": "^0.13.0",
    "electron": "^1.6.2",
    "electron-packager": "^8.6.0",
    "gulp": "^3.9.1",
    "serial-number": "^1.3.0",
    "getmac": "^1.2.1"
  }
}
Above the hyperlink also, the first is

**Comment by MarshallOfSound** [comment]
> "serial-number": "^1.3.0",

Your dependency is in `devDependencies` so it will be removed automatically in production.  Move it to the `dependencies` section and it will persist during production packaging

**Comment by tkggusraqk** [comment]
@MarshallOfSound 

{
  "name": "weichat",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "start": "electron .",
    "packager": "electron-packager ./app WKF --platform=win32 --out=./Outapp --version 1.0.0 --asar=true --prune=false --overwrite --icon=./app/logo.ico"
  },
  "author": "cxj",
  "license": "ISC",
  "devDependencies": {
    "asar": "^0.13.0",
    "electron": "^1.6.2",
    "electron-packager": "^8.6.0",
    "gulp": "^3.9.1",
    "serial-number": "^1.3.0",
    "getmac": "^1.2.1"
  },
  "dependencies":{
    "serial-number": "^1.3.0",
    "getmac": "^1.2.1"
  }
}

Is that right? But it is not right

**Comment by MarshallOfSound** [comment]
Don't have it in both, you only want it in `dependencies`

For more info check out the `package.json` spec https://docs.npmjs.com/files/package.json

**Comment by tkggusraqk** [comment]
@MarshallOfSound 
{
  "name": "weichat",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "start": "electron .",
    "packager": "electron-packager ./app WKF --platform=win32 --out=./Outapp --version 1.0.0 --asar=true --overwrite --icon=./app/logo.ico"
  },
  "author": "cxj",
  "license": "ISC",
  "devDependencies": {
    "asar": "^0.13.0",
    "electron": "^1.6.2",
    "electron-packager": "^8.6.0",
    "gulp": "^3.9.1" 
  },
  "dependencies":{
    "serial-number": "1.3.0",
    "getmac": "1.2.1"
  }
}
But still not

**Comment by MarshallOfSound** [comment]
@tkggusraqk Just changing the package.json won't fix it for you, you will need to rerun `npm install` and `npm run packager`

**Comment by tkggusraqk** [comment]
@MarshallOfSound 
Npm install do not understand, modify I re-run the npm run-script packager

**Comment by MarshallOfSound** [comment]
@tkggusraqk Are you by any chance using a two package json structure?

**Comment by tkggusraqk** [comment]
@MarshallOfSound 
{
  "name": "weichat",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "start": "electron .",
    "packager": "electron-packager ./app WKF --platform=win32 --out=./Outapp --version 1.0.0 --asar=true --overwrite --icon=./app/logo.ico --ignore=node_modules/electron-* --ignore=node_modules/.bin --ignore=.git --ignore=dist --prune"
  },
  "author": "cxj",
  "license": "ISC",
  "devDependencies": {
    "asar": "^0.13.0",
    "electron": "^1.6.2",
    "electron-packager": "^8.6.0",
    "gulp": "^3.9.1"
  },
  "dependencies": {
    "getmac": "^1.2.1",
    "serial-number": "1.3.0"
  }
}
Not too understand what you mean, and now the configuration is correct, how can we do the following package into the package
thank you very much
