### ISSUE TITLE
Unable to set icon on Linux target

### ISSUE THREAD

**Issue by DavisDevelopment** [electron-userland/electron-packager#635]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

I'm building on Ubuntu 16.04 for x64, and while simply running the app will show the icon just fine, the icon once packaged is always the electron icon. I have verified that the icon path is a valid one.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
  electron-packager Electron Packager 8.6.0 +0ms
  electron-packager Node v7.7.3 +2ms
  electron-packager Host Operating system: linux (x64) +0ms
  electron-packager Packager Options: {"name":"pman","appname":"pman","arch":"x64","platform":"linux","icon":null,"version":"1.6.5","dir":"/home/ryan/Documents/Development/bplayer4/dist","sourcedir":"/home/ryan/Documents/Development/bplayer4/dist","out":"/home/ryan/Documents/Development/bplayer4/dist/releases","overwrite":true,"asar":false,"prune":true,"app_version":null,"afterCopy":[null],"afterExtract":[]} +0ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +1ms
WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead
  electron-packager Inferring appVersion from version in /home/ryan/Documents/Development/bplayer4/dist/package.json +9ms
  electron-packager Application name: pman +0ms
  electron-packager Target Electron version: 1.6.5 +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"1.6.5"} +4ms
Packaging app for platform linux x64 using electron v1.6.5
  electron-packager Creating /tmp/electron-packager/linux-x64-template +319ms
  electron-packager Extracting /home/ryan/.electron/electron-v1.6.5-linux-x64.zip to /tmp/electron-packager/linux-x64-template +1ms
  electron-packager Initializing app in /tmp/electron-packager/linux-x64/pman-linux-x64 from /tmp/electron-packager/linux-x64-template template +1s
  electron-packager Ignored paths based on the out param: +1ms [ '/home/ryan/Documents/Development/bplayer4/dist/releases' ]
  electron-packager Running npm prune --production +3s
  electron-packager Renaming electron to pman in /tmp/electron-packager/linux-x64/pman-linux-x64 +5s
  electron-packager Moving /tmp/electron-packager/linux-x64/pman-linux-x64 to /home/ryan/Documents/Development/bplayer4/dist/releases/pman-linux-x64 +0ms
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

I'm using the API, but my options argument is generated programmatically and is thus pretty tricky to post here. I've resorted to simply not setting the 'icon' property.  The only reason I'm posting the issue here is that the icon works fine before I package the app, so I'm pretty sure it must be an issue with electron-packager and not with electron. Is there any way I could fix this, or is there some magical way to set the icon post-packaging that will work? The icon works everywhere else.

**Comment by DavisDevelopment** [comment]
I've since discovered that the icon does work once the app is installed via an installer created using electron-installer-debian, so I guess the issue is of low priority to me. Regardless, it does still seem to be a problem

**Comment by malept** [comment]
Thanks for filing a bug, but this flag is not used when you are building for Linux targets. From the [API docs for `--icon`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon):

> this option is not required, as the dock/window list icon is set via [the `icon` option in the `BrowserWindow` constructor](http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions). _Please note that you need to use a PNG, and not the OS X or Windows icon formats, in order for it to show up in the dock/window list._ Setting the icon in the file manager is not currently supported.

**Comment by DavisDevelopment** [comment]
Yes, I found that in the docs, which lead me to remove the flag. However, it's only when using electron-packager that my app's icon doesn't show up. This would indicate a problem, no?

**Comment by malept** [comment]
It doesn't actually do anything, though. What you're seeing with electron-installer-debian is that you're loading the Electron app via a .desktop file and the window manager is using the icon referenced there. If the icon doesn't show up when you don't use the .desktop file, I would consider that a bug in Electron, not Electron Packager.

**Comment by DavisDevelopment** [comment]
Ah, I didn't even think about the .desktop file. The icon, however, does show up when run with electron directly. It only fails after the app has been packaged

**Comment by malept** [comment]
Without looking at your code, I would guess that in the constructor, you're using a relative icon path instead of a path joined against `__dirname`.

**Comment by DavisDevelopment** [comment]
Nope, the path is absolute, joined against the path retrieved from `app.getAppPath`

**Comment by malept** [comment]
I would see what the path returned with `app.getAppPath` is and then see if the path you created for the icon actually exists.

**Comment by zxdong262** [comment]
same issue, solved with ` --icon` option,  

```js
exec(`${bin}/electron-installer-debian --src ${dir}/${name}-linux-x64 --dest ${dir}/installers/ --arch amd64 --icon ${dir}/${name}-linux-x64/resources/app/static/images/electerm-round-128.png`)
```

and I have set the icon option too, but without the `--icon` option will not work.
```js
  // Create the browser window.
  win = new BrowserWindow({
    width,
    height,
    fullscreenable: true,
    //fullscreen: true,
    icon: resolve(__dirname, 'static/images/electerm-round-128.png')
  })
```

```js
    "electron": "1.7.8",
    "electron-builder": "19.22.1",
```
