### ISSUE TITLE
root package.json not found when specifying different src directory

### ISSUE THREAD

**Issue by igloo15** [electron-userland/electron-packager#636]
Electron Version: 1.6.5
Electron Packager Version : 8.6.0
Node Version: 6.4.0
NPM Version: 3.10.3

I am using electron-packager with webpack. Essentially building my app with webpack to an output folder called dist and then calling electron-packager. I want to be able to call it like: electron-packager dist 
but it always fails saying there is no package.json. Obviously there is no package.json in the dist folder but there is an package.json in the root of the project one folder up. 

If I copy my package.json from the root into the dist folder and try again it works fine but barring that it will fail. Is there anyway to do this without copying the package.json. Ideally I would like electron-packager to take the root package.json and the code in the dist folder and produce a electron package. 

Project Structure

```
|-root
     |-dist
          |-app.js
          |-index.html
     |-node_modules
     |-src
         |-<source code>
     |-webpack.js
     |-package.json

```
electron-packager .         -   works (but copies everything in root level)
electron-package dist  -   fails

**Comment by MarshallOfSound** [comment]
The structure you have described can easily be achieved with the current options.

You want to set the "main" value in your package.json file to point at the generated entry point (your DIST folder) then set up the --ignore CLI argument or the ignore option in the API to ignore all files in the original src directory 👍

**Comment by mulles3008** [comment]
Hi, my folder structure differs slightly from the one outlined by @igloo15.

`electron/main.js` represents the entry point to the electron-apps. `main.js` loads my `index.html` that in turn includes the `bundle.js`. 

```
|-root
     |-native
     |-web
          |-public
               |-index.html
               |-bundle.js
     |-electron
         |-package.json
         |-main.js
         |-out
               |-<generated electron app>
     |-src
         |-<source code>
     |-package.json
```

This works fine when running electron locally.
However with electron-packager, `index.html`and `bundle.js` (in fact the whole `web/` folder) are not getting included into the generated app, and are hence not resolvable at runtime:

`Not allowed to load local resource: file:///<PROJECT_ROOT>/electron/out/MyApp.io-darwin-x64/MyApp.io.app/Contents/Resources/web/public/index.html`

Is there a way to solve this without having to move/duplicate my `index` and `bundle` files into the `electron` folder? Are there some configurations that I'm missing?

Thanks a lot

**Comment by dland512** [comment]
@MarshallOfSound, I'm having this exact same problem but I can't quite figure out how to implement your suggestion. Would you mind maybe listing out the full CLI command with the folder structure from @igloo15 or mine, which is

```
|-root
     |-build
          |-main.bundle.js
          |-renderer.bundle.js
          |-index.html
     |-node_modules
     |-app
         |-<source code>
     |-webpack.js
     |-package.json
```

My `package.json` contains

    "main": "build/main.bundle.js"

I tried running this

    electron-packager build --ignore='\.\/app\/*\.*'

but I get the error about not being able to find the `package.json` file:

> npm ERR! enoent ENOENT: no such file or directory, open '/private/var/folders/2k/pgyx4y5s0kxghmdmkbcj5xqw0000gn/T/electron-packager/darwin-x64/slot-compass-darwin-x64/Electron.app/Contents/Resources/app/package.json'

Like @igloo15 said, if I copy the `package.json` file into the `build` folder it works.

**Comment by malept** [comment]
The app directory that you specify in Electron Packager is assumed to have the `package.json` at its root. Seems like what you want is to copy `package.json` into your build directory at the same time you generate your webpack bundles _(although I'm not sure why you'd want to use webpack for an Electron app...)_.

**Comment by dland512** [comment]
Got it, thanks.
