### ISSUE TITLE
Add extraResource support for Windows/Linux targets

### ISSUE THREAD

**Issue by devildant** [electron-userland/electron-packager#637]
Hello,
i try to copy the binary outside asar, i launch this commande line : 
`electron-packager . --out=compiledBinary/win --platform=win32 --arch=ia32 --extraResource=\"aria2\" --asar=true`

when i go to compiledBinary/win/application/Resources i don't have the folder aria2
but i try to generate for osx it's work perfectly

could you help me ?
it's a bug ?
best regards

**Comment by devildant** [comment]
i look your sources code electron-packager/win32.js and i don't see the extra resource option

**Comment by devildant** [comment]
I temporarily added this command to solve the problem
`cp -r aria2 compiledBinary/win/*/resources/`

**Comment by malept** [comment]
Per the documentation, it has only been implemented for the darwin/mas targets. I would happily review a pull request to add this functionality to Windows (and Linux) targets, assuming that the request also includes documentation and sufficient tests.

**Comment by malept** [comment]
Also, it's quite odd that `--extraResource` worked.
