### ISSUE TITLE
Unable to determine application name when using electron-packager-interactive

### ISSUE THREAD

**Issue by toebber** [electron-userland/electron-packager#639]
Hi
I am getting the above error when i try to package my app. 
Have been searching around for hours, haven't been able to solve my problem.

My package.json looks like this

{
  "name": "Index",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^1.4.3"
  }
}

This is from terminal:

? Overwrite output directory ? Yes
? Use asar source packaging ? No
? Select Electron app source directory: /Users/torbenpoulsen/github/eApp
? Select Electron app output directory: /Users/torbenpoulsen/github/releases
? Select Application name: WeedIndex
? Select App Bundle Id (optional): 
? Select App Version(optional): 1.0.0
? Select Electron icon file: 
? Select Electron version release: 1.4.3
? Select platforms: 
? Select architecture: 
! No arch specified, defaulting to x64
! No platform specified, defaulting to darwin
Electron packager settings:
{ dir: '/Users/torbenpoulsen/github',
  name: '',
  platform: null,
  arch: null,
  version: '1.4.3',
  out: '/Users/torbenpoulsen/github/releases',
  'app-bundle-id': '',
  'app-version': '',
  overwrite: true,
  asar: false,
  icon: '',
  app_version: '1.0.0',
  bundle_id: '',
  appname: 'Index',
  sourcedir: '/Users/torbenpoulsen/github/eApp',
  ignore: '/Users/torbenpoulsen/github/releases' }
WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead
WARNING: The app-version parameter is deprecated when used from JS, use appVersion instead. It will be removed in the next major version.
WARNING: The app-bundle-id parameter is deprecated when used from JS, use appBundleId instead. It will be removed in the next major version.

✗ Error: Unable to determine application name. Please specify an application name

For more information, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#name

Unable to determine [Unknown Property]. Please specify an [Unknown Property]

For more information, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#

**Comment by malept** [comment]
There's something pretty wrong here:

```
{ dir: '/Users/torbenpoulsen/github',
name: '',
```

I'm assuming your `package.json` file is in `/Users/torbenpoulsen/github/eApp/package.json`. I would file a bug in the [`electron-packager-interactive` project](https://github.com/Urucas/electron-packager-interactive). I say this because it's passing a blank string to name, and the wrong directory to `dir` (which should be the directory where your `package.json` is), even though  you specified the source directory.

**Comment by toebber** [comment]
Hi Malept. 
Thanks for answer.

Yes my package.json is in specified folder.
Can't it be because i have installed the app wrong or something. I am very new to programming, so i always assume error is on my side? :)

**Comment by malept** [comment]
I don't see an error on your side, although I'm not too familiar with how electron-packager-interactive works. As I suggested in my earlier comment, you should file an issue in that repository.
