### ISSUE TITLE
Unable to find a valid app

### ISSUE THREAD

**Issue by vonch** [electron-userland/electron-packager#640]
sorry,English not well!

the project in production is ok, but not work after electron-packager.

open the packager app alert error

![image](https://cloud.githubusercontent.com/assets/1905760/25552886/cd25a854-2cd7-11e7-984d-a216da958b41.png)

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* What does your `package.json` look like? Does the file referenced in the `main` key exist?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by vonch** [comment]
the project is yours [electron-quick-start](https://github.com/electron/electron-quick-start) 
I dont modify anything.

"packsge.json"

{
  "name": "your-app",
  "version": "0.1.0",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "packager": "electron-packager ./app HelloWorld --all --out ./OutApp --electron-version 1.6.6 --overwrite --icon=./logo.ico --download.mirror=https://npm.taobao.org/mirrors/electron/"
  },
  "devDependencies": {
    "electron-packager": "^8.6.0",
    "electron-prebuilt": "^1.4.13"
  }
}

**Comment by malept** [comment]
It looks like you did modify it if your source directory is in `./app` as your packager command indicates.

Is there an `app/package.json` or something?

**Comment by vonch** [comment]
main.js

const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')

// 保持一个对于 window 对象的全局引用，如果你不这样做，
// 当 JavaScript 对象被垃圾回收， window 会被自动地关闭
let win

function createWindow () {
  // 创建浏览器窗口。
  win = new BrowserWindow({width: 800, height: 600})

  // 加载应用的 index.html。
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

  // 打开开发者工具。
  // win.webContents.openDevTools()

  // 当 window 被关闭，这个事件会被触发。
  win.on('closed', () => {
    // 取消引用 window 对象，如果你的应用支持多窗口的话，
    // 通常会把多个 window 对象存放在一个数组里面，
    // 与此同时，你应该删除相应的元素。
    win = null
  })
}

// Electron 会在初始化后并准备
// 创建浏览器窗口时，调用这个函数。
// 部分 API 在 ready 事件触发后才能使用。
app.on('ready', createWindow)

// 当全部窗口关闭时退出。
app.on('window-all-closed', () => {
  // 在 macOS 上，除非用户用 Cmd + Q 确定地退出，
  // 否则绝大部分应用及其菜单栏会保持激活。
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // 在这文件，你可以续写应用剩下主进程代码。
  // 也可以拆分成几个文件，然后用 require 导入。
  if (win === null) {
    createWindow()
  }
})

// 在这文件，你可以续写应用剩下主进程代码。
// 也可以拆分成几个文件，然后用 require 导入。




and


![image](https://cloud.githubusercontent.com/assets/1905760/25561897/04e738f4-2da8-11e7-97e6-3c1b496fe67e.png)

**Comment by malept** [comment]
Your source directory needs to be `.`, not `./app`. The `main.js` file isn't being packaged, that's why it's not working.
