### ISSUE TITLE
When express is a dependency in package.json, will it run if user does not have NodeJS installed, or is it self contained?

### ISSUE THREAD

**Issue by kgrosvenor** [electron-userland/electron-packager#641]
Sorry that this isn't an issue, just wondering if anyone could give me a quick answer 💯 

* [ ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
First, you should probably ask whether you actually need to use express. I don't think there are that many use cases where you wouldn't be able to use Node code directly. _(Insert [caveats about security](https://electron.atom.io/docs/tutorial/security/) here.)_

If you do decide to use it, you'll need to fork the express process yourself when you run the Electron app. I'm not entirely clear on how to do it personally, but I'm sure if you ask your question in one of the [Electron community forums](https://github.com/electron/electron#community), you'll get an answer.
