### ISSUE TITLE
Programmatic API should use `protocols`, not `protocol` and `protocolName`

### ISSUE THREAD

**Issue by TasukuUno** [electron-userland/electron-packager#643]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

--

Hi, I rewrote my gulpfile from one using [command line API](https://github.com/electron-userland/electron-packager/blob/v8.6.0/usage.txt) via gulp-shell to  one using [Programmatic API](https://github.com/electron-userland/electron-packager/blob/v8.6.0/docs/api.md). And I found that there are no `CFBundleURLName` `CFBundleURLSchemes` in Info.plist in the Mac app and the custom URL scheme is not working.
I think `protocol` and `protocolName` should be an array named `protocols` like following:

```js
[
  { schemes: [ 'sample' ], name: 'nameOfSample' }
]
```

I'm not sure which of [docs](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#protocol) or [code runs only on command line](https://github.com/electron-userland/electron-packager/blob/v8.6.0/common.js#L49-L53) should be fixed. But I will be very happy if you fix this!

**Comment by malept** [comment]
I will gladly review a proposal to unify the protocol options. However, it needs to work with the CLI without a lot of hackery, because that is not a maintainable solution. I do not want to have to maintain two different docs *just* for specifying protocols between API and CLI.

This will obviously also require a major version bump, due to the API change.

**Comment by malept** [comment]
Sigh. Apparently the programmatic API has used `protocols` for a while now.
