### ISSUE TITLE
tmpdir troubles due to extract-zip changes

### ISSUE THREAD

**Issue by avoidwork** [electron-userland/electron-packager#644]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Over the weekend my enterprise app builds failed due to dependencies of this project changing, which shouldn't affect my builds because they were locked on 7.0.4.

The `--tmp` flag changed/broke in one of the dependencies, but by simply removing `--tmpdir=tmp` it works. The build scripts for my* application have been stable for over a year.

```
Put the console output here
```

```console
Packaging app for platform darwin x64 using electron v1.4.16
fs.js:582
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'tmp/electron-packager/darwin-x64/Adobe Hub-darwin-x64/Electron.app/Contents/Info.plist'
    at Object.fs.openSync (fs.js:582:18)
    at Object.fs.readFileSync (fs.js:489:33)
    at buildMacApp (/Users/jamullig/Projects/nc-client/node_modules/electron-packager/mac.js:71:37)
    at /Users/jamullig/Projects/nc-client/node_modules/electron-packager/common.js:225:7
    at end (/Users/jamullig/Projects/nc-client/node_modules/run-series/index.js:8:15)
    at done (/Users/jamullig/Projects/nc-client/node_modules/run-series/index.js:11:10)
    at each (/Users/jamullig/Projects/nc-client/node_modules/run-series/index.js:16:43)
    at next (/Users/jamullig/Projects/nc-client/node_modules/rimraf/rimraf.js:74:7)
    at CB (/Users/jamullig/Projects/nc-client/node_modules/rimraf/rimraf.js:110:9)
    at /Users/jamullig/Projects/nc-client/node_modules/rimraf/rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:114:15)
```

```
Put the arguments or parameters here
```

`electron-packager ./build \"Adobe Hub\" --tmpdir=tmp --out=dist/osx --platform=darwin --arch=x64 --version=1.4.16 --icon=assets/icons/adobehub.icns --app-version=$npm_package_version`

**Comment by avoidwork** [comment]
When I remove `--tmpdir`...

```console
> electron-packager ./build "Adobe Hub" --out=dist/osx --platform=darwin --arch=x64 --version=1.4.16 --icon=assets/icons/adobehub.icns --app-version=$npm_package_version

Packaging app for platform darwin x64 using electron v1.4.16
Wrote new app to dist/osx/Adobe Hub-darwin-x64
```

**Comment by malept** [comment]
The dependency `extract-zip` changed over the weekend, which broke Electron Packager in a couple of ways. If you want to continue to use `--tmpdir`, you have two options:

* Upgrade to the unreleased 8.7.0 (master as of https://github.com/electron-userland/electron-packager/commit/a699abe3f531f6f7876618f4729a144057609917), which should fix `--tmpdir=tmp` in addition to `--tmpdir=false` (I just only noticed the latter failed the tests). I am trying to release 8.7.0 sometime within the next 24 hours, although I can't guarantee anything.
* Lock `extract-zip` to version 1.6.0.

**Comment by avoidwork** [comment]
@malept I think you misunderstand; your package.json files are seriously flawed for builds. If every dep is ^ than versioning electron-packager has no real impact other than adding or removing deps.

7.0.4 should not be using the same deps as 8.x, that's a major version difference (breaking change).

**Comment by malept** [comment]
That's a problem with upstream, if they had adhered to semver correctly there wouldn't have been a problem.

**Comment by avoidwork** [comment]
@malept no, that's a problem in your package.json because you're not locking to minor updates, and instead are taking major updates. you're doing semver wrong via these keys:

```
"dependencies": {
    "asar": "^0.13.0",
    "debug": "^2.2.0",
    "electron-download": "^4.0.0",
    "electron-osx-sign": "^0.4.1",
    "extract-zip": "^1.0.3",
    "fs-extra": "^2.0.0",
    "get-package-info": "^1.0.0",
    "minimist": "^1.1.1",
    "plist": "^2.0.0",
    "rcedit": "^0.8.0",
    "resolve": "^1.1.6",
    "run-series": "^1.1.1",
    "sanitize-filename": "^1.6.0",
    "semver": "^5.3.0"
  },
  "devDependencies": {
    "buffer-equal": "^1.0.0",
    "coveralls": "^2.11.6",
    "eslint": "^3.2.0",
    "eslint-config-standard": "^7.0.0",
    "eslint-plugin-promise": "^3.0.0",
    "eslint-plugin-standard": "^2.0.0",
    "eslint-plugin-tape": "^1.1.0",
    "nyc": "^10.0.0",
    "pkg-up": "^1.0.0",
    "rimraf": "^2.3.2",
    "run-waterfall": "^1.1.1",
    "tape": "^4.0.0",
    "which": "^1.2.14"
  },
```

^ that's this project. you're taking breaking changes spanning major versions of electron-packager.

**Comment by malept** [comment]
We are not taking major version updates without explicitly updating the version number in `package.json`. Please give a specific example of a dependency that changed major versions, *without* the version number changing in `package.json`.

**Comment by avoidwork** [comment]
I don't think you understand semver or npm; your package.json takes the latest version of every dep/dev dep regardless of your intention. Nothing is locked to a minor, via ~ so if tape released 6.0.0 tomorrow both 7.x & 8.x of electron-packager would install tape 6.0.0 on next `npm install`

This means that my CI pipeline is changing each build. That's not how you use semver.

**Comment by malept** [comment]
OK, let's test your assertion. Please tell me what versions of `rcedit` and `fs-extra` your Electron Packager is running. Also, which version of NPM are you running?

**Comment by avoidwork** [comment]
I explained it wrong, ^ is up to the next major version so your assertion is true; the issue is in the extract-zip which is equal in both 7 & 8 fresh installs.

rcedit is 0.5.4 in 7.0.4 & 0.7.0 in 8.0.0
fs-extra is 0.28.0 in 7.0.4 & 0.30.0 in 8.0.0
extra-zip is 1.6.5 in both

**Comment by avoidwork** [comment]
however, i remain firm that ^ is not the ideal operator to rely on from a deterministic pov. taking unknown new features is not ideal for an enterprise app; using ~ limits it to patches which is ideal.

**Comment by malept** [comment]
As you've mentioned, Electron Packager requires `extract-zip` 1.x.x, which would normally be fine, because according to semver, minor versions should only have feature additions that do not contain breaking changes. However, there was a change between `extract-zip` versions 1.6.0 and 1.6.1 (a patch version, mind you) which caused the breakage. So in this case, even limiting to patch version upgrades wouldn't have prevented this.

What I would suggest that you do is either use [npm-shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) or switch to Yarn, with its `yarn.lock` file.

**Comment by avoidwork** [comment]
@malept yes, except in this case 7.0.4 of electron-packager could've been using extra-zip 1.0.x instead of 1.x.x which would have avoided the problem entirely; based on the issues of extra-zip it looks like 7.x of electron-packager will be broken unless release 7.0.5 putting ^ to ~; that'd solve my build problems.

Please consider this change going forward, as the impact on enterprise apps can be significant compared to small projects someone might spin up in their spare time.

**Comment by malept** [comment]
I don't plan on backporting bugfixes to previous major/minor versions of Electron Packager. That's a lot of effort given that I don't get paid to work on this. My position on the current situation is that shrinkwrap/yarn exist to lock dependencies for apps which need to have deterministic builds, regardless of whether upstream developers make mistakes with semver.
