### ISSUE TITLE
Non-deterministic builds due to package.json using ^ instead of ~ broke my stable builds

### ISSUE THREAD

**Issue by avoidwork** [electron-userland/electron-packager#645]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Over the weekend my enterprise app builds failed due to dependencies of this project changing, which shouldn't affect my builds because they were locked on 7.0.4.

The `--tmp` flag changed/broke in one of the dependencies, but by simply removing `--tmpdir=tmp` it works. The build scripts for my* application have been stable for over a year.

```
Put the console output here
```

```console
Packaging app for platform darwin x64 using electron v1.4.16
fs.js:582
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'tmp/electron-packager/darwin-x64/Adobe Hub-darwin-x64/Electron.app/Contents/Info.plist'
    at Object.fs.openSync (fs.js:582:18)
    at Object.fs.readFileSync (fs.js:489:33)
    at buildMacApp (/Users/jamullig/Projects/nc-client/node_modules/electron-packager/mac.js:71:37)
    at /Users/jamullig/Projects/nc-client/node_modules/electron-packager/common.js:225:7
    at end (/Users/jamullig/Projects/nc-client/node_modules/run-series/index.js:8:15)
    at done (/Users/jamullig/Projects/nc-client/node_modules/run-series/index.js:11:10)
    at each (/Users/jamullig/Projects/nc-client/node_modules/run-series/index.js:16:43)
    at next (/Users/jamullig/Projects/nc-client/node_modules/rimraf/rimraf.js:74:7)
    at CB (/Users/jamullig/Projects/nc-client/node_modules/rimraf/rimraf.js:110:9)
    at /Users/jamullig/Projects/nc-client/node_modules/rimraf/rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:114:15)
```

```
Put the arguments or parameters here
```

`electron-packager ./build \"Adobe Hub\" --tmpdir=tmp --out=dist/osx --platform=darwin --arch=x64 --version=1.4.16 --icon=assets/icons/adobehub.icns --app-version=$npm_package_version`

The reason behind the breaking change is irrelevant to this particular ticket; it's the package.json in this project that is the issue!

Prematurely closing & renaming #644 does not address the core issue.

**Comment by malept** [comment]
Please do not open multiple issues. We can discuss it in the other one.
