### ISSUE TITLE
How to run electron app as sudo/root user?

### ISSUE THREAD

**Issue by miguelmota** [electron-userland/electron-packager#647]
In my npm start script I have `sudo electron .` but after running the packager the app does not start with sudo privileges. Can someone point me in the right direction for starting electron app as sudo user?

Some of my npm modules require sudo access for them to work

**Comment by malept** [comment]
I do not endorse the idea of starting an Electron app as root. Starting up a web browser engine with administrator access is a large security risk. What you should do instead is run it as an unprivileged user, and then use a module like [`sudo-prompt`](https://www.npmjs.com/package/sudo-prompt) to call the app again with a Node script that contains all the logic that requires superuser privileges, but with the [`ELECTRON_RUN_AS_NODE`](https://electron.atom.io/docs/api/environment-variables/#electron_run_as_node) variable set in the child environment.

**Comment by miguelmota** [comment]
@malept cool, thanks!

**Comment by miguelmota** [comment]
If someone is curious, neither [`sudo-prompt`](https://github.com/jorangreef/sudo-prompt) or [`electron-sudo`](https://github.com/automation-stack/electron-sudo) worked for me. I ended up using a custom [osascript](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/osascript.1.html) for my electron app on mac

```js
var cmd = '/usr/bin/osascript -e \'do shell script "echo some_command" with administrator privileges\''

var proc = exec(cmd)
```

**Comment by jorangreef** [comment]
@miguelmota I am the author of `sudo-prompt`, which uses essentially the same `osascript` (but with support for `status code`, `stdout` and `stderr` as well as an application icon in the Mac prompt) as well as cross-platform support. How could `sudo-prompt` be improved to work better for you?

**Comment by miguelmota** [comment]
@jorangreef I can't remember what the exact issue was but I think it wasn't getting stuck at some point and not returning a response which was halting my application.

If you're wondering here's my code where it's using a custom script for sudo prompt

https://github.com/miguelmota/global-keypress/blob/master/index.js

**Comment by jorangreef** [comment]
Thanks @miguelmota, if you ever encounter that again just let me know and I will open an issue so we can resolve it.

**Comment by matteoannibali** [comment]
Hi Guys,
I have many problems to run my Electron App using “system” privileges.

I need to run it with “system” privileges in order to view UAC messages.
I'm using desktopCapturer and navigator.mediaDevices.getUserMedia and i need to make remote connection "unattended".

Thanks in advance!
Matteo

**Comment by malept** [comment]
An unattended desktop capture sounds dubious. Anyway, try setting [`win32metadata.requested-execution-level`](https://github.com/electron-userland/electron-packager/blob/v12.0.2/docs/api.md#win32metadata). If that doesn't work, ask in [one of the community forums](https://github.com/electron/electron#community).

**Comment by matteoannibali** [comment]
Hi, someone can help me? :)

**Comment by malept** [comment]
There's nothing special about Electron in this sense. I would suggest looking up how to do what you're looking for in a standard Windows application.

If you require more assistance than that, please ask in [one of the community forums](https://github.com/electron/electron#community). More people look at those websites that could help you.

**Comment by matteoannibali** [comment]
Electron base app is made by 2/3 executables. Main process run other render processes.
I need that render processes runs with system privileges but seems not possible at all...
Do you have some useful resources where i can find something useful about?

**Comment by matteoannibali** [comment]
Hi, 
using psexec with my exe electron::
 
![image](https://user-images.githubusercontent.com/252208/41300412-f5a8143a-6e65-11e8-88aa-544ca8d07453.png)

**Comment by malept** [comment]
I used a search engine to look for "Electron UAC" and got http://layer0.authentise.com/electron-and-uac-on-windows.html

Try using `requireAdministrator` instead of `highestAvailable`.

If you require more assistance than that, please ask in [one of the community forums](https://github.com/electron/electron#community). More people look at those websites that could help you.

**Comment by matteoannibali** [comment]
Hi,
I tried change manifest.xml...but nothing happened.

Maybe it's for Electron Architecture?
I try everything..it's possible to run Electron processes with System Privileges ?? :(
Thanks for you help....i'm near to give up.

**Comment by chanble** [comment]
electron-builder add `"requestedExecutionLevel": "highestAvailable"    ` can work
```json
"build": {
    "productName": "MyApp",
    "compression": "maximum",
    "forceCodeSigning": false,
    "asar": true,
    "win": {
      "icon": "resources/icon/icon.ico",
      "requestedExecutionLevel": "highestAvailable"    
    }   
  }
```

**Comment by ukirdemonika** [comment]
> @miguelmota I am the author of `sudo-prompt`, which uses essentially the same `osascript` (but with support for `status code`, `stdout`, `stderr` and an application icon in the Mac prompt) as well as cross-platform support. How could `sudo-prompt` be improved to work better for you?

We are facing an issue with running privileged operations in our Electron-based application on MAC. Our application deals with accessing the hardware operations (which are in a DYLIB implemented in C), which we need to execute them(operations) in sudo mode.

We can perform them if we run the application from the terminal with sudo command (terminal --> sudo application_path and then giving the user credentials in the terminal to open the applications).

But that is running the entire application as a superuser.

We are trying to run a daemon via launched, which on application startup takes the users' credentials and keeps running in the background. Whenever the user initiates the hardware operations, the application will call this daemon to run those operations.

We are able to.... Created a simple daemon file and called it from a .js file. When the application runs, it asks for a password also. but .js was not able to survive on its own. As soon as it is started by launched, it will execute and exit. We want to create a daemon in such a way that runs quietly in the background, usually for a long time.

We tried with sudo-prompt, but the application was not run with root user privileges.

var sudo = require('sudo-prompt');
var options = {
  name: 'vgsPro',
};
// we can give here only cmmand
sudo.exec('npm run electron-build', options, function (error, stdout, stderr) {
  if (error) {
    console.log('error: ' + stderr);
    throw error;
  } else {
    console.log('stdout: ' + stdout);
  }
});

Please let us know 1. If we are having the correct approach and if yes, where are we going wrong? 2. Are we using sudo-prompt correctly?

Is there any better way to achieve this

**Comment by malept** [comment]
@ukirdemonika please direct your question to the sudo-prompt support forums as your question is off-topic for Electron Packager.
