### ISSUE TITLE
icon does not show in macOS launchpad 

### ISSUE THREAD

**Issue by dunwen** [electron-userland/electron-packager#648]
hi,i am sorry for my poor english.  
i had got a problem in packing mac app user this script:  
`"pack:osx": "electron-packager . \"app\" --out=dist/osx --platform=darwin --icon=build/icon.icns"`  
however the icon show in finder is no problem but is show a mac developing icon in launchpad which look like this:
![https://upload.sendongwang.com/resource/uploadImg/44952c0f-9729-4008-9090-66796a63551f.17.00.png](https://upload.sendongwang.com/resource/uploadImg/44952c0f-9729-4008-9090-66796a63551f.17.00.png)
and it look in finder:
![https://upload.sendongwang.com/resource/uploadImg/20ccf5cc-4859-4447-b0c1-059b81957ae1.21.33.png](https://upload.sendongwang.com/resource/uploadImg/20ccf5cc-4859-4447-b0c1-059b81957ae1.21.33.png)
my icon file is 256*256 witch you can download it in this url
[icon](https://upload.sendongwang.com/resource/uploadImg/581f3dc6-0455-42c9-ae00-6e236e27e2a5.icns)

i don't know which step is going wrong and hope you can spend some time to solve my problem....
thank for your kind!

**Comment by malept** [comment]
Macs are not my area of expertise, so my guess is that one of a few things could be happening:

* Your `build/icon.icns` needs more/different icon sizes embedded in it for it to work in Launchpad.
* You aren't specifying an icon when you create a new [`BrowserWindow` (zh-CN docs)](https://github.com/electron/electron/blob/master/docs-translations/zh-CN/api/browser-window.md#new-browserwindowoptions)
* The icon is being cached incorrectly by macOS. Search for how to flush the system icon cache.
