### ISSUE TITLE
Problem permission denied EACCES in SQLite

### ISSUE THREAD

**Issue by danilotecoliveira** [electron-userland/electron-packager#650]
Hi, everybody.

I've had a problem when I try build an Electron App to darwin platform. The process build is ok, the problem is on when I try open my App on MacOS.

When App started, the first step is create a database in SQLite. The problem is here.
In console log show the following error message:

EACCES: permission denied, open 'myDB.db'

In others platforms is ok, just in MacOS doesn't work my App.

Tks

**Comment by malept** [comment]
macOS sandboxing is probably preventing you from creating/writing to a file within the app. You shoud put your SQLite database in the user config folder, see [`app.getPath()`](https://electron.atom.io/docs/api/app/#appgetpathname).
