### ISSUE TITLE
rcedit.exe failed with exit code 193. wine: Bad EXE format 

### ISSUE THREAD

**Issue by dipenpatel235** [electron-userland/electron-packager#654]
**Please describe your issue:**
i have centos 7 64 bit
node v6.10.2

 electron-packager hello-win32-ia32_old hello --platform=win32 --arch=ia32 --overwrite --no-prune

using above command i have build but getting below errro

Packaging app for platform win32 ia32 using electron v1.6.8
rcedit.exe failed with exit code 193. wine: Bad EXE format for Z:\usr\lib\node_modules\electron-packager\node_modules\rcedit\bin\rcedit.exe.

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps

[root@aasd electron-quick-start]# npm start

> electron-quick-start@1.0.0 start /root/electron-quick-start
> electron .

npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/electron-quick-start/npm-debug.log

**Comment by malept** [comment]
Is this 64-bit wine?

**Comment by dipenpatel235** [comment]
Yes.

**Comment by malept** [comment]
64-bit wine is not currently supported by node-rcedit, see: https://github.com/electron/node-rcedit/issues/22

**Comment by dipenpatel235** [comment]
Ok...so I need to install wine 32bit in 64bit systems right ?

On May 25, 2017 11:40 AM, "Mark Lee" <notifications@github.com> wrote:

64-bit wine is not currently supported by node-rcedit, see:
electron/node-rcedit#22 <https://github.com/electron/node-rcedit/issues/22>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/electron-userland/electron-packager/issues/654#issuecomment-303931591>,
or mute the thread

**Comment by malept** [comment]
Yes.

**Comment by dipenpatel235** [comment]
Okey..thanks.
I will check it

**Comment by dipenpatel235** [comment]
So I cant build package for 64 bit os right ?

**Comment by malept** [comment]
No, you can certainly build Windows packages on non-Windows, 64-bit host platforms. In fact, the CI for this project does just that on both macOS and (Ubuntu 14.04) Linux. On Debian/Ubuntu-derived Linux distributions, if you only have wine64 installed, it prints the following instructions to help you install the 32-bit version of wine:

```
it looks like multiarch needs to be enabled.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32"
```

If you need instructions on how to do this for CentOS, I would suggest looking in CentOS-specific support channels.
