### ISSUE TITLE
Allow pruning multiple directories

### ISSUE THREAD

**Issue by DutchKevv** [electron-userland/electron-packager#657]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
Feature request: 

Would it be possible to prune multiple (sub)directories??

I have a package.json in the root directory, and also multiple in subdirectories that could use pruning.

Thanks!

**Comment by malept** [comment]
This isn't a use case that I want to support, as the percentage of users in this situation is too low for the amount of code that will need to be written and maintained.

However, you can do this yourself by using the [`afterCopy` hook](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#aftercopy), with something like:

```js
const path = require('path');
const pruneModules = require('electron-packager/prune').pruneModules;

electronPackagerOptions.afterExtract = [
  (buildPath, electronVersion, platform, arch, callback) => {
    for (const subdir of ['dir1', 'dir2']) {
      pruneModules(electronPackagerOptions, path.join(buildPath, subdir), (err) => {
        // ...
      })
    }
  }
];
```

(Code is meant to illustrate, not be the actual solution - it's not quite right. I'd do something like `pify` + `Promise.all`.)

**Comment by DutchKevv** [comment]
Understand, thanks for the code example! 

I'm using electron builder but it doesn't seem to support the `afterCopy` param (yet)
