### ISSUE TITLE
[Enhancement] Verbose Output

### ISSUE THREAD

**Issue by Bizarrus** [electron-userland/electron-packager#659]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
On written build-script, the source-path is not given (`electron-packager <Source-Path>`). The source-path will be set automatically by the script but `electron-packaher` can't find the `package.json` and can't  find the current `electron` version:

```
Unable to determine Electron version. Please specify an Electron version

For more information, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#e
lectronversion
```

Here is an Sample **Batch-File** (Build.bat on Windows):
```
@echo OFF

set CUR_DIR="%CD%"
set NAME_BUILD="Build"
set NAME_TEMP="Temp"

call electron-packager %CUR_DIR%\%NAME_TEMP% DSTEd --asar=true --overwrite --prune=true --icon=%CUR_DIR%\%NAME_TEMP%\Resources\window_icon.ico --app-version=1.0.0 --out %CUR_DIR%\%NAME_BUILD% --win32metadata.CompanyName="DSTEd - OpenSource" --win32metadata.ProductName="DSTEd" --win32metadata.OriginalFilename="DSTEd.exe"

```

I want following **enhancement**:

A new argument/parameter/option to set an **Verbose Output** to find the error,

**Sample:**
```
electron-packager <Source-Path> --verbose
```

If the verbose-output are enabled, `electron-packager` show additional informations on the output:
```
Unable to determine Electron version. Please specify an Electron version

For more information, please see
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#e
lectronversion

Debug:
Path: C:/Whatelse/DontKnow/
[...Other...]
```

**Comment by malept** [comment]
Thanks for the feature request, but this already exists in Electron Packager, in the form of the `debug` module. This is referenced in the [CONTRIBUTING documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#debugging).
