### ISSUE TITLE
Package OS X(darwin, x64) application in windows nothing happens

### ISSUE THREAD

**Issue by preco21** [electron-userland/electron-packager#66]
Using electron version: 0.28.1
Electron packager version: 4.1.2
OS: Windows 8.1

Build scripts:
```javascript
var packager = require('electron-packager');

packager({
    dir: 'app',
    name: 'App',
    platform: 'darwin',
    arch: 'x64',
    version: '0.28.1'
}, function(error, appPath) {
    if (error) {
        throw error;
    }
    
    console.log(appPath);
});
```

And run command: node test

Outputs:
![image 001](https://cloud.githubusercontent.com/assets/4936201/8150819/474090f0-1334-11e5-9f6d-7c0cdb04e05c.png)

I tried to the package application for OS X from Windows, but it seems nothing happend. (no outputs)
How can i fix it?

**Comment by jden** [comment]
Confirmed, I can reproduce this in my environment (win 8.1, electron-packager 4.1.2). It works when I run the packager script from within the electron-packager directory (e.g., `var packager = require('./');`) but not when electron-packager is an external dependency under `node_modules`. I can dig into this further later.

**Comment by kfranqueiro** [comment]
I think this sounds like the same thing as #71, but if that's the case, @jden's comment has me kind of perplexed.

**Comment by malept** [comment]
This issue hasn't had any further information in over a year, so I'm closing it.

## IF YOU HAVE THIS PROBLEM

Please make a minimal testcase based on [electron-quick-start](https://github.com/electron/electron-quick-start) and post the link here, along with very specific reproduction steps you used to package the app and as much debugging information as possible (please read the [bug reporting documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#before-opening-bug-reportstechnical-issues) for details).
