### ISSUE TITLE
JavaScript error with win64 distribution

### ISSUE THREAD

**Issue by burakkilic** [electron-userland/electron-packager#662]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Hello;

My electron app works fine normally. Also my electron-packager output for Mac OSX works fine. But Windows distribution is giving me the following error:

![screen shot 2017-05-31 at 18 44 59](https://cloud.githubusercontent.com/assets/123382/26640589/d6856caa-4630-11e7-9447-bf433369e0cd.png)

My build script is:

        "pack:win64": "electron-packager . $npm_package_productName --out=dist/win --platform=win32 --arch=x64 --icon=assets/icons/win/finedine.ico --overwrite --asar=true --prune=true",

How can I solve that?

**Comment by MarshallOfSound** [comment]
You need to run your native modules through `electron-rebuild` before packaging for an architecture that isn't your current platforms architecture.

See https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by burakkilic** [comment]
I did that with the command 

    ./node_modules/.bin/electron-rebuild node_modules --arch=x64 --platform=win32

and it is not working on MacOSX. I exported again with:

     "electron-packager . $npm_package_productName --out=dist/win --platform=win32 --arch=x64 --icon=assets/icons/win/finedine.ico --overwrite --asar=true --prune=true",

also gave me the same error.

**Comment by malept** [comment]
Get rid of `$npm_package_productName` from the command. Electron Packager has inferred the app name from the package.json file for a while.

Tangentially, `--prune=true` has also been the default for a while now.

**Comment by burakkilic** [comment]
Ok. Tried again but got the same problem. I'm almost sure it's because of the rebuild. I'll try with a windows computer.

**Comment by malept** [comment]
Oh, you can't rebuild native node modules when the host platform is not the target platform.
