### ISSUE TITLE
SyntaxError on opening binary when using an old version of Electron

### ISSUE THREAD

**Issue by yrahul3910** [electron-userland/electron-packager#671]
I packaged my app using `electron-packager` with the command:
```
electron-packager . Journal --platform=linux --arch=all
```
on my Debian 8 64-bit machine. It produced the 3 folders, but on running the binary executable, I get the error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/home/rahul/Desktop/Electron/Journal (copy)/Journal-linux-x64/resources/atom.asar/browser/lib/init.js:130:10)
    at Object.<anonymous> (/home/rahul/Desktop/Electron/Journal (copy)/Journal-linux-x64/resources/atom.asar/browser/lib/init.js:132:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

I ran `node -c *.js` as described in [#249](https://github.com/electron-userland/electron-packager/issues/249), but it gave no output, so I think that's not the issue, even though my code uses ES6. How do I fix this?
I'm running Node 7.10.0

**Comment by malept** [comment]
What version of Electron are you using? `atom.asar` is pretty old.

**Comment by yrahul3910** [comment]
I'm using version 1.6.10

**Comment by malept** [comment]
> I'm using version 1.6.10

I'm not sure about that.

In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`.

**Comment by yrahul3910** [comment]
Is there an option to do that? Sorry, I'm new to the tool.

**Comment by malept** [comment]
See the [debugging](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#debugging) section of the CONTRIBUTING document that was linked when you created a new issue.

**Comment by yrahul3910** [comment]
Okay, I did `npm install debug`, then `DEBUG=electron-packager`, and then ran the `electron-packager` command. The output wasn't different from without this configuration, but here it is:
```
Packaging app for platform linux ia32 using electron v0.35.6
Packaging app for platform linux x64 using electron v0.35.6
Packaging app for platform linux armv7l using electron v0.35.6
Wrote new apps to:
/home/rahul/Desktop/Electron/Journal (copy)/Journal-linux-ia32
/home/rahul/Desktop/Electron/Journal (copy)/Journal-linux-x64
/home/rahul/Desktop/Electron/Journal (copy)/Journal-linux-armv7l
```
I'm not sure why it says it's using the older Electron, though, running `electron -v` gave `v1.6.10`.

**Comment by malept** [comment]
It's because your `package.json` is using a really old version of Electron, whereas you have a globally installed version of Electron (you should uninstall that).

If you can upgrade your version of Electron, do so by modifying your `electron` entry in `package.json`. If you are unable to do that, you should use [`electron-compile`](https://github.com/electron/electron-compile) to compile your JavaScript into something that your version of Electron can understand.

**Comment by yrahul3910** [comment]
I see. Thanks :)
