### ISSUE TITLE
Add documentation for file 'version' in the package

### ISSUE THREAD

**Issue by emmanuelgeoffray** [electron-userland/electron-packager#672]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

After packaging on linux, there is a file name `version` inside the package, wihich contains a string, which I guess is the electronVersion (for me it's `v1.7.3`).
But I don't see anything in the doc mentioning this file.
To me, it would make more sense that this file contains the `appVersion` or `buildVersion`, as I see these strings are added in descriptors for OSX X or Windows, but not in Linux.

I can help on this, and do a pull request, but I don't see in the code where that file is created.

Thank you,
Emmanuel

**Comment by malept** [comment]
That comes with the prebuilt binary, Electron Packager doesn't create that file.

Because of this, I don't see where in the Electron Packager documentation this would go, because we don't describe all of the files that come with Electron itself. Perhaps this should go in the documentation for Electron?

**Comment by malept** [comment]
> To me, it would make more sense that this file contains the appVersion or buildVersion, as I see these strings are added in descriptors for OSX X or Windows, but not in Linux.

This is because as far as I know, there's no Linux metadata standard that needs things like `appVersion`, apart from creating distro packages (which is handled by other packages, like [`electron-installer-debian`](https://github.com/unindented/electron-installer-debian)).

**Comment by emmanuelgeoffray** [comment]
OK, thanks for the prompt reply and the right answers @malept !

**Comment by emmanuelgeoffray** [comment]
If I add this feature in electron-packager, would you add it to master? Or would you think it is too specific?
I feel that it is a missing feature in Linux.
I find it convenient that in windows and os x, appVersion and buildVersion are both used and user can inspect the build to find out what version he is running. 

The feature would be to add a file named buildVersion containing the buildVersion string and add a file named appVersion containing the appVersion string.

What do you think?

Best,
Emmanuel

**Comment by malept** [comment]
I think that it should be up to the app to implement that, either as a command line argument (`--version`) or an "about" dialog box.

**Comment by emmanuelgeoffray** [comment]
ok. thank you for your prompt reply.
