### ISSUE TITLE
Copyright on Windows metadata

### ISSUE THREAD

**Issue by andresitodeguzman** [electron-userland/electron-packager#674]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Is there such an option to change the copyright on windows metadata. I was able to change the CompanyName etc. through --win32metadata but there is no way to modify the copyright (Which uses Electron's default copyright notices).

**Comment by MarshallOfSound** [comment]
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#appcopyright
