### ISSUE TITLE
remove '.' from command line

### ISSUE THREAD

**Issue by zinwalin** [electron-userland/electron-packager#676]
I built an application with arguments and options when executed in command line,  like **./node_modules/.bin/electron . email --email_subject="hi there" --email_body="good morning."**

After packaging with electron-packager, I get .exe file on windows, and it works well like this: 
**./app.exe . email --email_subject="hi there" --email_body="good morning."**

the question:  is it possible to remove dot('.' ) from command line?   I want app execute like this:
**./app.exe email --email_subject="hi there" --email_body="good morning."**

**Comment by malept** [comment]
The `.` is not necessary because your app is packaged. It is necessary when you run `node_modules/.bin/electron` because it needs to know where your app lives.
