### ISSUE TITLE
Correct Syntax for --osx-sign parameter

### ISSUE THREAD

**Issue by quadrophobiac** [electron-userland/electron-packager#681]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

I am unclear on how to use electron-packager to sign an OSX app. When I pass the command 
`electron-packager . "App" --platform=darwin --arch=x64 --electron-version=1.4.13 --app-bundle-id="com.org.app" --app-version="0.5.0" --build-version="0.5.2" --ignore=docs --ignore=packages --icon=resources/icon.icns --osx-sign.identity=<ID> --osx-sign.entitlements="path/default.entitlements.darwin.plist" --osx-sign.entitlements-inherit="path/default.entitlements.darwin.plist"`

The command executes correctly generating this output at the end 

`Running electron-osx-sign with the options {"identity":"ID","entitlements":"packages/default.entitlements.darwin.plist","entitlements-inherit":"packages/default.entitlements.darwin.plist","platform":"darwin","app":"/path/darwin-x64/appdir/App.app","version":"n.n.n"}`

However when I run the application through RB App Checker Lite and the following commands it indicates no signing has taken place
```
codesign -d --deep --verbose=2 -r- = code object is not signed at all
spctl --assess -vv - = source=no usable signature
```
The same thing happens irrespective of passing a string or the SHA-1 ID for the Code Signing Certificate. Is there a way to debug why the app is failing to be signed?

**Comment by malept** [comment]
Try running with the `DEBUG=electron-osx-sign` environment variable. Apart from that, I would look at the docs for electron-osx-sign, which handles all of the Mac app signing for Electron Packager.

**Comment by quadrophobiac** [comment]
Thanks @malept , that helped things out. I arrived at this conundrum via https://github.com/electron-userland/electron-osx-sign/wiki/3.-App-Sandbox-and-Entitlements which contains some outdated instructions - if I copy in the updated commands here would you be able to add them to that wiki documentation? (i'm documenting my process as I go and want to be able to improve existing documentation if possible)

**Comment by malept** [comment]
You should file an issue in the electron-osx-sign issue tracker so that @sethlu can review the changes you want to make to the wiki documentation..

**Comment by sethlu** [comment]
@quadrophobiac also, the `electron-osx-sign` guide was drafted last year to work as a config generator for `electron-packager` and `electron-osx-sign` [here](http://mintkit.net/electron-userland/electron-osx-sign/guide/) if you haven't checked out yet
