### ISSUE TITLE
Is it possible to give Electron Packager a webpack config file and environment variable?

### ISSUE THREAD

**Issue by zackshapiro** [electron-userland/electron-packager#682]
Right now I'm setting up my webpack config files to compile for production and I want to pass a webpack config file and an environment string to `electron-packager . --mac --icon="./assets/icons/mac/icon.icns" --overwrite`.

I looked through the additional flags and didn't see anything to this extent. Is it possible to tell electron packager which webpack file to use and also give it an environment string like 'production'?

Thanks!

**Comment by MarshallOfSound** [comment]
@zackshapiro `electron-packager` has no concept of webpack, if you want to do something specific while packaging you should check out the `afterCopy` hooks in the API.
