### ISSUE TITLE
When electron is a package.json dependency, it's added to the build even when package-lock.json file is present

### ISSUE THREAD

**Issue by angrykoala** [electron-userland/electron-packager#684]
* [X] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

When a [package-lock.json](https://docs.npmjs.com/files/package-lock.json) file is present, the final build contains the `electron` dependency as part of node_modules, while under normal conditions (just the package.json file present) that dependency is automatically ignored.

As a result, the final build is around 140 MB bigger. Simply removing the package-lock file and executing the build seems to solve the problem while everything keeps working fine.

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager . --overwrite --out builds
```

**Comment by MarshallOfSound** [comment]
Can you please post your package.json file

**Comment by angrykoala** [comment]
```json
  "dependencies": {
    "electron": "^1.6.7",
    "jquery": "^3.1.1",
    "materialize-css": "^0.98.2",
    "vue": "^2.0.8",
    "yerbamate": "^2.0.0"
  },
  "devDependencies": {
    "chai": "^4.0.2",
    "electron-packager": "^8.3.0",
    "istanbul": "^0.4.5",
    "jshint": "^2.9.4",
    "mocha": "^3.2.0",
    "sinon": "^2.0.0"
  }
```

**Comment by MarshallOfSound** [comment]
Please move `electron` to the devDependencies section

**Comment by angrykoala** [comment]
It builds properly with electron as a devDependency and a package-lock.json

@MarshallOfSound Is there a reason for it being ignored from dependencies when no package-lock file is present but changing this behavior when it exists?

**Comment by malept** [comment]
Perhaps that's how `npm@5` works. All Electron Packager does is run `npm prune --production`.

**Comment by MarshallOfSound** [comment]
npm@5 will restore missing prod deps I believe when running prune production.  So even though we ignore it, npm puts it back
