### ISSUE TITLE
Not Support `SetVibrancy` function

### ISSUE THREAD

**Issue by MonFig** [electron-userland/electron-packager#687]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Here's `vibrancy: 'medium-light'` option in my code. It works fine when I use `electron` or `electron-builder`， but not working when I wanna release my app.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Uncaught Exception:
TypeError: focusedWindow.setVibrancy is not a function
    at template.submenu.click (/Users/monkeyfigaro/workspace/sohu/desktop-app/build/desktop-app-darwin-x64/desktop-app.app/Contents/Resources/app/main.js:83:35)
    at MenuItem.click (/Users/monkeyfigaro/workspace/sohu/desktop-app/build/desktop-app-darwin-x64/desktop-app.app/Contents/Resources/electron.asar/browser/api/menu-item.js:81:16)
    at Function.delegate.executeCommand (/Users/monkeyfigaro/workspace/sohu/desktop-app/build/desktop-app-darwin-x64/desktop-app.app/Contents/Resources/electron.asar/browser/api/menu.js:119:40)
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager ./ desktop-app --overwrite --platform=darwin --arch=all --out=./build --version=1.0.0 --icon=./app/img/app-icon.icns
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

```
let windowOption = {
        width: 800,
        height: 600,
        // frame: false,
        titleBarStyle: 'hidden',
        autoHideMenuBar: true,
        icon: 'public/img/app-icon.png',
        transparent: true,
        vibrancy: 'medium-light',
        backgroundColor: '#ddffffff',
};

MainWindow = new BrowserWindow(windowOption);
```

**Comment by malept** [comment]
You set the Electron version to 1.0.0 when you set `--version=1.0.0`. According to https://github.com/electron/electron/pull/7898 it was added in Electron 1.4.7.
