### ISSUE TITLE
'electron-packager' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by hitesh-soni** [electron-userland/electron-packager#688]
how to access 'electron-packager' command.

error="'electron-packager' is not recognized as an internal or external command,
operable program or batch file."

**Comment by MarshallOfSound** [comment]
```bash
npm i electron-packager
./node_modules/.bin/electron-packager
```

**Comment by hitesh-soni** [comment]
can you describe your answer @MarshallOfSound

**Comment by malept** [comment]
Either install Electron Packager globally, as described in the readme, or install it locally as @MarshallOfSound mentioned. On Windows, instead of `./node_modules/.bin/electron-packager`, I believe it's `node_modules\.bin\electron-packager`.
