### ISSUE TITLE
Packaging my app for Mac suddenly no longer shows the icon

### ISSUE THREAD

**Issue by zackshapiro** [electron-userland/electron-packager#691]
Running `"package-mac": "electron-packager ./ --mac --prune=true --icon='./assets/icons/mac/icon.icns' --out=./builds --overwrite",` works, but the icon is the icon that you get on Macs when the app doesn't have an icon.

The file hasn't changed, the path hasn't changed. I even went into GitHub and re-downloaded the icon file in case it got corrupted. I also tried without the single quotes around the `--icon` flag but to no avail.

Any idea what's going on? Running v8.7.1

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

It's possible that the OS X icon cache is corrupt. Have you tried on more than one machine?

I would also check to see if the electron.icns in the packaged app is the same as the one you're specifying in the command line.

A couple of things unrelated:

* `--mac` isn't a flag, look into `--platform` and `--arch` _(although it defaults to whatever the host computer's platform/arch is)_
* `--prune=true` has been default for a while now.

**Comment by zackshapiro** [comment]
I haven't tried on more than one machine, no.

The icon hasn't changed, the path hasn't changed. It worked last week and now it doesn't. Unclear as to why.
 
Here's the stack trace
```
> DEBUG=electron-packager electron-packager ./ --platform=darwin --arch=x64 --icon='./assets/icons/mac/icon.icns' --out=./builds --overwrite

  electron-packager Electron Packager 8.7.2 +0ms
  electron-packager Node v7.4.0 +2ms
  electron-packager Host Operating system: darwin (x64) +1ms
  electron-packager Packager Options: {"_":["./"],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":true,"prune":true,"quiet":false,"platform":"darwin","arch":"x64","icon":"./assets/icons/mac/icon.icns","out":"./builds","dir":"./","protocols":[]} +0ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring application name from productName in /Users/zackshapiro/dev/glimpse-electron/package.json +11ms
  electron-packager Inferring appVersion from version in /Users/zackshapiro/dev/glimpse-electron/package.json +1ms
  electron-packager Inferring target Electron version from electron in /Users/zackshapiro/dev/glimpse-electron/package.json +3ms
  electron-packager Application name: Glimpse +0ms
  electron-packager Target Electron version: 1.7.5 +0ms
  electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt(-compile)?($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ] +1ms
  electron-packager Downloading Electron with options {"strictSSL":true,"platform":"darwin","arch":"x64","version":"1.7.5"} +5ms
Packaging app for platform darwin x64 using electron v1.7.5
  electron-packager Creating /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64-template +251ms
  electron-packager Extracting /Users/zackshapiro/.electron/electron-v1.7.5-darwin-x64.zip to /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64-template +1ms
  electron-packager Initializing app in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64 from /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64-template template +1s
  electron-packager Ignored paths based on the out param: [ '/Users/zackshapiro/dev/glimpse-electron/builds' ] +2ms
  electron-packager Pruning modules via: npm prune --production +4s
  electron-packager Copying icon "./assets/icons/mac/icon.icns" to app's Resources as "electron.icns" +8s
  electron-packager Renaming Electron to Glimpse in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64/Electron.app/Contents/MacOS +3ms
  electron-packager Renaming Electron Helper to Glimpse Helper in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper.app to Glimpse Helper.app in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper EH to Glimpse Helper EH in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper EH.app to Glimpse Helper EH.app in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper NP to Glimpse Helper NP in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper NP.app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper NP.app to Glimpse Helper NP.app in /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Moving /var/folders/6n/9v3vtsss3pxd279s989x5t7w0000gn/T/electron-packager/darwin-x64/Glimpse-darwin-x64 to builds/Glimpse-darwin-x64 +1ms
Wrote new app to builds/Glimpse-darwin-x64
```

**Comment by malept** [comment]
Could you check `builds/Glimpse-darwin-x64/Glimpse.app/Contents/Resources/electron.icns` to see if it's the same icon?

**Comment by zackshapiro** [comment]
There is no `electron.icns` file in `builds/Glimpse-darwin-x64/Glimpse.app/Contents/Resources/`

**Comment by malept** [comment]
Well, the debug info says it was copied. Is `assets/icons/mac/icon.icns` a symlink or something? Can you try a different version of Node?

**Comment by zackshapiro** [comment]
It's not a symlink. It's a file right in my project. It was working fine last week, not sure what happened. I also tried downloading that .icns file from GH and replacing the image in my project. No luck

I'm using Node v7.4.0

**Comment by zackshapiro** [comment]
I tried again wrapping the icon route in single quotes: `"package-mac": "DEBUG=electron-packager electron-packager ./ --platform=darwin --arch=x64 --icon='./assets/icons/mac/icon.icns' --out=./builds --overwrite",`

And now I have an electron.icns file in `/Contents/Resources` but the file icon in the build that it put out is still the icon-less Mac app icon

**Comment by malept** [comment]
That's probably the OS X icon cache.

**Comment by zackshapiro** [comment]
I tried clearing the cache using a variety of the methods in here: https://gist.github.com/fabiofl/5873100#gistcomment-1887437 with no luck, unfortunately.

**Comment by malept** [comment]
I'm pretty sure that this is now an OS X problem, so I'm closing this issue.

**Comment by zackshapiro** [comment]
Thanks for your help @malept. Quick (hopefully) last question: if it was a caching issue, wouldn't my test users that I send the app to see the icon rather than the icon-less-app icon?

**Comment by malept** [comment]
That's correct, assuming they don't have the old app that doesn't have the custom icon.

**Comment by zackshapiro** [comment]
Confirmed with my friend that they have the custom icon correctly on their machine. So it must be a local caching issue. Thanks @malept, appreciate your time and your work on this library!

**Comment by mlb5000** [comment]
With package 10.1.0

I'm having this issue as well. My `.icns` file appears to be fine, but the one that gets pulled into the Mac `.app` bundle is not

<img width="562" alt="2017-11-24_1558" src="https://user-images.githubusercontent.com/207508/33223732-7f7b3fa8-d130-11e7-962e-d007bc42d4ea.png">

<img width="548" alt="2017-11-24_1600" src="https://user-images.githubusercontent.com/207508/33223738-93efa226-d130-11e7-8164-74092a2b373d.png">

I package using the Programmatic API

```
const packager = require('electron-packager');
const rebuild = require('electron-rebuild');
const zip = require('electron-installer-zip');
const createDmg = require('electron-installer-dmg');
const pmjson = require('./package.json');
const winstaller = require('electron-winstaller');

packager({
  dir: '.',
  platform: 'all',
  arch: 'x64',
  electronVersion: '1.7.9',
  prune: true,
  overwrite: false,
  icon: "app",
  out: "electron_build",
  // … other options
  afterCopy: [(buildPath, electronVersion, platform, arch, callback) => {
    rebuild.rebuild({ buildPath, electronVersion, arch })
      .then(() => callback())
      .catch((error) => callback(error));
  }],
  // … other options
}, function(err, appPaths) {
  if (err) {
    console.error(err);
    process.exit(1);
  }

  var version = pmjson.version;

  for (var i = 0; i < appPaths.length; i++) {
    var appPath = appPaths[i];
    console.log('App Path: ' + appPath);

    if (appPath.indexOf('darwin') !== -1) {
      console.log('creating OS X DMG');
      createDmg({
        appPath: appPath + '/plugin-manager.app',
        name: "SoftwarePM_v" + version,
        //out: 'electron_dist/',
        overwrite: true,
        icon: 'IconTemplate@2x.png'
      }, function(err) {
        if (err) {
          console.log('Error creating DMG: ' + err);
        } else {
          console.log('Successfully created DMG');
        }
      });
    } else if (appPath.indexOf('win32') !== -1) {

    }
  }
});
```

**Comment by malept** [comment]
@mlb5000 please file a new issue and fill in the issue template where appropriate.

**Comment by quanglam2807** [comment]
@mlb5000 I'm having the same problem. Have you figured out the solution? I understand this thread is 3 years old but this bug is really strange.

**Comment by malept** [comment]
@quanglam2807 please file a new issue and fill in the issue template where appropriate.
