### ISSUE TITLE
What are the dependencies for Electron on Ubuntu?

### ISSUE THREAD

**Issue by rontran** [electron-userland/electron-packager#696]
So on a freshly formatted Ubuntu 17.04 desktop(no node installed), I copied my folder over that electron-packager created.  I double click on the the app icon and nothing happened.  I then installed visual studio code and then went back and open my app.  It worked.  So the question is what dependancies did visual studio code installed and what is needed for electron in order to run?

**Comment by malept** [comment]
See: https://github.com/unindented/electron-installer-debian/blob/13b9de71940eb42f4ac720fdccb988f14aa1f198/src/installer.js#L142-L153 for a list.

I would use either [electron-installer-debian](https://github.com/unindented/electron-installer-debian) or [Electron Forge](https://github.com/electron-userland/electron-forge) (which uses both Packager and electron-installer-debian internally) to create `.deb` files so you don't have to figure out dependencies yourself.
