### ISSUE TITLE
Scaled dimensions after packaging

### ISSUE THREAD

**Issue by Apfelclonk** [electron-userland/electron-packager#697]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

After building my electron app, with the electron-packager or with electron-forge, the dimensions within the app appear to be bigger than they were when starting the app unpacked with electron via command line. E.g. elements that have a width of 16px (the chrome inspect tool even shows 16px) are 20px on my screen. I've checked webFrame.zoomFactor and webFrame.zoomLevel on both, the packed and unpacked version, they are 1. I'm using Windows 10.

Console output with DEBUG=electron-packager

```
Packaging app for platform linux ia32 using electron v1.6.2
Packaging app for platform win32 ia32 using electron v1.6.2
Packaging app for platform darwin x64 using electron v1.6.2
Packaging app for platform linux x64 using electron v1.6.2
Packaging app for platform mas x64 using electron v1.6.2
WARNING: signing is required for mas builds. Provide the osx-sign option, or manually sign the app later.
Packaging app for platform win32 x64 using electron v1.6.2
Packaging app for platform linux armv7l using electron v1.6.2
Wrote new apps to:
build\nanoMill-linux-ia32
build\nanoMill-win32-ia32
build\nanoMill-darwin-x64
build\nanoMill-linux-x64
build\nanoMill-mas-x64
build\nanoMill-win32-x64
build\nanoMill-linux-armv7l
```
Command line:
```
electron-packager ./app myapp --all --asar --electron-version=1.6.11 --overwrite --out=./build/ --icon=./app/icon/icon
```

Thanks for any help, I hope this is somehow correct here and is not a question too general to post here. I've found nothing even close to this topic.

Have a nice day!

**Comment by MarshallOfSound** [comment]
Going to prefix by saying this is **extremely** unlikely if you have checked the zoom values as you say.  You can provide a repro case for this.

**Comment by Apfelclonk** [comment]
I have this issue with the current version of my repos ([https://github.com/Apfelclonk/nanoMill](https://github.com/Apfelclonk/nanoMill )). But it's quite complex. I'll build test project and see if that problem persists.

**Comment by Apfelclonk** [comment]
This is pretty much a default setup, just with a few glyphs in it, but gives the same result. The packed one seems to be zoomed in over the unpacked one.
[testCase.zip](https://github.com/electron-userland/electron-packager/files/1214516/testCase.zip)

**Comment by malept** [comment]
Could you provide screenshots of the expected and actual behavior? I tried this on my Linux machine and they look the same to me.

The block itself is 16x16, but the text is 21x16 and it's overflowing outside of the container.

**Comment by Apfelclonk** [comment]
This is how they appear right after startup. I did not changed their size in any way. The left one is the unpackaged one, the right one is the one build with the packager. The 32bit and 64bit version behave the same in that aspect.

![scale_bug](https://user-images.githubusercontent.com/5251199/29179944-683b895c-7df6-11e7-9867-1a17791435a0.jpg)

**Comment by malept** [comment]
Can you try a different version of Electron, like the latest stable version? I can't reproduce it here.

**Comment by Apfelclonk** [comment]
I've tried 1.6.11 and 1.6.12 with the same result

**Comment by malept** [comment]
Unfortunately, I can't think of a reason why Electron Packager itself would have this effect on the application, as it doesn't modify the Electron binary aside from metadata. It might have something to do with how the default_app behaves (which is what happens when you run `electron path/to/app`) versus a packaged app. You will probably have better luck looking through the [Electron issue tracker](https://github.com/electron/electron/issues), with issues such as https://github.com/electron/electron/issues/9417. In any event, if you can't find the issue already raised, you should file a new one there. They'll be able to help you better.

**Comment by Apfelclonk** [comment]
Actually I've just found that link on my own, after searching for several ours. But thank you very much for you time, that fixed it for me.
