### ISSUE TITLE
Explicitly setting asar to false gives a warning

### ISSUE THREAD

**Issue by XuluWarrior** [electron-userland/electron-packager#698]
* [ x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
Adding --asar=false to the command line gives the warning 
`WARNING: asar parameter set to an invalid value (false), ignoring and disabling asar`

I realise that false is the default value but sometimes it aids clarity to set parameters explicitly.

**Comment by malept** [comment]
Due to how [minimist](https://github.com/substack/minimist) works (the command line argument parser we use), you need to specify `--no-asar` instead of `--asar=false` (which makes it think the value of the argument is the string `"false"`).

**Comment by XuluWarrior** [comment]
Is the option --no-asar or your use of minimist syntax documented anywhere?  I can't find it in [usage.txt](https://github.com/electron-userland/electron-packager/blob/master/usage.txt) or [api.md](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md)

In fact [api.md](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#asar) states

> asar
> 
> Boolean or Object (default: false)

**Comment by malept** [comment]
Well, there's [`--no-prune`](https://github.com/electron-userland/electron-packager/blob/93523ba8dbe8626906a6ef51db3ee02d54e19ad0/usage.txt#L50). There's [an issue in minimist about documenting `--no-`](https://github.com/substack/minimist/issues/54).

The API docs are written with the JS API in mind.

**Comment by malept** [comment]
> [...] sometimes it aids clarity to set parameters explicitly.

I would suggest instead of using the CLI, instead use the JavaScript API and enumerate all of the Packager options in a `build.js` file. Otherwise, you're going to hit "command too long" problems.
