### ISSUE TITLE
electron-v1.6.2-win32-x64.zip放在哪里

### ISSUE THREAD

**Issue by nagerenshifou** [electron-userland/electron-packager#699]
> electron-quick-start@1.0.0 packager D:\编程\electron\exp\resources\electron-quick-start
> electron-packager . app --win --out presenterTool --arch=x64 --version 1.6.2 --overwrite --ignore=node_modules
WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead
Downloading tmp-5756-0-electron-v1.6.2-win32-x64.zip
[>                                            ] 0.0% (0 B/s)
下载很慢,我自己找了electron-v1.6.2-win32-x64.zip下下来，该放在哪里

**Comment by MarshallOfSound** [comment]
Please do not raise multiple issues across repositories.  (RE https://github.com/electron/electron/issues/10255)

You may need to use a [mirror](https://github.com/electron/electron#mirrors) to download Electron

**Comment by yyhan** [comment]
在这一步 `Downloading tmp-5756-0-electron-v1.6.2-win32-x64.zip` 无法下载或者下载缓慢时，可以使用以下方式处理：

``` sh
# 指定ELECTRON_MIRROR使用淘宝镜像，最后的'/'是必须的
npm config set ELECTRON_MIRROR "https://npm.taobao.org/mirrors/electron/"
```
