### ISSUE TITLE
Electron-packager hanging forever on MacOS - codesign phase stuck

### ISSUE THREAD

**Issue by bengotow** [electron-userland/electron-packager#701]
Hey folks!

I spent a long time today debugging an issue with electron-packager. I've resolved it, but I wanted to post an issue here so others don't get stuck on the same issue.

I use electron-packager on Travis to package and codesign a Mac OS X build of an Electron app. Recently I needed to upgrade the Travis image to Mac OS Sierra by adding `osx_image: xcode8.3` to my `.travis.yml` file. After making this change, I discovered that `electron-packager` appeared to hang forever. The builds just timed out after ~45 minutes.

I edited the Travis configuration to invoke electron-packager and the rest of the build process with `DEBUG=electron-packager,electron-osx-sign`. This showed the last line that was logged before the process hung:

```
Mon, 14 Aug 2017 20:38:17 GMT electron-osx-sign Executing... codesign --sign 487B46D1C8E4FC8B7DB8666133B6A553E951B66A --force /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/nylas-build/electron-packager/darwin-x64/Merani-darwin-x64/Merani.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
```

I set up my local environment so I could package and codesign the app on my machine, complete with the "temporary keychain" setup used on the build machine. It turns out that starting in Mac OS X Sierra, `codesign` displays a UI prompt for permission to access the keychain, even if it's unlocked. Since Travis is headless, the build process locked forever at the permission dialog.

To fix this, I followed instructions here (https://stackoverflow.com/questions/39868578/security-codesign-in-sierra-keychain-ignores-access-control-settings-and-ui-p) and added this line to my keychain setup script:

```
security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k <<keychainPass>> <<keychainName>>
```

I think this issue is pretty rare because Travis still uses an older version of Mac OS X by default. When / if Travis starts defaulting to Sierra, this might be a common problem!

**Comment by malept** [comment]
Thanks for reporting this, @bengotow. When I have some time I'll look to see what version of OS X I'm running Travis with.

You may want to report this at electron-osx-sign as well.

**Comment by develar** [comment]
@bengotow Thanks a lot. electron-builder fully supports [code signing](https://github.com/electron-userland/electron-builder/wiki/Code-Signing) on macOS Sierra, including CI support. But I was not aware that we also need `set-key-partition-list` (all tests green, no user reports). But I saw this UI pop-uo only once, so, fixed.

**Comment by MarshallOfSound** [comment]
This is something I noticed a while ago when running on newer travis CI boxes.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/sig/import.sh#L21

Just need to run that command on CI 😄

**Comment by develar** [comment]
@MarshallOfSound Randomly or always? As far I know, only `list-keychains` is required on macOS Sierra Travis CI (`osx_image: xcode8.3`). I don't see user reports about it and it works for me (app and tests). Ok, in any case yet another command doesn't harm.

**Comment by MarshallOfSound** [comment]
@develar It was failing 100% of the time for me, not sure about others, currently using 8.1 image

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/.travis.yml#L3

**Comment by mailtokartik1** [comment]
@bengotow you saved me today! Thank you so much mate!!
