### ISSUE TITLE
"PowerPC applications are no longer supported" when running packaged darwin x64 application on OS X El Capitan

### ISSUE THREAD

**Issue by mbrodersen** [electron-userland/electron-packager#703]
A dialog with the text:
"PowerPC applications are no longer supported"
pops up when trying to run a packaged darwin x64 application on OS X El Capitan.

The same application (but different packages of course) works in Ubuntu 16.04 and Windows 7.

Console output:

Wed, 16 Aug 2017 01:18:37 GMT electron-packager Electron Packager 8.7.2
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Node v4.2.6
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Host Operating system: linux (x64)
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Packager Options: {"_":[".","RuleWizard1.0"],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":true,"prune":true,"quiet":false,"platform":"darwin","out":"./packages","dir":".","name":"RuleWizard1.0","protocols":[]}
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Target Platforms: darwin
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Target Architectures: x64
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Inferring appVersion from version in /home/morten/Projects/RuleWizard/package.json
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Inferring target Electron version from electron in /home/morten/Projects/RuleWizard/package.json
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Application name: RuleWizard1.0
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Target Electron version: 1.7.5
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt(-compile)?($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager' ]
Wed, 16 Aug 2017 01:18:37 GMT electron-packager Downloading Electron with options {"strictSSL":true,"platform":"darwin","arch":"x64","version":"1.7.5"}
Packaging app for platform darwin x64 using electron v1.7.5
Wed, 16 Aug 2017 01:18:38 GMT electron-packager Creating /tmp/electron-packager/darwin-x64-template
Wed, 16 Aug 2017 01:18:38 GMT electron-packager Extracting /home/morten/.cache/electron/electron-v1.7.5-darwin-x64.zip to /tmp/electron-packager/darwin-x64-template
Wed, 16 Aug 2017 01:18:40 GMT electron-packager Initializing app in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64 from /tmp/electron-packager/darwin-x64-template template
Wed, 16 Aug 2017 01:18:40 GMT electron-packager Ignored paths based on the out param: [ '/home/morten/Projects/RuleWizard/packages' ]
Wed, 16 Aug 2017 01:18:44 GMT electron-packager Pruning modules via: npm prune --production
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Renaming Electron to RuleWizard1.0 in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64/Electron.app/Contents/MacOS
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Renaming Electron Helper to RuleWizard1.0 Helper in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Renaming Electron Helper.app to RuleWizard1.0 Helper.app in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64/Electron.app/Contents/Frameworks
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Renaming Electron Helper EH to RuleWizard1.0 Helper EH in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/MacOS
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Renaming Electron Helper EH.app to RuleWizard1.0 Helper EH.app in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64/Electron.app/Contents/Frameworks
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Renaming Electron Helper NP to RuleWizard1.0 Helper NP in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper NP.app/Contents/MacOS
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Renaming Electron Helper NP.app to RuleWizard1.0 Helper NP.app in /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64/Electron.app/Contents/Frameworks
Wed, 16 Aug 2017 01:18:48 GMT electron-packager Moving /tmp/electron-packager/darwin-x64/RuleWizard1.0-darwin-x64 to packages/RuleWizard1.0-darwin-x64
Wrote new app to packages/RuleWizard1.0-darwin-x64

Command line arguments:

export DEBUG=electron-packager; ./node_modules/.bin/electron-packager . RuleWizard1.0 --platform=darwin --out=./packages --overwrite

Trying to run on MacOS:

1. (On Linux) Zip the generated package to RuleWizard1.0-darwin-x64.app.zip
2. Copy it to a Mac
3. (On Mac) Renamed to RuleWizard1.0-darwin-x64.app
4. (On Mac) Double click the RuleWizard1.0-darwin-x64.app file
=>
Dialog is shown:
"You can't open the application "RuleWizard1.0-darwin-x64" because PowerPC applications are no longer supported."

**Comment by malept** [comment]
* What command did you use to zip it?
* How, exactly, did you copy it to a Mac?
* What does "Renamed to RuleWizard1.0-darwin-x64.app" mean? Did you unzip it first?

**Comment by mbrodersen** [comment]
I tried to unzip first and now it works. Thanks for the comment malept! It pointed me in the right direction :-)
