### ISSUE TITLE
Packaging/Building for Windows

### ISSUE THREAD

**Issue by zackshapiro** [electron-userland/electron-packager#705]
I'm working with my business partner on getting an app I built up and running on his machine. He has a windows gaming laptop from 2013. I've run `"DEBUG=electron-packager electron-packager ./ --platform=win32 --arch=all --icon=./assets/icons/win/icon.ico --out=./builds --overwrite"` which gives him 2 options, the ia32 and the x64 versions of the app.

On my Mac, I see a Mac folder with 4 files in it: the app itself, a version file, and 2 license files.

When I open either of the windows-formatted builds, I see dozens of files, mostly `.dll.` files in addition to the `.exe` file. 

His machine asked him if he wanted to unpack some files (which took 10+ minutes) when he went to run the .exe which seems wrong. I feel like he should be able to just open the file and run the app.

Not having a Windows machine myself and doing this troubleshooting over the phone with him leaves me with limited ideas about what to do. Any suggestions here on smoothing out the experience for him and my other Windows beta users?

Thanks!

**Comment by MarshallOfSound** [comment]
@zackshapiro Sounds like you sent them a zip file or something and they're trying to run the `.exe` file from within that zip folder.

**Comment by zackshapiro** [comment]
They unzipped the folder which had 3 builds in it, a Mac build and 2 windows builds. They started with the x64 build, opening that folder and running the exe.

**Comment by MarshallOfSound** [comment]
I don't see the issue here (am I missing something).  You sent them a zip file, which took a long time to extract, and then they ran the `.exe` file successfully?

**Comment by zackshapiro** [comment]
They were able to unzip the 3 builds but when they went to run the .exe, it asked if they wanted to 'extract files' which took 10+ minutes to do. Unclear if they were able to run the .exe successfully. Waiting to hear back. The fact that I haven't yet leads me to believe that no, they haven't.

Seems like they should just be able to open the x64 build folder, run the exe and be good to go. Not sure why they're seeing dozens of `.dll` files and being asked about an extraction

**Comment by zackshapiro** [comment]
![https://d26dzxoao6i3hh.cloudfront.net/items/3y2q1T0M1i0u0U1L2621/Screen%20Shot%202017-08-16%20at%2010.14.21%20AM.png?v=2bbef6f7]()

**Comment by MarshallOfSound** [comment]
`electron-packager` does not make a single `.exe` file for you, it packages your app's code into a folder with all the electron bits and pieces in it.  If you want to create an installer (a single `.exe` file). I'd recommend checking out `electron-winstaller` or the simpler approach `electron-forge`.

Those `dll` files are all required for Electron apps to run.

> it asked if they wanted to 'extract files'

This sounds like a bit of miscommunication, Electron will never ask to "extract files", that string doesn't even exist anywhere in the Electron or Packager repositories.  Can you double check where exactly in the process that message appears.

That said, raising an issue for a third party makes this a pretty difficult communication channel.  Without a repro or a first hand recording or something there is basically nothing we can do here.

**Comment by malept** [comment]
I think the answer here is what @MarshallOfSound said, create a Windows installer using one of the methods described above.

**Comment by zackshapiro** [comment]
Gotcha re: all the files it generates and alternatives to `electron-packager`

I appreciate you helping me on behalf of a third party. I know not ideal, he's non-technical so I'm trying to debug this as best I can. 

The process he described is as follows:

1) Download a .zip file with all 3 builds in it
2) Unzip (quickly) and go into the Windows x64 build
3) Click on the .exe file and was prompted to unpack files (which took ~10 mins)
4) Once that was done, he was able to run the .exe file successfully.

Not sure what's going on in the third step

**Comment by malept** [comment]
I should note that Electron Forge uses both Packager and `electron-winstaller` under the hood, plus it has an import feature that lets you import an existing Electron project.

Electron Packager does not generate EXE files that prompts you to unpack files (unless you wrote your app to do that), so I don't know what's going on there. Perhaps if you got him to create a screencast of him opening up your app with that behavior, that would help you figure out what's happening.

**Comment by zackshapiro** [comment]
Just to follow up on this, I had a chance to see what my cofounder was seeing the other day.

After running the .exe file for the first time, windows prompts you to 'unpack' files and references `.dll` files that need to be unpacked. That takes ~5 mins or so and then the .exe file can run
