### ISSUE TITLE
Error during packaging

### ISSUE THREAD

**Issue by HaythemJ** [electron-userland/electron-packager#708]
I am facing error while executing the command npm run build.

Here is my package.json

{
  "name": "electrontoutorial",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "electron index.js",
    "package": "",
    "build": "electron-packager . ElectronToutorial"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {
    "asar": "^0.13.0",
    "electron": "^1.7.5",
    "electron-packager": "^8.7.2"
  }
}

Here is the log output:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle electrontoutorial@1.0.0~prebuild: electrontoutorial@1.0.0
6 info lifecycle electrontoutorial@1.0.0~build: electrontoutorial@1.0.0
7 verbose lifecycle electrontoutorial@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle electrontoutorial@1.0.0~build: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\Training\ElectronToutorial\node_modules\.bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Program Files\apache-maven-3.3.9\bin;C:\Program Files\MongoDB\Server\3.4\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\VisualSVN\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle electrontoutorial@1.0.0~build: CWD: D:\Training\ElectronToutorial
10 silly lifecycle electrontoutorial@1.0.0~build: Args: [ '/d /s /c', 'electron-packager . ElectronToutorial' ]
11 silly lifecycle electrontoutorial@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle electrontoutorial@1.0.0~build: Failed to exec build script
13 verbose stack Error: electrontoutorial@1.0.0 build: `electron-packager . ElectronToutorial`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid electrontoutorial@1.0.0
15 verbose cwd D:\Training\ElectronToutorial
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error electrontoutorial@1.0.0 build: `electron-packager . ElectronToutorial`
22 error Exit status 1
23 error Failed at the electrontoutorial@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by HaythemJ** [comment]
Just found that there is a similar issue solved here https://github.com/electron-userland/electron-forge/issues/266

I am currently using npm 5.30 so I downgraded my npm using this command:

npm install -g npm@4

**Comment by joshuapinter** [comment]
For ease of others landing here, this was fixed in npm 5.4.0 so just update your npm with:

```bash
npm update -g npm
```

And you should be good to go.
