### ISSUE TITLE
Cannot find module 'debug'

### ISSUE THREAD

**Issue by eminoda** [electron-userland/electron-packager#710]
* [ ] Run electron-packager is ok
* [ ] click xxx.exe,this error is opened.
````
electron-packager . --prune=true --ignore=src --ignore=out --ignore=e2e --overwrite --platform=win32 --arch=ia32 --out=out --icon=favicon.ico
````
````
"dependencies": {
    "debug": "^3.0.0",
    "electron-log": "^2.2.7",
    "fs": "0.0.1-security",
    "log4js": "^2.3.3"
  },
````
http://chuantu.biz/t6/16/1503385572x2890171803.png
http://chuantu.biz/t6/16/1503385593x2890171803.png

i dont know how to fix is.

**Comment by MarshallOfSound** [comment]
@eminoda The issue is with your `ignore` command.

```
--ignore=src
```

This will ignore **all** `src` folders including the ones in your node_modules folder (`node_modules/debug/src`).  You need a more exact ignore command or you will be ignoring things by accident that shouldn't be ignored 😄

**Comment by eminoda** [comment]
thanks. u are my god  @MarshallOfSound

**Comment by eminoda** [comment]
but i want to ignore src in root dir.how can i do？
i try this '--ignore=src --ignore=^node_modules/debug/src'
but this result is 'src' all ignore @MarshallOfSound
