### ISSUE TITLE
cannot use npm5 to package the electron app

### ISSUE THREAD

**Issue by chenyuncai** [electron-userland/electron-packager#712]
* [ y] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ y] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ y] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Packaging app for platform win32 x64 using electron v1.6.2
{ Error: Command failed: npm prune --production
npm ERR! May not delete: /private/var/folders/p_/x486xk1s20l1xg73wvcpg2tm0000gp/T/electron-packager/win32-x64/TMROBOTTEST-win32-x64/resources/app/node_modules/.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ray/.npm/_logs/2017-08-22T13_37_19_836Z-debug.log

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm prune --production' }
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
{
	arch: 'x64',
	dir: __dirname,
	platform: 'win32',
	asar: true,
	icon: "./build/icon",
	name: '*****',
	out: __dirname + '/releases',
	overwrite: true,
	electronVersion: '1.6.2',
	ignore: ['build.js']
}
```

**it runs well before i upgraded the npm to 5.0.**

**now i reinstall the nodejs so that the npm version went back to 3.10.10, and then succeed.**

**Comment by malept** [comment]
This is a known issue, see: https://github.com/npm/npm/issues/17781

At this point we're waiting for NPM to release a new version.
