### ISSUE TITLE
package for macos malloc error

### ISSUE THREAD

**Issue by bimohxh** [electron-userland/electron-packager#715]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I want to package for mac run 
```
electron-packager . --platform=darwin --arch=x64 --overwrite  --packageManager=yarn --icon=./imgs/logo.png.hqx

```
but got error
```
node(80551,0x7fffcc6873c0) malloc: *** error for object 0x12f3863e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    80551 abort      electron-packager . --platform=darwin --arch=x64 --overwrite  

```

**Comment by MarshallOfSound** [comment]
@bimohxh What version of node are you running?

**Comment by bimohxh** [comment]
@MarshallOfSound  node version is `8.4.0`, but this node version can run in windows with no error

**Comment by MarshallOfSound** [comment]
Looks like the new `8.4.0` version of nodejs has some issues, see #714 as well.  Might want to raise this upstream in the node repo

**Comment by malept** [comment]
Node 8.5.0 was released today, can you try that? If that doesn't work, can you downgrade to Node 6?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.

**Comment by ericboehs** [comment]
This seemed to be an issue with 8.4 and 8.5. I upgraded to 8.8.1 and this error went away.

**Comment by malept** [comment]
What are the version numbers referring to? There has never been an Electron Packager 8.8.1.

**Comment by ericboehs** [comment]
Node (updated the comment)
