### ISSUE TITLE
Windows automatic update prompts "Application is running"

### ISSUE THREAD

**Issue by ozooner** [electron-userland/electron-packager#716]
I recently updated from packager 19.18.0 to latest 19.27.0
We have an app in production packaged with 19.18.0, and when I build an update with latest version, windows automatic update displays a prompt:
![error](https://user-images.githubusercontent.com/2709373/29875653-56f09568-8da3-11e7-86d0-7396f83df784.png)
While pressin OK works fine, this is issue for unmanaged setups.
Building the update with builder v19.18.0 installs without any prompts.

Build options:
target: nsis
provider: generic
oneClick: true
perMachine: false

**Comment by malept** [comment]
This issue is for electron-builder, not Electron Packager.

**Comment by ozooner** [comment]
Fuck, wrong repo :/
