### ISSUE TITLE
Unable to execute python script top-level folder

### ISSUE THREAD

**Issue by MonkeyChap** [electron-userland/electron-packager#720]
Hi,

This may be obvious, so please excuse the noob question. I'm using a node module called python-shell to execute a python script in my electron app. This works fine when I run it with npm start, but when I use e-p to build an app (mac), it reports:

Error: python: can't open file 'script.py': [Errno 2] No such file or directory

The file is in the same folder (top level) as the index.html file. The javascript file is in a sub-folder called js. I also put a copy of the python script in there to test if it was a relative path problem, but that made no difference either. 

If I get node to report the __dirname it gives me:

<blah>/<app-folder>/<app-name>.app/Contents/Resources/app

If I open that up, I can see the python script is there.

Weird. And vaguely annoying. Any ideas if this is a bug or something I just haven't set in the package.json ?

Thanks

Ian

**Comment by malept** [comment]
You should use an absolute path instead of a relative path, e.g.

```javascript
const path = require('path');
const pathToPythonScript = path.join(__dirname, 'script.py');
// I don't know what python-shell's API looks like
runPython(pathToPythonScript);
```

**Comment by MonkeyChap** [comment]
Awesome - ta. I'd tried __dirname+"/script.py" - didn't realise I needed to use path.join.

**Comment by EduardoSantos7** [comment]
Thanks, It works!
