### ISSUE TITLE
package.json version

### ISSUE THREAD

**Issue by MonkeyChap** [electron-userland/electron-packager#721]
Hello

Not sure what's happening here, but if I run with npm start it complains if I have a 2 place version (e.g. 0.1). If I package it, E-P complains if it's 3 place (0.0.1) (npm ERR! Cannot read property '0' of undefined).

Not a complete disaster, but does mean I need to keep changing the version numbers between build and test.

Ian

**Comment by MarshallOfSound** [comment]
Can you post your package.json in both cases

**Comment by MonkeyChap** [comment]
"name": "config-app",
  "produceName": "config app",
  "version": "0.1",
  "description": "config tool",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "package-mac": "electron-packager . --overwrite --icon=./icons/i256.icns",
    "package-win": "electron-packager . --overwrite --asar=true --icon=./icons/i256.ico --prune=true ",
    "package-linux" : "electron-packager . --overwrite --platform=linux --icon=./icons/i256.png "
  },
  "repository": "",
  "keywords": [
    "illumr",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "Ian",
  "license": "commercial",
  "devDependencies": {
    "electron": "~1.6.2",
    "guid": "*",
    "path": "*",
    "python-shell": "*",
    "xml": "*",
    "xml-formatter": "*"
  }
}

or

  "name": "config-app",
  "produceName": "config app",
  "version": "0.0.1",
  "description": "config tool",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "package-mac": "electron-packager . --overwrite --icon=./icons/i256.icns",
    "package-win": "electron-packager . --overwrite --asar=true --icon=./icons/i256.ico --prune=true ",
    "package-linux" : "electron-packager . --overwrite --platform=linux --icon=./icons/i256.png "
  },
  "repository": "",
  "keywords": [
    "illumr",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "Ian",
  "license": "commercial",
  "devDependencies": {
    "electron": "~1.6.2",
    "guid": "*",
    "path": "*",
    "python-shell": "*",
    "xml": "*",
    "xml-formatter": "*"
  }
}

**Comment by malept** [comment]
Does this only happen when you run `npm run package-win`?

Could you post the full error (with backtrace, etc.)?

**Comment by MonkeyChap** [comment]
npm start doesn't like 2 digit version

electron-packager . --overwrite --icon=./icons/i256.icns
... doesn't like 3 digit ones.

npm run package-mac just doesn't work, and I've given up the will to live trying to figure out why, when the command prompt alternative does.

**Comment by malept** [comment]
> Could you post the full error (with backtrace, etc.)?

The message "npm ERR! Cannot read property '0' of undefined)" isn't enough context to be able to help.

**Comment by MonkeyChap** [comment]
Packaging app for platform darwin x64 using electron v1.6.12
Command failed: npm prune --production
npm WARN config-app@0.0.1 No repository field.
npm WARN config-app@0.0.1 license should be a valid SPDX license expression

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ian/.npm/_logs/2017-09-02T16_37_17_178Z-debug.log

Ians-MacBook-Pro-2:config-current ian$ electron-packager . --overwrite --icon=./icons/i256.icns
Packaging app for platform darwin x64 using electron v1.6.12
Wrote new app to /Users/ian/Documents/Development/config-current/config-app-darwin-x64

**Comment by MonkeyChap** [comment]
npm start
npm ERR! Invalid version: "0.1"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ian/.npm/_logs/2017-09-02T16_41_13_821Z-debug.log

**Comment by malept** [comment]
> Command failed: npm prune --production

What version of NPM is this? There is a known bug in NPM when you use NPM 5.3.0.

> A complete log of this run can be found in:

Could you attach the logs to this issue?

**Comment by MonkeyChap** [comment]
It is indeed 5.3.0 !

Any suggestion on a better version to run ?

**Comment by malept** [comment]
Try 5.4.0. If that doesn't work, try 4.x.

**Comment by MonkeyChap** [comment]
Thanks !
