### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory。

### ISSUE THREAD

**Issue by ochukai** [electron-userland/electron-packager#723]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

when i input  `DEBUG=electron-packager`,

![tim 20170905110538](https://user-images.githubusercontent.com/2998925/30043477-28b643a6-922a-11e7-8eca-26a32dfc9fdb.png)

Below is my error info:

![tim 20170905095112](https://user-images.githubusercontent.com/2998925/30043393-aa49443c-9229-11e7-9f43-7646d5ef449c.png)

I 

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager ./ Weiwei --platform=win32 --arch=ia32 --out=out --no-prune
```

What could i do to package this app ? thank you~

**Comment by ochukai** [comment]
System info：

![tim 20170905111208](https://user-images.githubusercontent.com/2998925/30043630-120bc544-922b-11e7-9152-464414587863.png)

**Comment by ochukai** [comment]
How could I turn on debug mode in window ?

**Comment by malept** [comment]
> How could I turn on debug mode in window ?

https://github.com/visionmedia/debug#windows-note

**Comment by malept** [comment]
Do you have large files in your app directory?

**Comment by malept** [comment]
How much free memory (RAM) do you have when you run Electron Packager?

**Comment by ochukai** [comment]
Thank you, I resolve this problem by ignore node_modules, ^.^  @malept

**Comment by ochukai** [comment]
I change the build command to

```
electron-packager ./ Weiwei --all --out=./out --prune --overwrite --ignore=src/* --ignore=node_modules/*
```

**Comment by NAIVEddd** [comment]
I think `--ignore=node_modules` should added by default.
It's so helpful, thanks.

**Comment by malept** [comment]
If you ignore `node_modules` you will lose any third party modules you've added to your Electron app.

**Comment by NAIVEddd** [comment]
You are right. But how to fix it? My computer don't have enough memory for `electron-packager`. The `node_modules` size is 3 GB ~

**Comment by malept** [comment]
There are several things you can do:

0. If possible, use Node 8 or higher. Those versions of Node have a more efficient way to copy files.
1. Make sure you're using the latest version of Electron Packager.
2. Make sure that only the dependencies that you need for your app to run are in the `dependencies` section of `package.json`. Anything relating to packaging/testing/etc., *including* `electron`, need to be in the `devDependencies` section.
3. Wipe out `node_modules` and reinstall it, just to make sure that there's no extraneous dependencies.
4. Make sure that the free space on the drive that you're creating the package is at least the same size as the app.
