### ISSUE TITLE
In the Windows system,electronic-packager error Command failed: npm prune --production

### ISSUE THREAD

**Issue by caishengmao** [electron-userland/electron-packager#725]
In the Windows system,Use the electronic-packager to packager,Prompt erro:
Command failed: npm prune --production
npm ERR! May not delete: C:\Users\ADMINI~1\AppData\Local\Temp\2\electron-packager\win32-ia32\Fetion-win32-ia32\resources\app\node_modules\.bin
How to solve？Thanks!

**Comment by caishengmao** [comment]
@MarshallOfSound   npm version 5.3.0

**Comment by MarshallOfSound** [comment]
@caishengmao Please update to `5.4.0`, this is a known issue with `npm@5.3.0`
