### ISSUE TITLE
Path to resources changes through packaging

### ISSUE THREAD

**Issue by waimaster** [electron-userland/electron-packager#726]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
When reading a file from the base directory of your app, you can usually just do `fs.readFileSync("data.json")` or similar. After packaging the path changes to `fs.readFileSync("resources\app\data.json")` and previously working code will break.

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager .
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**
This can easily be tested by installing quick start and changing renderer.cs to somthing like this: 
```
var a = require("fs");
var b = a.readFileSync("data.json", "utf8");
document.writeln(b);
```
Then package and the script won't work anymore. There are obviously easy workarounds for this, like just changing the path before packaging, but that can become a time consuming and repetitive task. I also spent a couple hours to find this out in the first place.

**Comment by MarshallOfSound** [comment]
Whenever you try to load a path in node.js through the `fs` API's, if you provide a non-absolute path it is resolved relative the the CWD of your application.  In dev this is the root of your app, in pacakged this is wherever your `exe` or `.app` file is.

You need to resolve absolute paths yourself using `path.resolve(__dirname, 'data.json')`

**Comment by Jarmahent** [comment]
@MarshallOfSound Setting Absolute path is not working for me, I have a db file in a directory and I added it to my build file as:

```json
"extraResources": [
      "app/clipboarddb/copydata.db",
    ]
```

When I look at the packaged apps resources I see the file, but in the Handler I have:

`const dbPath = path.resolve(__dirname, 'copydata.db')`

And I still get Error:

`Cannot open Database because the directory does not exist`

**Comment by malept** [comment]
If you put `copydata.db` into [`extraResource`](https://github.com/electron-userland/electron-packager/blob/v12.1.1/docs/api.md#extraresource), it's in the resources directory, not the app directory, per the docs. The resources directory is usually one folder above the packaged base app directory, if I remember correctly.
