### ISSUE TITLE
how to get the start up parameter

### ISSUE THREAD

**Issue by hackboy** [electron-userland/electron-packager#728]
hi
I use the electron-packager to package my app,
after that, i edit my regedit  and add a custome protocle so i can start the app from browser,
but i cant get the paramter from process.argv after start the app from browser
how can i get the paramter correctly

**Comment by malept** [comment]
This seems less like a question about Electron Packager and more a question about Windows custom protocols. I just made a quick app with [electron-quick-start](https://github.com/electron/electron-quick-start/) that proves that a packaged app can access its `process.argv` _(note: these instructions work for Linux/macOS, porting to Windows is an exercise for the reader)_:

1. `git clone https://github.com/electron/electron-quick-start`
2. `cd electron-quick-start`
3. `npm install --save-dev electron-packager`
4. `echo 'console.log(process.argv)' > main.js`
5. `$(npm bin)/electron-packager .`
6. `electron-quick-start-linux-x64/electron-quick-start --arg1 --arg2` _(packaged directory name varies based on host platform/arch)_

Output for me on Linux:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
[ '/path/to/packaged/electron-quick-start',
  '--arg1',
  '--arg2' ]
```

You'll probably have better luck with your question in one of the [community forums](https://github.com/electron/electron#community), where more people are around that might have the knowledge to answer your question.
