### ISSUE TITLE
Don't Compile File When Creating Package?

### ISSUE THREAD

**Issue by puremana** [electron-userland/electron-packager#730]
* [ x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I have read the docs but couldn't find a solution.
My program I want to package reads from and writes to a JSON file that the user must also have access to. 
When I used require to read the file it automatically got compiled and I wasn't able to write to it. When I used fs.read the packaged app fails to load and provides the error message (even when I copy the file into the directory)
![image](https://user-images.githubusercontent.com/2869411/30507427-a261548c-9ad8-11e7-8baa-a685729477c2.png)
How do I go about achieving this where both the program and user can use the file?

**Comment by puremana** [comment]
Link to source, may help https://github.com/puremana/IOU-Helper-2.0/blob/master/render.js
Line 14 -> 28

**Comment by malept** [comment]
I can't reproduce this behavior on Linux. Here's my minimal testcase: https://github.com/malept/electron-quick-start/tree/electron-packager-730

Instructions:

1. `git clone https://github.com/malept/electron-quick-start`
2. `cd electron-quick-start && git checkout electron-packager-730`
3. `npm install`
4. `npm start` (should pop up an alert with a JSON value)
5. `npm package`
6. `electron-quick-start-linux-x64/electron-quick-start` (obviously the folder name differs based on your host platform and arch, on Windows it would be something like `electron-quick-start-win32-x64\electron-quick-start`) - this should have the same behavior as step 4.

Could  you please see if this testcase produces the same errors as your app? If not, could you please create a minimal testcase that does reproduce the behavior?

**Comment by puremana** [comment]
You meant` npm run package` for 5. correct?
I followed your example and it worked. After various attempts at trying to understand why my project was then not working, I **reinstalled nodejs** and it finally packaged. Thanks.

**Comment by malept** [comment]
Yeah, that's what I meant for step 5.
