### ISSUE TITLE
Different verison of Electron downloaded, ignoring the one specified in package.json

### ISSUE THREAD

**Issue by gozzoo** [electron-userland/electron-packager#736]
In my `package.json` of my project I have

```
  "dependencies": {
   ....
    "electron": "^1.6.14",
   .....
  }
```

Despite that when I run electron-builder it downloads the latest Electron distrubution  (1.7.8)  and uses it when packaging This is a big problem for me because I have native modules that are compiled and bound to this specific version of electron with electron-builder.

How can I specify when runing electron-packager that I want to use the current versino of Electron?

**Comment by develar** [comment]
If you use electron-builder — electron-builder prefer to use locally installed Electron version to match what do you get during development. So, if you use npm, please remove node_modules and install it again. If you use reliable and recommended yarn, just `yarn`.

**Comment by malept** [comment]
@develar that is not relevant information, please do not do this.

@gozzoo According to the [Electron Versioning guide](https://electron.atom.io/docs/tutorial/electron-versioning/#electron-versioning-1):

> Due to its dependency on Node and Chromium, it is not possible for the Electron project to adhere to a SemVer policy. You should therefore always reference a specific version of Electron.
> [...]
> We recommend that you set a fixed version when installing Electron from npm:
>
> `npm install electron --save-exact --save-dev`
>
> The `--save-exact` flag will add `electron` to your `package.json` file without using a `^` or `~`, e.g. `1.6.2` instead of `^1.6.2`. This practice ensures that all upgrades of Electron are a manual operation made by you, the developer.
>
> Alternatively, you can use the ~ prefix in your SemVer range, like ~1.6.2. This will lock your major and minor version, but allow new patch versions to be installed.
