### ISSUE TITLE
MAS-signed executable hangs right after launch

### ISSUE THREAD

**Issue by goodhyun** [electron-userland/electron-packager#739]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

I just updated electron-packager up to 9.1.0 from 8.3.0
However, the MAS-signed executable hangs right after launch.
After some investigation, I found that the following option doesn't seem to be working out:
`'extend-info': {'ElectronTeamID': '12345678'},`
Obviously, the resulting app's Info.plist doesn't contain that line, and successive codesign is causing some problems.

We had to roll back to 8.3.0, where we didn't have that issue as of now.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
> After some investigation, I found that the following option doesn't seem to be working out:
> `'extend-info': {'ElectronTeamID': '12345678'},`

Since it looks like you're using the JavaScript API, it should be noted that one of the changes between 8.x and 9.x was that [hyphenated option names were replaced with more idiomatic camelCased names](https://github.com/electron-userland/electron-packager/blame/v9.0.0/NEWS.md#L41-L42). The hyphenated names were deprecated in 8.6.0.

So, if you use `extendInfo: { ... }` instead of `'extend-info': { ... }`, it should work.
