### ISSUE TITLE
 Error: ENAMETOOLONG: name too long, unlink

### ISSUE THREAD

**Issue by devarshjoshi** [electron-userland/electron-packager#741]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I saw this issue #396 and i followed the instructions provided there. I cleaned out the output but I am still seeing this issue. 

 "devDependencies": {
    "electron": "^1.7.6",
    "electron-installer-debian": "^0.6.0",
    "electron-installer-dmg": "^0.2.1",
    "electron-packager": "^9.1.0"
  },
  "dependencies": {
    "electron-pubsub": "^0.2.2",
    "mustache": "^2.3.0"
  }

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
 Error: ENAMETOOLONG: name too long, unlink app/electron-packager/linux-x64/myapp-linux-x64/resources/app/electron-packager/linux-x64/myapp-linux-x64/resources/app/electron-packager/linux-x64/myapp-linux-x64/resources/app/electron-packager/linux-x64/myapp-linux-x64/resources/app/electron-packager/linux-x64/myapp-linux-x64/resources/app/electron-packager/linux-x64/myapp-linux-x64/resources/app/electron-packager/linux-x64/myapp-linux-x64/resources

```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager . myapp --platform linux --arch x64 --out dist/ --overwrite
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Delete the `electron-packager` folder from your toplevel app folder and try again.

**Comment by devarshjoshi** [comment]
I have been doing that to no avail :(

**Comment by malept** [comment]
Add `--ignore=electron-packager` to your command line, then.

**Comment by devarshjoshi** [comment]
@malept awesome that helped!! thanks.
