### ISSUE TITLE
Use different package.json

### ISSUE THREAD

**Issue by gozzoo** [electron-userland/electron-packager#743]
I wan the packaged application to use different `package.json` than the original one. I want to strip `dependencies`, `devDependencies `and `scripts`, to change `main `property (the one in the dist folder).

How can I do that

**Comment by malept** [comment]
You can use the [`afterCopy` hook](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#aftercopy) to manipulate the `package.json` file that will be packaged. Please note that you will need to use the API, rather than the command line, to use the hook.

**Comment by umairfarooq44** [comment]
@malept  can you please give example to use aftercopy hook and how to give package.json path

**Comment by malept** [comment]
`package.json` should be in `path.join(buildPath, 'package.json')`.

**Comment by umairfarooq44** [comment]
Thanks a lot. I solved my issue by giving my directory in "dir" option and manually coping my package.json to that directory
