### ISSUE TITLE
Build zip file with version in the name

### ISSUE THREAD

**Issue by gozzoo** [electron-userland/electron-packager#744]
I'd like my final build instead of direactory to be a compressed file. I also want to be able to keep multiple releases of my app. I want the name of the build to include the version, like this:

` ${app-name}-v${version}-${platform}-${arch}.zip`

How should I do that?

**Comment by malept** [comment]
Thanks for filing an issue, but building ZIP files is outside the scope of Electron Packager. You should be using [`electron-installer-zip`](https://github.com/mongodb-js/electron-installer-zip) or [Electron Forge](https://github.com/electron-userland/electron-forge) instead.

**Comment by develar** [comment]
@gozzoo Better to use AppImage for Linux and portable for Windows — electron-builder can produce it ([info how to use electron-packager with electron-builder](https://github.com/electron-userland/electron-builder#pack-only-in-a-distributable-format)).
