### ISSUE TITLE
Electron packager should throw error if package.json not found in source directory

### ISSUE THREAD

**Issue by bonzzy** [electron-userland/electron-packager#748]
* [ X ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ X ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
```
When building windows exe file using node if package.json is not found in source directory (dir), electron-packager tries 
to find it by going to parent folder recursively until finds any package.json. 
If found package.json has "electron" dependency electron-packager it
just builds that parent folder where package.json is found. 
I think that proper way should be throwing an error if you source folder is not 
prepared properly, not trying to build something else and finish with success.
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
dir: string, 
out: string, 
platform: 'darwin', 
overwrite: true, 
arch: 'x64'
```

**Comment by malept** [comment]
Thanks for filing an issue, but this behavior is by design - there are use cases where this is desired. Please see https://github.com/electron-userland/electron-packager/issues/37 where the feature was first discussed, and https://github.com/electron-userland/electron-packager/pull/94 where the initial implementation was discussed.

**Comment by bonzzy** [comment]
in [#37](https://github.com/electron-userland/electron-packager/issues/37) I see that the problem was configuring package.json in too many places.
But I am not sure why whould electron-packager even try to build wrong path where package.json is found.
Current project structure is something like this: apps/app1, apps/app2
Apps folder has package.json and I am trying to build app1. Since electron-packager is recursively trying to find package.json it thinks that it needs to build "apps" folder, not "apps/app1". So it doesn't build my app, but builds somehow apps folder which creates executable file which is errored.
I am worried that this kind of behaviour could be misleading.

**Comment by malept** [comment]
It should only select a given `package.json` if `electron` is found in either `dependencies` or `devDependencies`. Why does your top-level `package.json` have `electron` as a dependency if it's not an Electron app?

**Comment by bonzzy** [comment]
Because in apps folder there are many similar `electron` applications which share the same `package.json`. In this case it doesn't make sense to separately init `npm` in all applications, so we use apps folder for this.

**Comment by malept** [comment]
You may be better off using an internal (private) module that contains common dependencies, rather than a top-level `package.json`.

**Comment by bonzzy** [comment]
Thank you for advice. 
I would propose that if `package.json` is not found in source directory than `electron-packager` should at least output a warning in console saying something like

> package.json not found in source dir, searching recursively. 

Just for information for user.

**Comment by malept** [comment]
Unfortunately, Electron Packager doesn't know that information, all of that logic is delegated to [`get-package-info`](https://www.npmjs.com/package/get-package-info).
