### ISSUE TITLE
Why the package is so large?

### ISSUE THREAD

**Issue by Triple-Z** [electron-userland/electron-packager#752]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I download the `electron-quick-start` (just a Hello World app), and pack it by `electron-package` in linux.
Then I found its size is approximately **280MB**. I think it is too large for a Hello World app.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Packaging app for platform linux x64 using electron v1.7.9
Wrote new app to pack/electron-quick-start-linux-x64
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager . --platform=linux --arch=x64 --overwrite --out=pack
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

I just wonder whether that size for electron is normal or not... It's too large to distribute...

**Comment by malept** [comment]
I did a quick check with electron-quick-start. If you use Electron 1.6.15, the output directory is 123MB.

In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by Triple-Z** [comment]
@malept `electron-quick-start` app indicates that my `node.js` version is 7.9.0, `chromium` version is 58.0 and `electron` version is 1.7.9.
![image](https://user-images.githubusercontent.com/16285716/32692601-f29ef432-c755-11e7-8833-5ab04d04e8ba.png)
![image](https://user-images.githubusercontent.com/16285716/32692603-05b7006e-c756-11e7-8c75-bd47a3aeda9b.png)

**Comment by Triple-Z** [comment]
This is the package.json.
```json
{
    "name": "electron-quick-start",
    "version": "1.0.0",
    "description": "A minimal Electron application",
    "main": "main.js",
    "scripts": {
        "start": "electron .",
        "dist": "electron-packager . --platform=linux --arch=x64 --overwrite --out=pack"
    },
    "repository": "https://github.com/electron/electron-quick-start",
    "keywords": [
        "Electron",
        "quick",
        "start",
        "tutorial",
        "demo"
    ],
    "author": "GitHub",
    "license": "CC0-1.0",
    "dependencies": {
        "electron": "~1.7.8"
    },
    "devDependencies": {
        "electron-packager": "^9.1.0"
    }
}
```

**Comment by Triple-Z** [comment]
![image](https://user-images.githubusercontent.com/16285716/32692653-e7628bd2-c756-11e7-9a33-7708797fd1f9.png)

And I still got **270MB** after changing electron version to 1.6.15.

**Comment by malept** [comment]
I can't reproduce this. Here are my steps, with truncated output:

```shell
$ git clone https://github.com/electron/electron-quick-start
# [... git output ...]
$ cd electron-quick-start
$ npm install
# [...]
$ npm install --save-dev electron-packager
# [...]
$ $(npm bin)/electron-packager . --overwrite --out=pack
Packaging app for platform linux x64 using electron v1.6.15
Wrote new app to pack/electron-quick-start-linux-x64
$ du -sh
123M	pack
```

My guess is that you have some lingering extra packaged application somewhere in your app directory that needs to get deleted before you package.

**Comment by Triple-Z** [comment]
@malept  It's like a magic! I have tried your method, and its size is reduced to **141 MB** .
If I use the `--asar` option, it would reduce to **136 MB**.

And I find the differents between these methods is I have put `electron` into `devDependencies` instead of `dependencies` in `package.json`.
- If I put `electron` into `dependencies`, the final package size will be **265 MB**;
- If I put `electron` into `devDependencies`, the final package size will be reduced to **136 MB**, this size is close to yours.

I wonder what's the main difference between `dependencies` and `devDependencies`...

**Comment by Triple-Z** [comment]
Another interesting result: if I use `cnpm` instead of `npm` to install packages, the distribution app will be much larger than before. I test it by `npm` with the same way, it produce **365 MB** directory.

Maybe this is related to the structure of the `node_modules` which generated by `npm` or `cnpm`.
