### ISSUE TITLE
How do I properly delete files before packaging?

### ISSUE THREAD

**Issue by AlaShiban** [electron-userland/electron-packager#754]
I'm trying to remove some platform specific node binaries prior to finishing the packaging of my Electron app. What's the proper way to do so? (.exe's for darwin, non .exe's for win32 as an example)

I've tried using the afterCopy hook, and the afterPrune hook, and I've double checked that the paths I'm using in the hook implementation are correct (and I synchronously delete the files I'm after), but they still show up in in the output folder/package

What the proper way to approach this? Thanks!

**Comment by malept** [comment]
I would set `ignore` to be a `Function`, per https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore

Pseudocode example:

```javascript
import packager from 'electron-packager';

const targetPlatform = 'win32';
const packagerOptions = {
  // ...
  platform: targetPlatform
  ignore: path => {
    if (targetPlatform !== 'win32' && path.ends_with?('.exe')) {
      return true;
    } // etc.

    return false;
  },
  // ...
};

packager(packagerOptions);
```
