### ISSUE TITLE
Packaged app not running on raspberry. No output.

### ISSUE THREAD

**Issue by nakvic** [electron-userland/electron-packager#760]
* [ x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

The application packaged with packager does not start on Raspberry Pi 3.
No output while starting the app. 

Packaged with 

electron-packager . --platform=linux --arch=armv7l

Victor

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by malept** [comment]
It would help to know what distro, distro version, and desktop environment you're running on your Raspberry Pi 3, along with the output of `uname -m` to make sure that the arch is correct.

Also, is there any console output if you try to run the Electron app via a terminal window?

**Comment by nakvic** [comment]
Its armv7l. No console output at all :( so I could not identify an issue. I have neither electron nor nodejs, chromium installed on the machine as I think, they all are packed to the release, don't they?
I packed all these on MAC OS and just copied to raspberry. I'm not sure, what am I doing wrong and googling did not give too much. The goal is to pack the app on MAC OS and deploy the release to raspberry with other dependency to be deployed.

Here is console output:

username@RB05:~/electron/assistant-linux-armv7l $ ls -l
total 95444
-rw-r--r-- 1 username raspberry     1060 Nov 20 22:26 LICENSE
-rw-r--r-- 1 username raspberry  1775951 Nov 20 22:27 LICENSES.chromium.html
-rwxr-xr-x 1 username raspberry 55462456 Nov 20 22:26 assistant
-rw-r--r-- 1 username raspberry    24844 Nov 20 22:27 blink_image_resources_200_percent.pak
-rw-r--r-- 1 username raspberry       15 Nov 20 22:26 content_resources_200_percent.pak
-rw-r--r-- 1 username raspberry 12032534 Nov 20 22:26 content_shell.pak
-rw-r--r-- 1 username raspberry 10130560 Nov 20 22:27 icudtl.dat
-rw-r--r-- 1 username raspberry  2002296 Nov 20 22:27 libffmpeg.so
-rwxr-xr-x 1 username raspberry 14323560 Nov 20 22:26 libnode.so
drwxr-xr-x 2 username raspberry     4096 Nov 20 22:27 locales
-rw-r--r-- 1 username raspberry   262947 Nov 20 22:27 natives_blob.bin
-rw-r--r-- 1 username raspberry   140979 Nov 20 22:27 pdf_viewer_resources.pak
drwxr-xr-x 3 username raspberry     4096 Nov 20 22:27 resources
-rw-r--r-- 1 username raspberry  1315500 Nov 20 22:27 snapshot_blob.bin
-rw-r--r-- 1 username raspberry   151829 Nov 20 22:26 ui_resources_200_percent.pak
-rw-r--r-- 1 username raspberry        6 Nov 20 22:27 version
-rw-r--r-- 1 username raspberry    57761 Nov 20 22:26 views_resources_200_percent.pak
username@RB05:~/electron/assistant-linux-armv7l $ 
username@RB05:~/electron/assistant-linux-armv7l $ 
username@RB05:~/electron/assistant-linux-armv7l $ uname -m
armv7l
username@RB05:~/electron/assistant-linux-armv7l $ sudo ./assistant 
username@RB05:~/electron/assistant-linux-armv7l $

**Comment by malept** [comment]
Why are you trying to run it via sudo?

It would help to know what distro, distro version, and desktop environment you're running on your Raspberry Pi 3.

**Comment by nakvic** [comment]
Its actually no matter, "sudo" or not. it does not run either.
I have no desktop environment, just CLI. No GUI.

Here is all other info:

username@RB05:~/electron/assistant-linux-armv7l $ ./assistant 
username@RB05:~/electron/assistant-linux-armv7l $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

username@RB05:~/electron/assistant-linux-armv7l $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

username@RB05:~/electron/assistant-linux-armv7l $ uname -a
Linux RB05 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

username@RB05:~/electron/assistant-linux-armv7l $ uname -r
4.9.35-v7+

username@RB05:~/electron/assistant-linux-armv7l $ uname -a
Linux RB05 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

Victor

**Comment by malept** [comment]
Your problem is that Electron requires an X session running on Linux.
