### ISSUE TITLE
After signing for MAS, app fails to launch and is rejected by MAS

### ISSUE THREAD

**Issue by armandn** [electron-userland/electron-packager#761]
Using electron-packager to create apps for MAS seems to fail and I just can't get the app accepted in the Mac App Store. Previously, I was using NWjs and that was working fine, albeit with more a tedious procedure.

Generating unsigned apps with
`electron-packager ./src MyApp --electron-version=1.6.15 --platform=mas --arch=x64 --asar --app-copyright="(C)2017 Me" --icon=./icon.icns --app-bundle-id=com.my.app --app-category-type=public.app-category.strategy-games --extend-info=./doctypes.plist --overwrite`
works just fine.

In the extended plist I have  `<key>ElectronTeamID</key><string>YNZZT2A9DW</string>` and a `<key>CFBundleDocumentTypes</key> [...]` for handling a doc type.

Now, if I use electron-packager to also sign the app, with
`electron-packager ./src MyApp --electron-version=1.6.15 --platform=mas --arch=x64 --asar --app-copyright="(C)2017 Me" --icon=./icon.icns --app-bundle-id=com.my.app --app-category-type=public.app-category.strategy-games --extend-info=./doctypes.plist --overwrite --osx-sign --osx-sign.identity="3rd Party Mac Developer Application: Me (MYID)" --osx-sign.entitlements=./parent.plist --osx-sign.entitlements-inherit=./child.plist`

Then after signing the app crashes with an error message and this bit in the report `Exception Type:        EXC_CRASH (Code Signature Invalid)`

Running `codesign --verify -vvvv MyApp.app`
results in
```
 --prepared:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--prepared:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/My Helper NP.app
--validated:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/My Helper NP.app
--prepared:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/My Helper.app
--validated:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/My Helper.app
--prepared:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/My Helper EH.app
--validated:/Users/me/Desktop/MAS/My.app/Contents/Frameworks/My Helper EH.app
My.app: valid on disk
My.app: satisfies its Designated Requirement
```
If I sign the app using the script in [Mac App Store Submission Guide](https://electronjs.org/docs/tutorial/mac-app-store-submission-guide) the app launches and then quits immediately without any error message.

Before Electron, I was using NWjs and there the app signed for MAS would run.

**Comment by malept** [comment]
CCing @sethlu because this is signing-specific.

**Comment by sethlu** [comment]
Hi @armandn, `electron-osx-sign` automatically adds `com.apple.developer.team-identifier` to the entitlements file following the code signing workflow for a typical app built from Xcode, which will cause an app code signed for MAS distribution to crash at launch locally. So what you're experiencing is an expected behavior.

I'd recommend checking out [`electron-osx-sign` guide](https://mintkit.net/electron-userland/electron-osx-sign/guide/) to have your app running locally before submitting to iTunes Connect for review.

**Comment by sethlu** [comment]
@armandn if you prefer to manually adjust the settings, you may adjust your entitlements file to include `com.apple.security.application-groups` and call `electron-osx-sign --no-pre-auto-entitlements` to skip the automation.

@malept there's a little incompatibility with pumping the opts to `electron-osx-sign` I think... Calling `electron-packager --osx-sign.some-thing` could result in `osxSign.someThing`. Would it be better for `electron-osx-sign` to follow a similar format or to adjust `electron-packager`'s argument parsing?

**Comment by malept** [comment]
> there's a little incompatibility with pumping the opts to `electron-osx-sign` I think... Calling `electron-packager --osx-sign.some-thing` could result in `osxSign.someThing`. Would it be better for `electron-osx-sign` to follow a similar format or to adjust `electron-packager`'s argument parsing?

@sethlu Darn, I was hoping that my argument parser changes didn't create side effects like that. It would be nice if you could add support for that, but if you don't I understand and will have to figure out how to fix that.

**Comment by sethlu** [comment]
@malept I think I can update `electron-osx-sign` some time to allow either forms of arguments... In the mean time users may interact with `electron-osx-sign` for the full customizations.

By the way I just posted some notes around codesigning for local testing and the expected failing behavior due to `com.apple.developer.team-identifier` following the Xcode workflow: https://github.com/electron-userland/electron-osx-sign/commit/1ca1ea269331ada9325bfb0b982348dc7c184cff

**Comment by armandn** [comment]
Thanks for the responses.

> which will cause an app code signed for MAS distribution to crash at launch locally. So what you're experiencing is an expected behavior.

I saw that in the guide. However, **the signed app is also crashing at launch for the reviewers, resulting in it being rejected**!

Also, in my experience with NWjs (and Flash/AIR before that) the signed app would be rejected by Gatekeeper, but wouldn't crash outright.

I'll experiment with `electron-osx-sign` and see what happens...

**Comment by sethlu** [comment]
@armandn did Apple send back with some details regarding the crashing at reviewing? I'm wondering if the version signed for development works locally? If you don't mind sharing a debug log with `export DEBUG=electron-osx-sign*` printed from `electron-osx-sign` I can help debug what may have caused the issue. 😺 Feel free to either [open an issue](https://github.com/electron-userland/electron-osx-sign/issues/new) under `electron-osx-sign` or continue the discussion here.

**Comment by armandn** [comment]
Apple says this:

> Specifically, App does not launch. After momentarily the icon appeared on Dock, app quits. No crash log generated. 

I'll investigate further.

**Comment by usergit** [comment]
@armandn did you solve the problem, I am experiencing the same rejection from the app store reviewers

**Comment by sethlu** [comment]
@usergit I think one way to test the app's behavior is to test run a development-signed version on a different machine so dependency issues may be investigated, if that's what's causing the crash?
