### ISSUE TITLE
Hangs and consumes 4GB+ of RAM when copying 32GB+ of files

### ISSUE THREAD

**Issue by bitwombat** [electron-userland/electron-packager#762]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
electron-packager appears to hang, with the spawned node process using up more and more RAM (more than 4GB).

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
  electron-packager Electron Packager 10.1.0 +0ms
  electron-packager Node v8.9.1 +2ms
  electron-packager Host Operating system: linux (x64) +0ms
  electron-packager Packager Options: {"_":[".","UF"],"all":false,"deref-symlinks":true,"derefSymlinks":true,"download":{"strictSSL":true},"overwrite":true,"prune":true,"quiet":false,"platform":"win32","arch":"ia32","electron-version":"1.7.9","electronVersion":"1.7.9","icon":"/www/uf/checkout/trunk/resource/platform/desktop-app/dist/win/resources/uf-icon.ico","out":"/data/uf-dist/work/electron_builds","tmpdir":"/data/tmp","dir":".","name":"UF","protocols":[]} +0ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: ia32 +0ms
  electron-packager Inferring appVersion from version in /data/uf-dist/work/electron/package.json +0ms
  electron-packager Application name: UF +25ms
  electron-packager Target Electron version: 1.7.9 +0ms
  electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt(-compile)?($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/data/tmp/electron-packager' ] +0ms
  electron-packager Downloading Electron with options {"strictSSL":true,"platform":"win32","arch":"ia32","version":"1.7.9"} +0ms
Packaging app for platform win32 ia32 using electron v1.7.9
  electron-packager Creating /data/tmp/electron-packager/win32-ia32-template +18s
  electron-packager Extracting /home/gbell2/.cache/electron/electron-v1.7.9-win32-ia32.zip to /data/tmp/electron-packager/win32-ia32-template +1ms
  electron-packager Initializing app in /data/tmp/electron-packager/win32-ia32/UF-win32-ia32 from /data/tmp/electron-packager/win32-ia32-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/data/uf-dist/work/electron_builds' ] +19s

```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
. UF --platform=win32 --arch=ia32 --electron-version=1.7.9 --overwrite --icon=$RESOURCES/uf-icon.ico --out=$DIST/work/electron_builds --tmpdir=/data/tmp`
```

Same with `--arch=x64 --no-prune --no-deref-symlinks`

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

Unable to provide a testcase - application has 32 GB of multimedia content.  The above command line worked last year with electron v1.4.10 (which behaves as 1.7.9 does today).

Without the huge content directory, electron-packager finishes, no problem.

System is Ubuntu 16.04 LTS.

**Comment by malept** [comment]
Try `--no-tmpdir`. Otherwise I'm not really sure what would cause an increase in memory usage.

**Comment by malept** [comment]
It would help to know what version of Electron Packager worked vs the version you're currently using.

**Comment by bitwombat** [comment]
I'm having luck moving the large multimedia content directory into place _after_ packager's done its thing.  Should there be any consequences to doing that?

> It would help to know what version of Electron Packager worked vs the version you're currently using

Agreed, unfortunately I tried and somehow failed to save off my old node_modules so that I could fall back to it.  Apparently electron-packager was installed somewhere else.

> Try --no-tmpdir. 

Will try.

**Comment by MarshallOfSound** [comment]
@malept Potentially the `fs` changes we made switched from streams to buffers behind the scenes at some point.  (So all this multimedia is being loaded into memory instead of being streamed)

**Comment by malept** [comment]
> I'm having luck moving the large multimedia content directory into place after packager's done its thing. Should there be any consequences to doing that?

There may be consequences if you're building for `darwin` or `mas` and signing your app via `--osx-sign`.

**Comment by malept** [comment]
> Potentially the `fs` changes we made switched from streams to buffers behind the scenes at some point.

@MarshallOfSound in `fs-extra`?

**Comment by bitwombat** [comment]
No difference with --no-tmpdir.

Is moving the 32GB of files into the app dir after the fact OK?

**Comment by malept** [comment]
@bitwombat see https://github.com/electron-userland/electron-packager/issues/762#issuecomment-347064544

**Comment by bitwombat** [comment]
Oops, sorry @malept.  Am building for darwin, but not signing.

**Comment by malept** [comment]
@MarshallOfSound fs-extra appears to use streams, not buffers:

https://github.com/jprichardson/node-fs-extra/blob/f934357bb6a933fc47138e31492b1507bc026ff4/lib/copy/ncp.js#L97-L99

@bitwombat fs-extra (the module that we use for copying folders) is going to use a native `copyFile` function (introduced in Node 8) in its next major release (v5). I've made a branch of Electron Packager in my personal fork that brings in those changes. Perhaps you can try using the latest Node 8 LTS and this branch? It seems like  you're using a globally installed CLI, so here are some instructions on how to install this without disturbing your existing install:

0. Open a new terminal
1. Install [`nodeenv`](http://ekalinin.github.io/nodeenv/)
2. Run `nodeenv --node=8.9.1 /path/to/electron-packager-node8-test` to install Node 8.9.1 locally
3. Run `source /path/to/electron-packager-node8-test/bin/activate` so the terminal will prefer your newly installed Node over the system Node
4. Run `npm install -g https://github.com/malept/electron-packager#fs-extra-v5-experimental` to install the modified Electron Packager
5. Run your Electron Packager command - it should pick the newly installed one

**Comment by bitwombat** [comment]
Thanks for the branch and instructions @MarshallOfSound .  I've got a reasonable workaround and don't have time on this project to experiment further.  I'm happy if you guys are convinced this won't be a problem in the near future.

**Comment by natew** [comment]
@malept would the experimental branch still need the `--no-tmpdir` option?

**Comment by malept** [comment]
@natew it's not required. Wouldn't hurt to try with/without, if you're so inclined.
