### ISSUE TITLE
"Unable to find a valid app" on macOS sometimes despite main script existing, due to permissions

### ISSUE THREAD

**Issue by frankangelone** [electron-userland/electron-packager#763]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please note that the package.json file is in my source directory.  The issue was reported by a user when trying to launch our application on Mac OS X.  When I try to launch the application on Mac (my development machine), I don't run into any errors.**  

**Which version of electron-packager are you using?**

_9.1.0_

**What cli arguments are you passing?**

_electron-packager . --overwrite --platform=darwin --arch=x64 --icon=icon.icns --prune=true --out=release-builds_

**What platform are you running electron-packager on? What platform(s) are you building for?**

_Running on Mac OS X, building for Mac OS X_

**Is there a stack trace in the error message you're seeing?**

_Error: Unable to find a valid app
at Object.<anonymous> (/Applications/TestApp.app/Contents/Resources/electron.asar/browser/init.js:121:9)_

**When possible, please provide instructions to reproduce your problem:**

_The issue occurs for the user when trying to launch the application.  The build process completes successfully._

**Here's what my package.json file looks like:** 

```
{
  "name": "TestApp",
  "version": "2.0.0",
  "description": "Test",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "FJA",
  "devDependencies": {
    "electron": "^1.7.9",
    "electron-installer-dmg": "^0.2.1",
    "electron-packager": "^9.1.0"
  }
}
```

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by frankangelone** [comment]
To reproduce the problem, I built the application using the CLI arguments provided above.  I then used electron-installer-dmg to create an installer for the application.  The user then double clicked the DMG, copied the .app to the Applications folder on their Mac and double clicked the .app file to launch it.  Upon trying to launch the application, that's when the error provided occurred for the user.

However, as mentioned, when I follow these steps, the error does not occur for me.  If you would prefer to have me have the user post a comment here about their exact steps that triggered the error, I can reach out to them.

**Comment by malept** [comment]
In this case, it would be preferable to have a failing minimal testcase that reproduces this error, because the problem space is currently too large.

**Comment by malept** [comment]
Given the information I have, the only reason I can think of as to why it doesn't work is because for some reason, `main.js` is not being copied correctly into the app. This can be checked by looking in the `TestApp.app/Contents/Resources/app` folder.

**Comment by frankangelone** [comment]
Just checked in `../Contents/Resources/app` and I saw the main.js file was copied successfully into the app folder.  I'm going to touch base with the user to see if they have any additional steps to provide that's causing the error.

**Comment by frankangelone** [comment]
The latest update I was provided was that there were permission issues on the application contents.  The application permissions had to be manually reset and repackaged.

**Comment by malept** [comment]
What sort of permission issues? What were the permissions on `main.js` in the package? What is the permissions on `main.js` in the source repo?

**Comment by frankangelone** [comment]
For both `main.js` in the package and source repo, the permissions were read only for everyone.  Only my development machine has read and write access to the `main.js` file.

The user reporting the permission issues handles the rolling out of our applications to our user base.  It appears the issue occurred when he tried to take the package and roll it into the most recent changes.  That's when he had to manually reset all of the application permissions and repackage.  I was told everything worked after that.  It may have been local to his machine when rolling in the new changes of the application where the permission issues occurred.  

We are going to test more to make sure the error message won't pop up now that it's been confirmed it's working.

**Comment by malept** [comment]
This doesn't sound like a bug in Electron Packager to me. I was looking at the source code of the copy method in `fs-extra` the other day, and it copies the permissions of the original file in addition to its contents.
