### ISSUE TITLE
Using yarn as package manager creates yarn.lock within app even when ignored

### ISSUE THREAD

**Issue by jmquigley** [electron-userland/electron-packager#764]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Changing the package manager to use `yarn` reproduces the `yarn.lock` within the app output even when it is ignored.  The `--ignore` will delete the original lock file, but it is then recreated during pruning when `yarn install --production --no-bin-links` is called in [prune.js](https://github.com/electron-userland/electron-packager/blob/master/prune.js).  Adding the option '--no-lockfile' to this cli call would prevent this behavior (I just modified my local copy of the app to try it).  The lock file is not needed for runtime.

**Comment by malept** [comment]
Thanks for catching this. FYI, I'm likely going to drop the `--package-manager` flag in the next major release (within the next several weeks) so even if I add `--no-lockfile` in the meantime, it's not going to hang around for much longer.
