### ISSUE TITLE
Support to manage the languages for mas/darwin builds

### ISSUE THREAD

**Issue by barinali** [electron-userland/electron-packager#767]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
After publishing the app on the mac app store, it seems it supports all possible languages. But we want to define the languages that we can support.

I think we need an argument that we can define the languages which we want. It would be nice if we have this feature in `electron-packager`. In the meantime, I'll achieve this by writing a script which is gonna work after the packing process and remove the not given languages. If this is wanted by @malept and the others also, I may add this support to `electron-packager`.

**Comment by malept** [comment]
I think this would be better off being a plugin for Electron Packager, similar to how [`electron-packager-plugin-non-proprietary-codecs-ffmpeg`](https://www.npmjs.com/package/electron-packager-plugin-non-proprietary-codecs-ffmpeg) uses the `afterExtract` hook. I would be happy to link to the node module once it's published.

My concerns about adding it to the core are the number of people who will use the feature vs. its complexity and its maintenance cost. How would the API option look? How would the CLI argument work?

**Comment by barinali** [comment]
That feature as a plugin sounds not bad. But then, the projects which are using electron-packager via CLI would need to change their approaches. That could be my concern here.

I guess I can't say anything **about the number**. But in my opinion, developers who are developing MacOS application and using electron-packager should be aware of the languages and should be able to manage them. They may have i18n support in their applications, but not for all languages probably. **Its maintenance cost** shouldn't be that much. Those language file/folders are not frequently changing. I think once we develop the feature, it would go for a long while if there is nothing wrong. For CLI argument, we may accept inline comma separated string or a .json file. So it may look like one of these;

- `electron-packager . Sample --languages=en,en_GB,de`
- `electron-packager . Sample --languages=./languages.json`

Then `languages.json` would look like; `["en", en_GB", "de"]`.

Anyway, I need this and would prepare a solution. Would you like to see that plugin in README here if I develop it?

**Comment by malept** [comment]
I'm OK with having this be effectively an API-only feature. It's the same if you need to change ffmpeg or use native modules. (Although, if you use Electron Forge, I think you don't need to use its JavaScript config with these kinds of packager hooks.)

I would gladly link to the plugin in the readme.

**Comment by barinali** [comment]
Hello again @malept, I've created a plugin to meet this need. Here is [the repository URL](https://github.com/barinali/electron-packager-languages) and [the NPM package](https://www.npmjs.com/package/electron-packager-languages). What is gonna happen to this issue is up to you. :)

If there is anything missing that you see, let me know.
