### ISSUE TITLE
--asar flag seems to break CSS background-image

### ISSUE THREAD

**Issue by Alaricus** [electron-userland/electron-packager#773]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Hello! I have a React app that I am trying to package for Windows. The images in my `/public/images/` folder are being used both within `<img>` tags and also within CSS `background-image` styles, for example like this:

```
const bg = 'url("./images/myImage.png")';
<div className="myClass" style={{backgroundImage: bg}}>
```

Everything works great until I try to use the `--asar` flag for the build. While the images within the <img> tags continue to work fine, the CSS backgrounds simply don't display.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
$ npm run build

> goldmine@0.1.0 build C:\Users\Me\Desktop\Electron
> electron-packager . --overwrite --asar --platform=win32 --arch=ia32 --icon=./images/favicon.ico --prune=true --out=release-builds --version-string.CompanyName="Me" --version-string.FileDescription=MyApp --version-string.OriginalFilename=MyApp --version-string.LegalCopyright="Me" --version-string.ProductName=MyAppPackaging app for platform win32 ia32 using electron v1.8.1
Wrote new app to release-builds\myapp-win32-ia32
```

**Comment by malept** [comment]
You should use an absolute path, not a relative path. Please see the following FAQ entry:

https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working
