### ISSUE TITLE
Struggling to solve the relative path issue, despite the FAQ

### ISSUE THREAD

**Issue by ZenoFox** [electron-userland/electron-packager#777]
My app is working as long as I start it using the terminal/cmd line.
Now I've packaged the app using the electron packager, but I get the following two errors:

    Uncaught Exception:
    Error: ENOENT: no such file or directory, open 'settings.json'

And:

    Uncaught Exception:
    SyntaxError: Unexpected token u in JSON at position 0
        at JSON.parse (<anonymous>)
        at ReadFileContext.fs.readFile [as callback] (/Users/zeno/Applications/splyr-cop/dist/splyr-cop-darwin-x64/splyr-cop.app/Contents/Resources/app.asar/main.js:202:21)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

These errors only happen in the packaged version of the app.
I assume it has something to do with the paths of settings.json and billing.json:

    const path = require('path');
    var settings = path.resolve('./settings.json');
    var billing = path.resolve('./billing.json');

[Both .json are placed directly in the folder of the app.][1]

According to the FAQ of the electron-packager, this is a common error [(see here)][2].

  [1]: https://i.stack.imgur.com/UiAKh.png
  [2]: https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working

Recommend is something like this:

> `AppName 

>├── package.json 

>├── data -> somedata.json 

>└── src -> main.js

>In src/main.js, you would access data/somedata.json similar to this:
> 
> 
> 
>     const path = require('path');
>     const jsonFilename = path.resolve(__dirname, '..', 'data', 'somedata.json');
>     console.log(require(jsonFilename));

Also tried using const instead of var, but this just leads to another error. It should be possible for the app to make changes to settings.json.

Line 202 looks like this (202 is: profiles = JSON.parse(data);)

    ipcMain.on('setupUi', function(event) {
      fs.readFile('settings.json', (err, data) => {
                  if(err){throw err;} else{
                  settings = JSON.parse(data);
                  mainWin.webContents.send('setupUi', JSON.parse(data));
                  }
      });
      fs.readFile( 'billing.json', (err, data) => {
        profiles = JSON.parse(data);
        for (p in profiles) {
          switch(profiles[p].country) {
            case 'US':
              profilesUS[p] = profiles[p];
              break;
            case 'UK':
              profilesUK[p] = profiles[p];
          }
        }
      });
    })

I'd really appreciate any help, I've been trying to fix this for hours.

**Comment by ZenoFox** [comment]
Also tried "var settings = path.resolve(__dirname, 'settings.json');" etc., nothing worked.

**Comment by malept** [comment]
Please don't open new issues for the same question (#776).

The JSON parse error means that it's invalid JSON (not an Electron Packager error), so it at least found the file. I would suggest looking for a JSON validator.

In the future, I suggest you ask in one of [Electron's support channels](https://github.com/electron-userland/electron-packager/blob/master/SUPPORT.md). I say this because I have limited time these days to tend to the issue tracker, and you'd get a faster response from more people.
