### ISSUE TITLE
White color screen on Debian Linux armv7l

### ISSUE THREAD

**Issue by patriciovergaratobar** [electron-userland/electron-packager#778]
Hello there,

I have a problem with my application building for Linux armv7l. The problem comes after approximately three days of working application.  The screen went blank. 

![electronpantallaerror](https://user-images.githubusercontent.com/11562776/34046633-a06f1916-e1a5-11e7-89a3-0633f2ca86c0.png)

In the operating system proccess I see the next:

![electronproccerror](https://user-images.githubusercontent.com/11562776/34046722-dd3686a4-e1a5-11e7-925b-b4883dd1de6c.png)

When the application is working good the proccess are: 

![electronproccok](https://user-images.githubusercontent.com/11562776/34047150-325ff7c2-e1a7-11e7-8bd9-7b667f114472.png)
 
my temporary solution for this problem is have a bash script in the operating systema which is checking the proccess of my application  where "--type=renderer" and restart the application when is not working.

the name of my application is consolaview, and the main script is: 

```
const electron = require('electron');
const app = electron.app;
const BrowserWindows = electron.BrowserWindow;
const path = require('path');
const url = require('url');
var mainWindow;
app.on('ready', () => {
    app.commandLine.appendSwitch('disable-web-security');
    let configuracion = {
        width: 840,
        height: 440,
        backgroundColor: '#ededed',
        devTools: false,
        contextIsolation: false,
        autoHideMenuBar: true,
        'node-integration': 'iframe',
        'webPreferences': {
                   'webSecurity': false,
	           'defaultFontSize': 12,
                   'defaultMonospaceFontSize': 13,
	           'zoomFactor': 0.98
        },
        fullscreen: true
    };
    mainWindow = new BrowserWindows(configuracion);
    let conexion = () => {
            mainWindow.loadURL('file://' +  __dirname + '/main.html', {
                mode: 'no-cors'
            });
    };
    mainWindow.on('closed', () => {
        mainWindow = null;
    });
    conexion();
});

app.on('window-all-closed', () => {
  app.quit()
})

```
The version of Electron is: 
electron "1.7.9",
electron-packager "10.1.0"

The info of my environment is:

![info1](https://user-images.githubusercontent.com/11562776/34049990-32da5c1a-e1b1-11e7-87c9-554d851cc797.png)
 
My question is: Exist other solutions for this problem?

**Comment by malept** [comment]
Does this happen in any other target platform/arch, or just armv7l?

**Comment by patriciovergaratobar** [comment]
only happens in armv7l

**Comment by malept** [comment]
This doesn't sound like an Electron Packager specific problem, but rather an issue with Electron proper. I would suggest seeing if anyone else in the [Electron community](https://github.com/electron/electron#community) has this problem, and if necessary, filing a bug in the Electron issue tracker.

**Comment by Camixxx** [comment]
I met same problem on raspberrypi. 
 armv7l.

**Comment by malept** [comment]
This is likely https://github.com/electron/electron/issues/12937 (and not caused by Electron Packager itself).
