### ISSUE TITLE
linux ubuntu 17.10 cannot open shared object file libgconf-2.so.4

### ISSUE THREAD

**Issue by nphias** [electron-userland/electron-packager#779]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

using electron 1.8.1, electron-packager 10.1.0, on mac osx 10.11
files are written to a directory with success message.
later i copy the files to linux and run from the command line ./myapp
I get the error message that a lib is missing (libgconf-2.so.4)
I am guessing there is a reason for the lib missing... its outdated not used by gnome anymore
by doing sudo apt-get install libgconf-2-4 you risk causing problems to gconf-service
the workaround works but needs a fix in the electron-packager code

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
not sure how to do this or if neccessary```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager . myapp --platform=linux --arch=x64 --out=./../dist --overwrite --icon=./assets/ico/linux_icon.icns"
```

**Comment by malept** [comment]
Thanks for filing an issue, but it's not the responsibility of Electron Packager to provide (library) dependency management for your Electron app. I suggest using [Electron Forge](https://github.com/electron-userland/electron-forge) to build `.deb`, `.rpm`, or `.flatpak` files (more coming in the future), all of which handle dependency management via their respective packaging systems.
