### ISSUE TITLE
Mac FileAssociation icon not applying

### ISSUE THREAD

**Issue by Karric** [electron-userland/electron-packager#782]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Using electron-packager to package app for MacOS. App uses custom file type. App builds successfully, files can be launched with app, but files are not displayed with the file type icon that is set in package.json below:

```
... 
"build": {
    "dmg.icon": null,
    "appId": "iTask",
    "fileAssociations": {
      "ext": "test",
      "name": "TEST",
      "description": "A test file",
      "icon": "./Icons/testFile.icns",
      "role": "Editor",
      "isPackage": false
    }
...
```

I've tried icon path in a variety of ways (absolute, relative to build direc, etc), none have worked.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
*COULD NOT GET DEBUG TO WORK*
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager . --icon=build/app.icns --prune=true
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

Test case would be quick start with the build property above added and a dummy icon file.

**Comment by malept** [comment]
Your config appears to be for electron-builder, not Electron Packager.
