### ISSUE TITLE
Packaging the LICENSE file

### ISSUE THREAD

**Issue by arximboldi** [electron-userland/electron-packager#788]
Currently, the packager copies the Electron license into a `LICENSE` file and the Chromium license in LICENSES.chromium`. This is confusing because it seems that the LICENSE file affects the whole package, while it is only about the Electron parts. I suggest the following alternative structure:

- `LICENSE` -- copy the `LICENSE` file at the root of the app being packaged.
- `LICENSE.electron` -- the Electron license.
- `LICENSE.chronium...` (etc.) -- like currently.

What do you think?

**Comment by malept** [comment]
Makes sense.

**Comment by malept** [comment]
I looked into it a bit more. The application's license is already copied into the app directory, along with the application code. It would be more work and code than I'd like to have to maintain in Packager, particularly considering that developers don't all name their license files the same.

You can achieve the same thing by creating an Electron Packager plugin that uses the `afterExtract` and `afterCopy` hooks. The `afterExtract` hook would rename the Electron license file, and the `afterCopy` hook would move the app license file to the same directory as the Electron/Chromium licenses.

If you choose to create the plugin and open source it, I would be happy to link to it in the Packager README.

**Comment by arximboldi** [comment]
> You can achieve the same thing by creating an Electron Packager plugin
> that uses the `afterExtract` and `afterCopy` hooks. The `afterExtract`
> hook would rename the Electron license file, and the `afterCopy` hook
> would move the app license file to the same directory as the
> Electron/Chromium licenses.

Thanks Mark.  I was not aware of that plugin API, that is good enough.

Cheers!

  JP

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es
