### ISSUE TITLE
The appearances are different between dev && release.

### ISSUE THREAD

**Issue by JackieLs** [electron-userland/electron-packager#789]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I found a very strange difference between `run dev` && `run release`.
The only thing that I do in `release` just package the app.
So I could not understand how this happened.The right one is the release version.
**Packager Config**
```
{
	appVersion: pkg.version,
	arch: ['x64'], // ia32, x64, armv7l, all
	asar: os.platform() !== 'win32',
	dir: path.join(__dirname, '../app'),
	icon: path.join(__dirname, '../app/icons/icon'),
	ignore: /renderer/,
	out: path.join(__dirname, '../builds'),
	overwrite: true,
	platform: process.env.PLATFORM_TARGET,
	extraResource: [ 
		path.join(__dirname, '../app/mind/mind_darwin'), 
		path.join(__dirname, '../app/mind/mind_win32.exe')
	]
}
```
**Main Window Config**

```
global.MainWindow = new BrowserWindow({
		show: false,
		width: 750, 
		height: 450,
		resizable: false,
		maximizable: false
})
```

![wechatimg10376](https://user-images.githubusercontent.com/14228179/34930122-ea15259a-fa02-11e7-856c-0cf8ca293100.jpeg)

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by JackieLs** [comment]
![image](https://user-images.githubusercontent.com/14228179/34932277-353a0874-fa0d-11e7-8be3-1f8bf1366ce2.png)
content's width: 819px
![image](https://user-images.githubusercontent.com/14228179/34932306-4f519786-fa0d-11e7-88ab-2689d1bfc5e0.png)
the window's width: 754
I don't under stand this.

**Comment by malept** [comment]
Could you please provide a minimal testcase in code? Screenshots don't help with determining the root cause.

**Comment by JackieLs** [comment]
Sorry this is not your issue.This is the electron's
