### ISSUE TITLE
Overwrite doesn't work if arch and platform not set

### ISSUE THREAD

**Issue by BOOMER74** [electron-userland/electron-packager#792]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

If ```arch``` and ```platform``` is not set, in function https://github.com/electron-userland/electron-packager/blob/5c0113dcf3776991adeeb766981cf1e19759be7b/common.js#L74 they become to ```undefined```, so ```overwrite: true``` ignored, but output folder name is correct 'AppName-win32-x64'.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by BOOMER74** [comment]
@malept I'm using API with options:
```js
const options = {
    appCopyright: "...",
    asar: true,
    dir: `${__dirname}/src/`,
    icon: `${__dirname}/src/logo.ico`,
    ignore: [/\.gitignore/],
    name: "...",
    out: "out/",
    overwrite: true,
    win32metadata: {
        CompanyName: "...",
        FileDescription: "...",
        InternalName: "...",
        OriginalFilename: "...",
        ProductName: "..."
    }
};
```
and additional with ```arch``` and ```platform``` if this arguments passed to script (if they passed, all work fine). No special project required, just start packager script without setup ```arch``` and ```platform```.

Console output have only one difference (with passed arguments):
```
electron-packager Packager Options: { ..., "arch":"x64","platform":"win32" }
```

Full log (without arguments):
```
  electron-packager Electron Packager 10.1.1 +0ms
  electron-packager Node v9.4.0 +2ms
  electron-packager Host Operating system: win32 (x64) +1ms
  electron-packager Packager Options: {"appCopyright":"...","asar":true,"dir":"src/","icon":"src/logo.ico","ignore":[{},{},{},{}],"name":"...","out":".../out/","overwrite":true,"win32metadata":{"CompanyName":"...","FileDescription":"...","InternalName":"...","OriginalFilename":"...","ProductName":"..."}} +0ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in ...\src\package.json +0ms
  electron-packager Inferring target Electron version from electron in ...\package.json +4ms
  electron-packager Application name: ... +33ms
  electron-packager Target Electron version: 1.8.2-beta.3 +0ms
  electron-packager Ignored path regular expressions: [ /\.gitignore/,
  '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt(-compile)?($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"1.8.2-beta.3"} +0ms
Packaging app for platform win32 x64 using electron v1.8.2-beta.3
  electron-packager Creating ...\Temp\electron-packager\win32-x64-template +356ms
  electron-packager Extracting ...\.electron\electron-v1.8.2-beta.3-win32-x64.zip to ...\Temp\electron-packager\win32-x64-template +3ms
  electron-packager Initializing app in ...\Temp\electron-packager\win32-x64\...-win32-x64 from ...\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '...\\out' ] +3s
  electron-packager Pruning modules via: npm prune --production +0ms
  electron-packager Running asar with the options {} +46s
  electron-packager Renaming electron.exe to ....exe in ...\Temp\electron-packager\win32-x64\...-win32-x64 +5s
  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"...","InternalName":"...","OriginalFilename":"...","ProductName":"...","CompanyName":"...","LegalCopyright":"..."},"file-version":"...","product-version":"...","icon":"src/images/logo.ico"} +0ms
  electron-packager Moving ...\Temp\electron-packager\win32-x64\...-win32-x64 to ...\out\...-win32-x64 +628ms
```

**Comment by malept** [comment]
The error is:

```
EEXIST: file already exists, link '/tmp/electron-packager/linux-x64/electron-quick-start-linux-x64' -> 'dir/electron-quick-start-linux-x64'
```
