### ISSUE TITLE
dependency from github not included in build due to NPM pruning

### ISSUE THREAD

**Issue by trickpattyFH20** [electron-userland/electron-packager#796]
* [X] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I need to include a dependency directly from github targeting a specific branch:

`"dependencies": {
    "hoxy": "github:trickpattyFH20/hoxy#forkrelease"
}`

This does not get included in the compiled build using electron-packager
After running the compiled build, I will see this error:

"Uncaught Exception: Error: Cannot find module 'hoxy'"

If I inspect the .app directory, hoxy is indeed missing

**Comment by malept** [comment]
I can't reproduce this. My steps:

```shell
git clone electron-quick-start
cd electron-quick-start
npm install
npm install --save-dev electron-packager
npm install --save 'github:trickpattyFH20/hoxy#forkrelease'
$(npm bin)/electron-packager .
ls electron-quick-start-linux-x64/resources/app/node_modules/hoxy
```

In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by trickpattyFH20** [comment]
Hey @malept thanks for the response

Here are the steps that I am able to reproduce this with:

**Using nodejs versions (8.9.x and 9.x) - macOS 10.13.1**
```
git clone https://github.com/electron/electron-quick-start.git
cd electron-quick-start
npm i
npm i --save-dev electron-packager
npm i --save 'github:trickpattyFH20/hoxy#forkrelease'
echo "const hoxy = require('hoxy')" >> ./main.js
$(npm bin)/electron-packager . --overwrite
```
_Linux test_
```
ls electron-quick-start-linux-x64/resources/app/node_modules/hoxy
```
_macOS test_
```
open ./electron-quick-start-darwin-x64/electron-quick-start.app
```

**Comment by trickpattyFH20** [comment]
I noticed that `electron-packager` runs `npm prune --production` when compiling.
looks like this issue relates to another one here: [https://github.com/npm/npm/issues/19356](https://github.com/npm/npm/issues/19356) 

a temp workaround can be to install github dependencies using the tarball url rather than the .git url

so instead of:
`npm i --save github:trickpattyFH20/hoxy#forkrelease`
use:
`npm i --save https://github.com/trickpattyFH20/hoxy/tarball/forkrelease`

**Comment by malept** [comment]
The other workaround is to use [another package manager setting](https://github.com/electron-userland/electron-packager/blob/v10.1.2/docs/api.md#packagemanager).

Fortunately, pruning via package manager will be removed in a future major version.
