### ISSUE TITLE
npm >= 5's prune reinstalls ignored node modules

### ISSUE THREAD

**Issue by jean-emmanuel** [electron-userland/electron-packager#797]
Since version 5, `npm prune` reinstalls all missing dependencies, this breaks electron-packager's `--ignore` option when `--no-prune` is not set.

**Comment by malept** [comment]
I assume you mean when `--prune` is set, because `npm prune` isn't run when `--no-prune` is set.

Sigh. This is why I'm dropping all support for `npm` and `yarn` when pruning.

**Comment by jean-emmanuel** [comment]
Indeed !

**Comment by malept** [comment]
The current workaround is to set `--no-package-manager`.

**Comment by jean-emmanuel** [comment]
Thanks !
