### ISSUE TITLE
[Feature Request] Splash Screen for Portable executable

### ISSUE THREAD

**Issue by connollykeyjoint** [electron-userland/electron-packager#798]
My understanding is that the portable executable extracts the application to a temp folder to run it.

The problem I have is that the users are stuck waiting for the extraction process before they see the application has launched. The process is rather fast on my flash PC with its SSD and ridiculous CPU clock speeds but when you start running on a PC that is still running a 3rd Gen i3 CPU and HDD that's equally as old, you find that people are impatient and often end up opening the executable 4-5 times before the initial one opens.

Therefore, my proposal is that there be an option to include a splash screen/image that shows when the portable application executable is opened to indicate that something is actually happening in the background.

**Comment by malept** [comment]
Thanks for filing an issue, but this is outside of the scope of Electron Packager. If you'd like a splash screen during installation, you'll want to configure this sort of thing in, for example on Windows, [`electron-winstaller`](https://github.com/electron/windows-installer).

**Comment by montoyaaguirre** [comment]
@malept I think you missed the point here. His use case, is for a portable application (not an installer). The process of unziping the app may take several seconds depending on the app size. We would like for the user to see a splash screen as soon as the app executable is double clicked.
