### ISSUE TITLE
hello , run into a trouble

### ISSUE THREAD

**Issue by TongDaDa** [electron-userland/electron-packager#799]
![screen shot 2018-02-05 at 6 00 05 pm](https://user-images.githubusercontent.com/23241188/35798691-8a980ba8-0a9e-11e8-9c7a-a8df56deffb4.png)

why can in new directory , but in dist directory exception is thrown

**Comment by malept** [comment]
Given that there isn't very much information about your setup, I can only guess as to what's the problem. The best I can come up with is that your `ignore` settings ignored the file that's specified in your `main` key in `package.json`.

If you require more assistance, you'll likely be able to get more people to help you at one of the [community sites](https://github.com/electron-userland/electron-packager/blob/master/SUPPORT.md). There aren't that many people looking at this issue tracker to answer questions.

**Comment by TongDaDa** [comment]
@malept  thanks a lot , very very very good... sure enough is this problem.
