### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by silentpride** [electron-userland/electron-packager#801]
Hi there !
My project use electron-packager , and my package.json is like this:
【"packager":"electron-packager E:/js/project/tim/tim Tim --platform=win32 --arch=x64 --out C:/Users/MIKE.GAO/Desktop/package --version 1.7.5 --overwrite"】
I just run the output file , but it's white screen and nothing.
But when i am in developing , the project is totally OK.
I have no idea about it , can you help me ?

**Comment by malept** [comment]
Unfortunately, I can't know what's wrong without more information about your application. You're better off utilizing one of the [community-driven forums](https://github.com/electron/electron#community), where there are more people around to answer your questions and provide feedback in a timely manner.
