### ISSUE TITLE
Unable to load module that isn't specified in Electron app's package.json

### ISSUE THREAD

**Issue by navdeepio** [electron-userland/electron-packager#808]
I'm trying to package an electron app which resides in `electron-app/` folder in my project folder. The modules are installed in `../node_modules` folder.

I have a module that is required in the preload script(`electron-app/preload.js`) and attached to the `window` object. After packaging this app, electron throws the said error with `module not found`, but if I install the module in the `electron-app` folder, everything works fine.

I've tried to push the `../node_modules` to `module.paths` but to no avail.

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by navdeepio** [comment]
@malept https://github.com/navdeepio/electron-quick-start

Try packaging the app in electron-app folder and running it

**Comment by navdeepio** [comment]
`electron-packager electron-app/ ` from electron-quick-start/ folder

* Two package.json files are there for testing, but feel free to remove the one inside electron-app/

**Comment by malept** [comment]
The problem is that Electron Packager reads the `package.json` file inside of `electron-app`, so it prunes away any module that's not specified in `electron-app/package.json`. If you need to keep `instascan`, you need to add it to that `package.json`.

**Comment by navdeepio** [comment]
@malept tried that too, still not working. Please open it after verifying

**Comment by malept** [comment]
I ran `(cd electron-app && npm install --save instascan)` and it did this:

```diff
diff --git a/electron-app/package.json b/electron-app/package.json
index 8392c12..ccffd28 100644
--- a/electron-app/package.json
+++ b/electron-app/package.json
@@ -15,5 +15,8 @@
     "demo"
   ],
   "author": "GitHub",
-  "license": "CC0-1.0"
+  "license": "CC0-1.0",
+  "dependencies": {
+    "instascan": "^1.0.0"
+  }
 }
```

Then I ran `electron-packager electron-app`, and then `electron-quick-start-linux-x64/electron-quick-start`. I didn't get an error about `instascan` or `mykey`.

**Comment by navdeepio** [comment]
ok, that's the point - instascan is installed and available in the parent directory(electron-quick-start). So to not have two yarn.lock files(one in parent dir and one in electron-app/) I've removed electron-app/node_modules, which I request you to remove yourself

**Comment by malept** [comment]
At this point, I think you should make your webapp into a (private) module and add that into `dependencies` in `electron-app/package.json`. I suggest looking at yarn workspaces to make sure that there's only one yarn.lock, etc. (Although there is currently a bug with workspaces and pruning at the moment.)

**Comment by navdeepio** [comment]
@malept  I agree. But out of curiosity, shouldn't electron-packager be able to resolve the module from node_modules that's one dir up? Especially since module.path contains `electron-quick-start/node_modules`?

**Comment by malept** [comment]
How would it know about those folders? You've specified that the app resides in `electron-app`, not its parent directory. Electron Packager doesn't copy anything in the app's parent directory.
