### ISSUE TITLE
cannot open shared library when running electron-packager binary file

### ISSUE THREAD

**Issue by mase5** [electron-userland/electron-packager#810]
Hi,

When I'm starting my node software, it's executing a python package that have been packaged with `pyinstaller`. Running the python packaged binary file does rise any errors.

Packaging my node software using:
```
electron-packager . myapp --overwrite --asar --platform=linux --arch=x64 --prune=true --out=release
Packaging app for platform linux x64 using electron v1.8.3
Wrote new app to myapp/myapp-linux-x64
```
works fine!

But when I'm running the binary file generated by electron-packager:
`./release/myapp-linux-x64/myapp`
it throws me an error:
```
[19934] Error loading Python lib '/tmp/libpython3.6m.so.1.0': dlopen: /tmp/libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

Any idea how to solve this issue?

**Comment by malept** [comment]
I'm not too familiar with how PyInstaller works, but could you try without the `--asar` flag?

**Comment by mase5** [comment]
That was it :)
