### ISSUE TITLE
.exe does not open a window

### ISSUE THREAD

**Issue by kurisukun** [electron-userland/electron-packager#811]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Hi guys,

I'm new on Electron so I followed some tutorials to start an app quickly. Right now, I'm trying to display datas from a SQLite3 database on screen (so I use the module SQLite3 and Knex). My app runs perfectly with the command electron .
I successfully created a .exe file but when I try to launch it, nothing happens, the window does not open.
First of all, I thought it was a problem from my database which wasn't included but putting it manually in the directory of the app deployed doesn't solve the problem.

Then I tried to see if I was not correctly using electron-packager but it appears when I package other electron apps, the .exe file opens my browser. 

I just run:

electron-packager . App_Test --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="App Test"

EDIT: By running the .exe with the window cmd, I discovered that error:

C:\Users\Chris.BARROS-HENRIQU\Documents\GitHub\Test2\dist\test2-win32-ia32>test2

C:\Users\Chris.BARROS-HENRIQU\Documents\GitHub\Test2\dist\test2-win32-ia32>
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'C:\Users\Chris.BARROS-HENRIQU\Documents\GitHub\Test2\
dist\test2-win32-ia32\resources\app.asar\node_modules\sqlite3\lib\binding\electr
on-v1.8-win32-ia32\node_sqlite3.node'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\Chris.BARROS-HENRIQU\Documents
\GitHub\Test2\dist\test2-win32-ia32\resources\electron.asar\common\reset-search-
paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Chris.BARROS-HENRIQU\Documents\GitHub\Test2\
dist\test2-win32-ia32\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js:4:1
5)
    at Object.<anonymous> (C:\Users\Chris.BARROS-HENRIQU\Documents\GitHub\Test2\
dist\test2-win32-ia32\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js:190
:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (C:\Users\Chris.BARROS-HENRIQU\Documents\GitHub\Te
st2\dist\test2-win32-ia32\resources\app.asar\node_modules\knex\lib\dialects\sqli
te3\index.js:79:12)
    at Client_SQLite3.initializeDriver (C:\Users\Chris.BARROS-HENRIQU\Documents\
GitHub\Test2\dist\test2-win32-ia32\resources\app.asar\node_modules\knex\lib\clie
nt.js:240:26)

Before packaging, I already have launched electron rebuild to make sure my module was the good one for Windows. That does not make sense for me since I don't understand why the command npm install sqlite3 --save.. I've already done it.

**Comment by malept** [comment]
Can you try without the `--asar=true` flag?

**Comment by kurisukun** [comment]
Already tested and it does not change anything, I get the same issue.

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by kurisukun** [comment]
I'm not sure what you're telling me to do:
-using electron-packager with electron-quick-strart and see if I encounter the issue I got?
-using electron-quick-start as a base and code my program with it?

The first option seems not that necessary, in fact, as I said, I tested it on an other programm I got and I didn't get any problem with it.
So I'll try the second option for now

Btw thanks for helping

**Comment by malept** [comment]
I can't help you if I can't reproduce the problem myself.

**Comment by kurisukun** [comment]
Ok so I downloaded electron-quick-start and packaged it with electron-packager. Everything is ok as expected. The file .exe executes correctly and opens the browser. I tested it with the command window. 
What can I do now?

**Comment by malept** [comment]
It could be any number of things. Incrementally add small parts of your codebase to the quick start app until the behavior you describe happens with the packaged app. One possible reason is documented in this [FAQ entry](https://github.com/electron-userland/electron-packager/blob/v11.1.0/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working).
