### ISSUE TITLE
How are Windows exes packaged?

### ISSUE THREAD

**Issue by kusti8** [electron-userland/electron-packager#813]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Hi,

I'm the creator of [proton-native](https://github.com/kusti8/proton-native) and I'm wondering how your Windows packager works. I'm working with @mischnic and @albe-rosado on a packager and so far it's working on Mac and Linux, but I'm wondering how you got electron packaging working with Windows. It seems like you're getting an exe and then modifying it?

Thanks,
Gustav

**Comment by develar** [comment]
electron provides completed executable binary and electron-packager/electron-builder only modifies resources (icons, file properties).

Installers produced by Squirrel.Windows or NSIS (external modules, not part of electron-packager).

**Comment by malept** [comment]
Specifically, in the case of Electron Packager, we use the [`rcedit`](https://github.com/electron/node-rcedit) module (a wrapper for [`rcedit.exe`](https://github.com/electron/rcedit)) to modify the metadata.
