### ISSUE TITLE
How to pass cmd line parameters to stand alone exe file?

### ISSUE THREAD

**Issue by sambits** [electron-userland/electron-packager#816]
I am using the ‘electron-winstaller’ node module to create the standalone exe. I am not getting the cmd line parameters to work on the stand alone exe. here is my code

var argv = require(‘minimist’)(process.argv);

cmd:- AutoFileSender.exe 58748009341a7d5840a51414 sambit@bc.com Sambit Swain 59c9d0c64a4ed3599a59df0b_58748009341a7d5840a51414 sender C:\ConnectUs-SFTSend\ C:\ConnectUs-SFTReceive\ rmrqaF

But if i run the same cmd with the basic unpacked exe (in the win32-ia32 folder) it gets the parameters.

**Comment by malept** [comment]
Thanks for filing an issue. This question is not specific to Electron Packager, so you'll have more luck with asking in one of the [community sites](https://github.com/electron/electron#community), where there are more people around to respond.
