### ISSUE TITLE
electron-packager seems to not include 'electron-store'

### ISSUE THREAD

**Issue by jon-ryan** [electron-userland/electron-packager#818]
Hello forum,

there is a problem with electron-packager I can't resolve. 
I want to use and include the 'electron-store'. 
I installed it with the command: "npm install electron-store -g --save-dev".
In my package.json file the 'electron-store' is listed in the "devDependencies".
when I test my program with "npm start" (I added "start": "electron ." to my scripts list in package.json) everything works just fine.
So I package my project for windows. And before I added the 'electron-store' to my project my .exe worked just fine.
But now, as soon as I open my .exe I get a javascript error in the main process: "cant find module 'electron-store'".
So far, I havn't added any other modules to the project.

I'm feeling very lost, since I'm new to electron.

I appreciate every help.

![capture](https://user-images.githubusercontent.com/37742289/37865169-f056269c-2f78-11e8-8ae8-a8742b813b90.PNG)

**Comment by MarshallOfSound** [comment]
> In my package.json file the 'electron-store' is listed in the "devDependencies".

This is your problem, a "devDependency" is a dependency that is only needed during development, this means when you package your app for production the dependency is removed.  Use `--save` instead of `--save-dev` and everything will work fine

**Comment by jon-ryan** [comment]
sorry, but that didn't work. There is no entry in dependencies being generated, as it was the case in devDependencies. Even if I add the line "electron-store": "^1.3.0" manually to the section "dependencies" it doesn't work.

**Comment by MarshallOfSound** [comment]
It needs to only be in `dependencies` and *not* present in `devDependencies`

**Comment by jon-ryan** [comment]
didn't work

**Comment by jon-ryan** [comment]
I fixed it. Had some issues with my directory

**Comment by jon-ryan** [comment]
I put the index.js and the index.html in the root directory.

**Comment by Eve-Sama** [comment]
It happens to me.

**Comment by dulePan** [comment]
I had the same issue and the way of resolving was:
1. Put modules before those: 
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "run": "^1.5.0",
    "start": "^5.1.0"
Like this:
```
"dependencies": {
    "@openiap/nodeagent": "^0.0.114",
    "@openiap/nodeapi": "^0.0.41",
    "better-sqlite3": "12.1.1",
    "electron-store": "^8.2.0",
    "auto-launch": "^5.0.6",
    "fs-extra": "^11.3.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "run": "^1.5.0",
    "start": "^5.1.0"
  }
```
2. Remove those packages from    "devDependencies": {} list.
