### ISSUE TITLE
"Inheriting" base build options? *QUESTION*

### ISSUE THREAD

**Issue by AliOsseili** [electron-userland/electron-packager#825]
* [ X] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Hello, I was wondering if there was a way in grunt to sort of make a "template" of the options so different builds can be shorter. Right now I have something like this

        'electron-packager': {
            buildWithIMZ: {
                options: {
                    platform        : os.platform(),
                    arch            : os.arch(),
                    dir             : '.',
                    out             : '../gameBuilds/buildWithIMZ',
                    name            : artifactIdIMZ,
                    executableName  : 'run',
                    electronVersion : '1.8.2',
                    asar            : true,
                    overwrite       : true
                }
            },
            buildWithoutIMZ: {
                options: {
                    platform        : os.platform(),
                    arch            : os.arch(),
                    dir             : '.',
                    out             : '../gameBuilds/buildWithoutIMZ',
                    name            : artifactIdNonIMZ,
                    executableName  : 'run',
                    electronVersion : '1.8.2',
                    asar            : true,                  
                    overwrite       : true
                }

but I'd like for it to be like this:

	default: {
		options: {
                    platform        : os.platform(),
                    arch            : os.arch(),
                    dir             : '.',
                    executableName  : 'run',
                    electronVersion : '1.8.2',
                    asar            : true,
                    overwrite       : true
                }
	},         
	buildWithIMZ: {
                options: {
                    out             : '../gameBuilds/buildWithIMZ',
                    name            : artifactId . '-imz'
                }
            },
            buildWithoutIMZ: {
                options: {
                    out             : '../gameBuilds/buildWithoutIMZ',
                    name            : artifactId . '-noimz'
                }
            }

So that all the tasks do is just look at the rest of the options in the one named default then use what they have inside them. Is this possible or a feature to be?

**Comment by malept** [comment]
This seems more like a question about usage with grunt and I'm not very familiar with that integration. You would more likely get an answer if you ask on one of the [community-driven sites](https://github.com/electron/electron#community).
