### ISSUE TITLE
WARNING: Found 'electron' but not as a devDependency, pruning anyway

### ISSUE THREAD

**Issue by sebast1** [electron-userland/electron-packager#827]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I have a problem when package my application.
I have an error message "WARNING: Found 'electron' but not as a devDependency, pruning anyway". Yet electron is good in the devDependency like this :

```
"devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "electron": "^1.8.4",
    "electron-icon-maker": "0.0.4",
    "electron-packager": "^12.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
```

```
> electron-packager . --overwrite --out=release --ignore=e2e/ --platform=darwin --arch=x64

Packaging app for platform darwin x64 using electron v1.8.4
WARNING: Found 'electron' but not as a devDependency, pruning anyway
Wrote new app to release/Rekord-darwin-x64
```

I use npm (instead yarn like electron-builder) :
```
> node -v && npm -version
v6.10.3
5.7.1
```

Thanks for your reply,

sebast1

**Comment by malept** [comment]
That's a warning, not an error. Could you provide the `dependencies` as well?

**Comment by pushkin-** [comment]
I get the same warning and my dependencies are:

    "electron": "2.0.0",
    "find-process": "1.1.1",
    "request": "2.86.0",
    "url-join": "4.0.0"

Additionally, I don't understand the warning. Shouldn't `electron` be a devDependency?

**Comment by malept** [comment]
`electron` should be under `devDependencies`, not `dependencies`.

**Comment by pushkin-** [comment]
@malept Why is that? Isn't `electron` required at runtime?

**Comment by malept** [comment]
@pushkin- Electron Packager bundles Electron into your app, so you don't need the NPM dependency.

**Comment by preethamsridhar** [comment]
Thank you. I had the same issue. Solved it now.

**Comment by z1988hf** [comment]
How did you solve it?

**Comment by malept** [comment]
Move the `electron` dependency from `dependencies` to `devDependencies`.

**Comment by BradPrit09** [comment]
Just do an npm install after moving the package.
