### ISSUE TITLE
`npm prune` runs very slow, but executed every time even unnecessary

### ISSUE THREAD

**Issue by hibiyasleep** [electron-userland/electron-packager#830]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Please describe your issue:

I'm developing on Raspberry Pi 3 Model B, it slow as sucks, I'm really sorry bothing you with this hardware, but I have no replacement due to hardware dependencies.

```
  electron-packager Pruning modules via: npm prune --production +3m
```

this take 3 minutes, nearly 40% of progress. I'm trying to solve #829 and repeating build progress, this progress is too long to just wait. May this step skipped when not nessesary?

### Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.

```
  electron-packager Pruning modules via: npm prune --production +3m
```

### What command line arguments are you passing? Alternatively, if you are using the API, what parameters are you passing to the `packager()` function?

Independent, I think.

**Comment by malept** [comment]
This is not a problem with Electron Packager 12 and above, it does not call out to NPM to prune.
