### ISSUE TITLE
Folders that are not NPM modules but have package.json files are unintentionally pruned

### ISSUE THREAD

**Issue by inukshuk** [electron-userland/electron-packager#845]
As discussed in #844 I've noticed at least one case where a folder (containing a package.json file and nothing else) in a dependency is filtered when packaging an app with the prune option.

Here is a minimal test case:

    $ mkdir tmp
    $ cd tmp
    $ npm init
    $ npm i electron electron-packager --save-dev
    $ npm i redux-saga
    $ $(npm bin)/electron-packager . test --platform=linux

And then:

    $ ls -l node_modules/redux-saga/effects/package.json
    $ ls -l test-linux-x64/resources/app/node_modules/redux-saga/

And note that the effects folder is missing.

EDIT:

I should add that this does not happen in 11.x.

**Comment by malept** [comment]
It's because of this line:

https://github.com/electron-userland/electron-packager/blob/b3c610cd13de72b9b0f22b72c99fb73aa5b53bdb/prune.js#L61

That line needs to be changed so that the check `basename(dirname(pathToCheck)) == 'node_modules'` is added, along with a regression test.

**Comment by malept** [comment]
Fix in #847.
