### ISSUE TITLE
Trying to use nightmare (with an Electron dependency) with pruning

### ISSUE THREAD

**Issue by aixinalei** [electron-userland/electron-packager#846]
i meet the same problem in this question,
this is my package.json:
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "dlJia",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^2.0.0"
  },
  "dependencies": {
    "global": "^4.3.2",
    "cheerio": "^0.22.0",
    "lodash": "^4.17.4",
    "nightmare":"2.10.0"
  }
}

I must need nightmare in my project ,and it need another electron.
but when my package my app , the console push a warning to me:
WARNING: Found 'electron' but not as a devDependency, pruning anyway
it's obvious that it's remove my electron
my command is:electron-packager C:\Users\dljia\Desktop\e2 test --electron-version=2.0.0 --out=C:\Users\dljia\Desktop --overwrite
what should i do?

**Comment by malept** [comment]
I would strongly urge you to figure out a better way to deal with your use case. Having two copies of Electron in an Electron app seems like a really bad idea. Additionally, you'd have to figure out how to dynamically download the correct prebuilt Electron binary if you want to use your app on more than one platform/arch combination.

If you do decide to go through with this and write all of the supporting code necessary for this to work, you should run Electron Packager via the JavaScript API, disable pruning (`prune: false`), and write your own `ignore` function (see the [`ignore` documentation](https://github.com/electron-userland/electron-packager/blob/v12.0.2/docs/api.md#ignore) for how the function should be declared).
