### ISSUE TITLE
Electron linux-mips64el.zip not found using --all

### ISSUE THREAD

**Issue by zJesusJavier** [electron-userland/electron-packager#848]
**Please describe your issue:**

Using **--all** does not work with Electron 2.0.1, I believe linux-mips64el is not longer supported by Electron.

![2](https://user-images.githubusercontent.com/39272785/40247164-7bf9fe12-5a99-11e8-83e5-5c9f52aedc2a.PNG)

**Comment by malept** [comment]
Thanks for filing an issue. This was fixed in https://github.com/electron-userland/electron-packager/pull/843 and will be released when I get some time to do so. In the meantime, the workaround is to not use `--all` or `--platform=linux --arch=all`.

**Comment by malept** [comment]
The fix has been released in version 12.1.0.
