### ISSUE TITLE
win32 / arm

### ISSUE THREAD

**Issue by niklasschroetler** [electron-userland/electron-packager#849]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I want to make an UWP-App for Windows IoT Core on a Raspberry Pi 3. 
For that, I think, the electron-packager has to be able to package apps in the win32/arm format. 

Is there a way to get a win32/arm-compatible output with electron-packager?

Thanks in advance,
Niklas

**Comment by malept** [comment]
According to https://github.com/electron/electron/issues/9456 (which links to a Chromium bug), it sounds like Chromium doesn't support Windows on ARM yet. This would be a blocker for Electron, which is transitively a blocker for Electron Packager. So there is currently no way to bundle an Electron app for win32/arm.
