### ISSUE TITLE
Add filename opt into execute script

### ISSUE THREAD

**Issue by lieutandat** [electron-userland/electron-packager#850]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I think this is a great tool which let me create new mobile app by javascript really fast. And It will be better for me (maybe others) if you could add **filename** flag to execute script rather than use **name** or **productName** for both App title name and excute file name. That filename flag can be set the name of .app file in Mac (same when use executable-name for .exe)

something like this
```
"package:osx": "npm run build-prod & cross-var electron-packager $npm_package_productName --filename=$npm_package_name-$npm_package_version  dist --platform=darwin --arch=x64 --overwrite"
```

**Comment by malept** [comment]
I'm not going to be adding this feature request. Adding a new flag for this would make the renaming code more complicated for the benefit of a small fraction of the users. You can rename the `.app` folder yourself after Electron Packager has completed running in `package:osx`.

**Comment by lieutandat** [comment]
Thank you, I just want to automatic generate file which has version number in that for easier detect with old version. Maybe, I have to do this manual :D

**Comment by malept** [comment]
For updating, you should look at the [Updating Applications guide](https://electronjs.org/docs/tutorial/updates). For differentiating between installer versions on macOS, you should [build DMGs](https://github.com/mongodb-js/electron-installer-dmg) making sure that the `--dmgPath` is set to the name + version of  your app.
