### ISSUE TITLE
Web worker can not run after packaged

### ISSUE THREAD

**Issue by BruceAn1978** [electron-userland/electron-packager#858]
**Please describe your issue:**
The onmessage and postMessage function of web worker can interact well in vs code dev invironment, but the postMessage function can not response to the caller after packaged.

**html page**
_var worker = new Worker('./js/uploader.js');
worker.onmessage = function(evt)
{
console.log('callback:' + evt);
};
worker.postMessage('hello');_

**uploader.js**
_onmessage = function(evt)
{
console.log(evt);
postMessage('world');
}_

**package cmd:**
_electron-packager ./ FileUpload --platform=win32 --arch=ia32 --out ./target --app-version 3.0.0 --overwrite --icon=./app/img/file.ico --ignore=.history --ignore=.vscode --ignore=__recovery_

**Comment by BruceAn1978** [comment]
Is there any other parameters to solve this problem?
or some extra parameters for electron platform to solve this problem?

**Comment by malept** [comment]
Unfortunately, this is not an Electron Packager specific problem but rather an issue with how your app code is written. For assistance with app code, please visit one of the [community forums](https://github.com/electron/electron#community), as more people will be able to help you there.

**Comment by malept** [comment]
I don't have time to debug your code, but if I had to guess, it's probably related to this [Frequently Asked Question](https://github.com/electron-userland/electron-packager/blob/v12.1.0/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working).

**Comment by BruceAn1978** [comment]
Don't close the issue carelessly!!!

I can reduce this problem by the code above: It works well in vs code dev environment, but no any response after packaged.

So I don't think this is a problem of code is written.

**Comment by malept** [comment]
Please read [the answer in my previous comment](https://github.com/electron-userland/electron-packager/issues/858#issuecomment-396116322) which has a link that you should also read.

This is not a bug in Electron Packager.

**Comment by BruceAn1978** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
Thanks for this mesage.the Frequently Asked Question page has few docs and I could not find my solution.                


    On 6/11/2018 12:00，Mark Lee<notifications@github.com> wrote： 


I don't have time to debug your code, but if I had to guess, it's probably related to this Frequently Asked Question.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.




        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by malept** [comment]
> `new Worker('./js/uploader.js');`

This uses a relative path. It should instead be an absolute path.

**Comment by BruceAn1978** [comment]
Thanks a lot.

I will have a try.

**Comment by BruceAn1978** [comment]
It's the problem of absolute path.

Thanks.
