### ISSUE TITLE
Fail to run on NodeJS 10. It says "Node 4.0 or above"

### ISSUE THREAD

**Issue by Wohlstand** [electron-userland/electron-packager#863]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```sh
CANNOT RUN WITH NODE 10.5.0
Electron Packager requires Node 4.0 or above.
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager ./app "xxxxx" --out=dist --package-manager=yarn --platform=win32 --arch=x64 --electron-version=1.7.8 --icon=assets/win/xxxxx.ico
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

I have NodeJS 10.5 installed and I have tried to use yarn build thing to compile some application, however, electron-packager fails. It thinks "10.5" is OLDER than 4.0. What the heck? :rofl:

**Comment by Wohlstand** [comment]
Just now I made analysis of existing code, and I have found next:
```js
var curVer = [4, 0, 0];

var nodeVersionInfo = process.versions.node.split('.').map(function (n) { return Number(n) })
if (nodeVersionInfo < curVer) {
    console.error(nodeVersionInfo + " is smaller than " + curVer);
} else {
    console.error(nodeVersionInfo + " is greater than " + curVer);
}
```

it prints me next:
```
$ node check.js
10,5,0 is smaller than 4,0,0
```

So, it's needed a totally different check of this, it's wrong logic as I see.

**Comment by Wohlstand** [comment]
Okay, I have made the better check which is completely resolves this issue:
```js
var curVer = [4, 0, 0];

function versionOlder(current, needed)
{
    for(var i = 0; i < current.length && i < needed.length; i++)
    {
        if(current[i] == needed[i])
            continue;
        return current[i] < needed[i];
    }
    return false;
}

var nodeVersionInfo = process.versions.node.split('.').map(function (n) { return Number(n) })
if (versionOlder(nodeVersionInfo, curVer)) {
    console.error(nodeVersionInfo + " is smaller than " + curVer);
} else {
    console.error(nodeVersionInfo + " is greater than " + curVer);
}
```
And output now
```
$ node check.js
10,5,0 is greater than 4,0,0
```

**Comment by Wohlstand** [comment]
And the final code:
```js
function versionOlder(current, needed) {
  for (var i = 0; i < current.length && i < needed.length; i++) {
    if (current[i] == needed[i])
      continue;
    return current[i] < needed[i];
  }
  return false;
}

var nodeVersionInfo = process.versions.node.split('.').map(function (n) { return Number(n) });
if (versionOlder(nodeVersionInfo, [4, 0, 0])) {
  console.error('CANNOT RUN WITH NODE ' + process.versions.node)
  console.error('Electron Packager requires Node 4.0 or above.')
  process.exit(1)
}
```

**Comment by Wohlstand** [comment]
Okay, just now I checked your `master` branch, and I see you have already fixed it by using `semver` thing. Version of electron packager at me is `8.7.2` came with npm installation. So, everything must be fine.

**Comment by obendesmond** [comment]
You could also update your electron package to 3.0.8 and electron package manager to 12.1.0.

**Comment by pranayreddy123** [comment]
try to change "electron-packager": to "^12.1.0" in package,json

and run gradle info build.. so that you can see exact issue
