### ISSUE TITLE
linux/arm64 not available

### ISSUE THREAD

**Issue by storm-factory** [electron-userland/electron-packager#865]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I'm wanting to build for linux/arm which the documentation suggests is possible on 12.1.0 but it isn't an available option when i execute

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
$ electron-packager . --appname=wsp_kiosk  --platform=linux --arch=arm64  --version=2.0.0
Unsupported arch arm64; must be one of: ia32, x64
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
 --appname=wsp_kiosk  --platform=linux --arch=arm64  --version=2.0.0
```

Using electron-quickstart I'm trying to package my app for arm but it isn't working.

**Comment by malept** [comment]
Can you make sure what version of Electron Packager you're running? if `electron-packager --version` doesn't print out version numbers, it's too old.

**Comment by malept** [comment]
Also, `--appname` is not a valid parameter.

**Comment by storm-factory** [comment]
Strange, when I run npm list it shows the version as 12.1.0, but electron-packager --version returns nothing. looks like a dependency issue on my end thanks

**Comment by malept** [comment]
I just realized that you're using `--version` to specify the Electron version. This hasn't been the way to specify that parameter since it was [deprecated in 8.5.0](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#850---2017-01-10) and [replaced in version 9](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#900---2017-08-23). You need to use `--electron-version`. Check out `--help` for details.

**Comment by storm-factory** [comment]
Yeah, thanks again, uninstalled/installed the package and it's all working correctly now. Thanks again, obviously i've been using this for a couple years and appreciate what ya'll do!
