### ISSUE TITLE
When running child_process inside packaged app, env vars are different

### ISSUE THREAD

**Issue by larsbs** [electron-userland/electron-packager#866]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

I have an app that's calling a executable located in process.env.PATH. When I'm running the app using electron without packaging it, the PATH has all the information, but when I run the packaged app, PATH only contains: `/usr/bin:/bin:/usr/sbin:/sbin` so of course the executable is not found (it's in a different folder) and it fails.

Running on Mac OS X 10.13.5

**Comment by malept** [comment]
GUI programs (including Electron apps) don't read your shell initialization files because you're not in a shell, you're running it from the macOS window manager. Use [`fix-path`](https://npm.im/fix-path) to get around this limitation.
