### ISSUE TITLE
How to reduce package size

### ISSUE THREAD

**Issue by Devhercule** [electron-userland/electron-packager#867]
Hi,

Is there a possibility to reduce the package size?

Using electron-packager, the size of the result package is 280 Mb?

Is that normal?

Thanks

**Comment by malept** [comment]
This is normal. From [the README](https://github.com/electron-userland/electron-packager#about):

> Note that packaged Electron applications can be relatively large. A zipped, minimal Electron
application is approximately the same size as the zipped prebuilt binary for a given target
platform, target arch, and [Electron version](https://github.com/electron/electron/releases)
*(files named `electron-v${version}-${platform}-${arch}.zip`)*.
