### ISSUE TITLE
Is it possible to have the package folder name to be different from the exe?

### ISSUE THREAD

**Issue by RockGuitarist1** [electron-userland/electron-packager#868]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Hello, I am trying to find out whether or not it is possible to have the packaged folder name different from the exe inside. For example, I package my application and get a folder called `CompanyApp-DEV-win32-ia32`. Is it possible to keep this folder name, but have the exe inside called CompanyApp,? Right now it says CompanyApp-DEV.

Right now I am just using this basic script:

`electron-packager . CompanyApp-DEV --overwrite --asar --prune=true --platform=win32 --arch=ia32`

**Comment by MarshallOfSound** [comment]
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#executablename
