### ISSUE TITLE
Can not make a windows installers

### ISSUE THREAD

**Issue by gasparyanyur** [electron-userland/electron-packager#869]
Hi all. I am trying to make windows installer by running command 
`node installers/windows/createinstaller.js`

but as a response I am getting an error look like this 

> The path or file name is too long. The full file name must be less than 260 characters, and the directory name is less than 248 characters.

Here is my `createinstaller.js`

```
const createWindowsInstaller = require('electron-winstaller').createWindowsInstaller
const path = require('path')



getInstallerConfig()
    .then(createWindowsInstaller)
    .catch((error) => {
        console.error(error.message || error)
        process.exit(1)
    })

function getInstallerConfig() {
    console.log('creating windows installer')
    const rootPath = path.join('./')
    const outPath = path.join(rootPath, 'release-builds')

    return Promise.resolve({
        appDirectory: path.join(outPath, 'AppWin/'),
        authors: 'App App',
        noMsi: true,
        outputDirectory:outPath,
        exe: 'even.exe',
        setupExe: 'AppWin.exe',
        setupIcon: path.join(rootPath, 'system', 'icons', 'favicon.ico')
    })
}
```
Please help to solve this problem! 
Thanks!

**Comment by gasparyanyur** [comment]
Solved! 

Have changed `process.env.NODE_ENV` to `production`

Just run `export NODE_ENV=production` in your `cmd`

**Comment by malept** [comment]
Thanks for filing an issue, but the question nor the answer have anything to do with Electron Packager. You're referring to [`electron-winstaller`](https://github.com/electron/windows-installer) in the script, and Packager doesn't use the `NODE_ENV` environment variable.
