### ISSUE TITLE
Can not make right msi installer

### ISSUE THREAD

**Issue by gasparyanyur** [electron-userland/electron-packager#870]
I am trying to make a `msi `setup file but my `msi `file only shows loading and nothing else. But when open the `Control Panel -> Programs` there is a installed program called `App Machile-Wide Installer`.
So I need to make a real msi file which will ask users to accept some terms and select the disk where the program will installed.

**Comment by malept** [comment]
Making MSI files is outside the scope of Electron Packager. If you need help using `electron-winstaller` (one of the Electron tool packages that creates MSIs), ask for help on one of the [community websites](https://electronjs.org/community).
