### ISSUE TITLE
Is there a way to change CFBundleDisplayName via config?

### ISSUE THREAD

**Issue by odiseo42** [electron-userland/electron-packager#872]
I need to be able to change CFBundleDisplayName without affecting CFBundleName i.e. I want my app menu bar to be other than the one used in the `.app` file and folder, mostly because I use auto updates and I don't want users losing personal data when upgraded to a version with a new productName.

Reading [this issue](https://github.com/electron-userland/electron-packager/pull/438) seems that a proposal to do so was dismissed due to technical difficulties. Has any progress been made about it? is it in the road map? are there any alternative?

**Comment by malept** [comment]
According to the code, `CFBundleDisplayName` corresponds to the `executableName` (`--executable-name` in the CLI) and `CFBundleName` corresponds to the application name.
