### ISSUE TITLE
ENOET - can't find resources in the package

### ISSUE THREAD

**Issue by liverpoologic** [electron-userland/electron-packager#873]
I am trying to package my app for Mac (windows works fine).
When I run the packaged app, the app errors as it cannot find the resource that I have put as an `extra-resource`
I can see the resource in the app under Contents/Resources, and have tried using the filepath `./Contents/Resources/Dict.json` but it still returns ENOET: no such file or directory.
Do you know how I can reference this resource in my code?

`  electron-packager . menu-generator --mac --extra-resource=./resources/Dict.json --extra-resource=./resources/settings.png --overwrite --ignore=\\.gitignore --ignore=./resources --ignore=./release-builds  --ignore=./PDFs --asar=true --platform=darwin --arch=x64 --icon=./resources/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName='Menu Generator'
`

**Comment by malept** [comment]
This is better asked in one of the [community websites](https://electronjs.org/community) since it's not Electron Packager specific.

That being said, you probably want to start by using a path relative to [`app.getAppPath()`](https://electronjs.org/docs/api/app#appgetapppath).
