### ISSUE TITLE
Windows issue when path ends with round brackets

### ISSUE THREAD

**Issue by winrono** [electron-userland/electron-packager#874]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

It appears that packager behaves incorrectly if path contains multiple dashes and round brackets (e.g. **test-on-test-(windows)**). Actually during build process **(windows)** part is being removed from path somehow.

Here is simplified version (removed copyright, icon and win32metadata) of my build script:

```
let packager = require('electron-packager');
let rebuild = require('electron-rebuild').rebuild;

packager({
    dir: './build',
    out: 'dist',
    prune: true,
    asar: true,
    overwrite: true,
    platform: 'win32',
    arch: 'x64',
    afterCopy: [
        (buildPath, electronVersion, platform, arch, callback) => {
            rebuild({ buildPath, electronVersion: '2.0.5', arch })
                .then(() => callback())
                .catch(error => callback(error));
        }
    ]
});
```

And here is an error from console which I receive:

```
An unhandled error occurred inside electron-rebuild
'D:\Work\EikonLight\desktopframework\src\products\test-on-test-' is not recognized as an internal or external command,
operable program or batch file.
```

I also observed that script works as expected if path is, for example, **test-(windows)**

**Comment by malept** [comment]
> `An unhandled error occurred inside electron-rebuild`

The first line of your error indicates that it's more likely an error in `electron-rebuild` than Electron Packager. From past experience, my guess is that it's some problem with node-gyp, as it has issues with special characters in the path on Windows.
