### ISSUE TITLE
Cannot find module ../electron.asar/browser/init.js

### ISSUE THREAD

**Issue by moki298** [electron-userland/electron-packager#877]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
Once I build my electron app using electron-packager, my requirement is to run it on a clean mac with no node installed. The app spawns a child process to which I used 'process.execPath' as command which is the path to the node executable bundled into electron app. But I am facing the following issue. My code looks like this:

```
'use strict'
 const fixPath = require('fix-path');

 let func = () => {
   fixPath();   
   const child = childProcess.spawn(process.execPath, ['/src/script.js', ...someFlag arguments],  {
     detached: true, 
     // stdio: 'ignore',
 });
 child.on('error', (err) => {
   console.log("\n\t\tERROR: spawn failed! (" + err + ")");
 });

 child.stderr.on('data', function(data) {
   console.log('stdout: ' +data);
 });

 child.on('exit', (code, signal) => {
   console.log(code);
   console.log(signal);
 });

 child.unref();
 }
```

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
    stdout: module.js:545
    throw err;
    ^

Error: Cannot find module '/Users/testpc/Desktop/appName.app/Contents/Frameworks/appName Helper.app/Contents/Resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

  
**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
      electron-packager . appName --overwrite --electron-vesrion=2.0.4 --no-asar --platform=darwin 
      --arch=x64 --icon gui/assets/icons/mac/logo.icns --out=package
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Sorry, I don't think this is a bug with Electron Packager, but rather a question about some behavior that happens when an Electron app is bundled. This issue tracker is for bugs with and feature requests for Packager only. Help with using Electron when packaged should be asked in one of the [community-driven sites](https://github.com/electron/electron#community).

**Comment by rsshilli** [comment]
Well, I'm here because the Google Chat client, which uses electron underneat, is throwing this error when I try to start it (no, I don't work for Google). So clearly this is happening to mature developers with relatively mature products out in the wild.

**Comment by malept** [comment]
I still don't think this is a bug in Electron Packager itself. I don't know what the Google Chat client uses to bundle and package its app.
