### ISSUE TITLE
No react component when ignoring node_modules

### ISSUE THREAD

**Issue by nuugut** [electron-userland/electron-packager#880]
I'm very new about Electron and how to package from react web app to native app.

I'm implementing react web app and want to package into native app. I choose  electron-packager to pack.

My problem is when I open my native app. It's only display what is in index.html and no any react component display on screen.

This is how I create react app

> https://github.com/facebook/create-react-app

This is my project structure
https://i.stack.imgur.com/g8dxV.png

This is my electron.js

    const electron = require('electron');
    const app = electron.app;
    const BrowserWindow = electron.BrowserWindow;
    
    const path = require('path');
    const url = require('url');
    
    let mainWindow;
    let startUrl = process.env.ELECTRON_START_URL || url.format({
      pathname: path.join(__dirname, '/build/index.html'),
      protocol: 'file:',
      slashes: true
    })
    
    function createWindow() {
      mainWindow = new BrowserWindow({width: 1366, height: 675});
      mainWindow.setMenu(null)
      mainWindow.loadURL(startUrl)
      mainWindow.webContents.openDevTools()
      mainWindow.on('closed', () => mainWindow = null);
    }
    
    app.on('ready', createWindow);
    
    app.on('window-all-closed', () => {
      if (process.platform !== 'darwin') {
        app.quit();
      }
    });
    
    app.on('activate', () => {
      if (mainWindow === null) {
        createWindow();
      }
    });

This is my package.json that related to electron config

    {
      ...,
      "devDependencies": {
        "concurrently": "^3.6.1",
        "electron": "^2.0.5",
        "electron-packager": "^12.1.1",
        "wait-on": "^2.1.0"
      },
      "main": "./electron.js",
      "homepage": "./",
      "build": {
        "dir": "./build",
        "files": [
          "build/**/*",
          "node_modules/**/*"
        ],
        "directories":{
          "buildResources": "assets"
        }
      }
    }

this is how I run to pack my app

    electron-packager . MyCoolApp --platform=linux --arch=x64 --no-prune --ignore=/node_modules --ignore=/src

This is my result
https://i.stack.imgur.com/c69Aa.png

This is what I want
https://i.stack.imgur.com/eEZzU.png

Please help
Thanks

**Comment by malept** [comment]
The problem is that you're ignoring `node_modules`, which contains all of your dependencies.
