### ISSUE TITLE
NWJS  - executar script no package json

### ISSUE THREAD

**Issue by Militao36** [electron-userland/electron-packager#886]
`{
  "name": "nwjs-sdk-v0.32.3-win-x64",
  "version": "1.0.0",
  "description": "",
  "node-main": "./app.js",
  "main": "http://localhost:3000",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node ./app.js"
  },
  "dependencies": {
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.9",
    "ejs": "~2.5.7",
    "express": "~4.16.0",
    "http-errors": "~1.6.2",
    "morgan": "~1.9.0"
  }
}
`

tenho esse package.json quero executar oque estiver na tag script automaticamente

**Comment by malept** [comment]
Thanks for filing an issue, but Electron Packager does not support NW.js.
