### ISSUE TITLE
Windows compilation error: "EPERM operation not permitted, open C:\Users\username\AppData\...\package.json'"

### ISSUE THREAD

**Issue by nrxszvo** [electron-userland/electron-packager#887]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

I get this error after executing `electron-forge make` from my project directory:

```An unhandled error has occurred inside Forge:
EPERM: operation not permitted, open 'C:\Users\username\AppData\Local\Temp\electron-packager\win32-x64\myproj-win32-x64\resources\app\package.json'
```

This is using Windows 7.  From what I have read and can tell, it has to do with everything under the AppData folder being read-only.  I've tried all of the ideas I can find to prevent files from being read-only (unchecking 'read-only' property, 'attrib -r <file-or-dirname>', running with admin rights, changing folder ownership), but nothing seems to have any persistent effect on the read-only property of files and folders under AppData.  Is there some simple solution I just haven't figured out yet?

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
- Preparing to Package Application for arch: x64  electron-packager Electron Packager 11.2.0 +0ms
  electron-packager Node v8.11.4 +0ms
  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"asar":false,"overwrite":true,"packageManager":"npm","afterCopy":[null],"afterExtract":[null],"afterPrune":[null],"dir":"C:\\Users\\username\\myproj","arch":"x64","platform":"win32","out":"C:\\Users\\username\\myproj\\out","electronVersion":"2.0.7","quiet":true} +0ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring application name from productName in C:\Users\username\myproj\package.json +0ms
  electron-packager Inferring appVersion from version in C:\Users\username\myproj\package.json +0ms
  electron-packager Inferring win32metadata.CompanyName from author in C:\Users\username\myproj\package.json +0ms
  electron-packager Application name: myproj +16ms
  electron-packager Target Electron version: 2.0.7 +0ms
  electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt(-compile)?($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ] +0ms
| Preparing to Package Application for arch: x64  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"2.0.7"} +0ms
- Preparing to Package Application for arch: x64  electron-packager Creating C:\Users\username\AppData\Local\Temp\electron-packager\win32-x64-template +3s
  electron-packager Extracting C:\Users\username\.electron\electron-v2.0.7-win32-x64.zip to C:\Users\username\AppData\Local\Temp\electron-packager\win32-x64-template +32ms
/ Preparing to Package Application for arch: x64  electron-packager Initializing app in C:\Users\username\AppData\Local\Temp\electron-packager\win32-x64\myproj-win32-x64 from C:\Users\username\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
- Preparing to Package Application for arch: x64  electron-packager Ignored paths based on the out param: [ 'C:\\Users\\username\\myproj\\out' ] +6s
√ Preparing to Package Application for arch: x64
× Compiling Application

An unhandled error has occurred inside Forge:
EPERM: operation not permitted, open 'C:\Users\username\AppData\Local\Temp\electron-packager\win32-x64\myproj-win32-x64\resources\app\package.json'
Error: EPERM: operation not permitted, open 'C:\Users\username\AppData\Local\Temp\electron-packager\win32-x64\myproj-win32-x64\resources\app\package.json'
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-forge make
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Have you tried setting `tmpdir` to some other directory?

**Comment by nrxszvo** [comment]
doh!  Stupid mistake.  I was using a VC system that I normally don't use in which all files are read-only by default.  I just needed to check everything out.  Sorry!
