### ISSUE TITLE
Looking for a way to automatically test the built bundle

### ISSUE THREAD

**Issue by HopefulLlama** [electron-userland/electron-packager#897]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Looking for a way to run some sanity tests on the built bundle produced by `electron-packager`. Some sort of automated test that I could run on CI to ensure that the bundle built at least pulls in the correct files, etc.

I haven't been able to find any way to automate this however. The current process is the manually check the bundle before committing and pushing any changes to master. This is cumbersome and misses some edge cases on occasions. To this end, it'd be nice if I could run some system or E2E tests on the bundle.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

Not applicable

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

Not applicable

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

Not applicable

**Comment by malept** [comment]
The best advice I can give you is to adapt some of Electron Packager's own tests into your testsuite, since it checks that various files exist and have certain state.
