### ISSUE TITLE
Electron Mac app fails for the notarization process because it missed the 'runtime' flag during codesign for the Helper App

### ISSUE THREAD

**Issue by poojas2288** [electron-userland/electron-packager#898]
Hello team

I have created a Mac app using electron framework (electron-packager) and embedded it within my another Mac app (non-electron).

I have already added sandbox entitlement in my electron mac app.

I'm trying to get our non-AppStore version of my main app through Apples notarization.

It fails for the notarization process (https://help.apple.com/xcode/mac/current/#/dev88332a81e)
because it missed the 'runtime' flag during codesign for the Helper App.

Therefore I need to create a Mac app which :
1. is compatible with app store submission
2. can be signed as runtime (seems to be equal to hardened runtime : https://help.apple.com/xcode/mac/current/#/devf87a2ac8f) for non-AppStore submission and notarization.
Help would be appreciated.

Thanka
Pooja

**Comment by MarshallOfSound** [comment]
@poojas2288 I'm working on notarization support for the Electron packaging workflow this week.  Luckily I think the bit you need just landed inside `electron-osx-sign`.

There is a new `hardenedRuntime` flag for `electron-osx-sign` that does what you need. 
 See the README of https://github.com/electron-userland/electron-osx-sign

I'm also working on [`electron-notarize`](https://github.com/electron-userland/electron-notarize) which will automate the whole process of notarizing an Electron app.  (There isn't actually much Electron specific stuff, it'd work for any `.app` file really).

Closing this out as notarization is being brought to the table by that module not `electron-packager` itself.

**Comment by poojas2288** [comment]
HI @MarshallOfSound 

I tried using hardenedRuntime for electron-osx-sign, used the certificate  - Developer ID Application:

But when I launch my app, it crashes with the error message as "Invalid signature"

NOTE -I am using target as "mas" when I package my app using electron-packager.

The same certificate works fine when I use electron-builder to b uild Mac app.

**Comment by poojas2288** [comment]
Is there any other way to enable runtime flag, where we can avoid the signing process because the main app, which includes this electron app, will already be signed later along with the bundled component ?

**Comment by poojas2288** [comment]
HI @MarshallOfSound 
Is there any update on my comments above ?

**Comment by poojas2288** [comment]
HI @MarshallOfSound 
Is there any update on my issue above ?

**Comment by malept** [comment]
Notarization support has been added in Electron Packager 13.0.0.

**Comment by malept** [comment]
The best way to learn about how to use any part of the Electron Packager options is to look at the API docs. Here is a direct link to the [v13.0.0 docs for `osxNotarize`](https://github.com/electron-userland/electron-packager/blob/v13.0.0/docs/api.md#osxnotarize).

**Comment by poojas2288** [comment]
Hi @malept 

I went through this notarize process.

The only thing they are doing is calling the Apple stuff to upload. I've used the sample and the following commands:

**electron-packager . --overwrite --platform=darwin --arch=x64 --icon=group.icns --prune=true --out=release-builds --app-bundle-id=bundleId --electron-version=4.0.0-beta.8 electron-osx-sign ./release-builds/ElectronSigning-darwin-x64/ElectronSigning.app --platform=darwin --identity="Developer ID Application: certificateName" --type=distribution --entitlements=../ent.entitlements --entitlements-inherit=../inherit.entitlements --hardenedRuntime** (electron-packager updated to 13.0)

I've tried with and without entitlements, I've tried with and without sandboxing. But I always get the same result. Without the '--hardenedRuntime' parameter, the sample app launches just fine. As soon as I include the parameter, the app crashes. 
I've attached a report with the latest electron beta. It also crashes with older/stable versions.
[CrashHardenedRuntime.txt](https://github.com/electron-userland/electron-packager/files/2662953/CrashHardenedRuntime.txt)

**Comment by MarshallOfSound** [comment]
@poojas2288 Can you provide a minimal sample app that reproduces that issue? If hardened runtime is causing Electron to crash that's something we can look at, but only if there's a minimal repro for the crash 👍

**Comment by poojas2288** [comment]
Hi @MarshallOfSound 

This was the app I've used, it is the Electron quick start app from https://electronjs.org/

# Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

# Go into the repository
$ cd electron-quick-start

# Install the dependencies and run
$ npm install && npm start

The most basic electron app.

**Comment by poojas2288** [comment]
Hi @MarshallOfSound 

Is there any update on this ?

Thanks
Pooja
