### ISSUE TITLE
[enhancement] place builds in a "bin" directory for easy gitignoring

### ISSUE THREAD

**Issue by Flying-Toast** [electron-userland/electron-packager#904]
Builds for each target are placed in the directory `{app name}-{platform}`. In order to .gitignore the builds, you have to add a line to .gitignore for each build target. Also, if you change the `productName` in package.json, you have to update the entries in the gitignore file. If builds were placed in a common build directory, for example `bin/{app name}-{platform}`, then you could just add `bin/**` to the gitignore file to ignore all the builds.

**Comment by malept** [comment]
This is already a feature, please see the [`out` option](https://github.com/electron-userland/electron-packager/blob/v12.2.0/docs/api.md#out).
