### ISSUE TITLE
asar.unpackDir directory will be included both in "app.asar" and in "app.asar.unpacked".

### ISSUE THREAD

**Issue by taku-o** [electron-userland/electron-packager#905]
I found my own built Electrion Application contains duplicated file
in "app.asar", and in "app.asar.unpacked".

There is a way to remove duplicated file
in generated "app.asar" with electron-packager ?

Steps to reproduce:
1. build Electrion Application with electron-packager.
```
  electron-packager . hello-electron-000 --platform=darwin --arch=x64 --electronVersion=2.0.8 --overwrite --asar.unpackDir=unpack
```

2. app.asar.unpacked directory contains "asar.unpackDir" file.
```
  ls hello-electron-000-darwin-x64/hello-electron-000.app/Contents/Resources/app.asar.unpacked/unpack 
  > test.txt
```

3. app.asar contains "asar.unpackDir" file, too.
```
  asar e hello-electron-000-darwin-x64/hello-electron-000.app/Contents/Resources/app.asar dist
  ls dist/unpack
  > test.txt
```

**Console output. **

```
% npm run package

> hello-electron-000@0.1.0 package /Users/taku.omi/Desktop/hello-electron-000
> electron-packager . hello-electron-000 --platform=darwin --arch=x64 --electronVersion=2.0.8 --overwrite --asar.unpackDir=unpack

Packaging app for platform darwin x64 using electron v2.0.8
Wrote new app to /Users/taku.omi/Desktop/hello-electron-000/hello-electron-000-darwin-x64
% ls hello-electron-000-darwin-x64/hello-electron-000.app/Contents/Resources/app.asar.unpacked/unpack 
test.txt
% asar e hello-electron-000-darwin-x64/hello-electron-000.app/Contents/Resources/app.asar dist
% ls dist/unpack
test.txt
```

using minimum electron project:
- https://github.com/taku-o/hello-electron-000

environment:
Mac OS X 10.13.6
electron-packager 9.1.0, and 12.2.0

**Comment by malept** [comment]
It's not actually in the `app.asar` file. There is an entry in the asar file for the file in its metadata, but the contents are not actually there. To verify this, you can run:

```shell
grep aaaaa hello-electron-000-darwin-x64/hello-electron-000.app/Contents/Resources/app.asar
```

On my machine, it cannot find the contents of `unpack/test.txt`.
