### ISSUE TITLE
Asar documentation

### ISSUE THREAD

**Issue by nuthinking** [electron-userland/electron-packager#908]
Looks like many people have problems with Asar. In my case, I embed a binary in the app which can't be run by spawn because needs to be unpacked first. Is there a comprehensive guide on why and how to use Asar? I saw way too many solutions (including different ways to unpack things). So far I disabled Asar. Thanks!

**Comment by malept** [comment]
Yes there is, in the [Electron documentation](https://electronjs.org/docs/tutorial/application-packaging). This is linked to in the [Packager API documentation](https://github.com/electron-userland/electron-packager/blob/v12.2.0/docs/api.md#asar), which details most of the pertinent ASAR options.
