### ISSUE TITLE
Relative out dir not being ignored

### ISSUE THREAD

**Issue by chenluu** [electron-userland/electron-packager#918]
I'm running the command 

electron-packager . myapp --overwrite --platform=win32 --asar --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds

And noticed the folder is not being ignored. what ever is in the "release-builds" still gets packaged into the app

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run `electron-packager` with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

**Comment by chenluu** [comment]
Hiya, please see below of the console output

c:\code\myapp>npm run package-win

--

 myapp@0.0.2 package-win c:\code\myapp
 electron-packager . myapp --overwrite --platform=win32 --asar --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=BE --version-string.FileDescription=myapp --version-string.ProductName="myapp"

  electron-packager Electron Packager 13.0.0
  electron-packager Node v8.9.4
  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"_":[".","myapp"],"deref-symlinks":true,"derefSymlinks":true,"download":{"strictSSL":true,"strict-ssl":true},"prune":true,"overwrite":true,"platform":"win32","asar":true,"arch":"ia32","icon":"assets/icons/win/icon.ico","out":"release-builds","version-string":{"CompanyName":"BE","FileDescription":"myapp","ProductName":"myapp"},"versionString":{"companyName":"BE","fileDescription":"myapp","productName":"myapp"},"dir":".","name":"myapp","protocols":[]} +3ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: ia32 +0ms
  electron-packager Inferring appVersion from version in c:\code\myapp\package.json +0ms
  electron-packager Inferring win32metadata.CompanyName from author in c:\code\myapp\package.json +1ms
  electron-packager Inferring target Electron version from electron in c:\code\myapp\package.json +5ms
  electron-packager Application name: myapp +27ms
  electron-packager Target Electron version: 3.0.10 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"strictSSL":true,"strict-ssl":true,"platform":"win32","arch":"ia32","version":"3.0.10"} +0ms
  electron-packager Removing release-builds\myapp-win32-ia32 due to settingoverwrite: true +219ms Packaging app for platform win32 ia32 using electron v3.0.10
  electron-packager Creating C:\Users\user\AppData\Local\Temp\electron-packager\win32-ia32-template +49ms
  electron-packager Extracting C:\Users\user\AppData\Local\electron\Cache\electron-v3.0.10-win32-ia32.zip to C:\Users\user\AppData\Local\Temp\electron-packager\win32-ia32-template +3ms
  electron-packager Initializing app in C:\Users\user\AppData\Local\Temp\electron-packager\win32-ia32\myapp-win32-ia32 from C:\Users\user\AppData\Local\Temp\electron-packager\win32-ia32-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'c:\\code\\myapp\\release-builds' ] +1s
  electron-packager Running asar with the options {} +2s
  electron-packager Renaming electron.exe to myapp.exe in C:\Users\user\AppData\Local\Temp\electron-packager\win32-ia32\myapp-win32-ia32 +1s
  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"myapp","InternalName":"myapp","OriginalFilename":"myapp.exe","ProductName":"myapp","CompanyName":"BE"},"file-version":"0.0.2","product-version":"0.0.2","icon":"assets/icons/win/icon.ico"} +0ms
  electron-packager Moving C:\Users\user\AppData\Local\Temp\electron-packager\win32-ia32\myapp-win32-ia32 to release-builds\myapp-win32-ia32 +552ms
  Wrote new app to release-builds\user-win32-ia32

**Comment by chenluu** [comment]
Hi, 

here you go, just a plain app with nothing added using the electron-quick-start base.

https://github.com/chenluu/testapp

See start scripts in package.json for the commands I'm running eg. npm run package-win, npm run package-mac

Same issue. The first build is fine because the folder is empty, but then when i go to build for another OS it still includes the release builds folder.

At first I was wondering why each build for a different OS was getting incrementally (and ridiculously) larger. So then I ran the build without the --asar switch and saw the release-builds folder as part of the app.
