### ISSUE TITLE
OSX build out isn't the same

### ISSUE THREAD

**Issue by krainboltgreene** [electron-userland/electron-packager#92]
So previously I could do:

```
$ electron-packager ./ 'Lowbrow' --platform=darwin --arch=x64 --out=releases/build/osx/x64
```

And it would create `releases/build/osx/x64/Lowbrow.app`. Now it creates:
```
releases
└── build
    └── osx
        └── x64
            └── Lowbrow-darwin-x64
                ├── LICENSE
                ├── Lowbrow.app
                └── version
```

Oddly this is also not in line with the linux build:

```
lowbrow
├── LICENSE
├── Lowbrow
├── content_shell.pak
├── icudtl.dat
├── libffmpegsumo.so
├── libgcrypt.so.11
├── libnode.so
├── libnotify.so.4
├── locales
├── natives_blob.bin
├── resources
├── snapshot_blob.bin
└── version
```

I mean the linux one makes sense, since there's no "self contained linux package format". What happened to the previous way? In addition, why the name convention?

**Comment by krainboltgreene** [comment]
Also I just notice that the linux build folder and mac build folder are now different.

**Comment by malept** [comment]
Is the behavior consistent with the outcome of #38?

**Comment by krainboltgreene** [comment]
I don't understand @malept.

**Comment by malept** [comment]
`--out` and its default behavior changed when #38 was closed (particularly with regards to Linux). Is what the discussion in that issue, plus what Max did in 86edff6 consistent with the the output directory behavior that you're seeing?

**Comment by kfranqueiro** [comment]
This change has to do with `--all` (and support for building multiple platforms/archs from one command) being added.  For consistency's sake, all builds now result in a top-level directory whose name includes the platform and arch.

This does result in extra nesting of the Mac app, which I realize could be considered a bit awkward, but the same process is now being followed for all platforms, and results in consistent naming of output folders when building multiple platforms at once (e.g. myapp-darwin-x64, myapp-linux-x64, myapp-windows-x64).
