### ISSUE TITLE
How to set environment variables for a built package? (Required for: mas)

### ISSUE THREAD

**Issue by kaansoral** [electron-userland/electron-packager#923]
So all Mac App Store apps need to be sandboxed, but this bug that propagated from Chromium: https://github.com/electron/electron/issues/15304 - breaks that mac-specific sandboxing, I've tried manually setting `process.env.TMPDIR` - but it doesn't work (in hindsight, it's obvious that it won't work, but I had to try)

I'm wondering whether there's a way to change the value of the `TMPDIR` environment variable on an electron-packager build?

Otherwise, if you have `app.requestSingleInstanceLock()` - your Electron app can't pass Mac App Store review, and you are forced to have an annoying app that relaunches a new window everytime the icon is clicked 

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Comment by MarshallOfSound** [comment]
> I'm wondering whether there's a way to change the value of the TMPDIR environment variable on an electron-packager build?

That's not how environment variables work, they aren't set in an application, they are read from the environment at runtime.  You're best bet as a workaround is probably something like this in your main file.

```js
const expectedTmpDirValue = resolveThingy('$XDG_RUNTIME_DIR/$APP_ID/')
if (process.env.TMPDIR !== expectedTmpDirValue) {
  childProcess.spawn(process.execPath, process.argv, {
    env: {
      ...process.env,
      TMPDIR: expectedTmpDirValue
    },
    detached: true,
  });
  process.exit(0);
}
```

That should (untested) restart your app quickly at runtime with the env var you want.
