### ISSUE TITLE
App Fails to Build on Travis CI using OSX

### ISSUE THREAD

**Issue by RailRunner166** [electron-userland/electron-packager#927]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I am unable to build my app for mac (also on mac) on Travis CI. I get this error:
```
ENOENT: no such file or directory, open '/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/electron-packager/darwin-x64/MyRPC-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist'
Error: ENOENT: no such file or directory, open '/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/electron-packager/darwin-x64/MyRPC-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist
```

I am using electron forge, an my Travis build can be found at https://travis-ci.org/RailRunner166/MyRPC/jobs/474484348

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

The console output would be the build output, I guess?
https://travis-ci.org/RailRunner166/MyRPC/jobs/474484348

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

I'm not passing any more arguments than the ones that electron-forge does.

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

[My Code](https://github.com/railrunner166/myrpc) is built on Travis CI, maybe fork and test?

**Comment by malept** [comment]
Upgrade electron-packager to 11.2.1, this bug was fixed yesterday in the 11.2 series for Electron Forge 5.

**Comment by RailRunner166** [comment]
Is there a way i can re-open this, i upgraded to 11.2.1, and it continues to fail on the same step. 😞 

Latest Build:
https://travis-ci.org/RailRunner166/MyRPC/jobs/474518677

**Comment by malept** [comment]
Don't add `electron-packager` to your `devDependencies`. You still have an `electron-packager` that doesn't have the fix: https://github.com/RailRunner166/MyRPC/blob/508101facbb41f199a1c00888a77f190fd091327/yarn.lock#L2785-L2807

**Comment by RailRunner166** [comment]
oof how do i upgrade it then?

**Comment by RailRunner166** [comment]
i tried `yarn upgrade`... that didn't work
what d i do? upgrade forge?

**Comment by malept** [comment]
https://yarnpkg.com/lang/en/docs/cli/upgrade-interactive/ perhaps?

I can't really help very much with how to use Yarn itself, unfortunately.

**Comment by RailRunner166** [comment]
i can understand that, i'll look at that page. thanks! you guys are awesome, btw, i love what you guys do ;)

**Comment by MarshallOfSound** [comment]
`yarn upgrade electron-forge` will make yarn update all deps of forge

**Comment by MajuMadhusudanan** [comment]
I'm getting the below error when i try to run electron-packager from Jenkins server.

Packaging app for platform darwin x64 using electron v5.0.0
ENOENT: no such file or directory, open '/var/folders/2p/jkhwg32562l2gy3bc0z_ryd00000gn/T/electron-packager/darwin-x64/Automate-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist'
[WFM:JENKINS] Current directory - /Users/jenkins/Home/workspace/sudanan_NotarizationJenkinsBuild
File Doesn't Exist, Will Create: /Users/jenkins/Home/workspace/sudanan_NotarizationJenkinsBuild/Automate Electron App/release-builds/Automate-darwin-x64/automate.app/Contents/Info.plist

**Comment by n0wfal** [comment]
This still seems to be an issue with Electron v11.3.0 and Electron-packager version 15.2.0
I've checked the tmp folder and I couldn't find an Electron Helper EH.app folder there was a Electron Helper.app folder inside it with a Contents folder and an info.plist file.
