### ISSUE TITLE
rc edit does not work on windows

### ISSUE THREAD

**Issue by miles-waldron** [electron-userland/electron-packager#934]
Calling rcedit to get a version returns a number that is separated by commas. Calling rcedit to set a version number with commas does not work. You have to call rcedit with a version number separated by periods to make it work. RC edit is not self consistent.

Calling rcedit to set an executable version number, fileVersion, and productVersion, truncates the target file to 53k rendering the target file useless.

Called from a visual studio post build script:

$(SolutionDir)rcedit $(SolutionDir)Installer\x64\KMDocsMS.exe --get-version-string ProductVersion > productVersion.txt
set /p productVersionVar= < productVersion.txt
set cleanProductVersionVar=%productVersionVar:,=.%
$(SolutionDir)rcedit $(SolutionDir)Installer\installdocunity.exe --set-product-version %cleanProductVersionVar%
del productVersion.txt

$(SolutionDir)rcedit $(SolutionDir)Installer\x64\KMDocsMS.exe --get-version-string FileVersion > fileVersion.txt
set /p fileVersionVar= < fileVersion.txt
set cleanFileVersionVar=%fileVersionVar:,=.%
$(SolutionDir)rcedit $(SolutionDir)Installer\installdocunity.exe --set-file-version %cleanFileVersionVar%
del fileVersion.txt

**Comment by malept** [comment]
This sounds like a bug in rcedit, not Electron Packager itself. You should file a bug in the [rcedit issue tracker](https://github.com/electron/rcedit/issues).
