### ISSUE TITLE
No icon on executable on linux

### ISSUE THREAD

**Issue by crashbdx** [electron-userland/electron-packager#935]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

I dont have icon on the executable for linux (ubuntu), the icon on the left dock is ok though.

Here the command im using, icon.png is present in assets/build/png/icon.png

```
electron-packager . chain-wallet --overwrite --asar --platform=linux --arch=x64 --icon=assets/build/png/icon.png --prune=true --out=release-builds
```

[https://imgur.com/EAz6ax8](https://imgur.com/EAz6ax8)

Im missing something ? Icons working well on windows.

**Comment by malept** [comment]
Linux icons work differently from other target platforms: https://github.com/electron-userland/electron-packager/blob/v13.0.1/docs/faq.md#how-do-i-set-an-icon-on-linux

You will not see an icon in your file manager because Linux file managers do not support that functionality.

**Comment by crashbdx** [comment]
Ok thanks, if this is normal then all good.

**Comment by crashbdx** [comment]
Sorry to bother again, juste quick question, is it same on macos ? or im suppose to have the icon on macos ? Getting this for now: [https://imgur.com/caxF5vn](https://imgur.com/caxF5vn)

**Comment by malept** [comment]
Per the [icon docs](https://github.com/electron-userland/electron-packager/blob/v13.0.1/docs/api.md#icon), make sure your icon for macOS is in ICNS format. It's important to note that macOS has an app icon cache, so during development it may not show up until that cache evicts the entry for your app. _(Use StackOverflow or similar to find out how to clear that cache.)_

**Comment by karimmorta** [comment]
Hi @malept, I think it's important to add that note about macOS app icon cache, I've been trying to build with the icon for a few hours with no success, until I found this :)

Then used :
```
sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3;sudo touch /Applications/* ; killall Dock; killall Finder

**Comment by karimmorta** [comment]
Hi @malept, I think it's important to add that note about macOS app icon cache, I've been trying to build with the icon for a few hours with no success, until I found this :)

Then used :
```
sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3;sudo touch /Applications/* ; killall Dock; killall Finder

Then built the app again and this time I had the custom icon.
