### ISSUE TITLE
Font awesome not loading properly once packaged

### ISSUE THREAD

**Issue by starsoccer** [electron-userland/electron-packager#936]
I have a project I am working where I am using font awesome locally via node_modules and then falling back to load if via cdn if running in browser. While this works fine when developing in electron and in browser, after being packaged, this no longer works.

What is a bit unusual is that the css file for font awesome loads fine but then all the associated font files give an error saying file not found. If I check the sources though in the electron app they are all shown and are loadable.

The project I am working on is open source so you can see all of the code here, https://github.com/starsoccer/cryptotithe/pull/12

**Comment by malept** [comment]
Unfortunately, I don't have time to run/debug your app to see why it's not working, as I work on this in my spare time. However, from a cursory glance, this may be a [relative path issue](https://github.com/electron-userland/electron-packager/blob/v13.0.1/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working).

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).

**Comment by starsoccer** [comment]
@malept I understand that, I wasnt really expecting you to fully run it, more just to see the code as the guidelines say to provide some code. Would you prefer I make an barebones example of the issue using electron-quick-start?

Ive looking into the relative path issue a bit prior to posting this. The reason I dont think this is the issue is because the other css files Im using/referencing are loaded fine. So if it was path related I assume none of my css files would load not just font awesome

**Comment by malept** [comment]
> Would you prefer I make an barebones example of the issue using electron-quick-start?

This would be helpful.

**Comment by starsoccer** [comment]
Upon further testing it seems the issue was not with relative path but was actually with a regex I was using to ignore .ts(typescript) files. For some reason it was I assume, breaking something related to font awesome. I am still not sure exactly what the issue was but upon removing the regex it works fine so I will just play around with it a bit more and see if I can get a work around.
