### ISSUE TITLE
afterCopy - callback is not a function

### ISSUE THREAD

**Issue by djbreen7** [electron-userland/electron-packager#939]
**EDIT - 1/30/2019:** Simplified description

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
The `afterCopy` hook throws the error `callback() is not a function`. Everything runs fine if I remove `callback()`, however, the documentation says that its required. I can't confirm if there have been any side effects.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
// I realize this isn't the DEBUG=electron-packager output. I'm working on providing that.
[06:49:44] Starting 'package'...
Packaging app for platform win32 x64 using electron v2.0.16
Downloading patent safe FFMPEG for platform win32 x64 using electron v2.0.16
Loaded FFMPEG successfully
(node:13808) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at Object.<anonymous> (C:\Users\daniel.breen\Development\Kno2\kno2-desktop\build\win32.ts:54:13)
    at result.then (C:\Users\daniel.breen\Development\Kno2\kno2-desktop\node_modules\electron-packager\hooks.js:19:41)
    at <anonymous>
(node:13808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[06:51:18] 'package' errored after 1.55 min
[06:51:18] TypeError: callback is not a function
    at Timeout._onTimeout (C:\Users\daniel.breen\Development\Company\app-desktop\build\win32.ts:45:17)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
[06:51:18] 'build' errored after 1.95 min
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
export const packagerOptions = {
    name: 'AppDesktop',
    platform: 'win32',
    arch: 'x64',
    dir: path.join(__dirname, '../'),
    out: path.join(__dirname, '../dist/packaged'),
    ignore: [
        /^\/(build|e2e|src)($|\/)/,
        /^\/dist\/(installer|packaged)($|\/)/,
        /^\/node_modules\/edge\/(build|test)($|\/)/,
        /^\/node_modules\/edge\/.+\\.(dll|node)$/,
        /^\/node_modules\/electron-edge-js\/(?!.+8\.9\.3).+\.(dll|node)$/,
    ],
    icon: path.join(__dirname, '../assets/win32/app-windows.ico'),
    asar: {
        unpack: '*.{dll,ico,node}'
    },
    prune: true,
    overwrite: true,
    win32metadata: {
        CompanyName: 'Company',
        FileDescription: 'App Desktop',
        ProductName: 'App Desktop',
        InternalName: 'App Desktop'
    },
    afterExtract: [safeFFMPEG],
    afterCopy: [serialHooks([
        (buildPath, electronVersion, platform, arch, callback) => {
            setTimeout(() => {
                console.log('first function')
                callback()
         }, 1000)
    },
    (buildPath, electronVersion, platform, arch, callback) => {
      console.log('second function')
      callback()
    }
  ])],
};
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

1. Add the `afterCopy` code provided in the documentation to your packagerOptions.
2. Attempt to pacakage your project

**Comment by malept** [comment]
Thanks for reporting. This is a bug in the documentation - `serialHooks` only takes Promises, not callback-style functions. I fixed the docs in https://github.com/electron-userland/electron-packager/commit/f30456924dc649187025948a752bd4102021b7f7.
