### ISSUE TITLE
Packaging fails without any error on macOS 10.14.2

### ISSUE THREAD

**Issue by harish0507** [electron-userland/electron-packager#942]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Hi, I'm trying to package my app with the below command 

```DEBUG=electron-packager ./node_modules/.bin/electron-packager . POSBytz --out=dist```

which breaks silently without any error

Here is my console output

```
electron-packager Electron Packager 13.0.1
electron-packager Node v10.15.1
electron-packager Host Operating system: darwin (x64) +0ms
electron-packager Packager Options: {"_":[".","POSBytz"],"deref-symlinks":true,"derefSymlinks":true,"download":{"strictSSL":true,"strict-ssl":true},"prune":true,"out":"dist","dir":".","name":"POSBytz","protocols":[]} +3ms
electron-packager Target Platforms: darwin +1ms
electron-packager Target Architectures: x64 +1ms
electron-packager Inferring appVersion from version in /Users/harishmohan/Projects/posbytz/electron-app/cross-platform/package.json +0ms
electron-packager Inferring target Electron version from electron in /Users/harishmohan/Projects/posbytz/electron-app/cross-platform/package.json +7ms
electron-packager Application name: POSBytz +21ms
electron-packager Target Electron version: 4.0.3 +0ms
electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
electron-packager Downloading Electron with options {"strictSSL":true,"strict-ssl":true,"platform":"darwin","arch":"x64","version":"4.0.3"} +0ms
Packaging app for platform darwin x64 using electron v4.0.3
electron-packager Creating /var/folders/ng/h9_sdtts661_qdcnxvvlgqjc0000gn/T/electron-packager/darwin-x64-template +279ms
electron-packager Extracting /Users/harishmohan/Library/Caches/electron/electron-v4.0.3-darwin-x64.zip to /var/folders/ng/h9_sdtts661_qdcnxvvlgqjc0000gn/T/electron-packager/darwin-x64-template +0ms
electron-packager Initializing app in /var/folders/ng/h9_sdtts661_qdcnxvvlgqjc0000gn/T/electron-packager/darwin-x64/POSBytz-darwin-x64 from /var/folders/ng/h9_sdtts661_qdcnxvvlgqjc0000gn/T/electron-packager/darwin-x64-template template +0ms
electron-packager Ignored paths based on the out param: [ '/Users/harishmohan/Projects/posbytz/electron-app/cross-platform/dist' ] +2s
```

I have also tried with ```DEBUG=*``` and it seems like the process breaks after these lines

```
...
extract-zip zip extraction complete +0ms
electron-packager Initializing app in /var/folders/ng/h9_sdtts661_qdcnxvvlgqjc0000gn/T/electron-packager/darwin-x64/POSBytz-darwin-x64 from /var/folders/ng/h9_sdtts661_qdcnxvvlgqjc0000gn/T/electron-packager/darwin-x64-template template +0ms
electron-packager Ignored paths based on the out param: [ '/Users/harishmohan/Projects/posbytz/electron-app/cross-platform/dist' ] +2s
flora-colossus creating walker with rootModule=. +0ms
```

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by harish0507** [comment]
Worked after doing a clean ```npm install``` by removing ```node_modules``` and ```package-lock.json```

**Comment by vostoksystem** [comment]
hi, 
this is an old bug report and I'm in a different platform but since I got here searching for a similar error, my answer may help other.
I'm on linux and  I too got this issue with electron-packager silently closing with no error message and no output files. 
As many I'm using tmpfs for my /tmp, what happened it's an app filled my 4go space (!) so electron-packager was not able to download and build files. After removing some tmp files, the script was able to run as expected.
