### ISSUE TITLE
Does not exit from terminal / command prompt when clicked close button on electron

### ISSUE THREAD

**Issue by tbhaxor** [electron-userland/electron-packager#943]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I packaged my application with
```
$ electron-packger . --all
```

And when i started the application i worked fine but the error comes when i tried to close it from the close button from top right corner then its hiding the application but not exiting on the terminal.

Since i am new to electron please help me where i am wrong

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should consider use one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.

**Comment by gadamsgh** [comment]
I ran into this as well.  When invoked from a cmd window, apps packaged with electron-packager don't look like they exit the terminal normally.  The cursor is left on a newline and you have to press enter to get the command prompt back.  

Simple steps to repro with electron-quick-start: 
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm install electron-packager --save-dev
Add this to package.json scripts: "package": "electron-packager ."
npm run package
cd electron-quick-start-win32-x64
.\electron-quick-start.exe
Close x on the app that starts
See the issue with newline in the terminal.
```

What you get: 
![image](https://user-images.githubusercontent.com/39625845/94442855-0f501600-016a-11eb-9396-23336f3fc5fc.png)

After pressing enter: 
![image](https://user-images.githubusercontent.com/39625845/94442886-18d97e00-016a-11eb-89b2-528db6fabf85.png)

**Comment by gadamsgh** [comment]
@malept FYI I added a simple repro to this issue if you'd consider reopening or if it'd help look into it.

**Comment by malept** [comment]
This is not specific to Electron Packager or Electron apps bundled with Electron Packager. For proof, try this, from the `electron-quick-start` directory after running `npm install`:

```
node_modules\electron\dist\electron.exe .
```

This is the bare command to run your Electron app in dev mode (not recommended, you should normally use `node_modules\.bin\electron`).

**Comment by gadamsgh** [comment]
Yeah I was just poking through the electron-packager code and arrived at the same conclusion.  Not your bug, thanks for taking a look though.
