### ISSUE TITLE
Packaged build behaving differently than the one running "npm start"

### ISSUE THREAD

**Issue by thegergo02** [electron-userland/electron-packager#944]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
When I run `npm start` (it's just doing `electron .`), my app behaves correctly (launches login screen, after that the dashboard tab.). But when I use `electron-packager --platform=linux --arch=x64`, on my computer I immediately see my part of the dashboard (just my name), and on another test machine the login works fine, but after logging in I see the user's name and again, just part of the dashboard.
(If I start the application from the terminal, it's working as it should.) (My application creates some directoryies, and when ran from terminal, it creates them where the executable is, but when ran from my file manager (nemo), or from the windows explorer (if I build it to win32), it creates the folders in the resources/app folder. )  

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
$ electron-packager ./ --platform=linux --arch=x64
  electron-packager Electron Packager 13.0.1
  electron-packager Node v8.10.0
  electron-packager Host Operating system: linux (x64) +0ms
  electron-packager Packager Options: {"_":["./"],"deref-symlinks":true,"derefSymlinks":true,"download":{"strictSSL":true,"strict-ssl":true},"prune":true,"platform":"linux","arch":"x64","dir":"./","protocols":[]} +3ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring application name from name in /home/thegergo02/Documents/Electron/gKreta/package.json +0ms
  electron-packager Inferring appVersion from version in /home/thegergo02/Documents/Electron/gKreta/package.json +0ms
  electron-packager Inferring target Electron version from electron in /home/thegergo02/Documents/Electron/gKreta/package.json +3ms
  electron-packager Application name: gkreta +30ms
  electron-packager Target Electron version: 4.0.3 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager' ] +0ms
  electron-packager Downloading Electron with options {"strictSSL":true,"strict-ssl":true,"platform":"linux","arch":"x64","version":"4.0.3"} +0ms
Packaging app for platform linux x64 using electron v4.0.3
  electron-packager Creating /tmp/electron-packager/linux-x64-template +841ms
  electron-packager Extracting /home/thegergo02/.cache/electron/electron-v4.0.3-linux-x64.zip to /tmp/electron-packager/linux-x64-template +1ms
  electron-packager Initializing app in /tmp/electron-packager/linux-x64/gkreta-linux-x64 from /tmp/electron-packager/linux-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/home/thegergo02/Documents/Electron/gKreta/gkreta-darwin-x64',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-linux-ia32',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-linux-x64',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-linux-armv7l',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-linux-arm64',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-linux-mips64el',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-mas-x64',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-win32-ia32',
  '/home/thegergo02/Documents/Electron/gKreta/gkreta-win32-x64' ] +4s
  electron-packager Renaming electron to gkreta in /tmp/electron-packager/linux-x64/gkreta-linux-x64 +126ms
  electron-packager Moving /tmp/electron-packager/linux-x64/gkreta-linux-x64 to /home/thegergo02/Documents/Electron/gKreta/gkreta-linux-x64 +1ms
Wrote new app to /home/thegergo02/Documents/Electron/gKreta/gkreta-linux-x6
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-packager --platform=linux --arch=x64
or
electron-packager --platform=win32 --arch=x64
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**
I can't provide a minimal testcase, and I detailed the steps above. I can provide link to the actual code. 
[gKreta](https://github.com/thegergo02/gKreta)

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already covered in the [Frequently Asked Questions document](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md), and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.

**Comment by athanasu** [comment]
Hello @thegergo02, it seems like I have a similar issue with you. Did you find any solution to this?
