### ISSUE TITLE
Electron-packager failed to pack my package.json

### ISSUE THREAD

**Issue by rheza** [electron-userland/electron-packager#947]
* [ x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
Hi, 

Seems pretty basic, but I can't get around to package my electron app. 
I successfully pack and launch the app, but i got this error. So my application not usable.

`Uncaught Error: ENOENT: no such file or directory, open 'package.json'
    at Object.openSync (fs.js:436)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Object.readFileSync (fs.js:341)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:580)
    at Object.<anonymous> (/Users/rheza/Desktop…tron-db/index.js:14)
    at Object.<anonymous> (/Users/rheza/Desktop…ron-db/index.js:438)
    at Module._compile (internal/modules/cjs/loader.js:693)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)`

my package.json file
`{
  "name": "Grin",
  "version": "1.0.0",
  "description": "Wallet",
  "main": "main.js",
  "build": {
    "appId": "com.rheza.test",
    "mac": {
      "category": "Finance"
    }
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "Rheza Pahlevi",
  "license": "CC0-1.0",
  "scripts": {
    "start": "electron ."
  },
  "dependencies": {
    "app-root-dir": "^1.0.2",
    "electron-db": "^0.8.3",
    "electron-reload": "^1.4.0"
  },
  "devDependencies": {
    "electron": "^4.0.5",
    "electron-builder": "latest"
  }
}
`
Anyone can give me insight how to successfully pack my app please, 

Thanks

**Comment by tonton-pixel** [comment]
Your `package.json`file appears to make reference to `"electron-builder"`, not `"electron-packager"`. You'll probably get more appropriate answers by opening an [issue](https://github.com/electron-userland/electron-builder/issues) in the relevant [electron-userland/electron-builder](https://github.com/electron-userland/electron-builder) repository, although the error message you're getting ('package.json' not found) may suggest a problem at a different level...

**Comment by malept** [comment]
Since this issue refers to `electron-builder` and not Electron Packager, I'm closing this. The previous comment is correct about more appropriate support.
