### ISSUE TITLE
NODE_ENV is Undefined

### ISSUE THREAD

**Issue by danwhite-ad** [electron-userland/electron-packager#949]
I am using using the below script to package my app, but when I run the app from the exe the NODE_ENV variable is undefined. How do I set this to production?

"package-win": "electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds",

**Comment by malept** [comment]
In recent versions of Electron:

```javascript
const { app } = require('electron')

if (app.isPackaged) {
  process.env.NODE_ENV = 'production'
}
```

Docs for [`app.isPackaged`](https://electronjs.org/docs/api/app#appispackaged)

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), as this question isn't Electron Packager specific.
