### ISSUE TITLE
Question : How to handle package updates within compiled app?

### ISSUE THREAD

**Issue by s-a** [electron-userland/electron-packager#95]
Is there a mechanism like npm install or npm update within a compiled app available? I like to deploy package updates without the old binaries and make use of npm. Can some mention some electron docs?

**Comment by s-a** [comment]
Regarding to this and #72 :   
I wrote a code that can handle package management from within compiled app. Unfortunately this requires a node.js installation on the target machine. Regarding to native extensions the target machine will need a compiler system unless there is no way available to distribute pre-compiled binaries.  

 - [npmc.js](https://github.com/s-a/sulu/blob/0b487541db192530102ac280a88410da90644606/app/npmc.js)
 - [npm-test.js](https://github.com/s-a/sulu/blob/0b487541db192530102ac280a88410da90644606/app/npm-test.js)

May this is interesting for any one out there. :dog: 

Any chance to distribute NPM runtime libs with electron compiled package?

**Comment by kfranqueiro** [comment]
I'm not sure this approach would work in the case of native modules.  Have you seen [electron-rebuild](https://github.com/paulcbetts/electron-rebuild)?

**Comment by develar** [comment]
Please see https://github.com/EvolveLabs/electron-updater#note So, I think, this issue can be closed. Also, see https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by malept** [comment]
> I think, this issue can be closed.

Seems reasonable.
