### ISSUE TITLE
Update asar dependency to 1.0.0

### ISSUE THREAD

**Issue by Orrison** [electron-userland/electron-packager#950]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

asar 1.0.0 now has updated dependencies without which a high level "Arbitrary File Overwrite" vulnerability is present.

The dependency path to this vulnerability is `electron-packager > asar > mksnapshot > decompress-zip` and it described here: https://www.npmjs.com/advisories/777

asar 1.0.0 was just updated to remove dependency of mksnapshot so the vulnerability is no longer present in the no longer maintained decompress-zip

**Comment by malept** [comment]
Yes, I was part of getting `asar` to 1.0.0. I plan on doing it when I have some free time.

**Comment by malept** [comment]
Also, I plan on adding dependabot to this repository, so for future reference to visitors to this repository, issues asking for dependency version updates are not necessary.
