### ISSUE TITLE
Fatal error: Unable to set icon

### ISSUE THREAD

**Issue by jakobolsen618** [electron-userland/electron-packager#951]
After trying to package an electron project for Windows, I came across this error I looked at almost all of the GitHub issues, and I couldn't find a solution that worked. The images are in the correct place, here is the script I am using to attempt to package my project:
<code>"package-win": "electron-packager . --overwrite --asar=true --platform=win32 --arch=x64 --icon=--prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"Launch Pad\""<code>

Thank you in advance,
Jakob

**Comment by malept** [comment]
You're not actually setting an icon to something valid. It looks like the icon is set to the value `--prune=true`.

**Comment by jakobolsen618** [comment]
Sorry, I think I copied that as I was changing locations, will edit it.

**Comment by malept** [comment]
If you're going to edit the comment, please consider *using* the [issue template](https://github.com/electron-userland/electron-packager/blob/v13.0.1/.github/issue_template.md) instead of *deleting* it. It makes it easier for us to diagnose your problem.
