### ISSUE TITLE
x86_64 architecture not supported on Linux

### ISSUE THREAD

**Issue by MechoshiPuhanaga** [electron-userland/electron-packager#954]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I'm trying to create a package on Ubuntu 18.04, architecture is x86_64 (got it after running 'uname -m' in terminal).
When I set --arch=x86_64 I get an error in console:

```
$ electron-packager . picollage --overwrite --asar --platform=linux --arch=x86_64  --prune=true --out=release-builds
Unsupported arch=x86_64 (string); must be a string matching: ia32, x64, armv7l, arm64, mips64el
```

Is it a bug or I'm missing something?

**Comment by malept** [comment]
Electron (and by extension, Electron Packager), for the most part, uses the same architecture names as [Node.js](https://nodejs.org/api/process.html#process_process_arch). These are different from the architecture names you'd find on your operating system.

To some extent, the supported architectures are also described on the [Electron Support page in the official Electron docs](https://electronjs.org/docs/tutorial/support#supported-platforms).
