### ISSUE TITLE
Cannot set an icon for windows

### ISSUE THREAD

**Issue by Tembero** [electron-userland/electron-packager#965]
I tried every single way that I could find and still wasn't able to change the icon of the application. This problem was occuring on windows 7 64bit. Is there any non hacky way to change it?

**Comment by malept** [comment]
There's not much to go on here, so I'm just going to give some guidelines.

1. Make sure you're setting `icon` to a `.ico` file that is valid
2. Make sure that the icon file contains a square image with [dimensions that are compatible with Windows 7](https://en.wikipedia.org/wiki/ICO_(file_format)#History).
