### ISSUE TITLE
Errors while trying to package an exe on macOS Mojave (10.14.3)

### ISSUE THREAD

**Issue by ScribbleNerd** [electron-userland/electron-packager#968]
When I run `electron-packager . electron-tutorial-app --overwrite --platform=win32 --arch=ia32 --icon=assets/index.html/images/favicon.png --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="ScribbleApp"` it gives me the following errors

`Packaging app for platform win32 ia32 using electron v4.1.0
rcedit.exe failed with exit code 1. preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
wine: configuration in '/Users/scribblenerd/.wine' has been updated.
Fatal error: Unable to parse version string for FileVersion
Hackintosh:app scribblenerd$ electron-packager . electron-tutorial-app --overwrite --platform=win32 --arch=ia32 --icon=assets/index.html/images/favicon.png --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="ScribbleApp"
Packaging app for platform win32 ia32 using electron v4.1.0
rcedit.exe failed with exit code 1. preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
preloader: Warning: failed to reserve range 00007fff40000000-00007fff41ff0000
Fatal error: Unable to parse version string for FileVersion` I installed wine via `brew install wine`

**Comment by malept** [comment]
From a cursory [internet search](https://duckduckgo.com/?q="preloader%3A+Warning%3A+failed+to+reserve+range"), this sounds like more of a problem with Wine rather than Electron Packager (or even `rcedit`). You'll probably get better support from a Wine forum or support channel.
