### ISSUE TITLE
grunt-electron latest version includes vulnerable mksnapshot

### ISSUE THREAD

**Issue by jlindberg-oss** [electron-userland/electron-packager#974]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details
#952 updated the asar dependency of electron-packager to move off of mksnapshot, which had a high severity vulnerability in a transitive dependency: https://www.npmjs.com/advisories/777

More details at https://github.com/electron/asar/pull/165

However no release of grunt-electron has been created so the latest version (9.0.1) still includes the vulnerable dependency.

I am opening this issue here per the README of grunt-electron: https://github.com/sindresorhus/grunt-electron/blob/master/readme.md

### To Reproduce
```
npm install --save grunt-electron
npm audit
```

**Comment by malept** [comment]
Despite what the `grunt-electron` README says, this issue should be reported in the `grunt-electron` repository itself. `electron-packager` already has the dependency update, and `grunt-electron` just needs to be updated to `electron-packager >= 13.1.0` as per the [NEWS file](https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#1310---2019-02-19).
