### ISSUE TITLE
path.join not working after Electron-packager pack my project

### ISSUE THREAD

**Issue by peterremote1980** [electron-userland/electron-packager#982]
Hi 
   These code has exception, it can't load up my image i think

```
win = TrayWindow.setOptions({
		trayIconPath: path.join('image/sharepoint2019.png'),
		window: mainWindow,
});
```

![exception](https://user-images.githubusercontent.com/36571333/56460914-c0cb1380-63dc-11e9-82e2-bcdb0da62395.JPG)

**Comment by malept** [comment]
Thanks for filing an issue, but this is covered in our Frequently Asked Questions document: [Why isn't the relative path in my app code working?](https://github.com/electron-userland/electron-packager/blob/v13.1.1/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working)
