### ISSUE TITLE
--asar.unpackDir multiple folders not working on macOS

### ISSUE THREAD

**Issue by HaveAGitGat** [electron-userland/electron-packager#986]
### Preflight Checklist

* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
"electron-packager": "^12.2.0",
* **Electron Version:**
"electron": "^3.1.8",
* **Operating System:**
  macOS 10.13.6
* **Last Known Working Electron Packager version:**:
NA

### Expected Behavior

Using --asar.unpackDir{x1,x2} works fine on Linux and Windows but does not work on macOS

### Actual Behavior

Using --asar.unpackDir{x1,x2} on macOS results in glob string error

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by malept** [comment]
Also, can you please use the latest released version of Electron Packager?

**Comment by HaveAGitGat** [comment]
Thanks for the quick response. Thought I had the latest version as I ran 'npm update'. I've uninstalled and re-installed electron packager and I'm now on 13.1.1 so will give it a try and provide the info later.

**Comment by HaveAGitGat** [comment]
Hi here is the error:

```
npm run package-mac

> hbbatchbeast@0.1.5 package-mac /Users/haveagitgat/Programs/HBBatchBeast/HBBatchBeast
> electron-packager . --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --out=release-builds --darwinDarkModeSupport=true  --asar.unpackDir={node_modules/ffprobe-static,node_modules/@ffmpeg-installer}

Packaging app for platform darwin x64 using electron v3.1.8
glob pattern string required
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hbbatchbeast@0.1.5 package-mac: `electron-packager . --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --out=release-builds --darwinDarkModeSupport=true  --asar.unpackDir={node_modules/ffprobe-static,node_modules/@ffmpeg-installer}`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hbbatchbeast@0.1.5 package-mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haveagitgat/.npm/_logs/2019-04-30T17_43_48_749Z-debug.log
```

You can replicate the error by doing this:

```
git clone https://github.com/HaveAGitGat/HBBatchBeast
npm install
npm run package-mac
```

**Comment by malept** [comment]
This is not a bug in Electron Packager, but rather a quirk in how NPM scripts are run. When you run `npm run package-mac`, it sends the value of that script to your OS's shell to be executed. So what happens is that bash processes the script and automatically expands the unpackDir string (as glob syntax is built-in to several shells' syntax).

Before bash processes it:

```shell
--asar.unpackDir={node_modules/ffprobe-static,node_modules/@ffmpeg-installer}
```

After bash processes it:

```shell
--asar.unpackDir=node_modules/ffprobe-static --asar.unpackDir=node_modules/@ffmpeg-installer
```

The `asar` module does not expect multiple arguments to `unpackDir`, so it fails.

The solution is to quote the value of `--asar.unpackDir` so bash does not expand it:

```shell
--asar.unpackDir='{node_modules/ffprobe-static,node_modules/@ffmpeg-installer}'
```

**Comment by HaveAGitGat** [comment]
Thank you for this!
