### ISSUE TITLE
Globally installed old version of Electron Packager cannot run with Node >= 10

### ISSUE THREAD

**Issue by albu77** [electron-userland/electron-packager#991]
### Preflight Checklist

* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details
* **Node Verion
Node v11.4.0
* **Electron Packager Version:**
  * Electron Packager 13.1.1
* **Electron Version:**
  * v1.8.1
* **Operating System:**
  * Host Operating system: win32 (ia32)
* **Last Known Working Electron Packager version:**:
  * 

### Actual Behavior
with 2 projects one with version of electron-packager :8.1 and 13.1.1
I've tried changing the dependency in my package.json .Nothing can change the error. I'm under visualCode and emit the following command in the terminal. Everything worked fine before but I don't remember which node version was installed...
D:\electron\TestVisa>electron-packager D:\electron\VisaChine TestVisa --platform=win32 --arch=ia32 --overwrite --prune=true --ignore=output --ignore=doc --ignore=essais --ignore=packaging --ignore=\.vscode --ignore=\.gitignore --icon=assets/images/favicon.ico --win32metadata.CompanyName='AlbuWeb' --win32metadata.ProductName='TestVisa' --win32metadata.FileDescription='TestVisa' --win32metadata.OriginalFilename='testvisa.exe' --app-copyright="(C)2019 AlbuWeb "
CANNOT RUN WITH NODE 11.4.0
Electron Packager requires Node 4.0 or above.

**Comment by malept** [comment]
Uninstall `electron-packager` globally, install the latest version in your project as one of the `devDependencies` (making sure that it is the latest stable version of Electron Packager), and add the following script in `package.json`:

```json
{
  "scripts": {
    "package": "electron-packager . --add-all-of-your-flags-here"
  }
}
```

Then you can run `npm run package` and it should just work with Node >= 10.

**Comment by albu77** [comment]
I did what you said. The error concerning the node version is not there anymore using the script (still there with the command line of the terminal). But I have another error which I don't catch the meaning
1°) My script description in my package.json is the following:
```
"scripts": {
    "package": "electron-packager . --platform=win32 --arch=ia32 --overwrite --prune=true --ignore=output  --ignore=doc --ignore=essais  --ignore=packaging --ignore=/.vscode  --ignore=/.gitignore --icon=assets/images/favicon.ico --win32metadata.CompanyName='AlbuWeb' --win32metadata.ProductName='VisaChine' --win32metadata.FileDescription='VisaChine' --win32metadata.OriginalFilename='visachine.exe' --app-copyright='(C)2019 AlbuWeb'"
  }
```
And in the log of the error I got what is in the attached file
I don't understand what I'm doing wrong... Is there anything badly insert in my options string?
[bugPackager.txt](https://github.com/electron-userland/electron-packager/files/3171943/bugPackager.txt)

**Comment by albu77** [comment]
Ok, trying bit by bit my options string.... the fault is the brackets around the` C `of the `app-copyright`.
So now the mistery is still there : why I can't use anymore the command line of my terminal with the same command?

**Comment by malept** [comment]
This is probably a limitation of how [NPM scripts](https://docs.npmjs.com/misc/scripts) work. In the case of Windows, it uses `cmd.exe` to parse and execute script commands, and my guess is that you can't use single quotes and parentheses at the same time.

**Comment by albu77** [comment]
Ok, trying bit by bit my options string.... the fault is the brackets around the C of the app-copyright.
So now the mistery is still there : why I can't use anymore the command line of my terminal with the same command?

**Comment by albu77** [comment]
Yes I guess too but what I can't explain is why my command which was working in the terminal (without npm ) `electron-packager D:\electron\VisaChine visachine --platform=win32 --arch=ia32 --overwrite --prune=true etc....` Doesn't work anymore ? 
I will work now with the npm script but it is not normal isn't it?

**Comment by malept** [comment]
Your quotes are different between the script and the original one you pasted in the issue summary for `--app-copyright` (double quotes originally, then single quotes in the script version).

If you need more help with writing NPM scripts, try asking in https://npm.community/ . Unfortunately, I don't have time to be answering general Node/NPM questions.

**Comment by malept** [comment]
Alternatively, you could use the [JS API](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md) to specify the options and then reference that script (assuming it's called `packager.js`):

```json
"scripts": {
    "package": "node packager.js"
}
```

**Comment by albu77** [comment]
Ok, thanks anyway for the time you spent.
