### ISSUE TITLE
Package dynamic libraries .dll too

### ISSUE THREAD

**Issue by Suhail** [electron-userland/electron-packager#994]
### Problem Description
I am using a C++ native node addon that's dependent on dynamic libraries in the root directory (.dlls) on Windows.

I could not find a simple way to make sure they get included in the packager without copying them over manually.

### Proposed Solution
Either:
1. A config parameter to specify their locations
2. Ensure they are not ignored somehow

### Alternatives Considered
Writing a manual script to do the task post installation but prior to the program running.

### Additional Information
n/a

**Comment by malept** [comment]
Take a look at the [`extraResource`](https://github.com/electron-userland/electron-packager/blob/v13.1.1/docs/api.md#extraresource) option.

For what it's worth, Electron Packager does not ignore `.dll` files by default so I'm not sure what you're seeing.

**Comment by Suhail** [comment]
Hey there,

Here's my directory pre-packaging: https://prnt.sc/npji5a

Here it is after without the .dlls in the root dir: http://prntscr.com/npjjlg

**Comment by malept** [comment]
If you want them in the same directory as the renamed `electron.exe`, then I suggest using the [`afterExtract` hook](https://github.com/electron-userland/electron-packager/blob/v13.1.1/docs/api.md#afterextract) to copy the DLLs.

**Comment by Suhail** [comment]
Gotcha - thanks; works for me.

**Comment by Suhail** [comment]
Ah, so new issue: if you look at the files during afterExtract in the tmpdir, there are only .asar files vs. the unpacked versions? So, any attempt to moves files will be met with "it can't find the file"

My asar=false.

**Comment by Suhail** [comment]
This looks like it works with afterCopy but not afterExtract.
